### ISSUE TITLE
How to bold text for each UI element

### ISSUE THREAD

**Issue by algorithmax** [notable/notable#1001]
On the page notable.md there is a screenshot of the program installed in Windows. I noticed that the text in this screenshot is thicker than the text after installing the program.  How can I bold the text for sidebar and this second column.
https://drive.google.com/open?id=1xpjp4TFM6my3fraXb6rP2_VEx2neBSFh
https://drive.google.com/open?id=1XWYmX4U8hfLs-LWqOUnENzlYId1w7Azq

**Comment by fabiospampinato** [comment]
That's not really possible, you're seeing the difference because Windows screenshots are actually generated from macOS, so font rendering will be a bit off.

You will however be able to switch to a thicker font, or change the thickness of the font with some css in the future:

- #102 
- #22 
- #444
