### ISSUE TITLE
Notable puts a new line after 'enter'

### ISSUE THREAD

**Issue by algorithmax** [notable/notable#1009]
Markdown files from github contain new lines in e.g. the middle of a sentence, then writing them into Notable I have to delete these new lines because these 'enters' Notable interprets as a new line. Is it possible that sentences in Notable after clicking on an enter are not separated, but continue to the same line?

Example mardown file (https://github.com/algorithmax/golang/blob/master/README.md)
In November 2016, the Go and Go Mono fonts which are sans-serif 
and monospaced respectively were released by type designers
Charles Bigelow and Kris Holmes. Both fonts adhere to WGL4 
and were designed to be legible with a large x-height 
and distinct letterforms by conforming to the DIN 1450 standard

**Comment by fabiospampinato** [comment]
No.

It seems that GitHub itself is not even consistent about this, i.e. the file you linked is rendered different than your comment.
