### ISSUE TITLE
Creation timestamp of notes created from template should be set to current date/time

### ISSUE THREAD

**Issue by epmoyer** [notable/notable#1013]
- **OS Version**: macOS 10.14.6
- **Notable Version**: 1.8.3

### Current behavior

When creating a new note from template,  the `created` timestamp of the new note (in the markdown metadata) is inherited from the template document, and the `modified` timestamp is set to the current date/time. 

### Expected behavior

On initial creation, both the `created` and `modified` timestamp of the new note should be set to the current date/time.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
