### ISSUE TITLE
Add shift-enter to the builtin editor to add a new line below the current line

### ISSUE THREAD

**Issue by gamato** [notable/notable#1017]
### Feature description

Often when editing a line of text I want to add a new line below the current one. Currently I've got to jump to the end of the current line and hit Enter. However, in some editors there's a very useful shortcut (Shift-Enter) that creates a new empty line below the current one (without breaking the current line) and moves cursor to the newly created line.

### Feature motivation

It's super useful and addictive. :-)

**Comment by fabiospampinato** [comment]
On macOS I can "Shift+Enter" to insert a newline _before_, and "Cmd+Enter" to insert a line _after_. 

Maybe under your OS it's "Ctrl+Enter" instead?

**Comment by gamato** [comment]
I tried it on OS X 10.11.6 -- now I see that Cmd+Enter works as you suggested but Shift+Enter just breaks the line the same way Enter does. Thanks.

**Comment by fabiospampinato** [comment]
> but Shift+Enter just breaks the line the same way Enter does

Oh yes I thought it worked differently. But you can "Cmd+Shift+Enter" to insert the newline before it seems.
