### ISSUE TITLE
Trojan:MacOS/ScarletFlash.A

### ISSUE THREAD

**Issue by kdlslyv** [notable/notable#1020]
- **OS Version**: Windows 10 1903
- **Notable Version**: 1.8.3

### Current behavior

After updating notable today, Windows Defender instantly killed and removed it as Trojan:MacOS/ScarletFlash.A.
I'd say it's certainly a false-positive.

### Expected behavior

Would be awesome if that can be sorted out somehow, as this is my favorite markdown notepad and a great piece of software.

Kind regards

**Comment by fabiospampinato** [comment]
Upstream issue: https://github.com/fsevents/fsevents/issues/305.

I've already fixed this and I'm in the process of crafting v1.8.4.

**Comment by fabiospampinato** [comment]
Just released v1.8.4, it'd be great if you could confirm that the issue is fixed.

**Comment by kdlslyv** [comment]
Yup, it's fixed.
Great work on the quick resolution!

**Comment by fabiospampinato** [comment]
Thanks for checking.
