### ISSUE TITLE
Is it possible to see the current versions of plugins

### ISSUE THREAD

**Issue by osdlge** [notable/notable#1026]
For example in #970 what version of Mermaid is currently being used?

It would be great if there was some way to see the current versions of plugins from within Notable so I would know what features are supported or be able to try and track down if a problem is within Notable or a third party

**Comment by fabiospampinato** [comment]
> Is it possible to see the current versions of plugins

Not yet, I think those kinds of plugins will just be open-sourced and you'll be able to retrieve the version used by looking at the code.

> For example in #970 what version of Mermaid is currently being used?

There I updated Mermaid from v8.2.6 to v8.4.5.

> so I would know what features are supported or be able to try and track down if a problem is within Notable or a third party

Generally we try to stay pretty up-to-date, if there's a problem you can just report it here and I check if it's an upstream issue or not.
