### ISSUE TITLE
Link in cheat sheet to Mermaid documentation is incorrect

### ISSUE THREAD

**Issue by osdlge** [notable/notable#1028]
- **OS Version**: Mac OS 10.15.2
- **Notable Version**: 1.8.4

### Current behavior

Inside the cheat sheet the link to mermaid takes you to http://knsv.github.io/mermaid

### Expected behavior

it looks like this has moved to https://mermaid-js.github.io/mermaid/#/

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
