### ISSUE TITLE
Notable crashes when a Data Directory is selected that does not contain a notes folder

### ISSUE THREAD

**Issue by stingray21** [notable/notable#1034]
I switched to *Notable* after using plenty of other markup editors and I am pretty satisfied with the way it works. Unfortunately, I have an issue when switching *data directories*.

- **OS Version**: Linux (Manjaro Gnome)
- **Notable Version**: 1.8.2

### Current behavior

Notable crashes, when selecting a directory via *Change Data Directory* and that directory does not contain a folder named *notes*.
A pop-up appears that says *'No "notes" subdirectory found in this data directory ...'*. There is no button to close the pop-up and it is not possible to select a different *data directory*

### Expected behavior

There should be a way to close the pop-up and choose a different directory or the *notes* directory should be automatically created.

**Comment by fabiospampinato** [comment]
That's strange, it's not that the app crashes, it's just telling you that you might have picked the wrong folder, I've added that dialog mostly for new users who might be wondering why their notes are not being found.

This is what I'm seeing:

<img width="720" alt="Screen Shot 2020-01-24 at 21 09 42" src="https://user-images.githubusercontent.com/1812093/73104285-f8c43180-3eed-11ea-97ac-037986a63562.png">


Could you send me a screenshot of what you're seeing? It's weird that the dialog is not closable for you.

**Comment by stingray21** [comment]
I meant crashing in the sense of I cannot use it anymore. I had to kill the process. 
![image](https://user-images.githubusercontent.com/4960916/73106043-c240e380-3efa-11ea-8538-7feffd3218d5.png)

However, I found now a way to continue. I can close the pop-up by right-clicking on the very top of the notification and select *close* in the context menu.
![image](https://user-images.githubusercontent.com/4960916/73106216-311e3c80-3efb-11ea-9c4e-19dd25a1dd84.png)

**Comment by fabiospampinato** [comment]
Alternatively you can delete `~/notable.json` and the app will forget that you've picked a data directory.

This is weird though. If you select more than one note and click the "Add Tags" button in the multi-note editor, without actually writing any tags, can you not close that dialog either?

What version of Manjaro are you running? I'll see if I can reproduce this.

**Comment by stingray21** [comment]
Manjaro should be up to date, it's Gnome 3.34.2

> This is weird though. If you select more than one note and click the "Add Tags" button in the multi-note editor, without actually writing any tags, can you not close that dialog either?

Yes, correct. It's the same behavior.

**Comment by paleboot** [comment]
Confirmed behaviour, was able to reproduce using
OS: Pop!_OS 19.10
Gnome 3.34.2

**Comment by fabiospampinato** [comment]
That's strange, it seems more of an issue with the desktop environment really, those dialogs should have a close button. I guess it might be better to reimplement them inside the app anyway.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.

Now we are using custom dialogs that don't (mis)behave depending on the DE used.
