### ISSUE TITLE
Menu bar Link to tutorial is broken

### ISSUE THREAD

**Issue by photoangell** [notable/notable#1035]
- **OS Version**: Windows 10
- **Notable Version**: 1.8.4

### Current behavior

Help -> Tutorial, opens dialog box. link in the dialog box "online tutorial" goes to this web page
https://notable.md/static/pdfs/tutorial/1.8.4.pdf which returns a 404.

### Expected behavior

expecting a pdf to load...

**Comment by fabiospampinato** [comment]
I've been updating my release workflow #1004 and I haven't uploaded that file yet, in the mean time check out the identical pdf for v1.8.3: https://notable.md/static/pdfs/tutorial/1.8.3.pdf

**Comment by fabiospampinato** [comment]
Fixed.
