### ISSUE TITLE
Allow Quick Open to Search Contents of Notes (not just heading) & "Switch" to Notebooks/Tags/Templates

### ISSUE THREAD

**Issue by macintacos** [notable/notable#1038]
### Feature description

Love the app. One thing that I do miss from Ulysses (which I was using pretty heavily before this) is that their quick open allows you to search the entire contents of the files as well as the title, and also switch between groups (which are _slightly_ analogous to Notebooks in Notable). It'd be really nice if the following could come to Notable's quick open functionality:

1. It searches the contents of the file as well as the title.
2. It allows you to "switch" to a notebook/tag/template that matches the search term (thus filtering the viewable notes down to the notes that match that notebook/tag/template).
3. (optional) it shows a preview of your matched term if the search is match is within the note; right now since quick open is searching for just the title it's not entirely necessary, but should this be implemented it might be confusing to just see a note's title that doesn't contain the search term you provided.

For no. 2, I'm imagining that hitting "enter" on a notebook/tag/template result would be effectively the same result as just clicking on that item in the sidebar.

Here's a screenshot of an example quick open search in Ulysses:

![image](https://user-images.githubusercontent.com/8128941/73140104-22db3800-4043-11ea-8414-b8e387ec63bb.png)

Apologies if this has been requested before; I did some preliminary searches through the Github issues and the Reddit and couldn't find something that was exactly asking for the above. I see #338 and #358, but IMO they don't match the spirit of my above request.

### Feature motivation

Take a look at the "CMD+O" shortcut implementation in Ulysses to see how this works there; essentially I would like that, but I'm sure you might have a

**Comment by fabiospampinato** [comment]
I see three issues here, I've split this into standalone and more manageable issues, let me know if I've missed anything:

- https://github.com/notable/notable/issues/1039
- https://github.com/notable/notable/issues/1040
- #243

**Comment by macintacos** [comment]
@fabiospampinato Makes sense to me 🙂
