### ISSUE TITLE
Sub and superscripts not working

### ISSUE THREAD

**Issue by justisGipson** [notable/notable#1042]
- **Mac 10.15.2**:
- **Notable Version - 1.8.4**:

### Subscripts and superscripts not working

<img width="461" alt="Screen Shot 2020-01-29 at 1 37 52 PM" src="https://user-images.githubusercontent.com/42194039/73386406-cbd09f80-429c-11ea-9802-4be1a974eb4f.png">
<img width="539" alt="Screen Shot 2020-01-29 at 1 40 23 PM" src="https://user-images.githubusercontent.com/42194039/73386495-ed318b80-429c-11ea-82f8-a7a4d841e04f.png">

Neither seem to be working for me, using the caret for the superscript or using tilde not enabling subscript. Didn't see any other open issues for this. Let me know if you need any further clarifications.

**Comment by WilliamSBunin** [comment]
Can you run the following?
````
Wrap up this component work taking~Takingtoolong~
Wrap up this component work taking^Takingtoolong^
````

**Comment by justisGipson** [comment]
<img width="421" alt="Screen Shot 2020-01-29 at 2 01 30 PM" src="https://user-images.githubusercontent.com/42194039/73388276-f1ab7380-429f-11ea-880e-72a8011b0292.png">

That seems to work... I see what I was doing wrong. Closing the issue. Thanks
