### ISSUE TITLE
How to resize a picture from the clipboard?

### ISSUE THREAD

**Issue by algorithmax** [notable/notable#1043]
How to set the size of the image pasted from the clipboard?

**Comment by fabiospampinato** [comment]
The fact that you pasted the image from the clipboard seems irrelevant 🤔 Or do you want the app to physically resize the things you paste?

We don't yet support the syntax for specifying image dimensions: https://github.com/notable/notable/issues/824

So you'll have to write a raw html `<img>` tag and set "width" and "height" attributes there.
