### ISSUE TITLE
Hierarchical notes

### ISSUE THREAD

**Issue by ma-sadeghi** [notable/notable#1044]
### Feature description
A picture worth a thousand words :)

![](https://www.giuspen.com/images/cherrytree-main_window_text.png)

### Feature motivation
It's very useful for organizing the notes.

**Comment by ma-sadeghi** [comment]
I just realized this has already been discussed and ruled out. Sorry for the duplicate issue. Just to confirm, is this still considered out-of-scope? @fabiospampinato

**Comment by fabiospampinato** [comment]
Let's track this here: https://github.com/notable/notable/issues/564 maybe once the UI becomes more flexible I or somebody else could write a plugin for this.
