### ISSUE TITLE
Impossible to type @-symbol on German Mac Keyboard

### ISSUE THREAD

**Issue by klickreflex** [notable/notable#1047]
- **OS Version**: MacOS 10.15.3
- **Notable Version**: 1.8.4

### Current behavior

Typing `alt + l` toggles the line count gutter

### Expected behavior

Typing `alt+ l` writes an `@` character (default keyboard layout on German MacOS)

**Comment by fabiospampinato** [comment]
Duplicate of https://github.com/notable/notable/issues/728
