### ISSUE TITLE
mermaid -Rendering Error

### ISSUE THREAD

**Issue by quotengrote** [notable/notable#1050]
with mermaid there is a rendering error

```mermaid
graph TD
	tray1-->hdd2["4TB 2,5#quot;" HDD<br>ID:ata-ST4000LM024-2AN17V_WCK3KK9P<br>Label:HDD4<br>Port:scsi4<br>Position:unten links]
```

is showing as:

<a href="https://ibb.co/vQTV8yJ"><img src="https://i.ibb.co/vQTV8yJ/Unbenannt.png" alt="Unbenannt" border="0"></a>

the last line isnt showing properly

**Comment by fabiospampinato** [comment]
Duplicate of #1027.

With your code I can reproduce the issue!
