### ISSUE TITLE
Notable crashes!

### ISSUE THREAD

**Issue by ioitiki** [notable/notable#1051]
- **OS Version**:
- **Notable Version**:

### Expected behavior

![Screen Shot 2020-02-05 at 4 27 08 PM](https://user-images.githubusercontent.com/26385844/73895444-7c5a1880-4834-11ea-91b4-f32baab28803.png)

**Comment by ioitiki** [comment]
updated the os and the problem went away :D

**Comment by fabiospampinato** [comment]
Do you mind filling up the following?:

> OS Version:
> Notable Version:

Also when did this happen, every time you opened the app? Did it ever open correctly?

**Comment by m-paolino** [comment]
> Also when did this happen, every time you opened the app? Did it ever open correctly?

It happens when you leave the app open and after the system reboot.

**Comment by fabiospampinato** [comment]
@m-paolino what OS are you on?

**Comment by m-paolino** [comment]
> @m-paolino what OS are you on?

macOS Catalina 10.15.3

**Comment by tobiaslieandersen** [comment]
Just updated from Mojave to Catalina (10.15.4) and this started happening. I was not able to open Notable at all. Downloaded the newest version of Notable and the issue disappeared.

**Comment by fabiospampinato** [comment]
@tobiaslieandersen what version of Notable were you using? And why didn't it automatically update itself?

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
