### ISSUE TITLE
Snap permissions error

### ISSUE THREAD

**Issue by zygfrydw** [notable/notable#1055]
The note co
- **OS Version**:
Ubuntu 18.04
- **Notable Version**:
1.8.4 installed with snap

### Current behavior
1. Install snap with `snap install notable_1.8.4_amd64.snap --dangerous`
2. Open Notable and use default directory for notes
3. Create a single note
4. Close Notable
5. Open Notable  - the contend of note created in step 3 is lost. Only the number of notes created in step 3 was unchanged, but all notes are lost.

### Expected behavior
The notes content should be preserved after closing the application. The application is working correctly when installed from deb package.

**Comment by fabiospampinato** [comment]
Can you reproduce reliably?

We have logic in place for saving in these exact circumstance, maybe you force-killed the app?

**Comment by zygfrydw** [comment]
> Can you reproduce reliably?

Yes, it is reproducible 10/10 for me.

>  maybe you force-killed the app?

No, I was closing it with "x" and I had the closing dialog with confirmation. 

I have noticed that when I use the option "Reveal in Folder", I get the following dialog: 
![DIALOG](https://user-images.githubusercontent.com/3630743/74635103-93b6d100-5165-11ea-8296-d26bdc8b27af.png)
Hence I guess that there might be an issue with notable privileges.

I have installed the Notable with the following command:
`sudo snap install notable_1.8.4_amd64.snap --dangerous`

**Comment by fabiospampinato** [comment]
It looks indeed like a permissions-related issue 🤔

**Comment by zygfrydw** [comment]
I am not very experienced in Linux system, but I am a software developer coming to Linux from Windows environment, therefore I hope, I can help you find the problem or provide you with additional logs, but I need some guidance on what to look for.

**Comment by fabiospampinato** [comment]
There isn't much guidance that I can offer, I would personally start looking into how snaps handle permissions, how electron and snap interact, and re-read the linux-part of the [electron-builder](https://www.electron.build/) documentation in case I missed something.

**Comment by fabiospampinato** [comment]
A user on twitter sent me some pretty detailed reproduction steps: https://t.co/rmeglKFna8

It looks indeed like a permission issue, I'll have to take a closer look at this.

@zygfrydw have you found a workaround for this?

**Comment by daaaaaavis** [comment]
Just found Notable and I'm very amazed by this project. 
Want to help as much as possible, so, naturally, I was testing out the app and had the same issue. 

OS: Ubuntu Budgie 19.10.
 
Not much to add to previously mentioned reproduction steps. 
The issue is exactly the same for me.

**Comment by fabiospampinato** [comment]
I've just fixed this, the new version of the snap now uses the "classic" confinement rather than the "strict" confinement, this allows the app to write to files on disk (which surprisingly before wasn't fully allowed to it seems), you should definitely update to that.
