### ISSUE TITLE
Mermaid link in cheatsheet broken

### ISSUE THREAD

**Issue by epmoyer** [notable/notable#1056]
- **OS Version**: OSX 10.14.6
- **Notable Version**: 1.8.4

### Current behavior

Markdown cheatsheet links to mermaid at: http://knsv.github.io
That link is broken.

### Expected behavior

Not sure what used to be at that link.  Perhaps https://mermaid-js.github.io/mermaid/ is a good replacement?

**Comment by fabiospampinato** [comment]
I fixed this already, the fix will be available in the next release.
