### ISSUE TITLE
When will be a new release?

### ISSUE THREAD

**Issue by algorithmax** [notable/notable#1064]
When will a new update with a quick search in the text be uploaded? I had to go back to Evernote, because my notes are so long that Notable has just become dysfunctional. Changing anything in a few thousand lines of text is so difficult that I'm giving up on this program. If the program was open source, this functionality would have been written by the community long ago. Maybe I'll come back when this situation changes.

**Comment by fabiospampinato** [comment]
I don't know, keep an I on the relevant issues I linked you.

The app has been open-source for about half is live and no-one submitted a PR for this. Actually if anybody would like to submit a PR based on [v1.5.1](https://github.com/notable/notable/tree/v1.5.1) please do it, I'd be able to port it pretty cleanly and quickly to the current version.
