### ISSUE TITLE
Data directory problem

### ISSUE THREAD

**Issue by SteveM2020** [notable/notable#1067]
I set up a directory: C:\Users\Steve\Sync\notes

Using Notable I click import file and open this directory. The program sees all the notes and lets me choose one or more. I click choose data directory (and choose the same one) but the program isn't reading the .md files in the directory and displaying them in the program.

I'm assuming I have to use "File import" and import all 300 notes even though they are already in the data directory? Is this correct?

**Comment by fabiospampinato** [comment]
Kinda, basically notable is assuming a different folder structure, read the second page of the tutorial: https://tutorial.notable.md/

Basically it's looking for notes in a "notes" subdirectory of your data directory, so put your notes inside another directory and use that as your data directory.
