### ISSUE TITLE
Comparison Matrix Update

### ISSUE THREAD

**Issue by walkercam** [notable/notable#1068]
The comparison matrix on the main documentation page is very helpful however I have noticed that under Joplin it is listed that emojis are not supported. This may now be outdated. See the plugin section on this page https://joplinapp.org/markdown/ . Github markdown emojis are supported by enabling this plugin. Can the matrix image be updated?

**Comment by fabiospampinato** [comment]
Sure, I didn't realize that Joplin had those plugins, I'm not sure what's the reasoning behind disabling the emoji plugin by default. I'll probably take care of that later today 👍

**Comment by walkercam** [comment]
Cool. Thanks.

**Comment by fabiospampinato** [comment]
Updated, thanks!
