### ISSUE TITLE
Show recent/popular notes in sidebar

### ISSUE THREAD

**Issue by MatanRubin** [notable/notable#107]
This feature should be similar to the Favorites feature, but the notes in the list should be selected automatically.
The logic is that people would often want to access:

1. Notes that have been recently accessed
2. The notes which are accessed the most

**Comment by MatanRubin** [comment]
> I guess often people want to see the most recently modified notes instead, which you can already do

How?

> Just favorite/pin it.

The idea is that these automatically bubble up based on your usage pattern, instead of you having to pin it yourself. Similar to what Safari does when you open a new tab (shows you the most recently and most accessed websites)

**Comment by MatanRubin** [comment]
Thanks, I didn't realize that was clickable :)

**Comment by fabiospampinato** [comment]
I'm closing this as sorting by modification date is probably good enough.
