### ISSUE TITLE
Open Markdown files outside of the data directory

### ISSUE THREAD

**Issue by mattiaswerner** [notable/notable#1070]
Notable installed via snap on ubuntu 18.04.4.

I want to associate all .md files to be opened with notable.

The "open with" tab does not list notable as an option.

Could support for this be added please.

Thank you for your time.

**Comment by fabiospampinato** [comment]
👍 I think we should have an issue tracking this already but I can't find it.

**Comment by fabiospampinato** [comment]
Here it is: #940

**Comment by mattiaswerner** [comment]
Awesome, thanks!
