### ISSUE TITLE
Windows prompts users to delete the installer - as it is not signed

### ISSUE THREAD

**Issue by rathboma** [notable/notable#1075]
When downloading the setup file for windows (in Edge), users are greeted with an error message noting that Windows Defender recommends the file is deleted, as it is not signed by a publisher and is not commonly downloaded.

Signing your installer would solve this issue.

![image](https://user-images.githubusercontent.com/279769/75564588-094a5900-5a12-11ea-9182-88674e101fe3.png)

**Comment by rathboma** [comment]
![image](https://user-images.githubusercontent.com/279769/75564811-71993a80-5a12-11ea-939c-b7a453b60fff.png)

**Comment by fabiospampinato** [comment]
Let's track that here: #797. I wanted to buy an EV certificate but that seems super expensive, it might be enough to buy an OV certificate instead, I haven't looked into that deeply enough, I'm not entirely sure what the result of that for the end user would be.
