### ISSUE TITLE
Multi-cursors bug with reserved keywords

### ISSUE THREAD

**Issue by renanwillian** [notable/notable#1077]
- **OS Version**: Linux Mint
- **Notable Version**: 1.8.4

### Current behavior

When I try to get multi-cursors in a line on the start of 'test' it won't work properly. The bug happens with both middle mouse drag and shift+alt+down shortcut.
![image](https://user-images.githubusercontent.com/30376796/75878325-31fa9600-5df8-11ea-9811-b654db0cbc27.png)

```
# Test

test                               test
test                               test
date/­tim­e/d­ate­tim­e                 test
testtesttest                       test
_­if_­                               test
test                               test
testtesttest                       test
test                               test
```
It appears to be a bug in monaco editor, vscode has the same bug.

### Expected behavior
It should get multi-cursors in a line, like this in sublime text:
![image](https://user-images.githubusercontent.com/30376796/75879107-86524580-5df9-11ea-981b-c89167c03b0c.png)

**Comment by fabiospampinato** [comment]
> It appears to be a bug in monaco editor, vscode has the same bug.

Do you know if this bug has been reported to them already?

**Comment by renanwillian** [comment]
> Do you know if this bug has been reported to them already?

I didn't find anything, so I reported it:
https://github.com/microsoft/vscode/issues/92016

**Comment by renanwillian** [comment]
Actualy this is happening due to the presence of `U+00AD` in the text, not due reserved keywords nonsense.

Although other editors like Sublime Text handle this fine, this won't be fixed in VS Code. I don't think this is worth fixing just in Notable, so I'm closing the issue.
