### ISSUE TITLE
Vertical centering of page while editing

### ISSUE THREAD

**Issue by fabienbelmonte** [notable/notable#1081]
### Feature description

Would it be possible to vertically center on screen/window the paragraph being edited ?

### Feature motivation

When the text lenght is taller than the window, the edited area is on the bottom of the window. Having it always centered vertically on screen may improve ergonomy.

Thanks.

**Comment by fabiospampinato** [comment]
> Would it be possible to vertically center on screen/window the paragraph being edited ?

You mean like having the cursor always at the center of the app?

> When the text lenght is taller than the window, the edited area is on the bottom of the window. Having it always centered vertically on screen may improve ergonomy.

I'm not sure what you mean by this, are you saying that you'd prefer to avoid having to scroll the editor manually? It might be useful if you could post a screenshot showcasing the problem.

**Comment by fabienbelmonte** [comment]
Yes this is the idea : having the cursor always at the center of the app.

<img width="1110" alt="Capture d’écran 2020-03-08 à 15 04 39" src="https://user-images.githubusercontent.com/1895368/76164322-41f2dc80-614e-11ea-97a8-d4c78267403f.png">

**Comment by fabiospampinato** [comment]
Do you want it near the center of the app _always_ or mostly only when editing the last lines of a note?

**Comment by fabienbelmonte** [comment]
I have no religion on these two solutions. I just propose to have a way to not edit at the bottom of screen for better ergonomic

Thank

Fb.

Le 8 mars 2020 à 15:58, Fabio Spampinato <notifications@github.com> a écrit :

﻿

Do you want it near the center of the app always or mostly only when editing the last lines of a note?

**Comment by fabiospampinato** [comment]
Then we already have an option to scroll the editor beyond to the last line, it can be toggled with "Alt+L", this will be more easily configurable in v1.9.
