### ISSUE TITLE
Can't share the document again before delete last share action url.

### ISSUE THREAD

**Issue by baofeidyz** [notable/notable#1084]
- **OS Version**:
macOS 10.15.3
- **Notable Version**:
1.8.4
### Current behavior
Use the share button to share my own markdown file, then delete it by using the API `https://echo.notable.md/delete/[ID]` according [reddit](https://www.reddit.com/r/Notable/comments/e1v4rt/disable_share_via_link_feature/)

Then try to share this document again, it's failed.

### Expected behavior
share the document again will be successful.

**Comment by fabiospampinato** [comment]
I can't reproduce, and I'm not sure how this could happen knowing the server-side code that gets executed 🤔, can you try again? If it doesn't work again, do you get any error?

**Comment by baofeidyz** [comment]
I can't reproduce it yet. Maybe I couldn't access your server last time. I guess this is just my client network error. If there are any logs of this error, you can tell me where the log file is. I want to check it so we can determine why the error occurred.

**Comment by fabiospampinato** [comment]
> Maybe I couldn't access your server last time.

I suppose that's indeed what happened.

> So could I use socket or http proxy in notable app?

The app has no built-in support for setting a proxy, can you set one at the OS-level maybe?
