### ISSUE TITLE
Shortcut option+l and option+z is interfering with system shortcut for specific character

### ISSUE THREAD

**Issue by amwk** [notable/notable#1093]
- System os: macOS 10.15.2 
- Notable version: 1.8.1

### Current behavior

When pressing option+l and option+z I'm getting formatting and lines toggle on/off instead of my native language characters ( ż and ł )

### Expected behavior

I would expect that after pressing option+l and option+z I'm getting "ł" and "ż" similar to other applications :) 

Is there a way to workaround this issue (disable a shortcut for example) ?

**Comment by fabiospampinato** [comment]
There's no workaround in v1.8, but this actually got fixed in my development branch already, in v1.9 those shortcuts would just not exist anymore (until you configure them explicitly).
