### ISSUE TITLE
Lost all my data after a reboot

### ISSUE THREAD

**Issue by edsonmedina** [notable/notable#1095]
- **OS Version**: Ubuntu Studio 19.10 
- **Notable Version**: 1.8.4 (installed via snap)

### Current behavior

Prior to rebooting (desktop crashed) I had several notes, all with names and lots of content.

Now I only see one of my notes title, but it's empty. I also see an "Untitled" note (empty too)

### Expected behavior

I expected to see all of my notes.

**Comment by fabiospampinato** [comment]
Did you install the snap?

**Comment by edsonmedina** [comment]
Yes

**Comment by fabiospampinato** [comment]
There's a sandboxing issue with that, we are tracking it elsewhere. I've been waiting for about 3 weeks now I think for the Snapcraft guys to allow me to publish a working version in the store...

The deb should work fine, can you install that?

**Comment by edsonmedina** [comment]
Just did. Now I can't see *any* notes.
Which folder does the snap version use by default?

**Comment by fabiospampinato** [comment]
I don't think those notes were saved in the first place, for some reason the default strict confinement of the snap format allows Notable to create a file but not to edit it later on, which I don't understand. So I don't think you'd find anything usable in the folder used by the snap, which I can't remember exactly what it is, but it's something like `~/.snap/notable/.notable` or something. And I'd like to note that the snap environment itself is rewriting our default `~/.notable` into that.

**Comment by edsonmedina** [comment]
There were some files in there (one untitled and another with the title of another of my missing notes, but no content).

I just lost an entire day of work. :( 

Thanks.

**Comment by fabiospampinato** [comment]
I'm truly sorry about that! I'm working toward getting that fixed for good.
