### ISSUE TITLE
[question] how long a shared not is available (on https://echo.notable.md/) ?

### ISSUE THREAD

**Issue by didrip** [notable/notable#1097]
Hello, I just saw this morning that some of the notes I shared are now gone (`NOT FOUND`), is there an expiration limit ? I am 100% I did not [deleted](https://www.reddit.com/r/Notable/comments/dzggx1/is_it_possible_to_remove_a_note_shared_via/) them.

**Comment by WilliamSBunin** [comment]
24 hours.

I'm not sure why I remember this I can't seem to find any documentation backing up my statement. I was able to find someone else who remembered the same thing (Please see next link).

https://www.reddit.com/r/Notable/comments/dzggx1/is_it_possible_to_remove_a_note_shared_via/

That being said, it might be a nice addition to say "Are you sure you want to share this note? The shared link will be available for 24 hours." or something like that... 

Also might be nice to document this (if it isn't already in the welcome to notable documents).

**Comment by fabiospampinato** [comment]
@WilliamSBunin is correct about this. Additionally notes will get deleted whenever I restart the server as they are only stored in RAM. Let's track improvements to this feature here: https://github.com/notable/notable/issues/1098
