### ISSUE TITLE
Why can't I add a folder as an attachment?

### ISSUE THREAD

**Issue by chaowise** [notable/notable#1104]
Why can't I add a folder as an attachment?
A note in my eyes is a folder.

**Comment by fabiospampinato** [comment]
Potentially I guess this could be implemented.

> A note in my eyes is a folder.

How so? When you write a note with a general-purpose text editor you create a new folder and then what?

**Comment by chaowise** [comment]
Take an example. I take notes of reading. I created a note with a word document and some pictures.
I'll consider putting the picture in a folder to distinguish between other attachments.
Of course, that's just my idea. How the specific software is good, should be considered comprehensively.

**Comment by chaowise** [comment]
I use the software for file management, i feel good. There are documented descriptions and label classifications. I don't know if anyone else will do that.

**Comment by fabiospampinato** [comment]
🤔 In some sense this is supported already, you could have one data directory for each of your rich notes, or whenever you need to have a note with all of its attachments in a single folder you can just export that. More granular and automatic folder structures I'm not sure would be beneficial. Anyway we already have a more general issue for this: #54
