### ISSUE TITLE
change data directory to a custom directory

### ISSUE THREAD

**Issue by BigGitWorld** [notable/notable#1109]
**Expected behavior:**
I'd like to be able to change data directory to an already folder including large number of text plain files.
**Current behavior:**
I have installed the notable and want to change data directory to a directory which has more than 2000 notes all written by gedit in ubuntu (but without any suffix for example .text or .md or .html).
I did the above but when open the notable, it shows only some note files (20 files) not folders at all.
Question(1):
Does the notable supports inner folders inside of my custom data directory?
Question(2):
If does not support, so why the notable opened some text files from the inner folders?
OS Version : Ubuntu 16.04
Notable Version : 1.8.4

**Comment by fabiospampinato** [comment]
Notable is expecting to find notes in a subfolder named "notes", maybe you have some of your notes inside a folder named like that?

Maybe we should support top-level notes, but things would get messy I think 🤔

**Comment by BigGitWorld** [comment]
Please suppose I have a directory structure as the below:
```
javaFolder
    javaeeFolder
       servletFolder
           one.txt
    javaseFolder
       two.txt
       collectionsFolder
           three.txt
androidFolder
    uiFolder
     four.txt
      materialFolder
         five.txt
```
Now I want to set data directory to the ``javaFolder``.
So I have renamed the ``javaFolder`` to the ``notes`` folder and selected it from the notable.

But the notable could not import my text files correctly.
First: It could not find all my notes (more than 2000 files) and found only 20 files randomly.
Second: It could not recognize my folders too.
    
I expect the notable be able to import all my text plain files.

**Comment by fabiospampinato** [comment]
Notable expects a "notes" folder inside your data directory, if you switch to it then that becomes your data directory and you have to have a "notes" folder inside that.

What's the end goal here, using Notable for editing Markdown files in existing projects?

If you just want to move all your notes into a Notable data directory you can just impor them from the app itself.

**Comment by BigGitWorld** [comment]
> Notable expects a "notes" folder inside your data directory, if you switch to it then that becomes your data directory and you have to have a "notes" folder inside that.
I did same thing.

> What's the end goal here, using Notable for editing Markdown files in existing projects?
I was looking for a note taking app always that is able to do nested tags and very features like as the notable have. Therefore I'd written my notes simply by the gedit software in the Ubuntu.
Now I want to edit all of them by the Notable. So I have decided to change the data directory to my notes directory.
But did not work.
I think this is a bug in the Notable and you can do a similar behavior like me to see the same result.

> If you just want to move all your notes into a Notable data directory you can just import them from the app itself.
I have very nested folders and if I want to add each folder notes manually, it is not good (waste my time). So I think it will be a feature if the Notable can do this automatically by selecting data directory only.

**Comment by fabiospampinato** [comment]
> So I think it will be a feature if the Notable can do this automatically by selecting data directory only.

Yeah I think you're onto something, the app should probably recursively import files automatically. However right now you can find all text files and copy them to a new folder in a few seconds right from within your file explorer.

I would want to try to reproduce your issue, but as I'm understanding it this is basically your folder structure:

```
javaFolder
    javaeeFolder
       servletFolder
           one.txt
    javaseFolder
       two.txt
       collectionsFolder
           three.txt
androidFolder
    uiFolder
      four.txt
      materialFolder
         five.txt
```

And you set "javaFolder" as your data directory, but where's "javaFolder/notes"?

**Comment by BigGitWorld** [comment]
No, I have a parent folder that called it as "notes", like the below:
```
notes
	javaFolder
		  javaeeFolder
		     servletFolder
		         one.txt
		  javaseFolder
		     two.txt
		     collectionsFolder
		         three.txt
	androidFolder
		  uiFolder
		    four.txt
		    materialFolder
		       five.txt
```
Please note that my real structure is more complicated than the above. 
I have more than 100 folders and 2000 files.

**Comment by fabiospampinato** [comment]
What's the data directory in that example? The data directory should be the one containing "notes".

**Comment by BigGitWorld** [comment]
Sorry for the mistake. I have modified that in the last above comment.

**Comment by fabiospampinato** [comment]
So that isn't able to read all notes? Are all notes with a ".txt" extension? Can you see any pattern between the notes that it can read and those that it can't?

**Comment by BigGitWorld** [comment]
No its not able.
No My notes does not have .txt extension. because as you know extension is an useless thing and OS can find the correct extension by the file format.

**Comment by BigGitWorld** [comment]
Another Question:
Please suppose I have several non text/plain files in my custom directory too.
for example some images and pdf and jar files.
Is it possible the existence of these files be disruptive?Or the Notable ignores unknown files automatically?

**Comment by fabiospampinato** [comment]
> No My notes does not have .txt extension. because as you know extension is an useless thing and OS can find the correct extension by the file format.

That's the issue then.

Extensions are useful, just to give one example it's impossible to decide if when opening a powerpoint file it should be opened in powerpoint or unzipped without an extension.

In our case the app can't just attempt to parse as notes everything, it needs files to have a supported extension.

> Is it possible the existence of these files be disruptive?Or the Notable ignores unknown files automatically?

They will be ignored.
