### ISSUE TITLE
Paste text doesn't work inside link

### ISSUE THREAD

**Issue by arthurdenner** [notable/notable#1114]
- **OS Version**: macOS Mojave 10.14.6
- **Notable Version**: Version 1.8.4

### Current behavior

Paste text doesn't work inside link. See below.

![notable-paste-bug](https://user-images.githubusercontent.com/13774309/78873611-6db5fa80-7a4b-11ea-8c1e-7da708b8d95e.gif)

### Expected behavior

Paste text would work as type does.

### Notes

I didn't find a similar issue. If there is, apologize me and close this as duplicate.

**Comment by fabiospampinato** [comment]
Those the bug occur when undoing a paste?

**Comment by arthurdenner** [comment]
Hi @fabiospampinato! Sorry, I was going to add more details but was pulled into a meeting and forgot about it. Thanks for the quick reply. My steps on the GIF:

1. Click on edit;
2. Select `app.md` and then `cmd + D` to select the other occurences;
3. Type `notable.md`, which succeeds;
4. `cmd + Z` to undo the changes;
5. `cmd + V` to paste `notable.md` that was in my clipboard, which breaks only inside the link.

> Those the bug occur when undoing a paste?

After pasting and getting the bug, `cmd + Z` undo it properly.

**Raw markdown used in the GIF:**

```
# Hi, app.md

Lorem ipsum app.md lorem ipsum. // line 1
Lorem ipsum [app.md](https://app.md) lorem ipsum. // line 2

> Type new text works on both lines
> Paste new text works on line 1
> Paste new text doesn't work inside link on line 2
```

**Comment by arthurdenner** [comment]
@fabiospampinato, FYI this is something that it's still happening and if you need more info from me, let me know.

**Comment by fabiospampinato** [comment]
@arthurdenner could you check if the latest v1.9 alpha works? https://github.com/notable/notable-experimental/releases

**Comment by arthurdenner** [comment]
@fabiospampinato unfortunately, it doesn't on 1.9.0-alpha.13.

![notable-paste-bug-alpha-13](https://user-images.githubusercontent.com/13774309/86498855-0973b000-bd88-11ea-8a76-4eff6f35829a.gif)

**Comment by fabiospampinato** [comment]
I can totally reproduce the issue, it's more about pasting multiple times in the same line than pasting inside a link.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.

Thank you very much for reporting this issue.

**Comment by arthurdenner** [comment]
Just tested with `1.9.0-alpha.17` and confirmed that it's fixed.

Thank you and I'm glad I could help. 🎉
