### ISSUE TITLE
Add support for removable media storage

### ISSUE THREAD

**Issue by cb3rnard** [notable/notable#1118]
Hello,
First, thank you for this very usefull app that I started using few months ago. I switched from Evernote and other related apps to keep my notes on my disk and it works quite well.

I first installed it on Windows, and then on my Ubuntu partition. The thing is : my notes are stored on my second disk, which is composed of two exfat partitions to keep it easily accessible on both systems.

On Windows, everything's working fine. But on Ubuntu, I can't edit or save notes. After looking for answers on several forums, I found out that snap packages need to have **support for "removable-media" interface/plugin** to do that. In the meantime, I have to edit files manually with another editor, which is a pity.

Could you consider adding that support in the next versions ?
Thanks in advance.
Clément.

**Comment by fabiospampinato** [comment]
Have you been using the snap published here on github? Can you try updating to the latest snap, which uses the "classic" confinement rather than the "strict" one?

**Comment by cb3rnard** [comment]
Thanks very much for the quick response !
I think I used the package available on the website, but I realize I can't remember so well, I tried several ways. I see there's a .deb package so I must have tried it too.
I'll try to reinstall with the github package right away !

**Comment by cb3rnard** [comment]
I just tried with no succes, after installing the .deb package with dpkg. I have also previously tried with the AppImage package, but had the same issue.

My partition is mounted on /media

**Comment by fabiospampinato** [comment]
I'll have to look more into this, thanks for reporting the issue.

**Comment by cb3rnard** [comment]
I figured it out ! My bad, the issue was coming from the partition's mouting options : it was missing the attributes uid and gid. I finally fixed it by adding these attributes :
`uid=yourusername,gid=yourusername`
I can use Notable on Ubuntu at last !
Thanks !
