### ISSUE TITLE
Buttons at window top-left don't move / resize when zooming in or out

### ISSUE THREAD

**Issue by dwilson5** [notable/notable#1125]
- **OS Version**: macOS Catalina (10.15.3) (and also macOS Mojave (10.14.6)
- **Notable Version**: 1.8.4

### Current behavior

When zooming in or out (`% +` and `% -`), buttons at top-left of window (i.e. close, minimize, full-screen) don't resize/readjust and cover other components if zooming out too far.

### Expected behavior

Buttons at top-left corner of window should resize / move with title bar when zooming in or out, or title bar could keep zoominess. Basically, the text is pretty large and I want to make it smaller so I can see more of my document

**Comment by fabiospampinato** [comment]
Those window control buttons are not meant to be resized too, they are controlled by the OS.

However there should still be a constant space left for them, so that these issues don't occur, I've already implement this actually, the fix be available in v1.9.
