### ISSUE TITLE
KISS - keep it short and simple

### ISSUE THREAD

**Issue by amunicapunica** [notable/notable#1134]
### enhancement

Reading all those enhancement topics, i just want to add a wish so i don't have to wait for another program again: please dont overload notable with quirky functions and much blingbling effects (metaphorically speaking). Imo, enhancements should focus on the following:
-running smoothly even with LOTS of notes
-smooth search
-making it possible to change one's notes and names or links without making the "card house fall"

many cool functions, that don't serve productivity per se could maybe be better offered as optional plugins?

Greets and keep going (Y)

**Comment by fabiospampinato** [comment]
I agree with anything 👍 and I think the app is tending toward complexity, but more for me really, for the user it should get a lot more powerful _and_ even more uncluttered potentially (with the ability to remove unwanted buttons for example).
