### ISSUE TITLE
Application preference to have Tags/Notebooks collapsed by default. 

### ISSUE THREAD

**Issue by amitn322** [notable/notable#1135]
### Feature description

Application preference to have Tags collapsed by default
### Feature motivation

Having the tags is awesome, but sometimes becomes confusing when you have a lot of notes. It would be nice to be able to force tags disabled by default. I can collapse right now, but every time notable is restarted, it is expanded. May be adding both Notebooks and Tags option to collapse/expand by default would be great addition.

**Comment by fabiospampinato** [comment]
I think adding support for remembering their collapsed state would be better, let's track this here: #339
