### ISSUE TITLE
Scrolling Past Last Line

### ISSUE THREAD

**Issue by Quigley-Brendan** [notable/notable#1138]
### Feature description

I think this is simple enough, I want to be able to keep the last line in the file closer to the centre of the screen instead of at the bottom. Right now when I'm writing a new note, once I get to the bottom of window unless I hit enter a bunch of times and create a bunch of blank lines the last line stays right on the bottom of the screen. 

I would like to be able to scroll past the last line without adding  a bunch of lines like this.

### Feature motivation

The first time I noticed it I intuitively tried to scroll past the line, and was surprised when it didn't work.

**Comment by fabiospampinato** [comment]
Triggering `Alt+L` should toggle this, have you tried it?

**Comment by Quigley-Brendan** [comment]
Alt+L shows line numbers.

**Comment by fabiospampinato** [comment]
Right, sorry, I should have said `Alt+B`.

**Comment by WilliamSBunin** [comment]
Where can I find a list of these shortcuts? Both of these are really nice.

**Comment by fabiospampinato** [comment]
@WilliamSBunin Help -> View Shortcuts.

**Comment by Quigley-Brendan** [comment]
This is Perfect! Amazing.
