### ISSUE TITLE
Sort by recently edited

### ISSUE THREAD

**Issue by codeHatcher** [notable/notable#1146]
### Feature description

Allow not only ordering of notes by title but also by "most recently edited"

### Feature motivation

Most other note-taking apps do this. Other apps doing something is not always a good reason but I believe the use case is I often have a better idea of notes that I took recently and those are the ones that will be more relevant to me when i'm making edits. I often say, "Oh I was just editing that note" and don't remember that title but remember I was editing it a few days ago. iOS/MacOS notes is an example of a good, simple, user experience of this

Also sometimes you may want to order by "note create date" but I rarely have had that use case with my notes

**Comment by fabiospampinato** [comment]
It's already implemented, click "Title" right below the search bar.

**Comment by codeHatcher** [comment]
Ah thanks! I tried it a couple of times and assumed the only thing you could click on was the bar on the right
