### ISSUE TITLE
Last AGPL release

### ISSUE THREAD

**Issue by prio** [notable/notable#1166]
Hi. You state in https://github.com/notable/notable/blob/master/SOURCE_CODE.md that the last AGPL release was v1.5.1, however a brach tagged v1.7.3 (https://github.com/notable/notable/tree/v1.7.3), with a version of 1.5.1, is also available under an AGPL licence. Can you please confirm the code in this v1.7.3 branch was the last AGPL release? Thanks.

**Comment by fabiospampinato** [comment]
Whatever the latest version available in the repo is the latest AGPL version available, that's still v1.5.1 though: https://github.com/notable/notable/blob/5268525128fd3a7d3d07e276afb76d0cb5a8f452/package.json#L5

Only some metadata files got updated to v1.7.3, like the readme and the changelog.

**Comment by prio** [comment]
Thanks
