### ISSUE TITLE
Using Notable as bookmark manager guidelines

### ISSUE THREAD

**Issue by Armagedoom** [notable/notable#1167]
I'd like to ask if someone is using Notable as a bookmark manager, and which would his guidelines on this use be.
I think there is probably a very good way to use notable as a bookmark manager, but cant really think of a perfect way yet.

Thanks!

-- Edit --
Not sure if this questions belong here, if not, please feel free to delete the issue.

**Comment by fabiospampinato** [comment]
That'd be an interesting use case. You might want to ask this question in the subreddit instead: https://www.reddit.com/r/Notable/, there'd be more likely that somebody sees it. I personally don't do anything special regarding bookmarks other than bookmarking websites in the browser I wouldn't really know what to recommend.
