### ISSUE TITLE
MacOS Spellcheck doesn't work

### ISSUE THREAD

**Issue by codeHatcher** [notable/notable#1173]
- **MacOS 10.15.4 (19E287)**:
- **1.8.4**:

### Current behavior

Incorrectly spell a word in a note. The OS spellcheck won't pick up the spelling error

### Expected behavior

I expect the built-in MacOS spell check to continue to working. I know there is a thread about built in notable spell checking but I am just talking about the MacOS spell check that shows up in any text field

Side note: the normal mac text context menu doesn't work in general

**Comment by fabiospampinato** [comment]
I'm not sure we should spell-check inputs too 🤔

**Comment by codeHatcher** [comment]
I don't think we need to let macos spellcheck the inputs but we should be letting macos spellcheck the markdown field

**Comment by codeHatcher** [comment]
As an example, in any mac text field the built in macos spell checker will underline the incorrect spelling such as my screenshot below 
![image](https://user-images.githubusercontent.com/5360982/83366370-7a781000-a363-11ea-94c3-41313237dc91.png)

however in notable this doesn't seem to be working when entering markdown

**Comment by codeHatcher** [comment]
here is a relevant github issue in the electron repo https://github.com/electron/electron/pull/20692 and here is one of the original discussions about it https://github.com/electron/electron/issues/3189 (make sure you read toward the bottom as it is a very old issue)

**Comment by fabiospampinato** [comment]
> I don't think we need to let macos spellcheck the inputs but we should be letting macos spellcheck the markdown field

Let's track this in the main issue about spell checking then: #108 

We can't just make macOS spell-check the editor, that's more like a webpage than an input really, and we need to sort of reimplement the spell checking anyway because the app needs to run in the browser too.
