### ISSUE TITLE
Add padding to editing space in Zen mode

### ISSUE THREAD

**Issue by CatalanCabbage** [notable/notable#1181]
### Feature description
When editing in Zen mode, the text area starts from the left till the right end. This length is not required. We can add padding on both sides and center the text area to improve usability, or at least add an option to.

### Feature motivation
Very difficult and unnatural to start typing text in a blank screen from the *absolute* left edge. We should add lots of padding.

**Comment by fabiospampinato** [comment]
Already implemented, it will be available in v1.9.
