### ISSUE TITLE
Settings for V1.9alpha

### ISSUE THREAD

**Issue by erex** [notable/notable#1184]
- Windows 10
- **Notable Version**: 1.9 alpha

### Current behavior

When viewing `Settings`, tabs exist but nothing else
![image](https://user-images.githubusercontent.com/330744/84386856-f9820980-abe9-11ea-87dc-3ba5e667740f.png)

### Expected behavior
Hoping to see some settings to play with

**Comment by fabiospampinato** [comment]
I'll take a look at this soon! Do the editors show up if you switch back and forth between the tabs? ore between the settings and shortcuts editor?

**Comment by erex** [comment]
Nothing appears in either Settings or Shortcuts regardless of which Tab is highlighted.

**Comment by fabiospampinato** [comment]
@erex Can you try the latest alpha? I fixed an issue that could have caused this in the latest one.

**Comment by erex** [comment]
Can confirm all Tabs of both Settings and Shortcuts are populated when using 1.9 alpha 5.

**Comment by fabiospampinato** [comment]
Awesome, this was pretty weird because I could only reproduce after updating Electron to v8.3.3 🤷‍♂️
