### ISSUE TITLE
Emoji insert

### ISSUE THREAD

**Issue by erex** [notable/notable#1185]
Perhaps ignorance on my part, but I don't know how to insert an Emoji.  The Emoji palette can be shown via:

Go | Standalone Palette | Emoji

but don't know how to insert into document.

**Comment by fabiospampinato** [comment]
The emoji palette just copies the selected emoji into the clipboard, does it do that for you? It's not super useful really, what we want is actually emoji autocompletion #103, which isn't here yet.

**Comment by erex** [comment]
yes, does copy into clipboard, which needs a second step to paste from clipboard into document

**Comment by fabiospampinato** [comment]
Maybe it should just write the emoji in the editor by itself 🤔 That's totally doable, I'll look into it
