### ISSUE TITLE
PDF Export Fails to Export Notes

### ISSUE THREAD

**Issue by JFM9** [notable/notable#1199]
- **OS Version**: Windows 10
- **Notable Version**: 1.8.4

### Current behavior
When exporting a markdown file to PDF, the images are exported to the `attachements` folder, but the PDF is never created. No error messages are displayed, nor is progress displayed.

In this case, the markdown file is of 32KB with a handful of images. Smaller file markdown files export without issue.

### Expected behavior
When exporting markdown notes to PDF, the PDF should be created and exported to the user's desired location.

Additionally:
1. Progress to be displayed
2. Displaying the status of the export (successful or failed)

**Comment by fabiospampinato** [comment]
I think this issue got fixed in the v1.9 alpha versions, you can find them in the chat (https://chat.notable.app) or what for v1.9 final to get released.

> Progress to be displayed
> Displaying the status of the export (successful or failed)

Can you open separate issues on this?

**Comment by JFM9** [comment]
@fabiospampinato I'll open a separate issue for the suggested UI changes.

Thank you for your prompt reply.
