### ISSUE TITLE
Pasting images from clipboard does nothing

### ISSUE THREAD

**Issue by ogglO** [notable/notable#1201]
- Windows 10
- v1.9.0-alpha.8

### Current behavior

Pasting an image from the clipboard into the editor does nothing. 

### Expected behavior

The image should be pasted into the attachement folder and the appropriate markdown added to the editor (behaviour in 1.8.4).

**Comment by mHatsune** [comment]
https://github.com/notable/notable/issues/1201

**Comment by epmoyer** [comment]
As of v1.9.0-alpha.15 on OSX, pasting images from the clipboard:

- Works (adds attachment, pastes link) from the dropdown menu (Edit -> Paste)
- Does not work (does nothing) from the command palette ("Editor: Paste")
- Does not work (does nothing) from the keyboard shortcut (⌘V)

Pasting plain text works using all 3 methods listed above.

**Comment by AldieNightStar** [comment]
I would add - i have notes folder with name `C#`. But there is pasting, but images are not rendered anyhow. Problem is inside path-name "#" at the end of name

**Comment by fabiospampinato** [comment]
@AldieNightStar Can you reproduce the issue with the alphas of v1.9? https://github.com/notable/notable-experimental/releases/tag/v1.9.0-alpha.19

**Comment by ogglO** [comment]
Sorry this took a while, but just to complete the original issue:
I just tried 1.9 beta 2 and it works as expected on Windows.

Thanks!
