### ISSUE TITLE
Open NOte in New Window

### ISSUE THREAD

**Issue by mikejones3** [notable/notable#1202]
### Feature description

I would love to be able to open a note in a new window.

### Feature motivation

Some times I want two different notes open at the same time. One on each monitor. One for reference and one for typing in. Really helpful when trying to link two notes together.

**Comment by fabiospampinato** [comment]
Let's track this here: https://github.com/notable/notable/issues/60

Although not exactly the same thing in practice implementing that would mean implementing this as well.
