### ISSUE TITLE
Is there a way to customize syntax highligting?

### ISSUE THREAD

**Issue by DannyDeLoach** [notable/notable#1204]
I love many features of Notable. Thanks for creating this great software!

It would be nice if there was a way to customize syntax highlighting. In the editor I created a code block like this:
![image](https://user-images.githubusercontent.com/24360823/85653366-f6235f00-b67a-11ea-8ed1-daa01e7d3d00.png)

[Note: I inserted a screenshot of the markdown text rather than the actual text. Otherwise, Github was rendering the text within this post.]

When I click Stop Editing, the code appears like this:
![image](https://user-images.githubusercontent.com/24360823/85653122-9f1d8a00-b67a-11ea-8d50-9c40ff6c9e49.png)

In VS Code the same text is highlighted like this:
![image](https://user-images.githubusercontent.com/24360823/85653612-47335300-b67b-11ea-9aa0-1e9d7a70b9a5.png)

Is there a way to customize the syntax highligting in Notable, so that I can make it appear the same as (or more similar to) the syntax highlighting in VS Code?

**Comment by fabiospampinato** [comment]
All colors are customizable with the v1.9 alphas. Custom syntax highlighters can't be added, let's track this here: #128
