### ISSUE TITLE
Edits not saved to disk if 'group' is not allowed to write

### ISSUE THREAD

**Issue by cancelliere** [notable/notable#1205]
* OS Version: Debian 10
* Notable Version: 1.8.4

## Problem
If the ownership of a `.md` file is set to a group not having writing permissions, Notable does not modify the stored file and does not report any error. Until the app is open, the changes are visible within the app, but the new edits are lost when closing and reopening.

## Steps to recreate
```bash
cd <your_notes_folder>
echo "1-Correct" > 1-Correct.md
echo "2-Buggy" > 2-Buggy.md
sudo chown <username>:<some_group_without_writing_permissions> 2-Buggy.md
```
Do some edits from Notable on both files, save them and check with a different editor or by closing and reopening Notable.

**Comment by fabiospampinato** [comment]
@cancelliere Could you check what happens under one of the v1.9 alphas? https://github.com/notable/notable-experimental/releases

I think an error should be displayed there, maybe only in the devtools, and possibly a temporary file containing the updated note should remain written on disk.

**Comment by cancelliere** [comment]
Thanks for the quick reply!
In the alpha version the problem disappears.

Quite unexpectedly though, Notable can save to disk even if all writing permissions (user, group and others) to the file are denied.

**Comment by fabiospampinato** [comment]
@cancelliere The app isn't really writing to the that file, it's replacing it with something else, so I guess writing permissions set on it don't matter.

v1.8 should do this as well though, I'm not sure why that wasn't working 🤔
