### ISSUE TITLE
Cannot type @ in germany kayboard layout (ALT-L)

### ISSUE THREAD

**Issue by ordnungswidrig** [notable/notable#1206]
- **OS Version**: MacOs 10.14.6 germany keyboard layout
- **Notable Version**: 1.8.4

### Current behavior

`ALT-L` is bound to toggle line numbers in the editor, this clashes with the german keyboard's combination to enter the `@` sign.

### Expected behavior

No keybinding clashes with standard / system keybindings.

**Comment by fabiospampinato** [comment]
That shouldn't be a problem anymore in v1.9, you can get one of the alphas here: https://github.com/notable/notable-experimental/releases
