### ISSUE TITLE
notable is open-source or not?

### ISSUE THREAD

**Issue by fazlearefin** [notable/notable#1213]
The table in https://notable.app/static/images/comparison.png says notable is open-source up to version v1.5.1. _Does that mean that parts of the latest version v1.8.4 is closed-source?_

(Apologies for the obvious but I fail to understand how can it be not open-source when you have notable code repo open to the world)

**Comment by fabiospampinato** [comment]
> The table in notable.app/static/images/comparison.png says notable is open-source up to version v1.5.1. Does that mean that parts of the latest version v1.8.4 is closed-source?

Correct. I would say more like parts of v1.8.4 are open-source rather.

> (Apologies for the obvious but I fail to understand how can it be not open-source when you have notable code repo open to the world)

Where's the code for v1.8.4?

**Comment by fazlearefin** [comment]
> Where's the code for v1.8.4?

My bad. 

Hope to see notable open-sourced again once you figure out licensing issues https://github.com/notable/notable/blob/master/SOURCE_CODE.md
