### ISSUE TITLE
GitHub is no longer showing images on the front page

### ISSUE THREAD

**Issue by yatesco** [notable/notable#1214]
no time to fix - just reporting in passing - sorry :-)
![Screenshot 2020-06-28 at 11 24 55](https://user-images.githubusercontent.com/181469/85944898-07e25c00-b932-11ea-92e3-1deecdfe96dc.png)

**Comment by fabiospampinato** [comment]
Looks like a temporary network issue, the badges' icons loaded after all.

**Comment by yatesco** [comment]
Still not showing six or seven images for me on the phone

**Comment by fabiospampinato** [comment]
I don't see what else could cause this for you.

What happens if click on one of the images that's not loading?

**Comment by yatesco** [comment]
It shows the image - weird. This is on both safari macos and iOS:

**Comment by fabiospampinato** [comment]
Hard refreshing the page should work then 🤔

**Comment by fabiospampinato** [comment]
Wait I can totally reproduce under Safari. That seems odd at best.

**Comment by fabiospampinato** [comment]
It's an issue with GitHub + Safari inability to render webp images, I can fix it, thanks for reporting the issue 👍

**Comment by yatesco** [comment]
Reset iOS Safari and same problem- I’ll try macos later

It works for you then?

**Comment by fabiospampinato** [comment]
It works on Chrome, it's broken on Safari because github is proxying the request and telling my server that it supports webp images, it then sends you the webp image which safari can't render.

**Comment by fabiospampinato** [comment]
I just fixed this.

@yatesco thank you very much for reporting the issue!

**Comment by yatesco** [comment]
confirmed - works for me after a cache clear out - nice work :-)
