### ISSUE TITLE
Direct input, editing and preview

### ISSUE THREAD

**Issue by mHatsune** [notable/notable#1220]
Don't blame me, this feature request about to change how notable work ;)

#### Current Behavior 
Default mode display "unformatted texts" and anything else we write using markdown(lists, font styles, tables) or other attachments only able to see once finished editing.

#### Expected Behavior 
Let us to see the preview real time same as any other text editing and note taking softwares.

**Comment by fabiospampinato** [comment]
Duplicate of #284
