### ISSUE TITLE
Ability to edit images size

### ISSUE THREAD

**Issue by mHatsune** [notable/notable#1221]
#### Current Behavior 
Only allow to add as attachments and no previews

#### Expected Behavior 

Display preview by default and let users to change size, movable around note page however original image necessary to remain in note folder

**Comment by mHatsune** [comment]
https://github.com/notable/notable/issues/1220

**Comment by fabiospampinato** [comment]
> Only allow to add as attachments and no previews

What do you mean? You can already just link to attachments without rendering them.

> Display preview by default and let users to change size, movable around note page however original image necessary to remain in note folder

That's kind of already implemented in v1.9, in the sense that you can set a custom width and height the attachment will be rendered at.

**Comment by mHatsune** [comment]
> That's kind of already implemented in v1.9, in the sense that you can set a custom width and height the attachment will be rendered at.

I didn't mean it. See below screenshot and this also need #284  

![image](https://user-images.githubusercontent.com/63988538/86549848-b3675e00-bf7b-11ea-835e-c97d325432b8.png)
(onenote let user to change size and move image to place on prefer area on note page)

1.9.0-alpha.14

**Comment by fabiospampinato** [comment]
I'd consider this part of the WYSIWYG then #284
