### ISSUE TITLE
more hierarchy

### ISSUE THREAD

**Issue by Akshaythorat376** [notable/notable#1225]
### Feature motivation

 more the choice better.

**Comment by fabiospampinato** [comment]
In the hierarchy spectrum you can nest tags and notebooks inside each other, and you can have multiple data directories. I'm not sure what you are proposing would add to this, are you asking for a way to have multiple data directories open at the same time?

**Comment by Akshaythorat376** [comment]
I am suggesting this so that those migrating from evernote will feel a bit familiar. Because, in evernote you can organize multiple notebooks into stacks.
I wasn't talking about data directory.

**Comment by fabiospampinato** [comment]
Here you can have notebooks inside other notebooks, that should suffice I think.
