### ISSUE TITLE
Sharing via link

### ISSUE THREAD

**Issue by kwolfy** [notable/notable#123]
I propose to implement the ability to share a link to your md file so you can view it using a browser. 

First, we must make notable-server which everyone can to run on his server. This server should be able to generate a secret,

The user adds a server to the notable at its address, notable automatically generates a secret for the user and in the future all publications are carried out with this secret. 

When user publishes "note", the notable-server generates a unique link that user can share with others

If you are ready to accept these changes, I can implement all this and send PR.

Thank you!

**Comment by kwolfy** [comment]
So, do you support this ?

**Comment by fabiospampinato** [comment]
Not really, I don't feel ready to define how I'd like the future server to work.

**Comment by fabiospampinato** [comment]
I'm closing this in favor of better export support #14. Let's keep track of other features similar to this one in the issue about the web app #83.

**Comment by elliotcoupe** [comment]
Hi, I'm a little bit confused about your sharing function. When I clicked the sharing icon in my note, the md file will be opened in Bracket. 
What I was expected is that safari our mail be opened. Is the existing of the Bracket causing the issue or something else?

**Comment by fabiospampinato** [comment]
@elliotcoupe there's no "Sharing icon" currently, what you clicked is the "Open in Default App" button, which opens the file in its default opener.

I'm reopening this issue since in hindsight it would be pretty interesting to implement something like this once we have a server.

**Comment by fabiospampinato** [comment]
Actually this has been implemented, albeit in a very raw way. I'm closing this but I plan on improving a lot on the current implementation.

**Comment by wjt199** [comment]
Can you set an expiration time for the share link, which can better ensure the security of the information.THX

**Comment by wjt199** [comment]
Hello, I'm a little bit confused about sharing function. Can you add an expiration time for the sharing link, which can better ensure the security of the information.

**Comment by MMK21Hub** [comment]
There's already support for setting an expiry time (TTL) to shared notes. Simply set a number of milliseconds in the `sharing.ttl` setting. You might also want to check out the `sharing.password` setting for added security.

**Comment by fabiospampinato** [comment]
And there's a default expiration time of 24h. The interface for sharing will be re-done after the next release.
