### ISSUE TITLE
Movable folders, files, tags and notes

### ISSUE THREAD

**Issue by mHatsune** [notable/notable#1261]
**Features**
- Ability to move by mouse or keyboard alt+up/down
- Ability to drag and drop certain child to another main folder or tag

Isn't it possible to edit certain note tag? but above features may save our time

![image](https://user-images.githubusercontent.com/63988538/86990551-cbd3b480-c1d7-11ea-8a7d-3e6f61f5b996.png)

**Comment by fabiospampinato** [comment]
The drag&drop part of this is tracked here: #15 

The keyboard part of this I don't think it's necessary 🤔 as in order to implement it we would need to require to user to think about where the focus is all the time, and that introduces unnecessary complications IMHO.

**Comment by mHatsune** [comment]
sorry for bad illustrations. either mouse or keyboard. it doesn't matter ;)
however you know this if use keepass

![image](https://user-images.githubusercontent.com/63988538/87103878-372d8d00-c291-11ea-8695-ec81e2d2e26e.png)
