### ISSUE TITLE
Unordered lists break task check marks in preview mode

### ISSUE THREAD

**Issue by JoshCooley** [notable/notable#1264]
- **OS Version**: macOS 10.15.5
- **Notable Version**: 1.8.4

### Current behavior

Create an unordered list with a task, followed by a task, i.e.:
```
* - [ ] foo
- [ ] bar
```
Switch back to preview mode.

Here's how it looks before attempting to check either of the tasks:

![image](https://user-images.githubusercontent.com/4670883/87212603-024b2580-c2e5-11ea-8c61-f537d998c73a.png)

Clicking the **second** task ("bar") does nothing.
Clicking the **first** task ("foo") actually checks the second box. Here's how it looks after that:
#### Rendered:
![image](https://user-images.githubusercontent.com/4670883/87212694-738ad880-c2e5-11ea-94e3-2d82450bc823.png)
#### Markdown:
![image](https://user-images.githubusercontent.com/4670883/87212700-7dacd700-c2e5-11ea-9aa0-6c4e3afd67f6.png)

### Expected behavior

Clicking a task check box should change the corresponding task's state by checking the box in preview mode and adding an `x` between it's opening and closing brackets.

**Comment by JoshCooley** [comment]
I'm actually not sure if that first task should show up at all. I just noticed the brackets aren't colorized in editing mode.

**Comment by fabiospampinato** [comment]
This stems from my ignorance that this should actually works: `* - [ ] foo`, github handles it fine so should Notable, thanks for reporting the issue 👍

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
