### ISSUE TITLE
[Feature Request] double-click in document to enable edit

### ISSUE THREAD

**Issue by venil7** [notable/notable#1273]
### Feature description
double clicking anywhere in document enables edit mode

### Feature motivation
clicking an edit button is not always convenient,  double clicking anywhere in document instead would be a great alternative

**Comment by fabiospampinato** [comment]
This is already implemented in the alphas: https://github.com/notable/notable-experimental/releases

You need to Ctrl+DoubleClick (or Cmd+DoubleClick on macOS) though.
