### ISSUE TITLE
Pressing command+L toggles line numbers instead of writing '@'

### ISSUE THREAD

**Issue by hirasso** [notable/notable#1277]
- **OS Version**: 10.14.6 (18G103)
- **Notable Version**: 1.8.4

### Current behavior

Pressing command+L toggles line numbers

### Expected behavior

Pressing command+L should output an `@`

**Comment by fabiospampinato** [comment]
Switch to the alphas of v1.9 or wait for the final release, that's been fixed there: https://github.com/notable/notable-experimental/releases
