### ISSUE TITLE
Option to disable keyboard shortcuts temporarily

### ISSUE THREAD

**Issue by gmrukwa** [notable/notable#1278]
Thanks for this sooooo useful tool! You're the boss! 👏 

### Feature description

I'd love to see an option to disable keyboard shortcuts temporarily (until enabled again) from the menu bar.

### Feature motivation

When you write plain English, it's all good. But I can't enter a lot of Polish characters like `ź` (`Option` + `x`), `ł` (`Option` + `l`) and so on. I love using Notable, but this issue brings me back to TextEdit / vim on Mac.

**Comment by fabiospampinato** [comment]
Switch to the alphas of v1.9, no need to temporarily disable shortcuts anymore: https://github.com/notable/notable-experimental
