### ISSUE TITLE
Unable to nest html tags (details tag)

### ISSUE THREAD

**Issue by UjwalNK** [notable/notable#1281]
- **Ubuntu 20.04**:
- **Notable-1.8.4.AppImage**:

### Unable to nest HTML tags to render html

Have the following in the md File:
[md.zip](https://github.com/notable/notable/files/5040922/SQL.copy.zip)

**Comment by fabiospampinato** [comment]
The way mixing HTML and Markdown works is pretty weird, you have to leave an empty line before and after the markdown part to make the rest recognized as Markdown. Or in Notable you can wrap the markdown in a `<markdown>` tag.
