### ISSUE TITLE
Opening a directory with notable command in terminal

### ISSUE THREAD

**Issue by zemse** [notable/notable#1288]
### Feature description

Through terminal, one can be able to do:

```sh
$ notable .
```

or 

```sh
$ notable workspace/notes/CS-101
```

This opens notable in that directory. If that directory is not a notable directory, then it may just print out this in terminal.

### Feature motivation

Since for github, I am already supposed to open the directory in terminal, there could be a handy way to open a notable based project directory, just like we can open vscode.

```sh
code .
```

**Comment by fabiospampinato** [comment]
Let's track that here: #667
