### ISSUE TITLE
Windows Download isn't working

### ISSUE THREAD

**Issue by param211** [notable/notable#1290]
- **OS Version**: Windows 10
- **Notable Version**: 1.8.4

### Current behavior

Download windows version from https://notable.app/

The downloads starts but soon fails showing "network error"

EDIT: tried this on multiple devices

**Comment by fabiospampinato** [comment]
I guess you really experienced some network errors then 🤔 

You can download it from here too: https://github.com/notable/notable/releases

Does that work for you?

**Comment by param211** [comment]
Well, I checked again today and it worked!
It's weird because I tried downloading for an entire day from multiple devices and it didn't work. But now its working.

Thanks for the quick response!
