### ISSUE TITLE
Dialog box is not needed when closing/minimize Notable on OSX

### ISSUE THREAD

**Issue by fabiosirna** [notable/notable#1291]
- **OSX 10.15.6 Catalina**:
- **Notable Version 1.8.4**:

### Current behavior

- Click on the red button on the OSX windows to close/minimize/put in background Notable
- A dialog box appears and ask if I'm sure to to do this [screenshot](https://www.dropbox.com/s/xwcjmivr703k5tq/Screenshot%202020-08-25%20at%2009.34.54.png?dl=0)
- Click on yes to close the modal and minimize Notable

### Expected behavior

- Click on the red button on the OSX windows to close/minimize/put in background Notable
- Notable is minimized in the background (stay in the dock, with dock)[screenshot](﻿﻿﻿https://www.dropbox.com/s/bsfpa0l6cwhl45f/Screenshot%202020-08-25%20at%2009.44.54.png?dl=0)

**Comment by fabiospampinato** [comment]
That's been removed in the alphas of v1.9 https://github.com/notable/notable-experimental/releases
