### ISSUE TITLE
On-hover toolbar in Zen mode

### ISSUE THREAD

**Issue by fabiosirna** [notable/notable#1295]
### Feature description

Switching to zen mode will make the toolbar disappear. It's hard to switch between edit/view mode unless using the CMD+E shortcut.

### Feature motivation
2 user stories:

As a user in the zen mode scenario I want to use the editing toolbar so that I can access the edit functionality with the mouse (e.g. edit tags, attachments, toggle edit/view etc). 

As a user in the zen mode scenario I want to show/hide the editing toolbar on mouse over so that I can access the editing functionalities.

The second story is to keep the zen mode as a "full zen mode": the toolbar can appear/disappear as soon as the user is interacting with the mouse close to the top area.

**Comment by fabiospampinato** [comment]
Doable but the current toolbar might be wider than the available space, it requires some modifications to be able to display well in any case.

**Comment by fabiosirna** [comment]
Thanks for heads up. Do you have a Figma or Sketch files of notable to share? I can create a quick prototype to test the idea before spend time on developing

**Comment by fabiospampinato** [comment]
Nope, I don't (can't really) do any proper mockups.

**Comment by fabiospampinato** [comment]
It's pretty clear how to implement that though, the on-hover toolbar, albeit currently empty, is already implement for the macOS version fo the app as there otherwise there would be no other way to drag the window of the app around in zen mode.

What's left is making the toolbar work decently in narrow widths, which essentially mean moving actions from the toolbar to a dropdown menu if they don't fit.

**Comment by fabiosirna** [comment]
Hi @fabiospampinato ,
I made a [prototype](https://www.dropbox.com/s/q3ik9ny6zldloo7/Notable%20-%20Zen%20Mode%20prototype.mp4?dl=0) in Figma to explore the idea. I didn't yet investigated what happens when you narrow the width, but I see what you mean.
I reviewed also some icons (based always on the Material theme) but I'll explain this in another concept.

Let me know what you think!

**Comment by fabiospampinato** [comment]
@fabiosirna loved the video 😂 Commenting on it:

- First of all if you are not on the alphas of v1.9 you should try them, quite a few things changed, even UI-wise https://github.com/notable/notable-experimental/releases
  - Also if you have other general suggestions I'd be happy to hear/watch them, especially if they would make the UI simpler overall
- I should probably add transitions when toggling elements of the UI, it's a bit tricky to implement though I think, let's not do it for now
- The thing that you added to the toolbar looks useful but also takes a lot of space (i.e. there won't be enough space for it under some circumstances), maybe I could add a similar popover that's triggered from an icon in the statusbar or something, would you like that? Showing the statusbar in zen mode might be problematic though 🤔 And/or maybe I should add a dedicated palette for this.

**Comment by fabiosirna** [comment]
hey @fabiospampinato thanks, much appreciated :)

I discovered and I started using the experimental version only after I made the prototype :( So yes, the prototype is not aligned. But I don't see any problem updating it. I made a Figma prototype a created all the basic components, so it'd be easy to update.

Transitions: I agree with your approach, and it's safe to don't have it. In the prototype I'm using a smart animation transition that is not perfect, but...hey it's just a prototype and just wanted to see what happens :) For sure they will help, but I agree with your approach and they should be that latest things to explore.

I leveraged the current toolbar design to not completely disrupt the application. I see that there are some tricky points to solve here. Let me use the experimental a bit and try to rework on the prototype a bit.

BTW are you foreseen a mobile/responsive version? Because I was playing a bit with what I made and starting exploring a responsive version as well, where the sidebar collapse. The idea was to have a responsive view on the desktop to take notes in a smaller window. Solving these points in the smaller screen will help for sure solve them for the desktop as well. 

In any case, let me do some explorations and I'll come back.

**Comment by fabiospampinato** [comment]
> But I don't see any problem updating it. I made a Figma prototype a created all the basic components, so it'd be easy to update.

Yeah pretty much everything in your video maps to the alpha releases pretty cleanly too.

> I leveraged the current toolbar design to not completely disrupt the application. I see that there are some tricky points to solve here. Let me use the experimental a bit and try to rework on the prototype a bit.

As a rule of thumb anything can be changed, if there's a good enough reason for doing so.

> BTW are you foreseen a mobile/responsive version?

Yes, for the most part I think I'll just move the sidebar(s) to a drawer or something.

**Comment by fabiosirna** [comment]
Hi @fabiospampinato 

I reviewed the prototype and made [another video](https://www.dropbox.com/s/aj57jj5r8fcxu3v/Notable%20-%20Prototype.mp4?dl=0) :)

I'm using the experimental since last time and reviewed the layout in order to match the latest version.

I start designing a mobile/responsive version first and then designed the interaction for the desktop one. You can watch the respoinsive version at the end of the video.

In the video you can see:

- how the general navigation is working; 
- a solution for hiding the sidebar but let the user navigate to the notebooks or notes;
- zen mode, with a redesigned toolbar (at the bottom) that can work as well on the mobile/responsive version; the idea is that if the user can resize Notable to the size of a mobile screen, he can keep it aside to another software and write notes on the same screen; the toolbar has also the action to switch between view/edit mode and turn on/off the zen mode (in the current version is only possible via keyboard shortcuts).

Please let me know what do you think.

**Comment by fabiospampinato** [comment]
@fabiosirna There's quite a bit to comment on. Overall I mostly like the mobile experience, the tweaks to the desktop interface less so, they don't seem to be adding much of value 🤔 there's another mockup somebody else made that I still have to provide detailed feedback on, I'll probably record a video about both yours and his at some point.

**Comment by fabiospampinato** [comment]
If you join the [chat](https://notable.app) I posted a video there a couple of days ago about a demo fo this working in the development version of the app: https://discord.com/channels/715934079559663646/737629614712815708/753713816382210149
