### ISSUE TITLE
Export to PDF results in gibberish 

### ISSUE THREAD

**Issue by pl98** [notable/notable#1298]
- **OSX 10.15.6**:
- **1.8.4**:

### Current behavior

Export to pdf as normal. Resulting PDF is formatted correctly but all the characters are gibberish. Screenshot is attached. 

![image](https://user-images.githubusercontent.com/29090662/91874060-c29b1d00-ec47-11ea-8a7e-4fbcf04023ca.png)

**Comment by pl98** [comment]
This appears to happen only when italics exist in the document. A document without italics exports normally.

**Comment by fabiospampinato** [comment]
Another reason not to upgrade to macOS ~~Vista~~ Catalina.

Upstream issue: https://github.com/electron/electron/issues/21724

Duplicate: #1031 

> This appears to happen only when italics exist in the document. A document without italics exports normally.

That's interesting 🤔 Do you happen to have any custom fonts installed in your system?

Maybe hop in the [chat](https://chat.notable.app/), the next alpha of v1.9 I'll post there should have a potential workaround for this issue.

**Comment by pl98** [comment]
I have some custom fonts installed I think, but how would that affect this?

**Comment by fabiospampinato** [comment]
I remember reading somebody's comment about that hypothesis, I don't know how that person came up with it or how that's supposed to cause the issue you are experiencing.
