### ISSUE TITLE
Resize Pasted Images

### ISSUE THREAD

**Issue by ijoseph** [notable/notable#1307]
### Feature description
Would like to be able to resize linked images with the 
```
![](image_url.png =widthxheight)
```
syntax described [here](https://stackoverflow.com/a/21242579/588437). 

### Feature motivation

Quiver has this and I've gotten hooked on it. Without this feature, images can take up arbitrarily large amounts of room in the note, making it hard to read the rest of it. 

It's one of the few things (other of which being popout windows which may be in another request too?) keeping me from switching.

**Comment by fabiospampinato** [comment]
Switch to the alphas of v1.9, that's already implemented there: https://github.com/notable/notable-experimental/releases
