### ISSUE TITLE
Some keyboard shortcut that require Cmd+Ctrl together can't be used in Windows/Linux

### ISSUE THREAD

**Issue by jhuangn** [notable/notable#1321]
For example:
in MacOs: Cmd+Ctrl+Up to move a line up,
but in windows, you cannot simply change Cmd to Ctrl because Ctrl is already used, 
I tried many different combination but they don't work, it seems that in Windows/Linux you cannot these keyboard short.

**Comment by fabiospampinato** [comment]
Switch to the alphas of v1.9, those shortcuts have been changed and there you can assign any shortcut you want to any command you like: https://github.com/notable/notable-experimental/releases
