### ISSUE TITLE
give the ability to scan and delete unused attachments

### ISSUE THREAD

**Issue by tahsinature** [notable/notable#1326]
### Feature description
if I paste an image from the clipboard, and then undo & paste again, it's creating a different file with the same image based on the timestamp.

### Feature motivation
some type of command which will detect all the files in the attachments directory and scan all notes to filter unused attachments.

- it will reduce junk or unwanted files at attachments dir

![screencast 2020-09-30 18-29-51](https://user-images.githubusercontent.com/41298152/94680504-07e86280-034c-11eb-9f61-c03964429a03.gif)

**Comment by fabiospampinato** [comment]
Definitely useful.

Let's track this here, which is more general and will include this: https://github.com/notable/notable/issues/1216
