### ISSUE TITLE
Highlight selected note in tag tree hierarchy (left pane)

### ISSUE THREAD

**Issue by exislow** [notable/notable#1331]
### Feature description

I would like to have the path of the selected note (md document) highlighted in the tag hierarchy (left side). So I know where the note is saved/categorized.

### Feature motivation

Especially if I use the search it is often unclear what tag path hierarchy (left pane) is the selected note categorized to. Sure I could click on the tag icon and check it, but this is rather uncomfortable an not efficien.

Would be great, if you could implement this!

**Comment by fabiospampinato** [comment]
> I would like to have the path of the selected note (md document) highlighted in the tag hierarchy (left side). So I know where the note is saved/categorized.

We'll use notebooks for that (details outlined here: https://github.com/notable/notable/issues/54#issuecomment-622594915).

Plus there will be ways to list tags for the current note, and notes found via search, without needing to open the popover.

Eventually some plugin will be able to put the path of the current note in the statusbar or something, currently I don't think rendering the full path of notes anywhere permanent would be a good idea, but maybe I could add the path of notes to their tooltip or something, like the thing that sometimes shows up when hovering something, would that be useful to you?

**Comment by exislow** [comment]
Actually I have organized all my notes with notebook tags. So for me it would be enough if the notebook path of the selected note is highlighted / rendered (totally sufficient, if you just color the path different).

What would also be great is, if notable would render vertical and horizontal lines in the tree structure (left pane), e.g. https://www.jstree.com/plugins/ (but without this shitty icons / windows like design). It is much more ergonomic if you actually have horizontal and vertical lines in your tree structure you are looking at.

**Comment by fabiospampinato** [comment]
> So for me it would be enough if the notebook path of the selected note is highlighted / rendered (totally sufficient, if you just color the path different).

Let me get the change I mentioned in first, that could potentially be a good idea at that point.

> What would also be great is, if notable would render vertical and horizontal lines in the tree structure (left pane), e.g. jstree.com/plugins (but without this shitty icons / windows like design). It is much more ergonomic if you actually have horizontal and vertical lines in your tree structure you are looking at.

Let's track this here: https://github.com/notable/notable/issues/1334

**Comment by exislow** [comment]
Sure. Thank you for your effort.
