### ISSUE TITLE
Text Pre-processor

### ISSUE THREAD

**Issue by jaxmatrix** [notable/notable#1336]
### Feature description

Add a option for text pre-processing through a JavaScript File. This will help the user to enhance notable as per their need. They can just load their scripts and then their scripts modify the output of the markdown file to desired output. Like we can add dynamic content. For example we can define a string which can be parsed into creating a SVG image. 

### Feature motivation
I am a chemist and use markdown apps to write my notes a lot of time to draw diagram I have to switch between application to generate images and then take a snip and paste into the file. This process makes the process of taking notes tedious. To simplify the work flow, a lot of time I have to write scripts that convert text strings into molecular structures or update information via web. But these post processing has to be done outside the app then again open the app to reflect the output.

Using this feature we can update fields by fetching information from internet or make our own real time version controller that takes in data and save it in some place on cloud, and this feature will enable people to create features to make notable a much more functional app. 

One of the possibility is using the same pre-processing script we can add the collaboration option, via google docs like file is updated in google docs then output can be fetched to see what everyone is writing or one can host their own server on Heroku then do the collaboration etc. etc.

**Comment by fabiospampinato** [comment]
Absolutely, let's track this in the broader "plugins" issue: #128 

Regarding diagrams the app can already directly render PlantUML diagrams, mermaid diagrams and DOT diagrams.

Regarding doing some pre/post processing although that will be implemented in the form of a plugins API you can already do some level of postprocessing by injecting some code via v1.9's custom JS editor, so for example you could write a script that replaces codeblocks written in a particular language with something else. Retrieving the language and code each codeblock highlights should be easy, there are dedicated HTML attributes for that.
