### ISSUE TITLE
Use relative, exported attachments in HTML export

### ISSUE THREAD

**Issue by broox** [notable/notable#1337]
- **OS Version**: macOS 10.15.7
- **Notable Version**: 1.8.4

This is similar to the link discussion in #772, but is more about attachments than links. 

### Current behavior

When exporting a note that contains `img` attachments, the attachments are exported alongside the markup file as expected. However, the `src` references in the markup continue using the absolute path from Notable's original data directory. This means that when an exported document is shared to another location, all of the linked attachments break.

### Expected behavior

It'd be great if the exported HTML file used the exported attachments, and that any references in the markup were `relative` so that the images would remain functional after the exported files are moved or shared.

**Comment by fabiospampinato** [comment]
Let's track this in #772 too.
