### ISSUE TITLE
TItle layer 2 not interpreted

### ISSUE THREAD

**Issue by fulljackz** [notable/notable#1344]
- **OS Version**: Ubuntu 20.04
- **Notable Version**: 1.8.4

### Current behavior

Don't know with precision how to reproduce issue.
When I create a new note and start writing it, everything ok. When I come back to edit and add content with a second layer 2 title, save note and then it happens : ## Title is not interpreted.

I already solved this by using vim on .md file and deleting every characters between title and text and creating them again.

![2020-10-20_10-14](https://user-images.githubusercontent.com/12140932/96559322-2c858980-12bd-11eb-9e62-7f3def710974.png)

**Comment by fabiospampinato** [comment]
> ## Title 2 must be interpreted.

It is interpreted like everything else, but if you want that to be a heading you need to put a space between `##` and `Title`, currently there's a non-breaking space there which is why that's not an heading.
