### ISSUE TITLE
Replace Multiple Occurrences of text on the same line

### ISSUE THREAD

**Issue by rajashree921** [notable/notable#1345]
- **OS Version**: Windows 10 1903
- **Notable Version**: 1.8.4

### Current behavior

Type some text that occurs multiple times in the same line:
```
hello, this is a piece of text, this is a piece of text again and then some more words.
```

Select the first occurrence text (which occurs multiple times) that you wish to replace, say, `this is a piece of text`
<pre>
hello, <b>this is a piece of text</b>, this is a piece of text again
</pre>
Assuming the bold text has been selected press either:
-`Ctrl+Shift+L` which selects all occurrences
-`Ctrl+D` which selects current occurrence and the next occurrence of the selection (wrap search)

The text is not replaced correctly:
```
hello, foo, this is a piece of tfoo more words.
```
### Expected behavior

Text should be replaced correctly:
```
hello, foo, foo again and then some more words.
```
I noticed this happen only when the text selection occurs multiple times in the same line, it works perfectly otherwise.
This issue isn't seen in Visual Studio Code, when I use the `Change All Occurrences`  option (which is basically what I was trying to 
do in Notable).

Since the text I was interested in occurs only twice in a line, I was able to find a workaround by selecting the *_second_* occurrence of the text, like so:
<pre>
hello, this is a piece of text, <b>this is a piece of text</b> again
</pre>
The text was replaced correctly.

However, when I tried with three occurrences:
```
hello, this is a piece of text, this is a piece of text, this is a piece of text again and then some more words.
```
It failed again:
```
hello, foo, this is a piece of tfoo some more words.
```
It doesn't seem to have even replaced the second occurrence of the phrase, and the output is identical to the problematic output with two occurrences.

**Comment by fabiospampinato** [comment]
This got fixed at some point in the v1.9 iteration cycle, you can try one of the alphas here: https://github.com/notable/notable-experimental/releases
