### ISSUE TITLE
Stop update page from automatically opening

### ISSUE THREAD

**Issue by NielsPrins** [notable/notable#1350]
- **OS Version**:  Win 10 20H2 (19042.572)
- **Notable Version**: 1.8.4:

### Current behavior

Every time notable starts, it opens the download website to update the app.
But I am running the latest version. Notable automatically starts with my PC.
![image](https://user-images.githubusercontent.com/28888849/97091185-52eb5200-163a-11eb-92ad-891e2903b9c6.png)

### Expected behavior

Without internet, dont check for updates?

**Comment by fabiospampinato** [comment]
Switch to the alpha builds for v1.9, that's been implemented there: https://github.com/notable/notable-experimental/releases
