### ISSUE TITLE
Deletes attachments when a note is moved

### ISSUE THREAD

**Issue by ColinNg** [notable/notable#1355]
- **OS Version**: macOS Catalina 10.15.6 (19G2021)
- **Notable Version**: 1.8.4

### Current behavior

Create a new note. 
Add attachments to the note (i.e. click the paperclip icon, navigate to, for example, a .png screenshot). 
Save the note. 
Right-click the note > Reveal in Finder. 
Move the note to a subfolder (i.e. from notes to notes/Computer). 
Context switch to a different app. 
Context switch back to Notable. The attachments for the note are now deleted. 

### Expected behavior

Attachments don't get deleted.

**Comment by fabiospampinato** [comment]
Switch to the last alpha of v1.9, attachments are never deleted automatically now: https://github.com/notable/notable-experimental/releases/tag/v1.9.0-alpha.19

**Comment by ColinNg** [comment]
Thanks! I was unaware. Downloading the alpha now.
