### ISSUE TITLE
Hide "All Notes", and "Tags"

### ISSUE THREAD

**Issue by bediu** [notable/notable#1356]
Hi, 

Is there a way to remove **All Notes** and **Tags** from the side menu?

**Comment by fabiospampinato** [comment]
You can remove "Tags" by not having any tags.

I'm not sure removing "All Notes" would be useful, let's say you want to search into all your notes, how would you do it without the "All Notes" section?

**Comment by fabiospampinato** [comment]
Eventually third-party plugins will be able to provide different sidebars with whatever contents they like, so I'm closing this in favor of the more general: #128
