### ISSUE TITLE
@ key not working in MacOS (DE)

### ISSUE THREAD

**Issue by marcschumacher** [notable/notable#1360]
- **OS Version**: 10.15.7
- **Notable Version**:
1.8.4

### Current behavior
When pressing ALT-L, which is the combination to get the @ sign in MacOS, the application instead toggles line numbers.

### Expected behavior
When pressing ALT-L I expect to get the @ sign in any application. Maybe toggling line numbers can be moved to ALT-SHIFT-L or something.

To have a key combination for toggling line numbers is totally fine, but it should not clash with a combination to produce an important character. Basically I currently am unable to use any @ signs with this tool, which is really a huge problem as I use it a lot! Is it possible to change the key bindings in Notable by myself? Or do you need to change that in the code?

**Comment by fabiospampinato** [comment]
Switch to v1.9 alpha 19, that shortcut is no longer being used, and all shortcuts are customizable: https://github.com/notable/notable-experimental/releases/tag/v1.9.0-alpha.19
