### ISSUE TITLE
Sub-folder management

### ISSUE THREAD

**Issue by houcy** [notable/notable#1361]
### Feature description
I'd like to create a sub-folder under "All Notes", and classify my notes to these sub-folders. Could this feature be implemented?

### Feature motivation
classify notes to sub-folders

**Comment by fabiospampinato** [comment]
@houcy have you tried using tags or notebooks? And if so why wouldn't that suffice for you?

**Comment by houcy** [comment]
> @houcy have you tried using tags or notebooks? And if so why wouldn't that suffice for you?

That's hidden function, users can't directly find it! Would you make it clearly to add sub-folders to users in menu bar or right-click menu context? Thanks!

**Comment by fabiospampinato** [comment]
I will, yeah.
