### ISSUE TITLE
Incorrect rendering of `<details>` tag inside a Checklist

### ISSUE THREAD

**Issue by ColinNg** [notable/notable#1365]
- **OS Version**: macOS Catalina 10.15.7 (19H2)
- **Notable Version**: Version 1.9.0-alpha.19

### Current behavior

Create a note with this content:
```
# Repro Issue

- [ ] Checklist Item
  - SubItem
  <details>
  <markdown>
  - SusSubItem
    - SubSubSubItem
  </markdown>
  </details>
- [ ] Next Checklist Item
```

In 1.9.0-alpha.19 it renders as:

![image](https://user-images.githubusercontent.com/137680/98427219-1ca5cd80-2051-11eb-88f0-fbe5d9ab542f.png)

### Expected behavior

In 1.8.4 it renders as:

![image](https://user-images.githubusercontent.com/137680/98427254-40691380-2051-11eb-876c-6544b5723664.png)

**Comment by fabiospampinato** [comment]
I can confirm that this issue is still present in the current development build of the app, I'll try to get it fixed before the next one, generally how the `<markdown>` tag behaves should be much better under the current development build, but clearly I've missed something.

**Comment by fabiospampinato** [comment]
Fixed, the fix will ship in alpha21/beta0
