### ISSUE TITLE
PDF does not render with specific combination of png properties and math formula

### ISSUE THREAD

**Issue by jochemvankempen** [notable/notable#1371]
- **OS Version**: macOS Mojave
- **Notable Version**: 1.8.4

### Current behavior

First of all, thanks for a great app!

The properties of a png (screenshot), depend on which screen I took the screenshot from (see below for properties). The pdf renders fine regardless of the properties of the png. However, when using specific mathematical formulas, the pdf renders when using images that were taken from my second monitor, but not when using images taken from my mac monitor. It does render to HTML.

##### Mac display
![Screenshot 2020-11-13 at 09 57 40](https://user-images.githubusercontent.com/4414348/99061950-20c67380-259a-11eb-8959-e2397cdf7034.png)

##### Second display
![Screenshot 2020-11-13 at 09 57 13](https://user-images.githubusercontent.com/4414348/99061367-5a4aaf00-2599-11eb-8a07-acf65cd59365.png)

#### formulas
$r \in \N$, s.t. $0 \leq r \leq min \{m,n\}$
It is specifically to do with $\N$

### Expected behavior

For pdf to render regardless of combination of png/formula

**Comment by fabiospampinato** [comment]
Could you check if this is still a problem in v1.9 alpha 19? https://github.com/notable/notable-experimental/releases/tag/v1.9.0-alpha.19

**Comment by jochemvankempen** [comment]
Yes, it works in this version. Thanks!
