### ISSUE TITLE
Could you please remove the 'closing window' alert?

### ISSUE THREAD

**Issue by jeremygautama** [notable/notable#1382]
In my opinion, this is one of the best apps that's on Github right now. But the user experience of closing the app is quite frustrating: it keeps on saying "Are you sure you want to close this window?", while other native Mac apps: Notes and Safari, instantly closes the application every time the red button is clicked. So, in my opinion Notable would have a better user experience if the 'closing window' alert is gone, do you think it's a good idea to remove the alert?

![closing window alert](https://user-images.githubusercontent.com/66259053/100537935-23de8680-325f-11eb-9773-505f9d2c0ebd.jpg)

**Comment by fabiospampinato** [comment]
That's been gone since v1.9 alpha 0 maybe, you should switch to alpha 20: https://github.com/notable/notable-experimental/releases/tag/v1.9.0-alpha.20

**Comment by jeremygautama** [comment]
Oh ok, thanks
