### ISSUE TITLE
prevent opening app twice

### ISSUE THREAD

**Issue by HengyueLi** [notable/notable#1390]
### Feature description
OS: Windows
Notable version: 1.8.4
Recently it is possible to open the app twice. 

I guess it is possible to modify the program so that it checks if it is already running on another process.
### Feature motivation
As I see, this is dangerous if some modification has done without saving the previous edition. I like to use the multiple windows function and I cannot keep remembering whether the app is already opened or not.

**Comment by fabiospampinato** [comment]
What version of the app are you on?

**Comment by HengyueLi** [comment]
`Version 1.8.4`
@fabiospampinato

**Comment by fabiospampinato** [comment]
Switch to v1.9 beta, it should check for that: https://github.com/notable/notable-insiders/releases
