### ISSUE TITLE
Can't see any images in the README.md

### ISSUE THREAD

**Issue by jeremygautama** [notable/notable#1391]
### Current behavior
Is it just me or does the README.md file doesn't seem to show any pictures
![notable](https://user-images.githubusercontent.com/66259053/100840333-4e6f5000-34a8-11eb-9010-7a7762f0169f.jpg)

### Expected behavior
There should be pictures

**Comment by fabiospampinato** [comment]
There's a stupid bug in GitHub that breaks things, I had written a workaround for it but they must have changed something, so I need to adjust the workaround.

**Comment by jeremygautama** [comment]
#1399 

Here's a fix I found for the README.md image to appear

**Comment by jeremygautama** [comment]
v1.8.4's README.md still has no images found
![v1 8 4](https://user-images.githubusercontent.com/66259053/101422352-0da08c80-3929-11eb-8f06-5f03ccea9112.jpg)
Could you help fix this too?

**Comment by fabiospampinato** [comment]
Commits are immutable I can't mutate the tagged commit, I don't think it's worth spending the time required for doing the shenanigans necessary to have the "v1.8.4 tag" button in github display those images, eventually you'll upgrade to Big Sur and they will work (I think).
