### ISSUE TITLE
Markdown table calculations (like excel)

### ISSUE THREAD

**Issue by kmccullen97** [notable/notable#1393]
### Feature description

I think it would be cool to create a showdown.js extension that performs calculations similar to excel or google sheets.

I've tried looking for an existing extension that would do this with no luck. If anyone knows of a library with functionality similar to this let me know in the comments.

##### Example
```
| Calc Table |      |        |
| ---------- | ---- | -------|
| 1000       | 200  | =A1+B1 |
```
| Calc Table |        |               |
| ---------- | ---- | --------- |
| 1000        | 200 | 1200 |
### Feature motivation

I take lots of notes that include some calculations, and it would be nice to do the calculations right into the markdown. I would be interested in working on this extension, and have created a repository document/develop the idea https://github.com/kmccullen97/md-calc.

**Comment by fabiospampinato** [comment]
That'd be very cool.

If you want to play with this you should download v1.9 beta (https://github.com/notable/notable-insiders/releases/tag/v1.9.0-beta.0), it contains a built-in custom JS editor, which injects some code into the app at startup, you might be able to do some interesting things with that, like replacing syntax highlighting for "```supertable" codeb locks with those kinds of tables.

**Comment by kmccullen97** [comment]
I just created the first release of Markdown Calc v0.1.0 (https://github.com/kmccullen97/md-calc)! So far it supports basic PEMDAS operations, and cell references. Let me know what you think!

I wrote it as a standalone package, but it could easily be converted to a showdown.js extension.
