### ISSUE TITLE
source code availability

### ISSUE THREAD

**Issue by zayn666** [notable/notable#1398]
i used to use notable back when it was open source and i stopped when the change to closed source was made. is notable still closed source?

**Comment by fabiospampinato** [comment]
Allow me to mention this cheeky quote first:

> If you can't tell, does it matter?

The app is still closed as of today, if you are interested in getting the source code for some of the core libraries that I wrote that make it they are released mostly under my [github profile](https://github.com/fabiospampinato?tab=repositories), the source code for the app as a whole is unavailable.

**Comment by zayn666** [comment]
Yes, contrary to what you think yes it does matter

**Comment by littledivy** [comment]
Source code matters.

**Comment by fabiospampinato** [comment]
To be clear I'm not saying that source code availability doesn't matter, like I'm not saying that whether we are inside a simulation or not doesn't matter, I'm just saying that if you can't tell which way it is maybe whichever way it is doesn't change anything to you.

**Comment by zayn666** [comment]
@fabiospampinato to me it matters but im okay and i understand that you want it not to be open source anymore, but why? The "If you can't tell, does it matter?" its not true for some cases and just doesnt make sense.. if notable is still free why not open source too?(like it was previously) if the main reason of it not being open source anymore is profitability why not a paid model? How is a free closed source model more profitable than a free open source model? (meaning that if user sponsoring is the main source of profitability why not open source with good licensing? more people(that wont it being closed source) would sponsor it.

**Either way i leave you some ideas about making it profitable while still being open source**

- Offering "Notable Enterprise" (or in case if its the full software suite maybe other name its more suited), fork of notable (and maybe other software down on the road, making a software suite more complete for enterprise use, ditching then ms, slack etc..) for enterprise use. Good and well made collaborating features, integration with slack and teams (and other similar software), integration with outlook, and other features. on very attractive pricing.
- fork of notable for consumer (for a public that mostly doesnt care about open software, privacy and licenses) use with features like direct integration with cloud services , integration with the browser maybe.. etc

i think that balance from the support from (ALOT) open source users and enterprise subscriptions will be very good and make everyone happy.
Good luck Fabio :)

**Comment by fabiospampinato** [comment]
@zayn666

- Why going closed source: I've written a couple of answers to that [here](https://news.ycombinator.com/item?id=23884208).
- Why not selling anything: the thing to sell (access to the mobile app initially basically) is just not ready yet.
