### ISSUE TITLE
How to enable minimap?

### ISSUE THREAD

**Issue by meadows19** [notable/notable#1409]
In the description, it says we can enable a minimap, like VSCode.
I couldn't find a way to do that.
Please can you tell me how?
Thank you.

**Comment by fabiospampinato** [comment]
I think it's Alt+M or something on v1.8.4, but I'd just switch to v1.9 beta 0 (https://github.com/notable/notable-insiders/releases/tag/v1.9.0-beta.0), here you can toggle that from the context menu, the app menu, the command palette, the settings, or can assign a shortcut to it.
