### ISSUE TITLE
Windows: Not all documentation is available. 

### ISSUE THREAD

**Issue by meadows19** [notable/notable#1410]
Windows 10
Notable 1.8.4

### Current behavior

After install, on first load, only the following files are available:
The others are missing.

![001052](https://user-images.githubusercontent.com/21014471/101988008-38337200-3ca8-11eb-9221-088a59cb66ff.png)

### Expected behavior

All the files should be available, as shown on the screenshot on the Notable webpage.

**Comment by fabiospampinato** [comment]
I think this got fixed at some point in the v1.9 iteration cycle.
