### ISSUE TITLE
Disable auto-update check

### ISSUE THREAD

**Issue by meadows19** [notable/notable#1411]
Hello.
I'm using 1.9 beta.
Is there a way to stop Notable checking for updates on every start?
Thank you.

**Comment by fabiospampinato** [comment]
Add `"updater.interval": -1` to your settings.

**Comment by fabiospampinato** [comment]
Are you seeing any annoying notifications from the auto-updater? 🤔

**Comment by meadows19** [comment]
Thank you for your quick reply.

I'm not getting any notifications from Notable itself, but rater from my firewall.

It seems Notable is trying to connect to 172.217.23.110 (owned by Google?) even after I added 
```

  "updater": {
    "interval": -1
  },
```

to my settings.

**Comment by fabiospampinato** [comment]
> 172.217.23.110 (owned by Google?)

I don't know that IP, it must be Electron contacting that for some reason, unfortunately I'm not aware of the reason for that and of a way to disable Electron/Chromium from doing these requests.

**Comment by fabiospampinato** [comment]
You might want to add `"telemetry.enabled": false` too if you'd like to remove some more requests.

**Comment by meadows19** [comment]
Thank you, I've already disabled telemetry.
