### ISSUE TITLE
Markdown shortcut keys (Ctrl+B for bold, etc)

### ISSUE THREAD

**Issue by chrisant996** [notable/notable#1415]
### Markdown Shortcut Keys

- Ctrl+B for applying boldface to the selected text (or word at cursor; or just `**`|`**` if in whitespace, with | representing the cursor position)
- Ctrl+I for applying italics to the selected text (or word at cursor; etc)
- Maybe Ctrl+K for inserting `<kbd>` and `</kbd>` around the selected text (or word at cursor; etc)
- Various other useful Markdown shortcut keys

### Feature motivation

Notable uses Markdown for formatting, but doesn't seem to have any features to make editing Markdown be convenient.

**Comment by fabiospampinato** [comment]
Formatting shortcuts are available in insiders builds of v1.9 https://github.com/notable/notable-insiders/releases

I recently added a command for wrapping selections with custom wrappers, in case you want to have a shortcut for wrapping things in "kbd", which would be too unusual to deserve a built-in dedicated command for it. That, and support for formatting commands on empty selections, will ship in the next beta.


> Various other useful Markdown shortcut keys

Please open a separate issue for that, this line is too general to really do anything about it, maybe it is addressed already, maybe it isn't.
