### ISSUE TITLE
Mouse Pointer

### ISSUE THREAD

**Issue by Joe-a-d** [notable/notable#1416]
- Big Sure 11.0.1
- 1.9.0-alpha.14

### Current behavior

When clicking at the start of a line the mouse pointer either does nothing or moves to the wrong coordinates.

### Expected behavior

Mouse pointer should move to click coordinates

https://user-images.githubusercontent.com/16567525/103036907-af97ba00-4562-11eb-9a26-df242c238fc3.mp4

**Comment by fabiospampinato** [comment]
You are 7 release behind, try updating to beta0, does that fix it for you? https://github.com/notable/notable-insiders/releases

PS. This is the first time I see proper videos on github issues, awesome! Thanks for recording one.

**Comment by Joe-a-d** [comment]
That did it, thanks! :thumbsup:
