### ISSUE TITLE
Custom <mark> styling

### ISSUE THREAD

**Issue by Sleeping-Donut** [notable/notable#1423]
In my notes (v1.8.4) I sometimes a <style> tag at the start to set custom styling for mark with classes so I don't have to make the notes messy by having a style attribute for each use of a custom `<mark>`.
At the moment, to apply my styling over the default notable one for `<mark>`, I have to have at least 3 class names matching in the class attribute. I assume this is because of the CSS specificity rules.

Is this intentional?
If so could this be changed so these extra class names aren't required?

**Comment by fabiospampinato** [comment]
I can't change how CSS works, although ideally you should just be able to use the `!important` directive to for your styling over the default one, but I'm using `!important` too currently at the app level, that I can change eventually.

In the meantime you should switch to [v1.9](https://github.com/notable/notable-insiders/releases), which has a built-in custom CSS editor (you can find it from the menu or the command palette), there you can put your rule once and it would work for all notes. Writing an ugly selector but once shouldn't be that much of a problem.

**Comment by Sleeping-Donut** [comment]
Ok, I'll probably just use <b> for it then as there doesn't seem to be any app level css for that tag
