### ISSUE TITLE
Typing in large files causes the live view to scroll up with each keypress

### ISSUE THREAD

**Issue by TimeTravelPenguin** [notable/notable#1424]
- **OS Version**: Windows
- **Notable Version**: 1.8.4

### Current behavior

I have not seen this issue anywhere, so I would like to report it.
When typing with the live split-view shown, it scrolls up a little each time I type

### Expected behavior

Live view should stay-in-place, or follow as normal.

**Comment by fabiospampinato** [comment]
Could you check if the issue is still present in v1.9? https://github.com/notable/notable-insiders/releases/tag/v1.9.0-beta.1

(There's scroll synchronization in split-view there now!)

**Comment by TimeTravelPenguin** [comment]
> 
> 
> Could you check if the issue is still present in v1.9? https://github.com/notable/notable-insiders/releases/tag/v1.9.0-beta.1
> 
> (There's scroll synchronization in split-view there now!)

Awesome, it is indeed fixed!
