### ISSUE TITLE
If the contents of the sidebar overflow, some parts will cropped when scrolling bottom.

### ISSUE THREAD

**Issue by nibushibu** [notable/notable#1432]
- **OS Version**: macOS 11.1
- **Notable Version**: 1.9 beta-1

### Current behavior

The below image is a captured image of ver.1.9 beta-1 with the sidebar scrolled to the bottom.

<img width="1127" alt="Screen Shot 2021-01-25 at 23 01 54" src="https://user-images.githubusercontent.com/399949/105715940-8a330d00-5f61-11eb-897d-78caa563d110.png">

There is "Study" tag under "Music" tag, but it is hidden in 1.9 beta-1 and cannot be seen.

If there is enough space in the sidebar (if it doesn't overflow), It can be seen.
the below image is case of full screen mode.

![Screen Shot 2021-01-25 at 23 13 18](https://user-images.githubusercontent.com/399949/105717106-0f6af180-5f63-11eb-8982-d130eeee51a7.png)

### Expected behavior

in Stable(1.8) version.

<img width="1024" alt="Screen Shot 2021-01-25 at 23 03 56" src="https://user-images.githubusercontent.com/399949/105716026-a5058180-5f61-11eb-97bf-11491cd53f76.png">

**Comment by fabiospampinato** [comment]
This will be fixed in the next beta.
