### ISSUE TITLE
Where to find and how to install another dictionary?

### ISSUE THREAD

**Issue by redactedscribe** [notable/notable#1433]
From [what I've read](https://github.com/notable/notable/issues/108#issuecomment-729970830), version 1.9.0-alpha.20 introduced using dictionaries.

I see that Notable has a `en-US-9-0.bdic` in `%appdata%\Notable` as well as in the `Dictionaries` subdirectory.

Where can I find other `*.bdic` dictionaries, and how can I use them in Notable? I can find `*.dic`s (for English ones, see [this](https://www.syntevo.com/blog/?p=4883) and [this](https://extensions.libreoffice.org/en/extensions/show/english-dictionaries)), but `*.bdic`s don't seem to be readily available.

I'm specifically interested in en-GB.
```
Notable v1.9.0-beta.1
Windows 10 v20H2
```

**Comment by fabiospampinato** [comment]
You can set the spell checking language from the command palette or from the statusbar. You should probably update to beta1 for that.

Once you do that the dictionary will be downloaded automatically, the one for en-GB is actually bundled with the app.

Dictionaries that the app doesn't support already basically don't exist or are proprietary.

**Comment by redactedscribe** [comment]
To get this working, I had to first create/open a note. If no note is open, the command palette and statusbar do not show the necessary options.

Thanks.

**Comment by fabiospampinato** [comment]
Yeah those options are per-note, with no note open they don't make sense. Like there's no "default" language, the language is inferred.
