### ISSUE TITLE
The width of the sidebar and notelist is not preserved on exit

### ISSUE THREAD

**Issue by Dyrimon** [notable/notable#1436]
- **OS Version**: Fedora 33 Cinnamon
- **Notable Version**: 1.8.4 (AppImage)

### Current behaviour

The width of the sidebar that contains all the tags and the notes bar that contains all the notes can be resized with mouse. This is expected behaviour. When you restart the app however, the resized width is not preserved and it defaults to the annoyingly wide sidebar and notelist.

### Expected behaviour

The sidebar and notelist (along with the editor and viewer) should preserve the resized width.

**Side note**: I'm not sure if it's related to #22 or not, but the font and button zoom levels are also not preserved.

**Comment by fabiospampinato** [comment]
That's fixed on the betas https://github.com/notable/notable-insiders/releases/tag/v1.9.0-beta.1
