### ISSUE TITLE
Column Mode  Alt-Maj Shortcut

### ISSUE THREAD

**Issue by ThierryRassat** [notable/notable#1438]
Hello and thank you for your note tool that I use every day. I sponsor you. On Notepad ++ and many other tools, we have via the keyboard shortcut alt-maj which allows to put this in column mode. This mode would be very useful in Notable when you made a copy and paste in a note from another source. Thanks for your feedback, Kind Regards, Thierry

**Comment by fabiospampinato** [comment]
What's Alt+Maj? Do you have to press ALT and then M, A and J in the same shortcut?

And what's column mode

**Comment by ThierryRassat** [comment]
I use Alt+Maj with down arrow and up arrow
About column mode. Just open Notepad++   and I have this text :
"
         $i = 0
         $continue = $true
         $item = $null 
         while($continue){
             $item = $items[$i]
             if ($result.name -eq $OracleUID){
                 $continue = $false
             } else {
                 $i = $i + 1
                 $item = $null
                 $continue = ($i -le $items.count) 
             }
         }
"

I want to put # in front of all lines : 

"
#$i = 0
#$continue = $true
#$item = $null 
#while($continue){
#    $item = $items[$i]
#    if ($result.name -eq $OracleUID){
#        $continue = $false
#    } else {
#        $i = $i + 1
#        $item = $null
#        $continue = ($i -le $items.count) 
#    }
#}
"

I use columns mode.

**Comment by ThierryRassat** [comment]
It's possible to do with Tab or Tab+shift . So I closed it
