### ISSUE TITLE
Notes not showing in the middlebar

### ISSUE THREAD

**Issue by 9z0** [notable/notable#1445]
- **OS Version**: Windows 10
- **Notable Version**:  v1.9.0-beta.1

### To Reproduce
- Open a Notebook/tag with dozens of notes (at least enough number to require scrolling + a few more).
- Hover with the cursor below the last showing note, you would notice the upper part of a note that doesn't show.
- You can count the visible notes to confirm.

### Expected behavior

- All notes should show.

Possibly related to #1432

**Comment by fabiospampinato** [comment]
This will be fixed in the next beta.
