### ISSUE TITLE
In-App Markdown Cheat Sheet Links to Old, Unavailable Mermaid Github Page

### ISSUE THREAD

**Issue by JevonCW** [notable/notable#1451]
- **OS Version**: Windows 10 Version 10.0.19042 Build 19042
- **Notable Version**: 1.8.4

### Current behavior

Going Help -> View Cheatsheet and scrolling down to the Mermaid section. 
The hyperlinked "here" currently links to: https://knsv.github.io/mermaid which produces a 404

### Expected behavior

From what i can tell the current Mermaid documentation is hosted on: https://mermaid-js.github.io/mermaid/#/

**Comment by fabiospampinato** [comment]
That got fixed in the betas basically https://github.com/notable/notable-insiders/releases/tag/v1.9.0-beta.1
