### ISSUE TITLE
nested folders inside Notable

### ISSUE THREAD

**Issue by samislam** [notable/notable#1453]
### Feature description

Notable should have a feature such as the one we had in Joplin, 
using Joplin you can organize your notes by nesting them inside folders, you can have folders inside folders, and notes inside these folders.
for example, you can create a folder called JavaScript, and inside this folder you can create other folders called:
ReactJs, VUE.
you can even have notes (think of files) inside of the master folder (the JavaScript folder).

> Notable (my storage branch # 1)
> ├── Databases
> │   ├── MongoDB
> │   └── MYSQL
> ├── Languages
> │   └── JavaScript
> │       ├── arrays
> │       ├── libraries
> │       │   ├── JQuery
> │       │   ├── lodash
> │       │   └── _UnderscoreJS
> │       ├── React
> │       │   ├── classical components
> │       │   ├── functional components
> │       │   ├── hooks
> │       │   ├── intro
> │       │   └── JSX
> │       ├── regExp
> │       ├── variables
> │       └── Vue
> └── Networking
>     ├── CCNA
>     └── Network+
>

**Comment by 9z0** [comment]
You can do that already:

```
├── Databases
│   ├── MongoDB
```

Just add `Notebooks/Databases/MongoDB` tag to a note
