### ISSUE TITLE
Also search rendered markdown

### ISSUE THREAD

**Issue by 9z0** [notable/notable#1460]
For example,

search term: "unimportant note"

should match:

`**un**important note`

**Comment by fabiospampinato** [comment]
Mmm I kinda disagree with that, but in the next few release you'll be able to search rendered markdown directly, and search by regexes, which will address this issue also.

**Comment by 9z0** [comment]
Sometimes you'd want to add formatting without changing the sentence as a unit, especially if the text shouldn't be changed e.g. making a word in a famous quote bold. For example, "One **giant** step for mankind". Searching `"giant step"` should be a simple direct match without having to locate the file first!

Markdown forces your hand in that way unlike popular WYSIWYG formats like office files. Extending search to rendered markdown alleviates that.

Regex would be great, but how would it help unless you are already aware of the specific changes or using a very general pattern?
