### ISSUE TITLE
Mermaid not displayed

### ISSUE THREAD

**Issue by antoinekh** [notable/notable#1467]
- **OS Version**: WIN 10
- **Notable Version**: Version 1.9.0-beta.1

### Current behavior

```mermaid 
stateDiagram
  [*] --> Still
  Still --> [*]

  Still --> Moving
  Moving --> Still 
  Moving --> Crash: A transition
  Crash --> [*]
```

```mermaid 
pie
"Dogs" : 38
"Cats" : 85
"Rats" : 15
```

is displayed like this:
![image](https://user-images.githubusercontent.com/52744345/110826953-e1810880-8295-11eb-8512-914f8b866abd.png)

### Expected behavior

Display the mermaid graph. Works in 1.8.4

**Comment by Antoine-35** [comment]
Hello,

I found the issue, I had a space after all the "```mermaid "

So The module doesn't load, if at least one "```mermaid"  is without a space, everything works well.

**Comment by fabiospampinato** [comment]
Maybe this shouldn't be a problem to begin with 🤔
