### ISSUE TITLE
Double-click to edit

### ISSUE THREAD

**Issue by Sackbuoy** [notable/notable#1470]
### Feature description

I would like to be able to double click on the content of a note to edit it, when it is showing the markdown. I know I can click the edit button but being able to just double click would make it seem much more polished. This seems similar to https://github.com/notable/notable/issues/45 but it doesn't appear to have been implemented

### Feature motivation

I think the app would flow better, as it would be simpler and quicker to switch back and forth from editing to viewing. I think this would be advantageous because Notable is unique in that there are two separate views for a note, and it should be as simple as possible to transition between them.

**Comment by fabiospampinato** [comment]
You can already, but you need to be on the betas (https://github.com/notable/notable-insiders/releases/tag/v1.9.0-beta.1) and press down CTRL while double-clicking. Just double-clicking by default is used for selections.
