### ISSUE TITLE
Custom titlebar/window decoration on Windows

### ISSUE THREAD

**Issue by Alterae** [notable/notable#1498]
### Feature description

Instead of using the native Windows title bar and menu bar, notable should (at least provide the option to) use a custom titlebar, which matches the currently selected theme.  As notable is an electron app this should be entirely possible to implement.

### Feature motivation

Would make the app feel far nicer to use, as the native titlebar is incredibly ugly, especially when the dark theme is selected but windows as a whole is in light mode.

Would also make the windows desktop app better match the Mac app, which already integrates the window controls into the ui.

**Comment by fabiospampinato** [comment]
That's implemented in the betas https://github.com/notable/notable-insiders/releases

It does indeed make the app much nicer under Windows.
