### ISSUE TITLE
🚨 Potential Security Vulnerability

### ISSUE THREAD

**Issue by x3rz** [notable/notable#1507]
- **OS Version**: kali linux 2021.2
- **Notable Version**: 1.8.4

### Current behavior

I have found a potential security vulnerability in your project that I reported on huntr.dev, as reports are confidential which, can only be seen by maintainers and researcher. so please visit and validate.
https://www.huntr.dev/bounties/1-evilstreak/markdown-js/

### Expected behavior

As for markdown, it should not execute the payload.

**Comment by fabiospampinato** [comment]
Duplicate of https://github.com/notable/notable/issues/362.

Compiled Markdown is currently unsanitized and the app is not sandboxed yet.

**Comment by x3rz** [comment]
if possible can you please validate it.

**Comment by fabiospampinato** [comment]
@x3rz The website's auth request requires to read some private data it seems, I don't feel comfortable with that:

<img width="525" alt="Screen Shot 2021-06-30 at 17 33 22" src="https://user-images.githubusercontent.com/1812093/123998386-5acd7400-d9c9-11eb-8c58-d741f0e27fc9.png">

Could you send the report to me directly at fabio@notable.app?

**Comment by x3rz** [comment]
@fabiospampinato I completely understand your concern but they have magic links by which you can validate reports without a login 
Please check mail by  security@huntr.dev

**Comment by fabiospampinato** [comment]
I haven't received any email from them yet 🤔 

How does it work if I approve that you'll get some money?

**Comment by x3rz** [comment]
It's a startup I think they missed it :/
Yes sir if you approve then I will get paid

**Comment by fabiospampinato** [comment]
Alright let me figure this out 🤔

**Comment by x3rz** [comment]
Thank you sir 
I also asked them to sort this out

**Comment by fabiospampinato** [comment]
I logged in but I still see this:

<img width="1440" alt="Screen Shot 2021-06-30 at 18 26 25" src="https://user-images.githubusercontent.com/1812093/124005200-b64f3000-d9d0-11eb-908b-dfa946ae4830.png">

It looks like they could use some debugging too 😄

**Comment by x3rz** [comment]
https://www.huntr.dev/bounties/1624645184795-notable/notable/

**Comment by x3rz** [comment]
my bad sir please check this one

**Comment by fabiospampinato** [comment]
I can't see that one either 

<img width="1440" alt="Screen Shot 2021-06-30 at 18 28 51" src="https://user-images.githubusercontent.com/1812093/124005479-0af2ab00-d9d1-11eb-9e29-a6e3a3eecc07.png">

**Comment by x3rz** [comment]
how this is possible :/

i will ask them now I requested them to come here in this thread

**Comment by adam-nygate** [comment]
Hi both! Sorry about that - we're building out a way to notify maintainers of organisations automatically, as GitHub doesn't provide us with a way to know explicitly who is a maintainer of an organisation. Normally, we'll send you a magic link, so you don't need to signup to see the report.

In any case, as you've already registered, I've granted your account access to the report. Feel free to check it out [here](https://www.huntr.dev/bounties/1624645184795-notable/notable/).

(cc: @JamieSlome)

**Comment by fabiospampinato** [comment]
Approved 👍
