### ISSUE TITLE
How to disable opening browser when checking update failed?

### ISSUE THREAD

**Issue by cymin** [notable/notable#1553]
Hi fabiospampinato:

Notable check update usually failed in my network, and then it will open a web page(`https://notable.app/#download`).

It was so sudden when I switched to the browser application. Can it do not open the browser after checking updates  failed or disable auto-update?  I added following configuration to file `~/.notable.json`, but it didn't work:
```
{
 "telemetry": {
  "enabled": false
 },
 "updater": {
  "enabled": false,
  "interval": 1000000000
 },
}
```
Your help will be appreciated

**Comment by fabiospampinato** [comment]
Updating to v1.9 beta 1 should fix this (among many other things) https://github.com/notable/notable-insiders/releases/tag/v1.9.0-beta.1
