### ISSUE TITLE
AppImage 1.9.0-beta2 not rendering Katex, emojis, ..

### ISSUE THREAD

**Issue by Trenar** [notable/notable#1556]
I'm using the AppImage version of 1.9.0-beta2 and neither KaTeX nor Emojis get rendered properly, just the raw string is displayed in the viewer, however it is recognized as special text in the editor (highlighted orange). See screenshot:

![image](https://user-images.githubusercontent.com/31891152/148385494-40f9e6c3-8c02-4d4f-929f-634bd0c958f2.png)

Ubuntu 20.04
Notable 1.9.0-beta2, AppImage version

**Comment by fabiospampinato** [comment]
Fixed in beta3 https://github.com/notable/notable-insiders/releases/tag/v1.9.0-beta.3
