### ISSUE TITLE
Checklists are broken in Version 1.9.0-beta.2

### ISSUE THREAD

**Issue by satiowadahc** [notable/notable#1557]
- **OS Version**: Windows 10 Pro, 10.0.19041 N/A Build 19041
- **Notable Version**: Version 1.9.0-beta.2

### Current behavior

type
```
- [ ] Checklist Item 1
- [ ] Checklist Item 2
- [X] Checklist Item 3
```

(Minus the decimals to trick gitlabs markdown editor)
- [. ] Checklist Item 1
- [. ] Checklist Item 2
- [.X] Checklist Item 3

### Expected behavior
Expected Them to render like
- [ ] Checklist Item 1
- [ ] Checklist Item 2
- [X] Checklist Item 3

The editor highlights the `- [ ]` in red, but the preview does not.

Thanks for all your work on this app,

**Comment by Trenar** [comment]
related: #1556

**Comment by satiowadahc** [comment]
... and sponsor button clicked. Thanks for the fast patch.
