### ISSUE TITLE
Can't dismiss Changelog in 1.9.0-beta.2

### ISSUE THREAD

**Issue by genericmoniker** [notable/notable#1563]
- **OS Version**: Ubuntu 20.04
- **Notable Version**: 1.9.0-beta.2

### Current behavior

After downloading and installing 1.9.0-beta.2 with the .deb package, the Changelog page appears on startup. If I try to navigate elsewhere in the app (use the "x" button to close the Changelog note, go to Explorer or Search, etc.) the Changelog goes away briefly, but pops back up again, so I can't really use the app.

### Expected behavior

I expect to be able to dismiss the Changelog and use other features of the app. 

Speculation on my part, but maybe some issue (permissions?) writing persistently somewhere that the Changelog has already been shown? Is there more I need to do beyond install the package? Had previously been using beta.1 and prior non insiders versions on this machine.

**Comment by fabiospampinato** [comment]
I'll push a fix for that later today, that's caused by having multiple instances of the app (with different versions) open at the same time.

**Comment by genericmoniker** [comment]
Thanks, seems to be fixed in beta.3
