### ISSUE TITLE
App re-design suggestion

### ISSUE THREAD

**Issue by zschulzkump** [notable/notable#1566]
### Feature description

Here is a new design concept, if you like it, that you can use for a future revision of the app.

### Feature motivation

I designed this because I don't really think that three vertical panels, one being mainly for filtration purposes, was a good layout for screen real estate. The current design by default positions the document viewer / editor too far to the right of the screen, which is not really optimal for reading.

### Images

![Web 1920 – 1](https://user-images.githubusercontent.com/76266658/148701411-8d1e630a-8222-4be1-baf9-7dc9cb66a1a7.png)

![Web 1920 – 2](https://user-images.githubusercontent.com/76266658/148701420-097b311e-022a-47e7-8d64-3d627f6af924.png)

**Comment by fabiospampinato** [comment]
Try this 😉: https://github.com/notable/notable-insiders/releases/tag/v1.9.0-beta.3

**Comment by zschulzkump** [comment]
I'm glad to see that your redesigning the app. It looks much better and makes it easier to read documents than the current stable version without having to resize and hide panels.
