### ISSUE TITLE
Publish to homebrew

### ISSUE THREAD

**Issue by mingrammer** [notable/notable#157]
Would be great if this could be installed from [homebrew](https://brew.sh) package store for macOS users.

**Comment by iwoloschin** [comment]
It already is in Homebrew, though as a cask, so the proper command to install would be `brew cask install notable` instead of `brew install notable`.  Here's the information from the cask:
```
brew cask info notable
notable: 1.0.1
https://github.com/fabiospampinato/notable
/usr/local/Caskroom/notable/1.0.1 (64B)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/notable.rb
==> Name
Notable
==> Artifacts
Notable.app (App)
```

**Comment by mingrammer** [comment]
I can see the 'notable' cask after I updated the homebrew. Thank you!

**Comment by fabiospampinato** [comment]
I'm reopening this to keep track of the issue, while there's already a `notable` package on brew I'm not currently the one who's managing it.

**Comment by fabiospampinato** [comment]
I've submitted a PR to the cask repo: https://github.com/Homebrew/homebrew-cask/pull/77525

From now on I will manage this myself in an automated fashion.
