### ISSUE TITLE
Deleted notes keep coming back

### ISSUE THREAD

**Issue by D-Gross** [notable/notable#1588]
- **OS Version**: win32 10.0.22000
- **Notable Version**: v1.9.0-beta.5

### Current behavior

Deleted notes come back after application restart
deletion method : notes deleted after right click on it + Delete then "Are you sure you want to move "Title" to the computer's trash --> Yes
I can't see the notes in the trash folder

### Expected behavior

Full deletion of the notes

**Comment by Anzan** [comment]
I don't know if it's related but my Trash has around 50 documents in it and I can't empty it, the documents come back in the Trash after restarting the app (Win 10 & v1.9.0-beta.5)

**Comment by davidzoli** [comment]
On Widows files won't be deleted physically from `notes` nor `attachments` folders.

**Comment by Anzan** [comment]
Looks like it's fixed for me in version 1.9.0-beta.7 Win 10

**Comment by fabiospampinato** [comment]
Yeah it's fixed in beta 7.
