### ISSUE TITLE
The last line of the note editor sometimes show text-fragments from last edited note

### ISSUE THREAD

**Issue by mschmid** [notable/notable#160]
While working with Notable I experienced unexpected behavior. The last lines of the edit window sometimes contains text fragments of the last opened note, which are not editable. The just are shown to my confusion.

I can reproduce this behavior, please check my screenshot.
1. Click on edit
2. Click on the note "01  - The Data Directory"
3. Click on the note "Welcome to Notable"
4. See the additional text on the screenshot below

![bildschirmfoto 2019-01-02 um 10 48 03](https://user-images.githubusercontent.com/468039/50586966-24582200-0e7c-11e9-8548-bfcd42039729.png)

**Comment by mschmid** [comment]
@fabiospampinato Please compare to this screenshot, that has been taken before opening other notes:

![bildschirmfoto 2019-01-02 um 14 53 13](https://user-images.githubusercontent.com/468039/50594790-3c409d80-0e9e-11e9-9c82-129f84a7ebe5.png)

**Comment by fabiospampinato** [comment]
@mschmid Yes sorry, I see the problem now. I'll try to reproduce it.

**Comment by thykka** [comment]
I had something similar happen while editing a note; the next row became duplicated as I pressed enter. I then tried to select the duplicated paragraph, but the selection started at a different position than where I was clicking.

It seems as if there is some kind of a desynchronisation between what is shown and what is being edited.

I can't recreate this reliably, but I would assume this behaviour could lead to data loss in some scenarios, so this should be considered a high priority bug.

**Comment by mschmid** [comment]
@thykka: I assume this is the same issue. I also experienced the problem you describe.
Somehow the last selected line gets displayed below the note, no matter which one.
However, for me it is just a display issue, the notes are fine on the file level.

**Comment by fabiospampinato** [comment]
This will probably get fixed as soon as we switch to Monaco #203

**Comment by fabiospampinato** [comment]
We just switched to Monaco (#203) and I can no longer reproduce this issue.
