### ISSUE TITLE
Faster Startup Via Indexing

### ISSUE THREAD

**Issue by Alexhuszagh** [notable/notable#1603]
### Feature description

I have many notes, and currently this leads to quite slow startup times. This could likely be solved by using an index stored in a JSON file, which stores the metadata of each file, and on startup replaces any entries in the index if the `ctime` of the file's stat has changed since the last time the file was indexed.

I have a sample repository (unlicensed, so please feel free to use this with or without attribution: I just want this used) that contains the necessary code and a comparison between these two available [here](https://github.com/Alexhuszagh/notable-index-test).

A comparison of the time required to generate an index as follows of the below structure is below. Note that this includes the time to read and write the index, which writing the index would only occur on program shutdown and intermittently, so these numbers are slightly higher (by a constant value) than normal. 

**Time Comparison**

```bash
$ time node index.js 
real    0m0.428s
user    0m0.695s
sys     0m0.056s

$ time node index.js 
real    0m0.075s
user    0m0.072s
sys     0m0.008s

$ time node no_index.js 
real    0m0.456s
user    0m0.703s
sys     0m0.068s
```

**Index Structure**

```json
{
    "ASMS 2014 - Day 1 Oral Presentations.md": {
        "updated":"2022-03-31T14:26:59.078Z",
        "title":"Day 1 Oral Presentations",
        "created":"2014-06-16T18:51:02.000Z",
        "modified":"2014-06-17T01:50:24.000Z",
        "tags":["Notebooks/ASMS 2014"]
    },
    ...
}
```

Where the key is the basename of the note, and the `updated` key is the result of the `stat` exported as an ISO time string. Obviously, this index may be very different than what is used internally by Notable, however, the general idea should be similar (and it should be relatively easy to convert this indexing to and from the internal object used by Notable, which likely has a complete list of notebooks and tags as separate key/value pairs for the UI).

### Feature motivation

This significantly improves the startup times without any downsides (unless someone intentionally sets the `ctime` to indicate no changes, which won't happen by a user unintentionally and has no major downsides (it would just lead to different tags, which shouldn't be a security issues or similar).

### Other Notes

My sample code tries to be smart, so it reads lines incrementally from the file rather than read the entire file or a normal buffer size (like ~8KB-16KB), which I'm not sure how the performance compares to the latter. It's possible this could be fine-tuned somewhat, however the general idea for reading the metadata quite simple:

- Create a `readFileStream` from a file descriptor.
- Read lines until 2 lines that after stripping whitespace are `---`.
- Parse the lines between these two `--` lines as YAML.
- If the YAML header cannot be found, throw an error.

**Comment by fabiospampinato** [comment]
@Alexhuszagh are you experiencing slow startup times with the latest beta? https://github.com/notable/notable-insiders/releases/

**Comment by Alexhuszagh** [comment]
@fabiospampinato No I'm using version `1.9.0-beta1`, and was waiting to upgrade since I would be switching from an RPM to an AppImage. I'll update now and check if that changes anything.

**Comment by Alexhuszagh** [comment]
Whoops, I didn't read the release notes, the newest beta fixes the issues. Thank you.

> Tags hierarchy: creating it about 100x faster, and updating it much more quickly too

**Comment by fabiospampinato** [comment]
Nice, thanks for checking!

In general storing some kind of index for future use is a good idea, but I think it would be better for the app to use a single-file database, like sqlite, which would then be transparently synchronized in the background with the filesystem, that way you actually get kind of instant startup times. 

Computing modification times or parsing the YAML metadata is not actually that expensive, I don't think it's worth dealing with synchronization problems for a small gain in performance. Having a single source of truth simplifies things massively. Still one can only read and parse so many little files per second, we'd have to switch to use something like sqlite under the hood to be able to handle 100x the amount of content effertlessly.

**Comment by fabiospampinato** [comment]
Thank you 👍  And thank you for the GitHub sponsorship!  ❤️
