### ISSUE TITLE
Disable the close window confirmation dialog

### ISSUE THREAD

**Issue by 10kc-emilyk** [notable/notable#1610]
### Feature description

Add an option to disable this "Are you sure you want to close this window?"

![Screen Shot 2022-04-22 at 9 07 50 AM](https://user-images.githubusercontent.com/103954822/164770501-b18181bf-e781-4f03-9359-b6d4b8117c09.png)

This may depend on some options ui you're working on, but it is a small, nice, probably easy feature.

### Feature motivation

In MacOS, I prefer to just close the window instead of quit the application so it can stay in memory and re-open quickly, and wont be minimized and take up space bottom of the dock (my doc's on the side of my screen)

**Comment by fabiospampinato** [comment]
Just switch to the betas https://github.com/notable/notable-insiders/releases
