### ISSUE TITLE
Add attachments via copy/paste on Mac

### ISSUE THREAD

**Issue by dawngerpony** [notable/notable#1617]
### Feature description

#26 appears to have implemented copy & paste for image attachments for Windows and Linux; would it be possible to have the same ability in Notable for Mac?

### Feature motivation

I would love to be able to copy images and paste them into Notable notes, presumably as attachments.

PS. Very happy Notable user here, thank you for all your work!

**Comment by muxa** [comment]
I have just tested this on a Mac and it worked: it added the image to the `attachments` directory

**Comment by dawngerpony** [comment]
Yes, it does! I don't know why it wasn't working for me before. Thanks.
