### ISSUE TITLE
Links are not opened in the default system browser

### ISSUE THREAD

**Issue by lofidevops** [notable/notable#1620]
- **OS Version**: Ubuntu 20.04.4 LTS
- **Notable Version**: Version 1.8.4-2 (snap)

### Current behavior

* Open a note
* Switch to view mode
* Click on a link

### Expected behavior

* Link is opened in my default system browser

### What happens instead

* Link is opened in Gnome Web (Epiphany)

### Notes

* The same problem occurs when I pick "open in default app" from a note. The page is opened in Gnome Builder rather than my default markdown editor.
* Other snap applications correctly open in the default system browser.
* My default system browser is set in Settings / Default Applications and/or via `xdg-settings set default-web-browser`.

**Comment by lofidevops** [comment]
It seems that there is another (orthogonal) method to set the default browser:

```
sudo update-alternatives --config www-browser
```

...with this method I can only pick `epiphany` so I assume this is what Notable is using to look up the default browser. I don't know yet which setting "ought" to be preferred, I can only comment that I have not experienced this with any other applications. If I can find a definitive recommendation I will leave a comment.

**Comment by fabiospampinato** [comment]
We are building off Electron, which is built off of Chromium, hopefully whatever they are doing in this regard is fairly "correct".
