### ISSUE TITLE
Retain any additional fields in YAML frontmatter

### ISSUE THREAD

**Issue by lofidevops** [notable/notable#1621]
- **OS Version**: Ubuntu 20.04.4 LTS
- **Notable Version**: Version 1.8.4-2 (snap)

### Current behavior

* Create a note in Notable, then close Notable
* Open the note file in another editor
* Add another line to the YAML frontmatter, e.g. `foo: bar`, and save the file
* Open the note in Notable again
* Modify the note in Notable and save it
* Open the note file in another editor

### Expected behavior

Valid YAML is preserved.

### What happens instead

Fields not used by Notable have been removed (`foo: bar` no longer appears).

**Comment by lofidevops** [comment]
There are a few comments in https://github.com/notable/notable/issues/67 that indicate that the **intent** is that the frontmatter should be preserved. This is just a bug report about that, not a request to edit the frontmatter in Notable itself.

**Comment by fabiospampinato** [comment]
Beta10 should preserve additional metadata fields https://github.com/notable/notable-insiders/releases/tag/v1.9.0-beta.10
