### ISSUE TITLE
Additional keyboard shortcuts for whole line operations

### ISSUE THREAD

**Issue by maidmentdaniel** [notable/notable#1626]
### Feature description

1. I would like to be able to delete an entire line with one keyboard shortcut (ctrl-shft-d)
2. I would like to be able to select a whole line with a keyboard shortcut.
3. Duplicate a line with a keyboard shortcut (ctrl-d).

### Feature motivation
 I think the above features would significantly speed up ones ability to edit.

**Comment by fabiospampinato** [comment]
> I would like to be able to delete an entire line with one keyboard shortcut (ctrl-shft-d)

The `editor.delete.line` command does that. It's bound to CtrlOrCmd+Shift+K by default.

> I would like to be able to select a whole line with a keyboard shortcut.

`editor.selection.line` does that. It's not bound to any shortcut by default.

> Duplicate a line with a keyboard shortcut (ctrl-d).

`editor.copy.line.up` and `editor.copy.line.down` copy a line respectively up or down. They are bound by default to Alt+Shift+Up/Down.

These are available in the last beta https://github.com/notable/notable-insiders/releases/tag/v1.9.0-beta.10
