### ISSUE TITLE
How to export Note with attachments without @attachment prefix.

### ISSUE THREAD

**Issue by pkd2989** [notable/notable#1648]
Hi.

Can anyone please let me know to keep my attachment in note like while doing drag and drop. 
[](../attachments/myfile) without having to write it manually.

When I paste something from clipboard it automatically takes @attachment prefix. And it stays when I try to export the note, so the other app doesnt pick up the attachments.

Looking for some solution

Thanks.

**Comment by fabiospampinato** [comment]
The app doesn't currently support rewriting links, if you don't want it to use `@attachment` urls you'd have to not use them in the original notes.

**Comment by pkd2989** [comment]
Thanks for the reply.

Maybe this preference could be optional until we have a mechanism to resolve the attachment paths on Export. 
Also, this is not just about export, as I use Notable's suggested way of using other Cloud services to sync data directory, when I open the notes directory on iPad in a markdown viewer, the attachments are not parsed, because the relative path is not correct.

I use Notable as goto way to take notes with the assurance that I will be able to move/export/rearrange arrange notes later whenever I have to. I understand that @attachment has value in removing the unused attachments.

Also, since all attachments are exported to a single directory containing the notes as well, may be a simple logic/script to rename @attachment to './' would be sufficient ?

Anyways, Have a nice day.

**Comment by pkd2989** [comment]
Just a note for nyone else stumbling for this issue. The global Search and Replace works fine on all notes. In the notes panel select AllNotes-> Ctrl+Shift+F '@attachment' replace all with '../attachments'. 

Thanks

**Comment by fabiospampinato** [comment]
I'm reopening as a reminder to rewrite links automatically when exporting.
