### ISSUE TITLE
Cannot enter Polish-specific letter "ł"

### ISSUE THREAD

**Issue by rzarajczyk** [notable/notable#1650]
- **MacOS Ventura 13.1**:
- **1.8.4 (I guess... dunno how to check though)**:

### Current behavior

Pressing right Option+L toggles line numbering

### Expected behavior

Pressing right Option+L using Polish keyboard layout should enter Polish letter `ł`

**Note**: This bug is a showstopper for using Notable in Polish on MacOS. While I do understand that for non-polish keyboard layouts this keyboard shortcut is very neat, it would be nice to be able to modify (or at least disable it) if it conflicts with national characters.

**Comment by fabiospampinato** [comment]
This got fixed in the betas https://github.com/notable/notable-insiders/releases/tag/v1.9.0-beta.10

**Comment by rzarajczyk** [comment]
Thanks! I'll check the beta then!
