### ISSUE TITLE
Is there a way to visualise spaces and tabs in markdown?

### ISSUE THREAD

**Issue by D-Maxwell** [notable/notable#1655]
Hello there,

I have noticed however many spaces or tabs or even new lines I set, they all get cropped. Is this intended behaviour ?
I need my paragraphs to start with a tab, and I would like to be able to set new lines where I wish.

**Comment by fabiospampinato** [comment]
Yes that's how Markdown works, for better or for worse.

**Comment by D-Maxwell** [comment]
Nevermind I made an ahk script to make use of various tricks I found online, and remapped my keys accordingly.
I got another question, if you do not mind, before I close this issue : Do you know how to make an ordered list using roman numerals ?

**Comment by fabiospampinato** [comment]
If you are on the betas (https://github.com/notable/notable-insiders/releases/tag/v1.9.0-beta.10) you can set the necessary CSS for that. I'm not sure what it is, but I think you can just tell the browser to using roman rumerals rather than numbers. Maybe it's the "list-style-type" CSS property.

**Comment by D-Maxwell** [comment]
Thanks, I'll look into it.
I really wish there were extensions to solve these issues...

**Comment by fabiospampinato** [comment]
soonTM
