### ISSUE TITLE
Enable scrolling past last line

### ISSUE THREAD

**Issue by MiltFra** [notable/notable#168]
Please add the option to scroll until the last line is at the top of the editor, not until it first shows at the bottom. This is a feature that is present in most editors today.

**Comment by fabiospampinato** [comment]
I guess there's probably a CodeMirror setting for this, once that becomes customizable you should be able to enable this.

**Comment by muhlinux** [comment]
I second this,
When clicking a link in a TOC, it will display the clicked heading at the top of the screen. However if the document is short it will not scroll and therefor the heading clicked is not on top.

**Comment by fabiospampinato** [comment]
Let's wait until proper settings #476  are implemented first.

**Comment by fabiospampinato** [comment]
Implemented in v1.6, you can toggle it via a <kbd>Alt+B<kbd>.
