### ISSUE TITLE
Allow shortcut customisation

### ISSUE THREAD

**Issue by bendem** [notable/notable#179]
Somehow related to #17, #143 and probably others. Would it be possible to allow users to customize the application shortcuts?
Many users have global shortcuts setup that can conflict with the arbitrary ones you chose, or they are used to something more specific for their platform, or they have muscle memory from another note taking app.
Allowing users to edit the shortcuts would free you from having the users open issues to get a shortcut change.

**Comment by fabiospampinato** [comment]
Editing editor-level shortcuts -> absolutely.

Editing app-level shortcuts -> maybe, what conflicts did you find? Hopefully the ones I picked aren't that arbitrary but reasonable, if there's a conflict with something maybe they should be changed.

**Comment by bendem** [comment]
Conflicts were more of an after thought. What I really want is be able to use my own keybindings for the application (arrows to select notes, cmd+e to edit a note, cmd+n to create a note, delete to delete a note, cmd+t to edit the tags, etc.).
The more keybindings I can share between applications I use, the less friction I have when I work.

**Comment by divyanshu013** [comment]
There's a conflict with default shortcut in spectacle app for toggling focus mode. Definitely would be a great improvement, other option is to go back to the shortcut in conflicting app and changing that but it would need some getting used to. This can probably be just a JSON file as a good starting point.

**Comment by fabiospampinato** [comment]
Closing this in favor of #477
