### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by AndreyAkinshin** [notable/notable#18]

**Comment by fabiospampinato** [comment]
Definitely, if there's a dark version of the CSS GitHub is using for styling Markdown notes this should be easy to implement.

**Comment by RomanKornev** [comment]
Take a look at https://github.com/StylishThemes/GitHub-Dark.
It also has loads of syntax highlighting themes including `One Dark`.

**Comment by RomanKornev** [comment]
Darkmode Alpha is here: [RomanKornev/notable/tree/darkmode](https://github.com/RomanKornev/notable/tree/darkmode)

![main_dark](https://user-images.githubusercontent.com/5807561/50498524-b1e9db00-0a52-11e9-8864-267bf40d8c79.png)

What would be the best way to merge it?

**Comment by duynguyenhoang** [comment]
@fabiospampinato, I have implemented new version of dark mode according to @RomanKornev 's implementation. Thank @RomanKornev for your first idea. 

**Features:**
* Switch between 2 modes.
* Rewrite misc.css (Using scss)

![Main window](https://i.imgur.com/74y5fYS.png)
![Switch mode menu](https://i.imgur.com/id6E0As.png)
![Editor](https://i.imgur.com/Zb4p94B.png)

You guys can check it here https://github.com/duynguyenhoang/notable/tree/feature/add_dark_mode

It is still under early phase, I am fixing all styles to make sure it work correctly with both themes


Please give me your idea or feedback.

**Comment by RomanKornev** [comment]
Check out the new dark theme PR in #333 😄 .
@duynguyenhoang Sorry, but your implementation had too many merge conflicts and didn't compile.

**Comment by fabiospampinato** [comment]
Refactoring all that UI-related code (https://github.com/notable/notable/commit/7713012dabd200b87b2b0106baf779b1a0ad7679) took longer than expected, but now a dark theme, and eventually third-party themes, are much easier to implement:

Light theme:

<img width="685" alt="screen shot 2019-02-21 at 23 23 03" src="https://user-images.githubusercontent.com/1812093/53205882-e5e71400-362f-11e9-8d4a-69052bf61dae.png">

Dark theme:

<img width="685" alt="screen shot 2019-02-21 at 23 23 29" src="https://user-images.githubusercontent.com/1812093/53205905-ed0e2200-362f-11e9-92c3-3f6d05e9a9f4.png">

It isn't quite ready yet, as I still have to integrate into the code and properly theme a few more things (rendered Markdown theme, codemirror/monaco, syntax highlighting, katex formulas, mermaid diagrams), but I think it's a good start, what do you guys think?

PS. I've modeled the dark theme around my [Monokai Night theme](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-monokai-night) for vscode, perhaps you might want to take a look at that too.

PS2. A complete dark theme might land in about 2 releases, as there are some pressing bugs that I'd like to get fix for the next release.

**Comment by mikaelmello** [comment]
What is the status after v1.4? Is there some way I can activate it on my install?

**Comment by fabiospampinato** [comment]
@mikaelmello Hopefully this should land in v1.5, if you want to try it today (but keep in mind that it's very much not complete yet) you'll have to execute the following in the devtools: `$('body').toggleClass ( 'theme-light theme-dark' )`

**Comment by mikaelmello** [comment]
Thanks! I'll let you know about any issues I might encounter (hopefully I can fix them too!)

Also, if you have other "beta" features that are functional but need more robustness, feel free to ask me, I'm using notable a lot so my usecase can be useful

**Comment by raags** [comment]
The inline highlights are not visible in dark mode, and so is the table :

![image](https://user-images.githubusercontent.com/697714/55003279-1c80c780-4ffe-11e9-96c3-66e0f62aa62c.png)

**Comment by fabiospampinato** [comment]
@raggs yeah the editor & preview components are very much untheamed yet.

**Comment by fabiospampinato** [comment]
> if there's a dark version of the CSS GitHub is using for styling Markdown notes this should be easy to implement.

Famous last words, pretty much everything _except_ theming the rendered Markdown was difficult to do in some way.

I went all the way with the darkness, I'd be interested in hearing your feedback about this theme, here there are some screenshots:

<img width="685" alt="Screen Shot 2019-05-11 at 21 18 27" src="https://user-images.githubusercontent.com/1812093/57574075-8a5c4380-7432-11e9-99b4-53e084017be4.png">

<img width="685" alt="Screen Shot 2019-05-11 at 21 19 01" src="https://user-images.githubusercontent.com/1812093/57574077-8a5c4380-7432-11e9-8abd-284950288bf2.png">

<img width="685" alt="Screen Shot 2019-05-11 at 21 18 48" src="https://user-images.githubusercontent.com/1812093/57574076-8a5c4380-7432-11e9-9a20-90e39be7c201.png">

**Comment by eddex** [comment]
Just tried the new dark theme and I really like it. The menu bar at the top is not themed yet. Not sure how much of an effort it is to do this. As far as I know it also took the Visual Studio Code devs quite a while until they got this working.

Now the next step obviously would be user defined themes :wink:

**Comment by narfman0** [comment]
nb4 solarized dark :). User defined would be great, too.

Thanks so much for yalls work, looking forward to any incarnation of this!

**Comment by fabiospampinato** [comment]
> Not sure how much of an effort it is to do this. As far as I know it also took the Visual Studio Code devs quite a while until they got this working.

Yeah that's basically unthemeable, it would have to be reimplemented entirely, that's why it took a while for the vscode team to get there too.

> Now the next step obviously would be user defined themes 😉

Definitely, we'll to wait a while for that though, as that's a quite complicate thing to put up properly, and there are still lots of pressing issues to address, let's track that here #104
