### ISSUE TITLE
Installation fails on Windows if microphone is protected from privacy settings

### ISSUE THREAD

**Issue by Pastello** [notable/notable#182]
I tried installing Notable.1.0.1.exe and it did not work for me

**Comment by fabiospampinato** [comment]
@Pastello were you able to install it by changing the setting in question from the privacy settings?

**Comment by Pastello** [comment]
I did non try, sorry. It is a little bit creepy, why should it ask for microphone?

**Comment by fabiospampinato** [comment]
> why should it ask for microphone?

I've no idea, we make no use of the microphone.

**Comment by fabiospampinato** [comment]
@Pastello it may then be a related issue to #13, I'll have to document myself more about this.

**Comment by fabiospampinato** [comment]
@Pastello Is this no longer happening in recent releases?

**Comment by Pastello** [comment]
Hi @fabiospampinato. I think the problem was aobut the folder where I placed the sources and not about the microphone. Anyway, if I try to build it now, I get an error about zip command which cannot be executed:
```
> cd ./resources/tutorial && zip -FS -r ../../src/renderer/template/dist/tutorial.zip . -x '*.DS_Store'

"zip" non ▒ riconosciuto come comando interno o esterno
```

**Comment by fabiospampinato** [comment]
You can ignore that command, it's not absolutely necessary to run it.
