### ISSUE TITLE
Replace CodeMirror with Monaco

### ISSUE THREAD

**Issue by fabiospampinato** [notable/notable#203]
Replacing [CodeMirror](https://codemirror.net) with [Monaco](https://microsoft.github.io/monaco-editor/), the editor used in Visual Studio Code, is probably a good long-term choice.

It's probably more mature, it comes with less quirks, it's actively maintained by a big team, I'm more familiar with its APIs and I could probably more easily reuse code from my vscode extensions.

**Comment by bendem** [comment]
Handling of large files (>200KB) should be an acceptance criteria for the Monaco implementation. Currently, the notes are displayed slowly (>1s) starting at 120KB and the editor starts lagging badly at around 200KB.

**Comment by fabiospampinato** [comment]
Monaco is basically the editor used in VS Code, and I've successfully worked with multi-megabytes files there.

**Comment by bendem** [comment]
Sounds good to me, I'm just saying :)

**Comment by nesmyslny** [comment]
As for Vim keybindings (see #52), there's the [monaco-vim](https://github.com/brijeshb42/monaco-vim) package (also see [this](https://github.com/Microsoft/monaco-editor/issues/182) issue in monaco-editor).

**Comment by fabiospampinato** [comment]
We just switched to Monaco, although there are still many shortcuts left to implement.

**Comment by spikespaz** [comment]
Awesome! Thanks for the great work!
