### ISSUE TITLE
Native renaming support

### ISSUE THREAD

**Issue by fabiospampinato** [notable/notable#228]
Some people would prefer to have native support for renaming notes and attachments, rather than detecting the change from the filesystem.

**Comment by fabiospampinato** [comment]
Closing in favor of #480

**Comment by nsheff** [comment]
It's been a few years but I was wondering about this question too, in particular the part about renaming notes. This was closed in favor of #480, but that issue does not discuss the possibility of renaming notes.

My use case is that I have external programs that I want to read the notes that may expect certain filenames. I'd like to set these filenames from within notable. But the filenames need to be separate from the note titles. Right now, notable tightly couples note filenames to note titles. This forced tight coupling means notable cannot be used for my use case.

I like the linking between titles and filenames generally, but I would appreciate ability to override the note filename. Maybe a `custom_filename` attribute in the note header would suffice.
