### ISSUE TITLE
Change how file reloading is handled when edited outside of Notable

### ISSUE THREAD

**Issue by mikaelmello** [notable/notable#231]
I edited a note on my phone (synced using Google Drive) and when it got synced back to my computer, the note was reloaded to the recently synced/edited file, which led me to lose a whole paragraph of my current work.

We should have one (or both) of the following enhancements:

1. Ask if we want to reload the file or keep the current version.
2. Be able to undo the reloading altogether

If it helps, Visual Studio does #1 by the detecting if the current file has been changed after the base version in which the 'reload file' was edited, example:

- File.md was edited on 13:58. That is the current saved version.
- I have it opened on both Notable and a different editor, let's say VCode.
- I edited the note on Code and saved it on 14:08. The base version of the file for this edit is 13:58, the one opened on Notable.
  - If the file has been edited on Notable, based on the version of 13:58. Ask if we want to reload or not.
  - If the file has not been edited, that is, the file's content is still the same as of 13:58, just reload the latest changes without asking.

That's how VS works.

**Comment by bendem** [comment]
All major editors do that, that's the first law of text editing. You don't override user content automatically, you always ask first.

**Comment by fabiospampinato** [comment]
Just implemented:

<img width="1121" alt="screen shot 2019-02-10 at 19 08 24" src="https://user-images.githubusercontent.com/1812093/52537468-90755200-2d67-11e9-9d04-35dcd09a50e5.png">

**Comment by mikaelmello** [comment]
Thanks!
