### ISSUE TITLE
Scrollbar is offset when disabled

### ISSUE THREAD

**Issue by CptPotato** [notable/notable#239]
In edit-mode the scrollbar is pushed to the right and cut off when it's disabled (if the text is too short to scroll):

![image](https://user-images.githubusercontent.com/3957610/50824383-c2456400-1336-11e9-979e-b16cb5e97357.png)

Once the text exceeds the window height it is displayed properly.

I'm running Notable 1.1.0 on Windows 10.

**Comment by fabiospampinato** [comment]
We just switched to Monaco and I can't reproduce this anymore.
