### ISSUE TITLE
Add attachments via copy/paste

### ISSUE THREAD

**Issue by matejdro** [notable/notable#26]
It would be really helpful if pressing paste button when there is a image in the clipboard would:

1. Automatically attach this image to the note
2. Paste in Markdown text for displaying that attachment inline

As extra bonus, same behavior could be added for drag-dropping images into editor.

Basically, similar to how Github handles copy pasting images.

**Comment by matejdro** [comment]
A thought: image from clipboard has no name. Maybe editor should popup a text box first, asking for attachment name?

**Comment by MatanRubin** [comment]
Big +1 for this feature request.

> A thought: image from clipboard has no name. Maybe editor should popup a text box first, asking for attachment name?

Personally, when I copy-paste an image I don't really care about the filename. If I care about it, I save it as a file and name it myself.
I think some autogenerated name based on the note's title should be enough here.

**Comment by matejdro** [comment]
Well one huge feature of this app for me is that all notes are completely usable even without the program. Having attachments with random generated names would completely break that since I could not reasonably sift through attachments to find the right one.

**Comment by fabiospampinato** [comment]
I think in that particular situation when no file name is available the image should probably be called something like `Clipboard_<note-title>.<ext>`, does that sound ok?

**Comment by matejdro** [comment]
How about `<note-title>_Clipboard.ext` instead? That way your notes are organized by the note name, not all clipboard notes at the one place.

**Comment by MoHD20** [comment]
I guess this comes with implementing #139 too. As that will offer Pasting in Markdown text for displaying that attachment inline with ease.

**Comment by muhammad-saleh** [comment]
@matejdro @fabiospampinato What if you pasted multiple images in the same note?

I guess it should be `<note-title>_Clipboard_<epoch>.ext`

**Comment by thomai-d** [comment]
What about using folders? I think it helps a lot with the organization of your notes if you put all images/attachments of a note into a single folder within your attachment folder.

Furthermore it would be easy (and more safe) to remove all related attachments when deleting a note.

**Comment by fabiospampinato** [comment]
> What's wrong with storing a copy of the image in the rare case when you paste the same image into multiple notes?

It might be a _rare_ case for you but not for others. Some of the problems are:

1. Increased data directory side (this matters with synchronization).
2. If you want to edit an attachment (think about annotating something on an image) you can't just edit it once.
3. If you attach a markdown file to a note you're gonna have a hard time search & replacing only notes.

I think you're reasoning as if Notable where unavailable (which actually it isn't on mobile right now), we are not trying to optimize for ease of use outside of the app, even though that's important.

> what if you want to copy a note to share it with a coworker?

There are options for exporting notes.

**Comment by DutchPete** [comment]
> Where would you put an attachment that's linked to by multiple notes then? I don't think duplicating it or making a symlink are practical options.
Why not let the user decide for her/himself? For example: a user could have 1 folder for all images, and with a reference path multiple notes can link to 1 particular image. On the other hand, a user can choose to have a folder per note and then links only that particular note to the images in that folder.

Or is it that Notable can only handle that 1 folder currently designated for attachments?

**Comment by fabiospampinato** [comment]
@DutchPete Everyone has their preferences, if you want maximum flexibility in the folders structure then Notable might not be the app for you. I personally find the current solution OK, maybe finding a specific note's attachments is a bit tricky now but once we'll have proper web/mobile apps that problem will go away, I'd rather spend time developing those then making the folder structure maximally flexible.

**Comment by DutchPete** [comment]
@fabiospampinato After posting my comment I read your discussion in a thread with some other guys, so I am aware of your thinking about folders and your objectives, and will not try to make you change your mind. Suffice to say for me that only having 1 folder means that with a lot of notes in there it becomes an unorganised jumble. So, with Notable, yes you own your notes, that's for sure, but no, portability in a practical sense is virtually non-existent without a lot of manual, time-consuming work.

Having said, I will not bring up the issue of folders again.

**Comment by fabiospampinato** [comment]
@DutchPete There really isn't a way to embed attachments inside Markdown other than encoding them (Evernote is doing something similar, but with XML). That would be the only way to make this more portable (but not "100% portable", as we've got to store some metadata such as if a note is favorited or not etc. somewhere somehow, there's no agreed standard for this), but now accessing those attachments directly would be a nightmare. 

Maybe in the future we could have a plugin #128 for exporting notes to whatever format you like.

**Comment by Zeustopher** [comment]
I figured I'd jump in and offer another perspective on it and my common usecase.

I've been using a different note app, [Boostnote](https://github.com/BoostIO/Boostnote), for around a year now and have been pretty happy with it. I'm looking elsewhere though because one thing I'm not a super fan of is that it stores all its notes in a `cson` format. I really like the idea of having them in a straight `markdown` format for portability, mobile editing, version control, etc.

My most common usecase is for documenting things in a "triage" situation when a service at work has issues / goes down / etc. and I'm researching why it went down. I use [Flameshot](https://github.com/lupoDharkael/flameshot) to take constant very quick screenshots of dashboard panels, graphs, log snippets, etc. just copying them to the clipboard and immediately pasting them directly into Boostnote. Boostnote names them a random hash and automatically adds a `![asdf1234](asdf1234.png)` tag right where my cursor was.

I'm finding it difficult to transition over to using Noteable because of the attaching process of images to be much more time intensive. I have to save it, attach it, add the image tag by hand, etc. I completely understand the reasoning you gave for organizing and naming them coherently because you want the file system itself to be navigable.

If Noteable had some sort of image pasting capability I'd probably be all-in with using it. As it stands right now I'm not sure I can make the change.

**Comment by fabiospampinato** [comment]
This is probably going to get implemented in v1.5, I tried to squeeze it in v1.4 but that's long overdue already.

**Comment by fchabouis** [comment]
Hello,
Just an idea, there is this VS Code extension that does the same job : https://marketplace.visualstudio.com/items?itemName=telesoho.vscode-markdown-paste-image
You paste, there is this dialog showing at the top where you can change the name of the file if you need (and the default name is highlighted, so you can directly start typing) or you just press enter and the default name is used.
I think it's smart.

**Comment by fabiospampinato** [comment]
Should an attachment added this way just be added to the attachments list or also to the note? And should image be just linked or embedded?

Maybe we could just show a notification telling the user that a note has been added to the app (or animate the attachments icon in some way) for now 🤔 as the other details of this I think should really be configurable and we don't have proper settings #476 yet.

**Comment by cmadormo** [comment]
Will add my 2 cents, as this is main feature holding me back from using this as my primary note taking tool.

In terms of linked vs. embedded, I think both approaches address the main concern (eliminating the extra time taken to save and then attach the image). My personal preference is to have the image embedded and rendered inline within the note, but as you mention that may be a nice option for user configuration.

Looking forward to this feature getting implemented. Appreciate all the great work on this.

**Comment by renanwillian** [comment]
+1

**Comment by rmawatson** [comment]
+1, I see this this didn't make it to 1.6. Just settled on notable after trying a few other note apps, but not being able to quickly take a screenshot and paste it in is a real shame. Is this likely to make it in 1.7?

**Comment by fabiospampinato** [comment]
> Is this likely to make it in 1.7?

Yes, I think so.

**Comment by fabiospampinato** [comment]
> Basically, similar to how Github handles copy pasting images.

I'm implementing this feature right now, and only now, by reading this sentence again, I've realized that one can copy-paste images in GitHub 😨

**Comment by fabiospampinato** [comment]
Just implemented, check out a preview [here](https://www.reddit.com/r/Notable/comments/cntt7b/preview_add_image_attachments_via_copy_and_paste/).

**Comment by endfreude** [comment]
Copy and paste is not working on my machine 😞 
I guess there should be the appropriate string on the clipboard after drag-and-dropping an (image) file into Notable.

Windows 10 Pro (1809)
Notable 1.7.0

**Comment by fabiospampinato** [comment]
@endfreude What are you copying an image from your computer and then pasting it into Notable or drag-and-dropping it into Notable? I'll take a closer look at this as soon as i can.

**Comment by fabiospampinato** [comment]
@endfreude I've just quickly tried if this worked for me in my Win10 machine, and it doesn't work. I've tried if this worked in [Boostnote](https://boostnote.io), which already supported this feature, and it doesn't work either. This is pretty weird, perhaps Windows' clipboard just can't contain images, can you copy-paste images in any other Win10 apps? Can you copy-paste an image in a GitHub comment from Chrome?

**Comment by fabiospampinato** [comment]
@endfreude Yeah this really seems like a limitation of the OS, or another reason not to use Windows if you will. The thing actually works if you open an image in a program like Paint, select an area and copy that. When copying an image file Windows just doesn't put the image in the clipboard unfortunately.

Once I'll implement drag & drop #15 there'll be an easy, and more general since currently only images be added as attachments via copy-paste, way to add attachments under Windows too.

**Comment by gianlucatruda** [comment]
@fabiospampinato Just tried out the copy-paste feature in 1.7 and it's a game-changer. Notable is now just the app I've been looking for! Thanks for the great work.

**Comment by fabiospampinato** [comment]
@gianlucatruda I'm glad you like it! There are many other game changing features planned, in the future the app will be so much better.

**Comment by fabiospampinato** [comment]
Somebody mentioned on Reddit that copy/pasting images actually works on Windows in some apps, I tried VNote but it crashed in my Windows VM, can any of you Windows users point me at an app that has this feature working? Maybe this is not actually a limitation of the OS but a limitation of the APIs exposed by the browser, which we are using for reading the clipboard.

**Comment by guija** [comment]
I can confirm that it works with [Greenshot](https://getgreenshot.org/) .

**Comment by fabiospampinato** [comment]
Apparently we can retrieve images from the clipboard via some shell scripts across all platforms, I'll make sure to add support for Windows and Linux too soon 👍

**Comment by Kellermaan** [comment]
> 
> 
> Apparently we can retrieve images from the clipboard via some shell scripts across all platforms, I'll make sure to add support for Windows and Linux too soon 👍

Sure, thanks very much for the effort. I really think copy/paste image is a really important feature when the app is a notebook app.

**Comment by fabiospampinato** [comment]
I've just implemented copy/pasting of images for Windows and Linux too 👍 wait for the next release to try it out.

**Comment by ourweakness** [comment]
didn't know I needed this until I used it today - awesome
