### ISSUE TITLE
Links to notes that don't exist should create the note when clicked

### ISSUE THREAD

**Issue by lukaskawerau** [notable/notable#262]
### Feature description

Currently when you create a link to a note that does not exist, like `[](@note/This is a test.md)`, Notable takes you to a blank grey screen that you can't edit.  
Instead, Notable should create an empty note with a title that matches the link (so `This is a test` in this example).

### Feature motivation

This improves the writing workflow immensely: while writing you can already link to places you know you are going to create eventually and the only thing you need to do is click on the link.

**Comment by fabiospampinato** [comment]
Sounds like a reasonable idea 🤔 perhaps we shouldn't just assume the note is supposed to be missing though, like if you link a note that exists and than rename said note maybe you don't want it recreated but rather you'd like to fix the broken link.

**Comment by KewlCat** [comment]
Yes! I approve this idea.
May I suggest that, instead of greying everything out (button bar and where the editor should be), Notable had a button in the editor's place, saying "This note does not exist, click here to create it". Clicking the button would then create a note with the title equal to the text of the followed link, and maybe tags equals to the note from where we navigate ?
(and if the intention was not to create a new note, have a feature that allows to go back to the previous note -- and no, I'm absolutely not saying this because I created a new issue suggesting this feature) :-D

**Comment by fabiospampinato** [comment]
> Notable had a button in the editor's place, saying "This note does not exist, click here to create it". 

I agree, this is probably the best way to go about this.

> and maybe tags equals to the note from where we navigate ?

🤔 I'm not sure, I guess maybe this could be useful most of the times, and removing a tag is probably easy enough to do that having to do it every now and then is not too much of a burden to ask.

> (and if the intention was not to create a new note, have a feature that allows to go back to the previous note in order to correct it 

Rather then "going back" I think there's no point in navigating to an empty note if it doesn't exist.

**Comment by KewlCat** [comment]
> Rather then "going back" I think there's no point in navigating to non-existent note.

There might be no point in navigating to it _intentionally_ but if you edit a note, insert a malformed [ [ Link ] ] and try to preview it + click on it, you'd certainly want to go back to the note you were editing to make a correction.

And in my case (building a knowledge base) I might at some point want to create a new index for a subject, add a list of links to non(yet)existent notes and create them one after another when I have the time. I'd greatly appreciate the ability to click a link, a "create this note" button, and start typing...

**Comment by fabiospampinato** [comment]
Sure, I think if the note doesn't exist we should just ask the user: do you want to create it or not? If he doesn't want to create it we do nothing and don't change the currently active note at all.

**Comment by KewlCat** [comment]
Exactly.

**Comment by fabiospampinato** [comment]
Just implemented, the new note will have the name found in the link as its title:

![Kapture 2019-05-09 at 2 06 34](https://user-images.githubusercontent.com/1812093/57416159-4df4d180-71ff-11e9-8db9-6b92e309cc1d.gif)
