### ISSUE TITLE
Scroll a note with keyboard in preview mode

### ISSUE THREAD

**Issue by RomanKornev** [notable/notable#299]
- **OS Version**: Windows 10 x64 1809
- **Notable Version**: master a97cb0d4d06c7272cb0a766460cd531fcd0667c4

Is there a way to scroll a long note with a keyboard in preview mode?
I tried every combination of Ctrl/Alt/Shift + Arrows/PageUp/PageDown.
Also didn't find any reference in the tutorial.

Maybe Up/Down for small scrolls, PageUp/PageDown for whole page scrolls.
Because currently Up/Down are the same as Left/Right and they both select previous/next note.

Okay, apparently PageUp/PageDown works if I focus on it with a mouse first, but that's defeating the point. 
It stops working if I switch notes.

**Comment by fabiospampinato** [comment]
Maybe a could add some Shift+Up/Down and Shift+Spacebar commands 🤔

**Comment by RomanKornev** [comment]
PageUp/PageDown still stops working if I switch notes with a keyboard. I can't think of a reason why that's intended behavior.

**Comment by RomanKornev** [comment]
I figured it out. It's bugged regardless of using a mouse or not.
After selecting a note, the list is now in focus. So PageUp/PageDown and Space keys scroll the list instead of preview content. And there is no way to toggle what is in focus. Also, the focus is lost after toggling edit mode.

I guess we need different keybinds for scrolling the note list vs preview window and just keep the preview window in focus at all times?

**Comment by fabiospampinato** [comment]
> Also, the focus is lost after toggling edit mode.

It's not that it's "lost", but rather you're now focusing to the button.

> I guess we need different keybinds for scrolling the note list vs preview window and just keep the preview window in focus at all times?

I'll have to think more about this, I don't think that having the notes list scrollable (since we already have shortcuts for navigating it) is as important has having the preview scrollable.

**Comment by RomanKornev** [comment]
> I don't think that having the notes list scrollable (since we already have shortcuts for navigating it) is as important has having the preview scrollable

Agreed!

**Comment by jonek** [comment]
Please use `up` and `down` (cursor keys) to scroll long notes in preview mode.
`left` and `right` (cursor keys) are already bound to "previous note" and "next note".

The current situation in preview mode is that you have duplicated key board shortcuts for navigating between notes but _no_ keyboard shortcuts to scroll the note. :disappointed:

Snippet from the "07 - Shortcuts" note that is part of the tutorial:
- <kbd>Up</kbd> - Previous note, when previewing.
- <kbd>Left</kbd> - Previous note, when previewing.
- <kbd>Ctrl+Shift+Tab</kbd> - Previous note.
- <kbd>Ctrl+PageUp</kbd> - Previous note.
- <kbd>Down</kbd> - Next note, when previewing.
- <kbd>Right</kbd> - Next note, when previewing.
- <kbd>Ctrl+Tab</kbd> - Next note.
- <kbd>Ctrl+PageDown</kbd> - Next note.

**Comment by fabiospampinato** [comment]
This has been fixed in v1.6, as now the rendered note is always focused unless something with higher priority (an input for instance) has the focus, so you can use all the usual browser-provided shortcuts for scrolling notes.
