### ISSUE TITLE
LaTeX export to PDF rendering issue

### ISSUE THREAD

**Issue by RomanKornev** [notable/notable#303]
- **OS Version**: Windows 10 x64
- **Notable Version**: master baf40491739761b331907a7cbb92b8b0cac04967

### Current behavior

After exporting LaTeX to PDF, some formulas are rendered incorrectly:
```
$\frac{1}{2\pi}\int_{-\infty}^{\infty}e^{-\frac{x^2}{2}}dx$
``` 
gets rendered as:
![2019-1-19 15-43-12](https://user-images.githubusercontent.com/5807561/51426811-0f5fea80-1c01-11e9-84a0-e39aa9243d20.png)
Issue is also visible in `Tutorial/05 - Notes.md`: 
```
~sum_(i=1)^n i^3=((n(n+1))/2)^2~
```
![2019-1-19 15-46-42](https://user-images.githubusercontent.com/5807561/51426855-78476280-1c01-11e9-835d-8202f728c1ee.png)

Issue is also present when exporting to HTML and then converting that page to PDF.
I tried multiple PDF readers and browsers. It's visible everywhere.

I assume this is an upstream issue?

**Comment by fabiospampinato** [comment]
> Issue is also present when exporting to HTML and then converting that page to PDF.

This is in fact what Notable is doing under the hood.

> I assume this is an upstream issue?

Maybe, I'm not sure.

**Comment by OnyxDelta** [comment]
I just wanted to add that when exporting to a PDF using symbols from KaTeX also causes this issue:
![screenshot-20190304182946-392x134](https://user-images.githubusercontent.com/12561892/53772320-9d3f1e80-3eab-11e9-8a7e-6d2e40691fed.png)

**Comment by fabiospampinato** [comment]
Notes are now exported perfectly (as far as I can tell at least):

<img width="1440" alt="screen shot 2019-03-05 at 17 50 27" src="https://user-images.githubusercontent.com/1812093/53822067-3edb7400-3f6f-11e9-9a24-3a8952e1f43e.png">

**Comment by gsanmartinsilva** [comment]
Hi! I can't make Katex, or any latex syntax work on windows. I have the last version. Great program nevertheless!

**Comment by fabiospampinato** [comment]
@gsanmartinsilva can you open a separate issue about this? I suppose latex/katex expressions aren't rendered within the app either and the issue is not just about exporting, right?
