### ISSUE TITLE
Skeleton UI style generation

### ISSUE THREAD

**Issue by RomanKornev** [notable/notable#310]
- **OS Version**: Windows 10 x64 1809
- **Notable Version**: master 68720f5bf17319fb1cddb624ac548cec407d6b0e
### Current behavior

The skeleton UI in `src\renderer\index.html` has a hardcoded style. Right now it's not a problem, because the CSS is identical, but when we support custom themes it might cause issues.

I realize there are instructions on how to generate it here: `tasks\skeleton.md`. But it would be nice if that process was automatic.

### Expected behavior

Ensure that skeleton UI is properly generated using the main CSS.

**Comment by fabiospampinato** [comment]
This will also be a problem as soon as we preserve some state across restarts (is focus mode, is split view etc.)

**Comment by fabiospampinato** [comment]
> Can't we generate it after a theme is loaded for the first time? Or generate multiple of them and switch based on the theme?

It's not just about the theme, for instance if focus mode was enabled when the app quit the skeleton should reflect that, ultimately it doesn't matter what the intermediate states were, just the final one.

> I'm not really concerned about skeleton not matching the theme in the first couple of seconds. It's white for like a second, regardless of BrowserWindow.backgroundColor. Electron bug? Found it: electron/electron#15335

Are you seeing an all-white window before the skeleton loads? That can happen, currently the skeleton is shown [after 500ms](https://github.com/fabiospampinato/notable/blob/master/src%2Fmain%2Fwindows%2Fmain.ts/#L533). On production builds this problem should be far less noticeable.

> right now the skeleton CSS 'bleeds' into the theme and overrides it. We should wrap the skeleton in it's own property or something so it stops changing the theme after it's already loaded.

Good point, just removing the skeleton's style from the DOM would suffice.

**Comment by RomanKornev** [comment]
> It's not just about the theme, for instance if focus mode was enabled when the app quit the skeleton should reflect that, ultimately it doesn't matter what the intermediate states were, just the final one.

If it's supposed to save state after exiting fe90f1790b920c67b80033c86995847e5ad4e893, then I haven't seen it. It's still opening preview mode for me. 
Ultimately, it's pretty minor.

> Are you seeing an all-white window before the skeleton loads? 

I'm seeing white regardless of `BrowserWindow.backgroundColor`. Then after 800ms, it switches to skeleton color, then it loads the correct theme colors.
Setting timeout to 0 does not fix it.
But this does:
https://github.com/fabiospampinato/notable/compare/master...RomanKornev:white-flash-fix
It applies `backgroundColor` immediately.

**Comment by fabiospampinato** [comment]
> If it's supposed to save state after exiting fe90f17, then I haven't seen it

Not yet, but it's a planned improvement.

I'll check your branch, thanks.

**Comment by fabiospampinato** [comment]
> * 'm using [critical](https://github.com/addyosmani/critical) to extract the critical CSS, maybe this loads some heavy dependencies that would make the app bigger.

It actually downloads a whole browser 🙃 I guess it was just written for node.js usage, so I've rewritten it. Now the skeleton can be generated dynamically via an API, and the current DOM doesn't get disrupted at all.

**Comment by fabiospampinato** [comment]
I'm closing this as we now have a good way to generate the skeleton dynamically, even though we aren't really using it yet.
