### ISSUE TITLE
Import from Boostnote

### ISSUE THREAD

**Issue by fabiospampinato** [notable/notable#336]
Support for importing Boostnote notes should be added, so that people can more easily switch.

**Comment by adambro** [comment]
I see that Boostnote allow to export each note as Markdown file. I guess it is more about automatic import of the whole notepad collection, right?

**Comment by jasselin** [comment]
@fabiospampinato cson-parser doesn't seem to be compatible with yarn, are you using yarn or npm?

**Comment by fabiospampinato** [comment]
@jasselin npm.

**Comment by fabiospampinato** [comment]
I just implemented this as part of switching to [dumper](https://github.com/notable/dumper), wait for the next release to try it out.
