### ISSUE TITLE
Archive category

### ISSUE THREAD

**Issue by GlassGruber** [notable/notable#341]
### Feature description
Hey there! First of all thank you for this great app! :grin: 

An Archive category is a place to store old/unused notes. Notes in this category are not counted and displayed in tags/notebook/favs etc...

Notes in this category could be displayed as a separate collapseable sidebar section, just as normal notes, but with their tags/notebook/favs and so on. 

A flag/check for the search bar could be used to search also in the Archive, or only the archive.

As an alternative an "Archive" folder could be created on first start, then using a button like "send note to Archive" could move the note to said Archive folder.  
This way the user could use the already built in "Change data directory" feature (maybe just duplicate the menu item and name it "go to Archive" or something like that).

### Feature motivation

Just a way to put away some clutter that you don't want to delete.

**Comment by fabiospampinato** [comment]
What makes "Archive" different from the "Trash"?

**Comment by Fastidious** [comment]
@fabiospampinato I see no need for an archive, but I understand why some would like that feature (similar to Google Photos archives).

A trash is the place one use for discarded things to be deleted, and thus it is ephemeral. An archive is, well, for archival purposes. Things on the archive are not shown anywhere else, but under the archive category/tag, whatever approach is taken. Archives are kept, trash is not.

**Comment by fabiospampinato** [comment]
In Notable the trash is not emptied automatically though, so I don't really se the difference here. Maybe it could be useful for people how actually want to empty their trash, but the two seem too overlapping to me 🤔 

I'll keep this open to monitor the popularity of the request.

**Comment by Fastidious** [comment]
I smiled when I read you don't really see a difference, @fabiospampinato. Would you agree to rename Trash to Archives, then, and deleted notes (with a modifier key) are simply deleted (no recovery)? That way "delete" will send notes to Archives, and "⌘ delete" will just delete it.

**Comment by RomanKornev** [comment]
@Fastidious <kbd>Ctrl+Delete</kbd> is already permanently deleting notes. Renaming Trash -> Archive might be a solid idea, considering we don't automatically delete anything in Trash anyway.

**Comment by fabiospampinato** [comment]
> I smiled when I read you don't really see a difference, @fabiospampinato.

The key word was **here**:

> In Notable the trash is not emptied automatically though, so I don't really se the difference here.

As later in the message I'm actually addressing the main difference:

> Maybe it could be useful for people how actually want to empty their trash, but the two seem too overlapping to me 🤔

I'm saying they are very overlapping, not the same.

>  deleted notes (with a modifier key) are simply deleted (no recovery)? That way "delete" will send notes to Archives, and "⌘ delete" (CTRL for non-macOS users) will just delete it.

You pretty much described how it currently works.

> Would you agree to rename Trash to Archives

No, first of all "Archives" sounds weird, I'd use "Archive" instead, but other than that I don't see any benefits, only downsides.

**Comment by Fastidious** [comment]
> No, first of all "Archives" sounds weird, I'd use "Archive" instead, but other than that I don't see any benefits, only downsides.

Agreed, it was an oversight to write "Archives," as "Archive" would be the correct word. Wouldn't you agree, though, that recommending someone to archive things in the "Trash" is a downside (also weird 🙂)?

**Comment by fabiospampinato** [comment]
> Wouldn't you agree, though, that recommending someone to archive things in the "Trash" is a downside (also weird 🙂)?

Yes, especially if you want to actually empty it at some point. Let's see how many people request this feature, perhaps we could have both an archive and a trash.

**Comment by GlassGruber** [comment]
Thank you for considering this feature request!

> What makes "Archive" different from the "Trash"?
From a technical point of view not much, yet I think it's a rather "rough" implementation of it: you can't search for notes in it and you can't see tags, notebooks and so on.

So yea as mentioned by others above, it's more of a semantic issue, but quite reasonable to me, even more in the perspective of reordering and getting rid of some clutter.  
I think that normally, people cleaning out and ordering their spaces don't put valuable but no-more/barely used stuff straight in the trash can! 

Still I think that, in view of the future switch to VSC editor with possible plugins, something like the alternative I proposed earlier with a "switch to Archive" folder is possible to achieve later on.

**Comment by fabiospampinato** [comment]
Implemented fully (context menu items, main menu items, multi-editor buttons, sidebar section...) except for toolbar buttons, which I'll implement once it's possible to hide the ones one doesn't need.
