### ISSUE TITLE
Undo history is lost when leaving edit mode

### ISSUE THREAD

**Issue by mikaelmello** [notable/notable#344]
- **OS Version**: Windows 10
- **Notable Version**: v1.1.0

### Feature description

When we make changes, presings Ctrl+E to leave Edit mode and see the rendered note, then pressing Ctrl+E again, and *then* trying to undo the latest changes you did should work. That's not the current behavior. Your undo history is lost.

I should be able to undo the latest changes I did before leaving edit mode and going back at it again.

### Feature motivation

Being able to easily undo and modify quick edits made inbetween changes from Edit mode and Rendered mode.

**Comment by RomanKornev** [comment]
Split-view mode partially solves this. It's already live on master branch.

I do agree that need to preserve undo/redo history.
Also save different histories per note. So that after switching between notes we can still quickly undo changes. But that might be harder to implement.

**Comment by mikaelmello** [comment]
> Split-view mode partially solves this. It's already live on master branch.

I'm eager to try out the new features but will patiently wait for the next release, is there an ETA?

> Also save different histories per note. So that after switching between notes we can still quickly undo changes. But that might be harder to implement.

Although that could be a nice feature, it is something I wouldn't intuitively expect from the current UI. There aren't tabs that makes you think your work is still open. When you change a note, everything from the previous one is cleared out of the screen.

**Comment by fabiospampinato** [comment]
>  is there an ETA?

A few hours from now, probably.

> Although that could be a nice feature, it is something I wouldn't intuitively expect from the current UI. 

Yeah I feel the same.

**Comment by fabiospampinato** [comment]
I think the undo history is now preserved, definitely in the master branch, but probably also in v1.3 as well.
