### ISSUE TITLE
Exported file's view is differ from notable

### ISSUE THREAD

**Issue by mnikn** [notable/notable#346]
- **OS Version**:
macOs Sierra 10.12.6
- **Notable Version**:
1.2.0

### Current behavior

The exported file seems quite different from the note in notable, eg:
- no divider after the heading
- no code highlight

### Expected behavior

The style of the exported file should be as consistent as possible with notable.

**Comment by fabiospampinato** [comment]
@mnikn I've seen something similar when exporting to PDF, but things seem to mostly work when exporting to HTML, do you have the same experience?

**Comment by mnikn** [comment]
notable:
![notable](https://user-images.githubusercontent.com/12381740/51788127-79eec880-21b5-11e9-9c9c-baf539d31318.png)

html:
![html](https://user-images.githubusercontent.com/12381740/51788118-66436200-21b5-11e9-8d99-4fcd1c8afff6.png)

pdf:
![pdf](https://user-images.githubusercontent.com/12381740/51788119-6b081600-21b5-11e9-8578-2500b9d613ef.png)

Seems the css `node_modules/primer-markdown/build/build.css` is not working.

**Comment by fabiospampinato** [comment]
I'm closing this has actually this has been fixed recently: https://github.com/notable/notable/commit/3c6b528e573f0b0be7170324b457da955eaaa705
