### ISSUE TITLE
Add the ability to reload the window

### ISSUE THREAD

**Issue by Gedminas** [notable/notable#352]
The application should have the ability to reload the files loaded from the folder. Typical refresh (F5 key) functionality

The application works fine when it's used by one user on one computer, however if used using sshfs or similar services the notable is not notified on changes made on the server.

The only way to see the changes after this happens is to close the application and reopen it. Having a refresh button would solve the problem

**Comment by fabiospampinato** [comment]
@Gedminas I don't like the idea of having a refresh button, I believe this should be automatic. We are currently actually doing that [here](https://github.com/fabiospampinato/notable/blob/master/src%2Frenderer%2Futils%2Fwatcher.ts) via [chokidar](https://github.com/paulmillr/chokidar). 

I'm not sure why changes made via sshfs are not detected 🤔

**Comment by fabiospampinato** [comment]
@Gedminiux there's a possibility we might switch to [`@atom/watcher`](https://github.com/atom/watcher/issues/204), maybe that will fix the problem.

**Comment by lmihalkovic** [comment]
From what I have seen of the source code, you could use this as an incentive to refactor the model behind this app. I took the source code and added the ability to work with multiple locations at the same time (call them 'projects'). I ran into the fact that the state is spread accross multipe entries in MainCTX. As a first step I had to make a tree component that does not constantly poke into Main to find the state any given node. 

My main motivation was that I wanted to also support using folder names to feed the 'tags' structure that you have used. I want to work with the following structure and have the app automatically figure the order of the tags (Specs, Minutes)

```
/users/xxx/somewhere/Project XX
  ./01 Specs
      /01 spec1.md
      /spec2.md
  ./02 Minutes
     /2019-01-20 meeting.md
     /2019-01-27 meeting.md

/users/xxx/projects/Project AAA
  ./01 Specs
  ./02 Minutes

```

**Comment by fabiospampinato** [comment]
@lmihalkovic I don't see the correlation between this issue and your fork.

**Comment by lmihalkovic** [comment]
i was hinting that perhaps this proposal (the better support for watching live files) could be an opportunity to ‘clean’ the way the files are read and managed. for example, it might be an idea to avoid all these ‘await’.. or even avoid eagerly loading all the files on startup. you could read the front matter block only and replace the body with a function that provides it when asked (a document loader if you will). that was the link between the suggestion and this enhancement. 

As for the rest, it’s been my experience that they become simpler to do. but i do not know the codebase as you do, so maybe it is just a side effect of my ignorance.

**Comment by lmihalkovic** [comment]
Prefixing most API calls in note/notes/tag/tags/index

Reading by line and stopping after the front-matter closing tag. The point for me is that I want to use the app for projects, and some of them running for months have many meeting minutes.. among other documents.

Good point about searching... have not thought about it yet.

**Comment by fabiospampinato** [comment]
> Prefixing most API calls in note/notes/tag/tags/index

I'm not sure what you mean here. `index`? Are you referring to the way the state is split into multiple containers?

> Reading by line and stopping after the front-matter closing tag.

I don't think you can do that via Node.js in a performant manner.

> The point for me is that I want to use the app for projects, and some of them running for months have many meeting minutes

What are "meating _minutes_"? You mean they have too many notes that slow things down?

**Comment by lmihalkovic** [comment]
My point was just that there are many `await` throughout most of these containers. I am trying to use more promises and truly async code blocks.. that's all. :) 

> searching 

I figured an answer to that question: `ripgrep`. Then it will work without loading any docs

> front-matter

I am changing the markdown processor: front-matter contents is now processed directly during the markdown parsing. but I still want to do lazy loading so see next.

> Node.js

I will try to the `readline` module. It works from a read stream, which `fs` can create. For long docs that should make a difference. As I said, I work with projects that can have 60+ docs inside... I dont want to read all these files just so that I can look at a single one.. so skimming the header to get only the front-matter seems reasonable.

**Comment by fabiospampinato** [comment]
Maybe we could add a "Reload window" command to the command palette #338

**Comment by fabiospampinato** [comment]
Just implemented this a shortcut for now (Cmd+R).
