### ISSUE TITLE
Update #1 - Beyond not sucking, Subreddit and Patreon

### ISSUE THREAD

**Issue by fabiospampinato** [notable/notable#353]
This is the first update on the product. I'm going to add the [`announcement`](https://github.com/fabiospampinato/notable/labels/announcement) label to this and future updates for easier discoverability.

### Beyond not sucking

I've created Notable with the stated goal of "not sucking", at least for me and my specific use case. I think that goal has been mostly achieved for me personally and hopefully for many of you as well. 

The goals I'll be focusing on in the foreseeable future will be:

- **Hackability**: I want Notable to become kind of the VS Code of note-taking, and be truly hackable. As of the recently released [v1.2.0](https://github.com/fabiospampinato/notable/releases/tag/v1.2.0) you can already use the DevTools, but in the future I want to add support for loading custom CSS and JS and eventually support full-fledged plugins #128. With some effort Notable could become really powerful.

- **Profitability**: As stated [previously](https://github.com/fabiospampinato/notable/issues/135) the only way of ensuring that considerable development time gets put into the project is for Notable to become profitable. In the next few months I'll start experimenting with providing a managed synchronization and web app #83 solution for people who need this.

Of course bugs and other unrelated feature requests will also be taken care of.

### Subreddit

As some of you have already noticed I've created the [/r/notable](https://www.reddit.com/r/Notable/) subreddit, we'll use it to talk about anything not strictly related to the issue tracker. Come and say hi!

### Patreon 

Some people have suggest me to start a Patreon, at least until Notable becomes profitable and self-sustaining, so I did so, you can now support me and my work directly [here](https://www.patreon.com/fabiospampinato).

It's mostly an experiment, let's see how it goes. If it can help accelerate Notable's development or any of the other open-source tools I maintain it would be awesome.

I'm planning on redirecting most of the funds collected there towards projects Notable itself depends on, especially if supporting their maintainers means we'll have [less heavy](https://github.com/fabiospampinato/notable/issues/323) dependencies.

Patreon supporters will also get a special Reddit flair.

---

That's all for this update, as always I'd be interested in hearing your comments on this.

**Comment by lukaskawerau** [comment]
Great, I just became a Patron! :)

**Comment by mnikn** [comment]
@fabiospampinato  Seems like you want to make notable profitable by synchronization. 
I'm not sure how many guys want to pay for it and how much would they expect to pay, because right now you have a lot of programmer user, they have their own server and want to use it to sync the notes, maybe start a vote for it would be better.

**Comment by mikaelmello** [comment]
Regarding Patreon, I guess that $5 as the minimum amount creates a big barrier stopping a lot of people from contributing a simple dollar. Don't you agree? I don't think that this would make potential $5 supporters to change their minds and only support with $1, and even if it did, perhaps the amount of $1 could compensate

**Comment by fabiospampinato** [comment]
@mikaelmello maybe you're right, the Patreon page is not much more than an experiment at the moment.

**Comment by amelandri** [comment]
Maybe you could also add a "What other are saying about Notable" page. For example some days ago Lifehacker wrote an article about Notable: 

https://lifehacker.com/organize-your-thoughts-with-this-markdown-note-taking-a-1831803591

**Comment by Strongaloff** [comment]
> @Strongaloff I've actually shared the app on Reddit right after the v1.0.1 release, [here](https://www.reddit.com/r/programming/comments/a9tm4z/notable_the_markdownbased_notetaking_app_that/) and in a few other subreddits. I'm definitely open with regards to sharing/promoting it more, if you have any other appropriate subreddits to suggest I'm all ears. Feel also free to share a link to this repo wherever you want.

I came across a website that seems to have a little of attention regarding Github projects: [ycombinator](https://news.ycombinator.com/show). Also [Betapage](https://betapage.co/) seems another good way to promote, since (from what I understand) they have some bots on Twitter that share the news.

**Comment by glowacky** [comment]
I heard about Notable through [this post](https://news.ycombinator.com/item?id=18765482) on Hacker News (ycombinator)

**Comment by MelBourbon** [comment]
Agree to @mikaelmello. I really like this project and would love to support this. But 5$ is too much so far. Any way for doing a donation? And agree, what most people are looking for is a solution which can by synced. I think a possible way is to have the ability to sync with the own server (incl. webinterface) and then sell a hosted solutions for the people who don't want to set up theire own server. Some other projects are doing it like this.

**Comment by fabiospampinato** [comment]
@mikaelmello @MelBourbon If you guys would like to donate a different amount I think you con donate a custom amount via [this page](https://www.patreon.com/join/2401219/checkout?rid=0). Alternatively you could use [paypal](https://www.paypal.me/fabiospampinato). Thanks for considering supporting the project!
