### ISSUE TITLE
Split-view edit resets cursor position on focus

### ISSUE THREAD

**Issue by RomanKornev** [notable/notable#357]
- **OS Version**: Win10
- **Notable Version**: 508bdd1623f2c4646d4c90614fa690a1f4baf335

### Current behavior

After clicking on the right pane then clicking on the left, cursor position is not set to where I clicked. It still uses the previous coordinate. I then have to click a second time slowly to properly place a cursor at that location.

Gif of what happens while trying to select text:
![p85zawkh0b](https://user-images.githubusercontent.com/5807561/51790370-59b70d80-21a5-11e9-8e2f-eb87ceec5ff4.gif)
Notice the left view scolled up while the scroll bar didn't update at all.
Apparently, issue is also present in regular Edit mode as well.
Seems like a fix for #215 might have caused this.

My theme is not the issue, confirmed on the master branch.

### Expected behavior

Set the new cursor coordinate on the first click instead of resetting it to previous location.

**Comment by fabiospampinato** [comment]
Sounds like we are restoring the cursor a bit too aggressively, I'll work on a fix for the next release.
