### ISSUE TITLE
Notable Installer gets stuck closing notable.exe

### ISSUE THREAD

**Issue by HaleemDream** [notable/notable#363]
- **OS Version**:  WIN 10
- **Notable Version**: 1.2

### Current behavior

Notable get's stuck when closing trying to close notable.exe when installing

### Expected behavior

CMD should run and then exit.

https://imgur.com/a/hDOaQ9i

Note : manually closing the CMD allows installer to continue

**Comment by fabiospampinato** [comment]
@HaleemDream Is this still an issue in v1.6?
