### ISSUE TITLE
"Home" and "End" button behavior is different

### ISSUE THREAD

**Issue by HaleemDream** [notable/notable#364]
- **OS Version**: Win 10
- **Notable Version**: 1.2

### Current behavior

Pressing "Home" returns to the beginning of the paragraph. 
Pressing "End" returns to the end of the paragraph.

### Expected behavior

Pressing "Home" should return to the beginning of the current line. 
Pressing "End" should return to the end of the current line.

**Comment by fabiospampinato** [comment]
I can't reproduce in v1.8.2, perhaps this got fixed at some point, @HaleemDream can you still reproduce?

**Comment by fabiospampinato** [comment]
I think this got fixed when we switched to Monaco. Now Home moves to cursor to the start of the line, End moves the cursor to the end of the line, but in both cases if the cursor is already there the cursor is moved respectively to the beginning or end of the _pragraph_.
