### ISSUE TITLE
Change Ctrl + W to a different hotkey

### ISSUE THREAD

**Issue by HaleemDream** [notable/notable#365]
### Feature description

Change the behavior of "Ctrl+W" to a different shortcut. 

### Feature motivation

* Easy to miss click and press "Ctrl + W" instead of "Ctrl + E"
* "Ctrl +W" in other application does not close the executable (https://defkey.com/what-means/ctrl-w)

Note:  Behavior of "Ctrl + W" is not mentioned in the shortcuts section.

**Comment by sbuggay** [comment]
This doesn't make any sense to me.

> I don't like this, Ctrl+W is kind of standard at this point.

and

> Those other apps have multiple tabs or documents open, so it make sense for them. Notable can only edit one note at a time so there's no tab/document to close, therefore the window should be closed.

are conflicting points. You are saying it is standard but then say that Notable isn't like those other apps that use the standard. I would agree with you if Notable had tabs, but it doesn't. I'm not aware of any other single tab app that completely closes without warning on `ctrl+w`.

Additionally, the other apps that use `ctrl+w` to close tabs don't share Notable's most used (for me at least) shortcuts of `ctrl+e` and `ctrl+s` which happen to be right next to the shortcut in question on qwerty.

When I want to close my browser I press `ctrl+shift+w` to close the entire thing. If anything, that standard should be adopted. I wouldn't press `ctrl+w` as many times as tabs I had open to achieve my goal of closing the app.

**Comment by fabiospampinato** [comment]
What about this:

- We can support ctrl+shift+w too.
- We can add a dialog asking if you really want to quit the app on ctrl+w and ctrl+shift+w.
- Once shortcuts become customizable #477 you'll be able to assign whatever shortcut you want to this, or remove all of them.
- Once we get proper settings #476 I can add a setting that disables that dialog.

How does this sound?

**Comment by fabiospampinato** [comment]
I just implemented the first 2 points, wait for the next release to try it out.
