### ISSUE TITLE
Add code styleguide to CONTRIBUTING.md

### ISSUE THREAD

**Issue by RomanKornev** [notable/notable#367]
It's better if code styleguide is written down.
Provide instructions on how to autoformat code to these guidelines.
@fabiospampinato Are you using an extension with a custom config?

**Comment by mnikn** [comment]
The repo has the .editorconfig which defines the code style, but seems like it need to has more constraints to follow the code style.

**Comment by RomanKornev** [comment]
I'm talking about space before and after parenthesis, newline every other line etc.

**Comment by fabiospampinato** [comment]
> @fabiospampinato Are you using an extension with a custom config?

Not really, unfortunately I couldn't find a linter that I'm 100% happy with. I'll either have to search more, try to customize existing ones or adhere to a slightly different coding style for which proper formatters and linters are available.

**Comment by fabiospampinato** [comment]
I'm closing this in favor of #691.
