### ISSUE TITLE
Preview inline attachments

### ISSUE THREAD

**Issue by amelandri** [notable/notable#368]
### Feature description

When a notes has a PDF attached ant the PDF is referenced in the note content, the app could show a preview of the document instead of the link to the file.

The app could have a setting where the user can choose if he prefers displaying pdf as links or previewing the document.

### Feature motivation

I migrated from Evernote, and I have a lot of notes that contains PDF documents. It was very handy being able to preview the document without opening Acrobat.

To me, it's obviously a low priority feature, but a nice to have.

**Comment by fabiospampinato** [comment]
For future reference:

- https://github.com/mozilla/pdfjs-dist
- https://jsfiddle.net/pdfjs/wagvs9Lf/?utm_source=website&utm_medium=embed&utm_campaign=wagvs9Lf

**Comment by fabiospampinato** [comment]
Done, more on this on the subreddit soon.

![image](https://user-images.githubusercontent.com/1812093/77269167-fe48b880-6c9f-11ea-894f-0e923d518f13.png)
