### ISSUE TITLE
Single instance application

### ISSUE THREAD

**Issue by CoreParadox** [notable/notable#370]
When launching the notable executable, instead of creating a new instance, the running instance of notable should be focused instead.

It's pretty standard for similar apps to not have more than one copy open (I can't think of a real reason why you'd want more than one copy) and would be convenient, especially when using many monitors with multiple windows, it's easy to lose track of where/if you have Notable open.

**Comment by RomanKornev** [comment]
Makes sense, especially in the context of minimizing to tray #5.

**Comment by fabiospampinato** [comment]
I'm not sure this a good idea, especially since we don't support multiple windows by default and there's no easy way to switch between data directories.

**Comment by fabiospampinato** [comment]
Maybe in the future, right now the app kind of assumes there's only one instance of itself running.

**Comment by skank** [comment]
I second this. Please implement a [Single Instance callback](https://github.com/electron/electron/blob/v0.36.10/docs/api/app.md#appmakesingleinstancecallback)

**Comment by fabiospampinato** [comment]
I fixed this, the fix will be available in the next release.
