### ISSUE TITLE
Cursor position randomly resets to the top

### ISSUE THREAD

**Issue by HaleemDream** [notable/notable#374]
- **OS Version**: Win 10
- **Notable Version**: 1.2

### Current behavior

Hard to replicate but occurred 3 times in the past 25 minutes. The cursor position just resets to the top.  This happened as I was actively typing and when I was on a different application (going back to notable, cursor resets to the top).   

### Expected behavior

Cursor to remain where I left it.

**Comment by RomanKornev** [comment]
Just confirmed it on v1.2.0.
It happenes exactly when autosave triggers.
Just hold down any letter for 5 seconds and see the whole line get deleted when autosave hits. Doesn't happen all the time though.
I guess while it's autosaving, the note changes, and it thinks the cursor position is no longer valid or something. 
Not sure why the work is not saved though. Maybe a separate bug.

**Comment by fabiospampinato** [comment]
> It happenes exactly when autosave triggers.

Yes, this should have been fixed here https://github.com/fabiospampinato/notable/commit/cf5a89e2eb9c18ad3742f04918520f4b145232ef.

Let me know if you can reproduce the bug in v1.3 (I'll probably publish it today).
