### ISSUE TITLE
Support for renaming tags

### ISSUE THREAD

**Issue by benbarth** [notable/notable#38]
Tags are an essential feature and it would be great if tags could be renamed.

**Comment by fabiospampinato** [comment]
You can do this already by opening the data directory with your editor and performing a search & replace.

Better support for this should probably be added though.

**Comment by mnikn** [comment]
@fabiospampinato  is there anyway to change the tag of note? right now if we want to modify the note's tag, we must remove the tag and add a new tag, which is not so convenient.

**Comment by fabiospampinato** [comment]
@mnikn there's no better why right now other than using the multi-note editor or performing a search & replace with your editor.

**Comment by fabian-ep** [comment]
Would be great to be able to edit a tag directly inside the note. Always a pain if you have deeper tag nesting to rewrite everything.

**Comment by fabiospampinato** [comment]
Closing in favor of #480
