### ISSUE TITLE
Markdown cheatsheet

### ISSUE THREAD

**Issue by fabiospampinato** [notable/notable#392]
Some people are not 100% familiar with the syntax and it would be good to have an easy-to reach Markdown cheatsheet built into the app.

**Comment by k1nghat** [comment]
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
would be cool to maybe have a way to pull in stuff directly from github/gitlab. maybe document websites like https://readthedocs.org/.

**Comment by fabiospampinato** [comment]
FYI the [tutorial notes](https://github.com/fabiospampinato/notable/tree/master/resources/tutorial/notes) are already on GitHub.

**Comment by k1nghat** [comment]
> FYI the [tutorial notes](https://github.com/fabiospampinato/notable/tree/master/resources/tutorial/notes) are already on GitHub.

im not sure of the relation? i was just documenting a cheat sheet for future reference.

**Comment by fabiospampinato** [comment]
Oh yes, sorry, I thought you meant having that sort of information available also here on the repo.

**Comment by fabiospampinato** [comment]
I just implemented this, read [this](https://www.reddit.com/r/Notable/comments/cik08v/preview_markdown_cheatsheet_and_custom_markdown/)
