### ISSUE TITLE
Tag commands are case sensitive

### ISSUE THREAD

**Issue by tforward** [notable/notable#397]
### Feature description

If you type "notebooks/test" it appears as a tag not a notebook since the "n" in notebook is not capitalize. Make it all case insensitive. 

Notebook/test2 without the "s" should also work, since really as a user is creating a single notebook

Added feature would be Right click on Notebooks >>> New Notebook >>> Prompt user for name

Notebook >>> Rename . would be great to. 

### Feature motivation

UX UI

**Comment by fabiospampinato** [comment]
> If you type "notebooks/test" it appears as a tag not a notebook since the "n" in notebook is not capitalize. Make it all case insensitive.

I'll have to think more about this, I'm not sure this core behavior change is worth it.

> Added feature would be Right click on Notebooks >>> New Notebook >>> Prompt user for name

This doesn't make sense in the context of Notable, as we have no concept of notebooks that don't contain any notes. Read more about this [here](https://github.com/fabiospampinato/notable/issues/49) and [here](https://github.com/fabiospampinato/notable/issues/54).

> Notebook >>> Rename . would be great to.

You can sort of get the same result with multi-note editing, but I guess adding this feature would make it more convenient.

**Comment by amelandri** [comment]
> > If you type "notebooks/test" it appears as a tag not a notebook since the "n" in notebook is not capitalize. Make it all case insensitive.
> 
> I'll have to think more about this, I'm not sure this core behavior change is worth it.

Propably the issue could be mitigated by tag autocomplete, but tag duplication is indeed a problem IMHO.

After writing a lot of notes I ended up with this situation in tags:

-SQL
-sql
-Sql
-SQLServer
-SQLserver

**Comment by fabiospampinato** [comment]
I'm closing this because:

> If you type "notebooks/test" it appears as a tag not a notebook since the "n" in notebook is not capitalize. Make it all case insensitive.

Those are different tags, I think we should preserve case sensitivity.

> Notebook/test2 without the "s" should also work, since really as a user is creating a single notebook

Supporting multiple ways to do this would complicate things, both in the implementation and for users who are trying to understand how things work.

> Added feature would be Right click on Notebooks >>> New Notebook >>> Prompt user for name

Let's track this here #478 

> Notebook >>> Rename . would be great to.

Let's track this here #480
