### ISSUE TITLE
Notes content overwritten under edit mode (tags)

### ISSUE THREAD

**Issue by sanchezfranco** [notable/notable#401]
- **OS Version**: Windows 10 Pro
- **Notable Version**: 1.3.0

### Current behavior

Inside a tag on edit mode, note is overwritten with the content of the first.

https://imgur.com/a/ltNzbDM

**Comment by fabiospampinato** [comment]
@sanchezfranco can you also post the first few lines of the first note? There seems to be a bug there too.

**Comment by sanchezfranco** [comment]
Yeah of course, do you mean the title size? I think that was his normal behaviour.

https://imgur.com/a/e4z8KD6

**Comment by fabiospampinato** [comment]
@sanchezfranco You shouldn't write headers like that (`# # asd`), that's kind of invalid Markdown, if you meant to have your title wrapped in a h2 element, it should have been written like so: `## asd`. This is something that should be detected on Notable's end though, thanks for the help!

**Comment by Wangxiz** [comment]
the same problem

**Comment by gtwijma** [comment]
I also see the same problem.

**Comment by martins-olekss** [comment]
Same happened to me. Some of my notes got overwritten.
Don't think it's platform specific as I am working on Linux and saw the same issue.

**Comment by Green0Photon** [comment]
Ouch. This just got one of my notes after a long class discussion.

**Comment by Junich10** [comment]
same with mac osx.
Thanks to the author for creating this app. It is my favorite markdown editor.

**Comment by Pedrosoftware** [comment]
I also see the same problem.

**Comment by fabiospampinato** [comment]
Closing as duplicate of #459.

The other problem about notes starting with `# # Foo` has been resolved, now the displayed title will be `# Foo` and the title is never interpreted as Markdown.
