### ISSUE TITLE
Alt+Shift+Arrows to select columns

### ISSUE THREAD

**Issue by napstercc** [notable/notable#403]
### Feature description

It should be nice to select multiple columns similar to Notepad++ when you do ALT + SHIFT + ARROWs
### Feature motivation

Faster edits

**Comment by fabiospampinato** [comment]
I'm not sure what you mean here exactly, can you make a screencast or something?

Btw I was planning on using Alt+Shift+Up/Down for selecting also the previous/next.

**Comment by napstercc** [comment]
Something like this:
[Link to Gif](https://app.box.com/s/6551aa5nwxmz8lwrtip4hkvzfkcorcn4
)

Also CTRL + D to duplicate the current line; also like in Notepad++

**Comment by fabiospampinato** [comment]
Oh ok, you want multi-cursors. You can do that today with `ctrl+shift+up/down`.

> Also CTRL + D to duplicate the current line; also like in Notepad++

That shortcut is already using for favoriting a note.

These sorts of things will be fixed once the editor becomes customizable and we implement plugins #128.
