### ISSUE TITLE
Windows: `npm install` fails after Caporal dependency update

### ISSUE THREAD

**Issue by gunt3001** [notable/notable#408]
- **OS Version**: Windows 10 Build 17134
- **Notable Version**: 1.3

### Current behavior

When running `npm install` on Windows, npm errors out with the following message

```
> caporal@1.1.0 postinstall C:\Users\Me\notable-win\node_modules\enex-dump\node_modules\caporal
> true

'true' is not recognized as an internal or external command,
operable program or batch file.
```
Followed by
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! caporal@1.1.0 postinstall: `true`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the caporal@1.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### Expected behavior

npm installs the dependency normally

***

I've tracked it down to the post-install script changes made in https://github.com/fabiospampinato/Caporal.js/commit/06e41506bfa8e48a6b37115a1af769cefc5dab1d which breaks `npm install` on Windows because it doesn't take `true` as a command.

That said, the previous postinstall script was also broken on Windows, but npm finished the installation despite the error, so I'm not sure what's different now. My guess is the `|| exit 0` makes npm ignores the error.

**Comment by fabiospampinato** [comment]
Should be fixed now, `true` has been replaced with the more cross-platform `exit 0`.
