### ISSUE TITLE
Using backspace to remove on large notes is laggy

### ISSUE THREAD

**Issue by HaleemDream** [notable/notable#409]
- **OS Version**: Win 10
- **Notable Version**: 1.2

### Current behavior

Not sure if it's any slower then the regular behavior. Hard to describe so I recorded it:

Hard to to tell what I was doing but:
I was holding back space and then kept removing a bunch of paragraphs to show at what point the normal behavior returned.

https://i.imgur.com/HI4ptsA.gif

The bug I mentioned in #374 also happened to occur when I was recording this. 

Could be related to #232 but the amount of text in my case did not appear to be that large. 

### Expected behavior

To remove character by character as backspace is held down.

**Comment by fabiospampinato** [comment]
@HaleemDream sounds like a duplicate of #232. How big is this note?

**Comment by HaleemDream** [comment]
@fabiospampinato 

~1200 characters or more and the issue happens.
