### ISSUE TITLE
Split-view arrow keys conflict

### ISSUE THREAD

**Issue by RomanKornev** [notable/notable#410]
- **OS Version**: Win10
- **Notable Version**: v1.3.0

### Current behavior

Arrow keys to go to prev/next note only work once, after that the editor is now in focus and is moving the caret.
In edit mode it's not as apparent, but in split-view it's very confusing.
<kbd>Ctrl+Tab</kbd>,<kbd>Ctrl+Shift+Tab</kbd> to do the same thing works fine.

### Expected behavior

* Disable Arrow keys for prev/next note in split-view and edit mode
* Ensure that arrow keys always move caret even if it's not in focus

Related #299

**Comment by fabiospampinato** [comment]
I don't think the proposed solutions are right, IMHO the editor should take precedence if in focus, the point here is: maybe we shouldn't focus to the editor if it wasn't already in focus before, or one can't cycle through multiple notes with the arrow keys 🤔
