### ISSUE TITLE
WikiLinks should only be inline-link not Link Button

### ISSUE THREAD

**Issue by lukaskawerau** [notable/notable#411]
### Feature description

WikiLinks should always be inline style instead of default LinkButton style.

### Feature motivation

WikiLinks are used within text to link to/reference other notes. In text, the LinkButton style is hugely disruptive to reading, since it is a lot bigger and always includes the note extension. To get inline-style links, one always has to provide a description in the link. This duplicates information and is uneconomic to write: To get a link [History]() within the text, I have to write `[[History|History]]`, since otherwise I get [History.md]() in the text.

**Comment by fabiospampinato** [comment]
Makes sense.
