### ISSUE TITLE
WikiLink with dot in filename does not work

### ISSUE THREAD

**Issue by lukaskawerau** [notable/notable#412]
- **OS Version**: OS Mojave
- **Notable Version**: 1.3

### Current behavior

A note with the filename `B.H. Liddell Hart.md` can not be linked to using WikiLink syntax:
`[[B.H. Liddell Hart]]` should link to the appropriate note, but does not.

### Expected behavior
`[[B.H. Liddell Hart]]` should link to the appropriate note.

**Comment by fabiospampinato** [comment]
`. Liddell Hart` gets recognized as an extension 🤔
