### ISSUE TITLE
Non-breaking spaces render weirdly

### ISSUE THREAD

**Issue by jlnbdt** [notable/notable#413]
Hil,

- **Windows 10**
- **Notable Version 1.3.0**

### Current behavior

Using non-breaking spaces with french quotation marks renders weirdly, displaying the html code `&nbsp;`
Screenshot: https://screenpresso.com/=j0MUf

### Expected behavior

HTML code has not to be displayed.

**Comment by fabiospampinato** [comment]
@jlnbdt can you post the actual note content? (or at least enough to reproduce the problem)

**Comment by jlnbdt** [comment]
Here is an example file:

```markdown
---
title: This is a test
created: '2019-02-05T09:05:46.376Z'
modified: '2019-02-05T09:06:08.545Z'
---

# This is a test

Sentence with « non breakable » spaces
```

The original file is downloadable [here](https://nc.10qt.net/index.php/s/Z4o5627SoeyApTT).

![screenshot](http://cloud.screenpresso.com/Np0vb/2019-02-05_10h11_00.png)

**Comment by fabiospampinato** [comment]
I'm closing this as the problem seems resolved in the master branch:

<img width="312" alt="screen shot 2019-02-22 at 01 04 27" src="https://user-images.githubusercontent.com/1812093/53210370-d53d9a80-363d-11e9-9e86-024b06e9a556.png">
