### ISSUE TITLE
syntax highlighting disappeared?

### ISSUE THREAD

**Issue by minusf** [notable/notable#414]
- **OS Version**: macOS mojave 10.14.3
- **Notable Version**: 1.3

### Current behavior

Syntax highlighting of markdown that was there before is gone.

### Expected behavior

Syntax highlighting present for code parts

**Comment by fabiospampinato** [comment]
@minusf can you be more specific? what is actually missing? I can see my markdown code properly syntax highlighted:

<img width="305" alt="screen shot 2019-02-04 at 14 33 50" src="https://user-images.githubusercontent.com/1812093/52211367-fbb3b580-2889-11e9-9651-e766d6bcec80.png">

**Comment by minusf** [comment]
my bad, looks like `sh` is not a valid syntax type anymore.  `bash` works.

**Comment by fabiospampinato** [comment]
@minusf we switched highlighter, from highlight.js to prism in the latest version.

Since GitHub seems to highlight `sh` codeblocks properly I'll see if I can add support for this too.
