### ISSUE TITLE
Cannot open main window after closing it

### ISSUE THREAD

**Issue by minusf** [notable/notable#416]
- **OS Version**: macOS mojave 10.14.3
- **Notable Version**: 1.3

### Current behavior

So it's possible to close the main window with cmd-W. What is the official way to open it again?  (cmd-O is something else). In any case trying "Open data directory" results in an exception, which is not possible to copy paste, so here is a screenshot.
<img width="423" alt="screenshot 2019-02-04 at 13 58 35" src="https://user-images.githubusercontent.com/3632883/52210100-4df2d780-2886-11e9-9568-39675db7ae2c.png">

**Comment by fabiospampinato** [comment]
> What is the official way to open it again?

Just click on the icon again.

I guess after the window has been closed the menu should be updated 🤔

**Comment by minusf** [comment]
> Just click on the icon again.

which icon?  the application is still running.

**Comment by fabiospampinato** [comment]
@minusf the icon in the dock.
