### ISSUE TITLE
Split-view checkbox toggle doesn't save

### ISSUE THREAD

**Issue by RomanKornev** [notable/notable#418]
- **OS Version**:Win10
- **Notable Version**:v1.3.0

### Current behavior

Clicking on the checkbox on the right does not set it to `- [x]` on the left.
It's now toggled on the right but not on the left.
If I edit something else, the state is reset to original.

### Expected behavior

Clicking on the checkbox on the right should set it to `- [x]` on the left.

**Comment by fabiospampinato** [comment]
I think the problem here is that you're interacting with a new version of the note but the program is toggling the checkbox in the version of the note that's already saved.

Perhaps triggering an autosave might be enough.
