### ISSUE TITLE
Dollar sign incorrectly escaping because of KaTeX

### ISSUE THREAD

**Issue by brycekunkel** [notable/notable#422]
- **OS Version**: OSX 10.14.2
- **Notable Version**: 1.2.0

### Current behavior

The Markdown integration with KaTeX is rendering some code in unexpected ways. There is seemling no way to escape the `$` character. 

Currently `$$$` renders as `$`, and `I will give you $2 if you can solve $y = x^2$` renders as `I will give you 2 if you can solve 2ifyoucansolvey = x^2$`

### Expected behavior
There should be a way to escape the `$` so that multiple can be rendered without issues. For example, `\$\$` would fall in line with expected behaviors from other clients.

This is more complex, but there should be automatic detection of currency vs formulas and the render should account for this. 
`I will give you $2 if you can solve $y = x^2$` should render as `I will give you $2 if you can solve $y = x^2$`

**Comment by fabiospampinato** [comment]
> This is more complex, but there should be automatic detection of currency vs formulas and the render should account for this.

This is tricky as the program interprets `$2 if you can solve $` as an expression. I'm not sure there's any way to detect this sorts of things reliably.

**Comment by RomanKornev** [comment]
@brycekunkel You are using an outdated version. Please update to the latest v1.3.0.
You can use any of these right now:
```
I will give you $ 2 if you can solve $y = x^2$
I will give you $`2` if you can solve $y = x^2$
I will give you 2$ if you can solve $y = x^2$
```
It will correctly escape the `$` and render KaTeX as well.
But I agree that we should have a better way of escaping these symbols.

**Comment by brycekunkel** [comment]
Ahh thanks for the update, @RomanKornev. I thought I'd remembered Notable recommending that I updated (which I did), so I guess I was expecting automatic updates. Thanks for the help!

**Comment by fabiospampinato** [comment]
Let's keep this open so that I can more easily keep track of the issue.

**Comment by fabiospampinato** [comment]
Actually the problem here is that the program is trying to render `"$2 if you can solve $y = x^2$"` as a KaTeX expression. I'm going to add a way of escaping those special characters.

**Comment by fabiospampinato** [comment]
Added escaping support:

<img width="1000" alt="screen shot 2019-02-09 at 15 30 25" src="https://user-images.githubusercontent.com/1812093/52521975-baebe000-2c7f-11e9-83b8-913ec4b80501.png">
