### ISSUE TITLE
KaTeX with 1 symbol

### ISSUE THREAD

**Issue by RomanKornev** [notable/notable#427]
- **OS Version**: Win10
- **Notable Version**: v1.3.0

### Current behavior

`$x$, $y$, $z$` doesn't render KaTeX.
`$x0$, $y0$, $z0$` works.

### Expected behavior

Allow single symbol KaTeX rendering.

**Comment by rdipietro** [comment]
As a side note, a temporary workaround hack is to provide e.g. a blank subscript like `$x_{}$`. This even renders with no extra space after x.

**Comment by RomanKornev** [comment]
`$x$, $y$, $z$` still only renders `z` as KaTeX.

**Comment by fabiospampinato** [comment]
@RomanKornev that's a separate bug, `$x$` actually renders fine for me. Let's track this on the other issue.
