### ISSUE TITLE
Shortcut `alt/option+z` interfere with special characters like `ż` in Polish

### ISSUE THREAD

**Issue by croogie** [notable/notable#429]
- **OS Version**: 10.14.2
- **Notable Version**: 1.1.0

### Current behavior

Trying to enter a special character `ż` (in polish language) results in **toggle line wrapping** option.

### Expected behavior

`Toggling line wrapping` should have assigned a different keystroke. Keep in mind that `SHIFT+ALT/OPTION+Z` is reserved for `Ż` character. 

I would recommend something with `W` or `L`. I see that they are not assigned anywhere.

**Comment by RomanKornev** [comment]
There is already #119 
> Let's wait until configurable shortcuts are implemented.

**Comment by fabiospampinato** [comment]
Let's wait until custom shortcuts #477 are implemented.

**Comment by fabiospampinato** [comment]
`Alt+Z` is no longer bound to anything by default from v1.9 onwards, so this is no longer an issue.

If one wanted to restore the previous behavior, the following shortcut should be configured:

```json
{ "shortcut": "Alt+Z", "command": "editor.option.wordWrap.toggle" }
```
