### ISSUE TITLE
focus jumps from search field into note text

### ISSUE THREAD

**Issue by peterjbraam** [notable/notable#433]
- **OS Version**: 10.14.2
- **Notable Version**: 1.3.0

### Current behavior

Start typing in the search field.  After a few characters, seemingly when the list of found notes below the search field updates, the cursor jumps to the beginning of the first found note. 

This prevents the search from further refining the list and leads to messing up the first line of a note with a partial search string.

### Expected behavior

The cursor stays in the search box.

**Comment by fabiospampinato** [comment]
This should be fixed on the master branch.
