### ISSUE TITLE
mhchem for Katex

### ISSUE THREAD

**Issue by lucapoulos** [notable/notable#434]
### Adds a \ce command which allows for the addition of writing chemical equations

A lot of my note taking is for chemistry and I feel like the katex plugin is really cool and just the fact that it does offer this feature. It seems like a simple addition that would benefit chemistry note takers.

Here is the link to the code.
https://github.com/KaTeX/KaTeX/blob/master/contrib/mhchem/README.md

**Comment by fabiospampinato** [comment]
The offial link to mhchem is no longer working:

```
https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/contrib/mhchem.min.js
```

This sounds like a nice addition, but it has to be small and fast, as most people won't need this. Also I'm not sure how to implement this since even the official link is broken, and `mhchem` is not included in the version of KaTeX we are using.

**Comment by OnyxDelta** [comment]
> The offial link to mhchem is no longer working:
> 
> ```
> https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/contrib/mhchem.min.js
> ```
> 
> This sounds like a nice addition, but it has to be small and fast, as most people won't need this. Also I'm not sure how to implement this since even the official link is broken, and `mhchem` is not included in the version of KaTeX we are using.

After looking on the issues page for the package, I found this:
[Issue](https://github.com/KaTeX/KaTeX/issues/1866.)
From there, I found a new link that can be used to access the package:
[mhchem](https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/contrib/mhchem.min.js)

**Comment by fabiospampinato** [comment]
> Edit: It also appears that KaTeX 0.10.1 has included support for mhchem.

That's great, I'll see what needs to be done to enable it.

**Comment by fabiospampinato** [comment]
Just implemented:

<img width="571" alt="screen shot 2019-03-07 at 17 24 34" src="https://user-images.githubusercontent.com/1812093/53971896-1635b480-40fe-11e9-978d-92bbc621bf6d.png">

There seems to be an issue with formulae containing `$` or something though 🤔 I still have to fix that.
