### ISSUE TITLE
Switch to Affero

### ISSUE THREAD

**Issue by karimyaghmour** [notable/notable#435]
I was about to look into using Notable. FWIW the switch from MIT to Affero effectively ensures I wouldn't ever use Notable.

**Comment by fabiospampinato** [comment]
@karimyaghmour Thanks for the feedback. Why's that?

**Comment by karimyaghmour** [comment]
@fabiospampinato Affero tends to be used by companies providing online services that then utilize the license's terms to put customers in a "bait-and-switch" situation where customized additions require buying a commercial license to keep the customization private. I'm not sure what benefit is derived by Notable from using this type of license but I've personally chosen not to encourage any project that uses Affero. This might still be the right license for Notable, I can't say. But it's my point of view that the incentives put in place by Affero are unhealthy. Again, just a personal point of view.

**Comment by fabiospampinato** [comment]
@karimyaghmour From my point of view I simply can't justify putting lots of my time into the project with the risk that somebody could make a competing commercial product out of it and keep its code closed-sourced.

If you're worried about customizability I'm planning on adding support to plugins #128, which should be powerful enough for pretty much all needs, and if you really don't want to share their code I don't think you have to.

**Comment by karimyaghmour** [comment]
@fabiospampinato I completely understand your dilemma and I'm in no position to pontificate. Doing the work that you do is amazing and thanks for sharing it all around. The monetization issue and risk of someone developing commercial offspring is real, I won't downplay that.

FWIW, in 25-30 years of editor use I've almost never customized or developed plugins for them other than the occasional copy-paste of emacs recipes found on the net. So that's not really a concern for me. It's more a matter of principle.

One way to protect your work is to apply for a trademark. This way if someone does try to use your package then they won't be able to leverage the name you've built for it. FWIW, that's how the entire Android ecosystem is built: Google gives away the sources to anyone that wants to use mostly under a permissive license (ASL), but you can't label a device an Android device unless you have a legally-binding agreement with Google ... because they own the trademark.

**Comment by fabiospampinato** [comment]
@karimyaghmour I'll have to document myself on the trademark front. Surely the whole thing would feel less risky to me  if nobody else could use the name "Notable" for a note-taking app and if I owned "notable.com". I don't think the trademark is as important as it is for Android though, if somebody calls a derivative note-taking app "Notish" or something nobody would care, but if a phone manufacturer shipped a phone that is not technically using Android nor iOS I think they are going to have a hard time selling it.

Btw I'll be happy to reconsider relicensing the app under the MIT license once the business becomes sustainable if most of paying costumers pay for the server-side things. At this point in time I just don't know how the app will evolve exactly and I'm just playing it on the safe side.
