### ISSUE TITLE
Failing to detect filesystem changes (NextCloud)

### ISSUE THREAD

**Issue by ymjonline** [notable/notable#438]
Editing using the "Default app" feature does not seem to work anymore.

When I open in external app e.g. Typora by clicking on the "default app" button and then save; changes do not reflect back into Notable.

I can see the actual .md file has changed but Notable does not take it into account.
I have to close/restart Notable to see changes.

If I edit from within Notable prior to restart, changes are overwritten.

* **OS Version**: Windows 10
* **Notable Version**: 1.3.0

**Comment by fabiospampinato** [comment]
@ymjonline is your data directory inside some special folder (dropbox, google drive...)?

**Comment by ymjonline** [comment]
> @ymjonline is your data directory inside some special folder (dropbox, google drive...)?

Well it's in C:\Users\<username>\<synced_folder>
so, "special" that it is indeed a Dropbox-like folder.

It used to work fine in some former version.

**Comment by fabiospampinato** [comment]
@ymjonline how is this directory synced? And can you reproduce the issue consistently repeatedly even after restarting the app?

**Comment by ymjonline** [comment]
> @ymjonline how is this directory synced? And can you reproduce the issue consistently repeatedly even after restarting the app?

- synced with NextCloud client
- yes same behavior all the time

used to work in the same exact setup (at least in 1.1)

**Comment by fabiospampinato** [comment]
@ymjonline I'm not sure what the issue might be 🤔 It may be something related to NextCloud, maybe they updated something on their end? There's also an [known issue](https://github.com/nodejs/node/issues/12115) on Windows sometimes, maybe that is playing a part here too.

It would be great if somebody could help me reproduce this. First of all check if the master branch reproduces the problems too, then drop a "debugger" statement [here](https://github.com/notable/notable/blob/9be21f59b4aa9270acab42c33958675ba0d3e757/src/renderer/utils/watcher.ts#L88) to check what events are being emitted from the filesystem watcher, then check also [here](https://github.com/notable/notable/blob/9be21f59b4aa9270acab42c33958675ba0d3e757/src/renderer/utils/watcher.ts#L54) what ids are being computed, they should be strings representing numbers > 0.

**Comment by fabiospampinato** [comment]
I think this was probably the same issue as: https://github.com/notable/notable/issues/489, which I'm not considering (mostly) fixed. 

If anybody can still reproduce after v1.8.3 I'll be happy to take a second look at this.
