### ISSUE TITLE
Links inside table have no CSS link

### ISSUE THREAD

**Issue by BAKFR** [notable/notable#439]
- **OS Version**: Gentoo Linux
- **Notable Version**: v1.3.0

### Current behavior

Link located inside a table are indistinguishable from plain text.

Here is a screenshot:

![](https://imgur.com/WTY7NO3l.png)

### Expected behavior

Links should be blue.

**Comment by fabiospampinato** [comment]
Just fixed:

<img width="685" alt="screen shot 2019-02-11 at 18 51 35" src="https://user-images.githubusercontent.com/1812093/52582693-1360e000-2e2e-11e9-8b9f-fed3cdca371c.png">

**Comment by lkreimann** [comment]
Is that fix in a release already?

**Comment by johnletey** [comment]
Works fine for me @lkreimann, what version are you using?

**Comment by lkreimann** [comment]
Yes, just installed the most recent version and I have the fix there too. Sorry for stealing your precious time, @johnletey!

**Comment by johnletey** [comment]
No problem at all @lkreimann! Happy to help!
