### ISSUE TITLE
On Linux, Notable should use standard XDG directory for app-created files

### ISSUE THREAD

**Issue by BAKFR** [notable/notable#440]
The [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) defines standard paths inside $HOME folders that should be used by applications.

In summary,
- the config files should be located in `$XDG_CONFIG_HOME/notable`  (default to `$HOME/.config/Notable`)
- the cache files should be located in `$XDG_CACHE_HOME/notable` (default to `$HOME/.cache/Notable`)
- the data files should be located in `$XDG_DATA_HOME/notable` (default to `$HOME/.local/share/Notable`)

The spec is followed by a large number of applications. It provides some advantages like an more organized $HOME folder, an ease of deleting cache when needed, and a better integration with tools like backup applications.

### Current behavior

- Notable creates a `$HOME/.notable.json` config file.
- The default note directory is `$HOME/.notable`.

Note that there is also a `$HOME/.config/notable` directory created by electron.

### Expected behavior

- `$HOME/.notable.json` should be moved into `$XDG_CONFIG_HOME/notable`.
- I think the default note folder should be either hidden in `$HOME/.local/share/Notable`, or created as a non-hidden folder (`$HOME/Notable` ?)

**Comment by fabiospampinato** [comment]
`.notable.json` is going away within the next few releases.

IMHO future config files should be moved to `~/.config/notable` and the default data directory should remain `~/.notable`. I'd like to keep the two consistent across platforms, regardless of what each platforms' preferences might be.

> * I think the default note folder should be either hidden in `$HOME/.local/share/Notable`

Too verbose.

> * or created as a non-hidden folder (`$HOME/Notable` ?)

Maybe, I'll think about this. Boostnote is doing something like that, but I don't like the extra clutter in my home directory. And right now one can already put the data directory wherever he wants.
