### ISSUE TITLE
Quick open panel arrow keys shortcuts

### ISSUE THREAD

**Issue by RomanKornev** [notable/notable#441]
- **OS Version**: Win10
- **Notable Version**: 9be21f59b4aa9270acab42c33958675ba0d3e757

### Current behavior

Up/Down to select notes in the middlebar no longer works. It uses them for quick open panel. Is this intended? If that's the case then #410 is also obsolete.

### Expected behavior

Use quick open panel shortcuts only when it's active.

**Comment by fabiospampinato** [comment]
No it's not intended, currently the up/down keypresses are caught by some event handlers that don't do anything with those when the quick open panel is closed.
