### ISSUE TITLE
Add horizontal margin option for layout-content and editor to improve reading

### ISSUE THREAD

**Issue by Arecsu** [notable/notable#443]
When the window is maximized and Focus Mode is being used, it looks like this:

![notable_9giahei0cm](https://user-images.githubusercontent.com/12679098/52594401-37222700-2e2a-11e9-812b-24a5b0376e16.png)

**It's kinda hard to read a long horizontal text**. It feels, at least for me, not natural. One of the "solutions" available now is to simple resize the window to the desired width, but the difference with a maximized/full screen application is that it get you more in focus with the text and the editing/reading aspects. I've simulated with the Developer Tools how it would look if some margin is added. 

![notable_iwhesjce1y](https://user-images.githubusercontent.com/12679098/52594713-ef4fcf80-2e2a-11e9-8d8b-dfb5b3052791.png)

![notable_dh6qowizx5](https://user-images.githubusercontent.com/12679098/52594720-f24ac000-2e2a-11e9-8a80-b6a284e12c24.png)

I'm not saying it should look like this by default. Just having an option in the menus or something for people like me **would be pretty good** 👏.

Of course, I don't know if my div solution is the best. I've made that just to illustrate the point!

**Comment by fabiospampinato** [comment]
Maybe we could add some proper settings for this, but short-term this will be fixed once we implement support for persistent custom CSS and JS #444
