### ISSUE TITLE
Toggling a checkbox resets views

### ISSUE THREAD

**Issue by RomanKornev** [notable/notable#446]
- **OS Version**: Win10
- **Notable Version**: 7b53bf628043f7d9f6d6b9394b4bffda5251dbf1

### Current behavior

After toggling a checkbox in split-view, the edit side resets to the top.
Cursor also disappears.

### Expected behavior

Keep cursor position and current scroll position since line count doesn't change.

**Comment by fabiospampinato** [comment]
> Keep cursor position 

I'm not sure this is the right move, after all the user switched the focus to the preview pane, why would the editor cursor be preserved?

> and current scroll position since line count doesn't change.

Definitely.

**Comment by fabiospampinato** [comment]
It looks like the preview section will also get reset.

**Comment by fabiospampinato** [comment]
As of v1.6 this is partially fixed, but the editor's state is still reset while toggling the checkbox from the preview.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
