### ISSUE TITLE
Hardlinking notes to notebooks, tags, and favorites in the data directory.

### ISSUE THREAD

**Issue by muhlinux** [notable/notable#451]
### Feature description
Hardlinking notes to notebooks, tags, and favorites directories within the data directory.

[Pastebin example of the data directory tree](https://pastebin.com/raw/YRpGHB5y) `->` represents a link. (Left out favorites but you get the idea)
Additionally another cool directory would be "dated" where all note filenames is prefixed with the creation date.

Why hardlinks over symlinks? Hardlinks are more widely supported over various protocols (smb for example. probably also cloud storage) and since it's small text files it's very unlikely you'd need the multiple filesystem support symlinks offers.

### Feature motivation
This would support the "No proprietary formats" principle, and offer a more organized structure for finding notes with basic file explorers and phones.

This could be done with a bash script but I think it would be a very cool feature to have build in. Obviously people have different preferences so it should be an optional setting, with a way to configure additional hardlinked directories like the "dated" one and how the date is formatted etc.

Thanks for considering and making Notable! 
I'm almost at the point of making it my all-in-one documentation app. It could be the best out there. 

Regards.

**Comment by fabiospampinato** [comment]
@muhlinux There's been some discussion related to this one in the past (#54, #230 and others.).

I have no interest in supporting such structure as it would complicate other things and it's not something I have a use for myself.

Regarding changing how files are named: let's track this [here](https://github.com/notable/notable/issues/452).

**Comment by lmihalkovic** [comment]
The issue with a proposal like this is that the internals of the data model are not designed for anything other than what the app does now. So it would need to be rebuild... the second problem would be that loading is a completely serial process wich blocks everything until all is finished ... so with 60 docs inside 6 folders, i let u imagine what happens.. but that is what i also need anyhow.. so i am making all the changes. 

@fabiospampinato i shared some of my early tree rebuilding to decouple visuals from model. What i use now is different, but that is what i started from when i was trying not to break too many eggs. Applying the same phylosophy you can relatively simply implement what is described here (or other interesting schemes)
