### ISSUE TITLE
Hide Meta in Comment Tags

### ISSUE THREAD

**Issue by brycekunkel** [notable/notable#453]
### Feature description

I'd like to see the metadata of a note hidden in comment tags. Right now, it's stored at the top of a note between two sets of `---`. 

### Feature motivation

One of the great features of Notable is being able to open a note in another MD editor. However, this metadata is rendered at the top because it is not contained in comment tags.

**Comment by fabiospampinato** [comment]
I'm not sure what you're asking for, can you provide a code example?

**Comment by brycekunkel** [comment]
In Notable, the note appears without the meta tags. However, when rendered in another MD editor, the meta info appears. 

The first screenshot is Notable:
![screen shot 2019-02-13 at 8 50 46 am](https://user-images.githubusercontent.com/22450894/52720066-8ec8ab80-2f6c-11e9-92dd-e9d1d1042cdd.png)

The second is when opened in MacDown:
![screen shot 2019-02-13 at 8 50 57 am](https://user-images.githubusercontent.com/22450894/52720079-99834080-2f6c-11e9-8d34-eb076ad74d5b.png)

**Comment by fabiospampinato** [comment]
I see. That's called Markdown "front matter", and shouldn't be rendered, MacDown is rendering it because it doesn't support it at all. 

Those metadata shouldn't be visible in Notable's editor by design, but in some occasions you may want to edit them or add new ones, let's track this here: #67.

**Comment by brycekunkel** [comment]
Good to know! Thanks for the quick response as always!
