### ISSUE TITLE
Layout consideration

### ISSUE THREAD

**Issue by lmihalkovic** [notable/notable#462]
I noticed that some of the toolbar icones don't seem to exactly match the area where they appear. 

For e.g. creating a new document is accessible in the middle bar, while deleting one is accessible in the right hand side. My understanding is that the middle are is for dealing with documents, in which case, it would make sense that creating a new one, searching for existing ones, or deleting one would be located in that document related area, no?!

I made the following changes in my local branch (the layout issues are linked to a hack in svelto ... )

<img width="1076" alt="screen shot 2019-02-17 at 1 37 27 am" src="https://user-images.githubusercontent.com/1318077/52906843-6df6a380-3255-11e9-811c-f8e98170bdda.png">

**Comment by fabiospampinato** [comment]
I don't think the reasoning is sound. The right column deals with a single note at a time, so there you find actions for dealing with that specific note. In the middle column you find actions related to notes in general, sorting, filtering, and adding a new one from the list.

If you want to favorite/pin/delete a note from the middlebar just right click it and select the right option.

**Comment by lmihalkovic** [comment]
@fabiospampinato  I understand your rational... ..... .. I will even concede that pin/favorite belong to both sides, which is a change I will make.. but create/delete do belong together for me. I want to stay away from right-clicks and make everything clearly visible.

btw, in case you are curious, the misaligned icons come from the ```multiple:last() {margin-bottom:$gutter/2}``` in svelto... I'm sure it was there for a reason, but aside from the headache it caused me, I noticed it is also in your way.

thank you
