### ISSUE TITLE
Store Note Informations in a File not in the Header

### ISSUE THREAD

**Issue by Ad-An** [notable/notable#465]
The information of the notes are stored in the header of each one in the form

```
---
title: Text
created: '2019-02-18T15:30:34.012Z'
modified: '2019-02-18T15:30:41.477Z'
---
```

I would like to suggest instead of this approach to use a single text file for all notes, for example a JSON file in which to store those information for each note. That way every note would store only its original information and could be used easier.

When I open my notes with pdf viewers I always get those header information messing the output and when I need to use those notes in other applications I have to delete manually all the headers.

Given that Notable has managed very beautifully to not limit the usage of notes outside of it I believe by this change notes can be used much more easily and effectively. Also this suits great the aim of the project.

**Comment by fabiospampinato** [comment]
Thanks for the suggestion but that's not going to happen. I think the current approach is strictly better.

You're experiencing problems because you're opening a Markdown document with a PDF viewer or with a Markdown editor that doesn't understand the front matter.
