### ISSUE TITLE
Files not named correctly

### ISSUE THREAD

**Issue by zakariamehbi** [notable/notable#466]
- **OS Version**: Windows 10
- **Notable Version**: 1.3.0

### Current behavior

When you create a new note using the Search notes bar, with the "+" button, the note is created, but the name of the file is "Untitled (<integer>).md", the only way to give the file the same name is to rename the note again and save the edit.

### Expected behavior
The files should have the same name as the note from the start.

**Comment by fabiospampinato** [comment]
Are you seeing notes named exactly `"Untitled ().md"`? 🤔 

What would the name of the note be?

**Comment by zakariamehbi** [comment]
Untitled (number).md

replace "number" with a numeric value

**Comment by fabiospampinato** [comment]
Closing as I don't think this is actually a bug.
