### ISSUE TITLE
Support compressed folders

### ISSUE THREAD

**Issue by lmihalkovic** [notable/notable#468]
When I was hacking through the arduino ide, I added support for compressed sketches. Maybe people would be interested in quickly accessing an ‘old version’ of the ```.notable``` folder that has just been compressed. The app would just load the contents in read-only mode and display the contents normally.

It could dynamically uncpress the archive somewhere if the user want to add a note to this archived project.

Makes any sense?

**Comment by fabiospampinato** [comment]
I've no interest in this, just decompress the folder and open that.

**Comment by lmihalkovic** [comment]
You d be surprised by how easy it is to transform your code to do it.. i had the same debate with the arduino developper

**Comment by MyZeD** [comment]
It would be very compact, if you have only 1 file.
I wish, i found like a tool like yours only with compressed markdown and ressources.
