### ISSUE TITLE
Sort case-insensitively

### ISSUE THREAD

**Issue by Anzan** [notable/notable#471]
- **OS Version**: Windows 10
- **Notable Version**: 1.3

### Current behavior

The alphabetical sorting of notes by title is case sensitive. Notes with a title starting with upper case "A" will not be grouped close to notes with a title starting with a lower case "a". Upper case letters are shown first from A-Z then lower case letters are shown from a-z.

### Expected behavior

I expect the sorting of notes by title to be case insensitive. A note where the title starts with "Hello planet" should be close to another note where the title starts with "hello world", not separated by all the upper case H to Z titles in between.

**Comment by fabiospampinato** [comment]
Implemented in v1.6.
