### ISSUE TITLE
Async loading

### ISSUE THREAD

**Issue by lmihalkovic** [notable/notable#472]
### Feature description

Async loading

### Feature motivation

Faster startup
Easier reload when switching repo

This is my real code from ```container/main/index.ts```. It is still very close to yours, to the exception of the library part, which manages the multi-project part.

```
  refresh = () => {

    const path = Config.notes.path;
    if (! path) return;

    this.ctx.library.refresh(path)

        .then( async notesPath => {

          if ( !notesPath || !await File.exists ( notesPath ) ) return {};

          return this._loadProject(notesPath);

        })
        .then( async notes => {

          await this.ctx.attachments.refresh ();

          // await this.ctx.notes.refresh ();
          this.ctx.notes.set( notes );

          await this.ctx.tags.refresh ();

          await this.ctx.tag.update ();
          await this.ctx.search.update ();

          await this.ctx.loading.set ( false );

    })
    .catch(err => {
      // TODO: properly display load error
      console.log(err);
    });

  }
```

**Comment by lmihalkovic** [comment]
this is also affecting #99

**Comment by lmihalkovic** [comment]
This is only the first version. In the final one, the file access will be pushed to the main process, using ipc to send back the notes descriptions that have been read. 

As you can see, the changes are not really significant... much of it consists in changing the boundaries around someof the existing logic.

**Comment by fabiospampinato** [comment]
I don't see any difference async-wise with the current solution.

Offloading this to the main process is a bad idea probably, as when the main process is busy the renderer processes are kind of frozen, and doing this on the main process doesn't give any performance advantage.
