### ISSUE TITLE
Adding a new attachment with the same filename as an existing one does not work

### ISSUE THREAD

**Issue by fuslwusl** [notable/notable#474]
- **OS Version**:
MacOS High Sierra

- **Notable Version**:
1.3.0

### Current behavior
Adding a new attachment is ignored when a file with the same name already exists in the attachment folder.

* Create a file "image1.jpg" on your desktop
* Click the attachments icon in Notable and then "Add attachments" and select your file "image1.jpg"
* Delete "image1.jpg" from your desktop
* Create a file "image1.jpg" with new content on your desktop
* Click the attachments icon in Notable and then "Add attachments" and select your file "image1.jpg"

### Expected behavior
The new file "image1.jpg" should be copied to the attachments folder with a new name for example "image1-1.jpg".

**Comment by lmihalkovic** [comment]
Well .. my own expectations would be that my documents do not get renamed in a completely inpredictable way by a system that does not know any better. After a number of these colliisions finding which file goes with which note would become rather cumbersome, which sucks from ‘the editor that does not suck’ ;-)

**Comment by fabiospampinato** [comment]
@lmihalkovic I feel what you're saying, but I think the answer for almost all use cases is: keep your files organized and don't name them all the same.

**Comment by fuzzy76** [comment]
How would you know if a name is taken after a couple of years of usage? How many illustration.jpg will have to be renamed? Or how many meetingnotes.doc received through mail? If an attachment is attached to a note, that should be organization enough. Though this is really a sideeffect of using a single attachment folder.

**Comment by fabiospampinato** [comment]
> How would you know if a name is taken after a couple of years of usage?

That's a reasonable concern, let's track this here: #518 

>  If an attachment is attached to a note, that should be organization enough.

I agree. Even though `illustration.jpg` and `meetingnotes.doc` aren't really filenames to begin with. Maybe we could automatically add a date suffix/prefix or something to the filename.

> Though this is really a sideeffect of using a single attachment folder.

True but not for all use cases, as having an attachment folder for each note won't solve the general case either, as you could still attach multiple `illustration.jpg` images to a note.
