### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by fabiospampinato** [notable/notable#481]
We should make a decent-looking landing page, not all people are familiar with GitHub.

It would be awesome if instead of screenshots there were embedded versions of Notable, but it may take some time before we reach that point of flexibility.

**Comment by lmihalkovic** [comment]
judging from the current state of the 'backend' part of the codebase, this may still be a distant future?!

**Comment by fabiospampinato** [comment]
@lmihalkovic We could make a regular landing page tomorrow, but yeah having an embedded instance of Notable in there is a bit tricky right now, I don't think that future is too distant though, maybe with a couple of weeks of full-time work we could get there.

**Comment by lmihalkovic** [comment]
I have absolutely no doubt that you have the skills to do it.. I have seen enough of your work to believe it.

**Comment by noraj** [comment]
@fabiospampinato Right now you could simply generate a static website from your README automatically with GitHub pages by selecting "master branch" or a custom content by selecting "master branch /docs fodler":

![image](https://user-images.githubusercontent.com/16578570/57796199-111d6300-7748-11e9-87d0-4d5e6381fa88.png)

**Comment by fabiospampinato** [comment]
@noraj Thanks for the suggestion, I'll think about it.

**Comment by noraj** [comment]
@fabiospampinato I just did for a little tool, fro m a README like [this](https://github.com/noraj/flask-session-cookie-manager/blob/master/README.md) you'll obtain a website like [this](https://noraj.github.io/flask-session-cookie-manager/) and it literally take 10 seconds. You can choose between 12 themes.

**Comment by fabiospampinato** [comment]
Just implemented: https://notable.md.

I'll post an update about this in the subreddit.
