### ISSUE TITLE
New note with active search will not save properly

### ISSUE THREAD

**Issue by xpi-d** [notable/notable#483]
- **OS Version**: OSX 10.14.3
- **Notable Version**: 1.3.0

### Current behavior

- Search for a note
- While search is active, create a new note that does not meat the search criteria
  - New note created by shortcut or clicking `+`, not enter like the feature in #40
- Add content to the new note
- Exit edit mode
- New note contents are lost, or partially lost

### Expected behavior

New note should be saved in the background, even though it is not listed in the search results.

**Comment by fabiospampinato** [comment]
I can't reproduce the issue.

> or partially lost

What do you mean **partially** lost?

Are you referring to the fact that the currently edited note may no longer match the current search query so it may disappear from the search results?

**Comment by xpi-d** [comment]
A Line or two may be saved in the body and an incomplete title is saved.

> Are you referring to the fact that the currently edited note may no longer match the current search query so it may disappear from the search results?

No, but that is what I'd expect in the search functionality.

**Comment by xpi-d** [comment]
I cannot reproduce this anymore. I bet inadvertently you fixed it in release 1.4.0
