### ISSUE TITLE
"Snippet Note" Feature

### ISSUE THREAD

**Issue by lsascha** [notable/notable#491]
### Feature description

Coming from Boostnote i liked the "Snippet Note" Feature there that allows me to basicly add source-codes of multiple files into a single note.
The files are displayed as tabs inside the note.
So for example i can have a "Readme.md" File which describes stuff and a "something.sh" script that is the code for the file to execute.

Currently the only option is to attach the script as shell script, but i have to go to that file and open it inside a editor to see the source-code. and clicking on it just executes it directly which is not really something i always want.

### Feature motivation

For having multiple "files" codes attached to a single note and seeing its content immediately.

**Comment by fabiospampinato** [comment]
I don't think this will be implemented.

IMHO embedding the code in a code block is good enough. If you need to embed many snippets then you might want to use the "attachments" feature.

You raised a good point though, if opening an attachment executes it's not good in this scenarios 🤔 I think we could make sure to open executable files in a text editor if they aren't strictly binary, would that work for you?

**Comment by fabiospampinato** [comment]
Also you could attach those snippets as attachments, and then link to the inside the note, so the whole thing would be pretty clean, it's not like the note will be cluttered with all that code or the code will be hard to access because it's not reachable from the note itself.

**Comment by lsascha** [comment]
Sure. that would work too. It just should not execute the file just by clicking on it. Or at least it could ask what i want to do with that file.

**Comment by fabiospampinato** [comment]
Good, let's track this [here](https://github.com/notable/notable/issues/492) then.
