### ISSUE TITLE
ENEX import issues

### ISSUE THREAD

**Issue by msbentley** [notable/notable#494]
- **OS Version**: ubuntu 18.04
- **Notable Version**: 1.3.0

### Current behavior

Importing a simple ENEX note containing inline links and bullets doesn't reproduce the formatting in Notable.

[Test.zip](https://github.com/notable/notable/files/2900077/Test.zip)

### Expected behavior

Inline links and bullets are correctly formatted. Also the justification is odd.

This is how it looks in Evernote/Nixnote:

![image](https://user-images.githubusercontent.com/1671065/53331483-4a84c600-38f1-11e9-8e27-a8c666e33a4b.png)

and in Notable:

![image](https://user-images.githubusercontent.com/1671065/53331510-5f615980-38f1-11e9-92c5-e5ba72cf797c.png)

The generated MD in Notable is:

```
# Test

<p align="justify">This is testing [inline links](https://feedly.com/i/entry/Nt4fyhG21JbPujJtAXF21iv3D4YjLVs1hWXxg4HWlpY=_16922795307:ec771e:ad2b6584) first as normal</p>

- <p align="justify">Then [a link](https://feedly.com/i/entry/Nt4fyhG21JbPujJtAXF21iv3D4YjLVs1hWXxg4HWlpY=_16922795307:ec771e:ad2b6584) in a list</p>
    
- <p align="justify">etc.</p>

<p align="justify">Also testing different levels of bullets</p>

- <p align="justify">first</p>

- <p align="justify">second</p>

- <p align="justify">third</p>

- <p align="justify">second</p>

- <p align="justify">first</p>
```

Thanks!

Mark

**Comment by fabiospampinato** [comment]
Transfered here https://github.com/fabiospampinato/enex-dump/issues/9
