### ISSUE TITLE
Incorrect Note Name in file system

### ISSUE THREAD

**Issue by jeff9315** [notable/notable#495]
I'm a brand new user so I'm not sure if I'm doing something wrong, but sometimes when I name a note something like `# My Note` , the file that gets created is `My Note(2).md`. Am I doing something wrong or is this a bug? 

Note that there is NOT another note with the same name which is what would normally cause that to occur in other applications.

**Comment by fabiospampinato** [comment]
🤔 That can happen if there was a note named "My Note.md" relatively recently, even though that's not currently there in the disk, I think that's what's happening here and there was a "My Note.md" note before (perhaps the same one, and then the title changed a couple of times), is this not the case?

**Comment by jeff9315** [comment]
I'll keep an eye on this and see if it reoccurs when I KNOW that I have NOT previously created a note with the same name.

**Comment by fabiospampinato** [comment]
This should be fixed now, previously names used recently where blacklisted for a relatively long period of time, now instead once they are used they are released immediately, so this shouldn't occur anymore.
