### ISSUE TITLE
Single character math not working

### ISSUE THREAD

**Issue by Tyilo** [notable/notable#497]
- **OS Version**: Arch Linux
- **Notable Version**: 1.3.0

### Current behavior

When notable renders the following markdown, neither the inline or display math are working:

```markdown
This is a variable $a$.

Here it is again, but centered:

$$a$$
```

Both are just rendered as text containing `$a$` and `$$a$$`.

I can fix this by using `\text{}`, but it's an annoying work-around:

```markdown
This is a variable $\text{}a$.

Here it is again, but centered:

$$\text{}a$$
```

### Expected behavior

I would expect the first example to render exactly like the second.

**Comment by fabiospampinato** [comment]
This is already fixed in the master branch, hopefully I'll release v1.4.0 this week.

<img width="685" alt="screen shot 2019-02-27 at 00 25 10" src="https://user-images.githubusercontent.com/1812093/53454027-2ecf0c00-3a26-11e9-9373-c7f8c2a2b73a.png">
