### ISSUE TITLE
Changes made though default editor not always brought into Notable

### ISSUE THREAD

**Issue by jeff9315** [notable/notable#498]
Windows 10
Notable 1.3.0

This bug is similar to [#489](https://github.com/notable/notable/issues/489) ... but it appears to be sporadic. I can't duplicate it on a consistent basis.

I use a default editor called Ghostwriter for Markdown. When I'm editing a document in Notable, then open the external editor (from the top right of Notable's menu bar -- Open in Default App), make a change through the external editor, and come back to Notable, the changes are SOMETIMES NOT in Notable. nor is there any pop up asking me to do a refresh. If I immediately close Notable, the change is in the external file. Closing and reopening Notable brings the change in.

**Comment by fabiospampinato** [comment]
Let's track this in the issue you linked, #489.

I'm not sure why this is happening, definitely switching to a more reliable (and faster!) filesystem watcher is something we will have to do at some point.

**Comment by jeff9315** [comment]
I'm closing this just so that any future comments go into [#489](https://github.com/notable/notable/issues/489)
