### ISSUE TITLE
Find in file

### ISSUE THREAD

**Issue by gcfer** [notable/notable#502]
### Feature description

When searched in the field “Search notes...,” a word (or multiple words) is (are) used to find a list of files which contain that word(s). It would be nice to be able to search/find/replace/highlight words in the currently open file. 

### Feature motivation

Higher productivity. No need to find where a word in the file actually is when one knows that the word is there.

**Comment by fabiospampinato** [comment]
This might get implemented in the next release, as I'm not switching to Monaco as the editor and it has a nice find widget included.

**Comment by fabiospampinato** [comment]
Duplicate of #140
