### ISSUE TITLE
Focus and auto-select Untitled text on the new note

### ISSUE THREAD

**Issue by matejdro** [notable/notable#505]
Just small quality of  life improvement: 

When I create new note, the first thing I always do is set the name of new note. But at the moment I must manually move my cursor to the `Untitled` text, delete it and type new name instead.

What if upon creating new note, `Untitled` text would be already selected and cursor positioned on the start of the title, allowing me to just type the title in?

**Comment by fabiospampinato** [comment]
Sounds like a pretty good improvement 👍

**Comment by fabiospampinato** [comment]
![foo](https://user-images.githubusercontent.com/1812093/54157240-363fdd80-4448-11e9-98a4-9a4502c1e21c.gif)

👍

**Comment by Armagedoom** [comment]
This should also happen when the current focus is in the note list.
Currently, when a new note is created but the focus was in the note list (middle pane), the focus remains there and you cant write the tittle. A hack I am using is doing "control+e" twice, but the focus should automatically go to the editor once a new note is created.

This is tested in several different instances of Windows 10 machines, although in the gif in your comment seems to be behaving correctly. (Focus is in middle pane when creating the note and it automatically goes to tittle).

**Comment by fabiospampinato** [comment]
@Armagedoom can you open a separate issue about this?

**Comment by Armagedoom** [comment]
Done: https://github.com/notable/notable/issues/639
