### ISSUE TITLE
Always shows note tags

### ISSUE THREAD

**Issue by jlnbdt** [notable/notable#506]
### Feature description

Always shows tags wich are applied to a note when this one is opened 

### Feature motivation

I always use the same 'types' of tags to my notes (participants of the meeting, type of meeting, etc.) In order to check if I correctly set them, I have to click on the tag icon. IMHO, tags are an important metadata which should always be visible above a note.

**Comment by fabiospampinato** [comment]
I agree that the current solution is not great, let's track this here #105.
