### ISSUE TITLE
First appearance of string "sidebar" as heading is colored with dark background

### ISSUE THREAD

**Issue by mschaeling** [notable/notable#509]
- **Win10 64bit**:
- **Notable Version 1.3.0**:
![notable-sidebar-coloring](https://user-images.githubusercontent.com/22516886/53697781-25062980-3dd5-11e9-9a00-017b60f4c963.jpg)

### Current behavior

The first appearance (and only the first) of the string `"Sidebar"` or `"sidebar"` as any heading will be colored with a dark grey background (the same as the app sidebar is colored in).

### Expected behavior

Do not change background color if using `Sidebar` or `sidebar` in headings.

**Comment by fabiospampinato** [comment]
Related to #173, but kind of in reverse.
