### ISSUE TITLE
Is there a way to change the size of an attached image?

### ISSUE THREAD

**Issue by GeorgeHicks1** [notable/notable#511]
Hi,

I am trying to add a jpg to my note, I can display it in the note, but it appears very large. Is there a way to control its size?

Thanks,
George

**Comment by fabiospampinato** [comment]
There's no strictly-Markdown way to do that, but you can write arbitrary HTML in your notes, so you could write something like:

```html
<img src="@attachment/foo.png" width="400">
```

There's actually an extension of Markdown that let's do this, but we don't currently support it.

**Comment by GeorgeHicks1** [comment]
Thank you for the quick response, this is perfect.
