### ISSUE TITLE
A better scheme for creating filenames?

### ISSUE THREAD

**Issue by jeff9315** [notable/notable#513]
Currently, BOTH the title tag and the filename are taken directly from the H1 in the file. However, the CommonMark spec doesn't allow a space in a Destination Link.

So, I have this code in my file ``# This is a Test Note``.

The title tag is ``title: This is a Test Note`` which makes perfect sense. However, the filename is ``This is a Test Note.md`` which makes destination links look like either 

``See also [This is a Test Note](./This%20is%20a%20Test%20Note.md)`` 
or 
``See also [This is a Test Note](@note/This%20is%20a%20Test%20Note.md)`` 

which are both ugly and difficult. I wonder if Notable could create better filenames by changing the spaces to hyphens or underscores.

Hopefully, at some point we will also be able to pick a filename from a list and get it into the editor in a better manner, but that should be a separate request tied to one of the enhancement requests regarding picking tags.

**Comment by fabiospampinato** [comment]
> which are both ugly and difficult.

Actually you don't have to write links that way.

1. The escaping is done for you in this situation, so you can just write: `[This is a Test Note](@note/This is a Test Note.md)`

2. If you're ok with using the default title you can just omit it, so the code becomes: `[](@note/This is a Test Note.md)`

3. We support wiki-style links too, so in this scenario you could just write `[[This is a Test Note]]`. There was an issue with detecting extensions, by that has been fixed in the master branch #412. There was also an issue about non-inline wiki-style links, that's fixed too in the master branch #411.

IMHO given the current situation having to write `[[This is a Test Note]]` is pretty good.

> Hopefully, at some point we will also be able to pick a filename from a list and get it into the editor in a better manner, but that should be a separate request tied to one of the enhancement requests regarding picking tags.

Yeah once we fix #20 we can fix this too.

**Comment by fabiospampinato** [comment]
>  I wonder if Notable could create better filenames by changing the spaces to hyphens or underscores.

Let's track this part here: #452

**Comment by jeff9315** [comment]
The only problem with the spaces is that other Markdown Editors don't necessarily support spaces in destination addresses. So, in a [near] perfect world, it seems like there should be an option as to whether you want filenames to be converted with "-", "_", or left alone.

**Comment by fabiospampinato** [comment]
@jeff9315 🤔a customizable pre-processing step sounds like something we might implement.

**Comment by ahmetsevki** [comment]
Suggestion: Why not have uuid file names and have the title taken from metadata? Converting the top line to file name has too many file operations, files get deleted, re-created etc. And OS level operations do not have recoveries in some cases if you overwrite them.
If we used filenames as <uuid>.md, and parsed them, when someone deletes a file it can go to a different directory, which can serve as trash. This is a note taking app, and there is nothing more than you write a huge note, then delete it/overwrite it accidentally and not be able bring back. 
By having the first title serve also as a filename doesn't serve any purpose other than being able to look at the directory and say which file has what. If you want to get to that, you can always do a grep for the title and find which file it was. 
This also allows us to eventually perhaps move the data layer to s3 or some other storage.
I looked at issues to see if this was proposed before, my mistake if I did not see it.

**Comment by fabiospampinato** [comment]
@ahmetsevki could you open a separate issue about this so that we can better keep track of it?

**Comment by aisbergde** [comment]
> The only problem with the spaces is that other Markdown Editors don't necessarily support spaces in destination addresses. So, in a [near] perfect world, it seems like there should be an option as to whether you want filenames to be converted with "-", "_", or left alone.

That's also my issue. I need "-" instead of " ", then it will fine with other apps, with other wiki style links systems, ...

Currently I need to rename the files created by Notable manually and then not rename the first line to keep "-" and to avoide " "

**Comment by fabiospampinato** [comment]
Let's track this here: https://github.com/notable/notable/issues/452

An option for automatically using characters other than spaces for joining words can be added.
