### ISSUE TITLE
Note deleted when using third-party synchronization services

### ISSUE THREAD

**Issue by JonnyAiello** [notable/notable#515]
Platform Details: 
Ubuntu 16.04 LTS
Samsung Note 5 running Android

I have my notes directory stored within my Dropbox sync folder on my linux desktop. Any notes created/saved on the desktop sync seamlessly and can be accessed on my phone via the dropbox app. I can open a note and edit the note within the app (using the dropbox text editor).  ONCE I SAVE the note on the phone app, it is deleted from my desktop directory.  Did some tests and came up with the following:

- Restoring the file using the dropbox web client on my desktop successfully returns the note. The note syncs into the folder and appears in notable as soon as the sync completes
- Files that are restored this way contain the edits made on the phone, leading me to believe that the sync did complete before the file was deleted
- Attempting to save the file while notable is NOT open on my desktop works fine, the file is synced properly and remains after notable is opened
- Saving note files using an external phone app (QuickEdit) instead of the dropbox text editor yields the same results

Conclusions: it seems like if a notable .md file is updated by dropbox while notable is open, the program freaks out and kills the file. It has no problem adding new files, as is the case when dropbox restores one of the deleted notes, and doesn't seem to have a problem accepting notes that were edited while notable isn't running.

**Comment by fabiospampinato** [comment]
I think I found what's causing this, it's most probably a race condition involving the third-party synchronization service deleting the file and then recreating it, and Notable attempting to delete the deleted file again, which in the meantime might have been recreated.

Update fixing this coming soon.

**Comment by fabiospampinato** [comment]
I think I just fixed this, the fix will be available in the next release. Please do let me know if you'll still be able reproduce the issue.
