### ISSUE TITLE
KaTeX Rendering Issue Upon Export to PDF/HTML

### ISSUE THREAD

**Issue by OnyxDelta** [notable/notable#521]
- **Antergos Linux**:
- **Tested on 1.3.0 and Master (03/06/2019)**:

### Current behavior
Currently, when the following Markdown source is provided:
![Markdown](https://user-images.githubusercontent.com/12561892/53964253-959e9600-40b4-11e9-9858-eb73ce3f97ef.png)
It is exported to PDF as this:
![PDF](https://user-images.githubusercontent.com/12561892/53964046-23c64c80-40b4-11e9-893e-588170e233f6.png)
It is also exported to HTML as this:
![HTML](https://user-images.githubusercontent.com/12561892/53964091-3e002a80-40b4-11e9-8a43-76f4fd6d1534.png)

### Expected behavior
The expected behavior can be observed when the content is rendered in Notable:
![Notable](https://user-images.githubusercontent.com/12561892/53964137-5cfebc80-40b4-11e9-8efd-2977503426f3.png)

**Comment by fabiospampinato** [comment]
For future reference this is the text that's being used:

```katex
$\Sigma$
$\epsilon$

$\frac{x}{y}$

$$\frac{x}{y}$$
```

> Tested on 1.3.0 and Master (03/06/2019):

Interesting, what's the latest commit in your local repo?

I can't reproduce this anymore from the master branch:

<img width="1440" alt="screen shot 2019-03-07 at 15 53 42" src="https://user-images.githubusercontent.com/1812093/53965382-68240d80-40f1-11e9-8350-d2babcadeae8.png">

**Comment by OnyxDelta** [comment]
> For future reference this is the text that's being used:
> 
> ```
> $\Sigma$
> $\epsilon$
> 
> $\frac{x}{y}$
> 
> $$\frac{x}{y}$$
> ```
> 
> > Tested on 1.3.0 and Master (03/06/2019):
> 
> Interesting, what's the latest commit in your local repo?
> 
> I can't reproduce this anymore from the master branch:
> 
> <img alt="screen shot 2019-03-07 at 15 53 42" width="1440" src="https://user-images.githubusercontent.com/1812093/53965382-68240d80-40f1-11e9-8350-d2babcadeae8.png">

The latest commit in my local repo is when CodeMirror was replaced with Monaco.

**Comment by fabiospampinato** [comment]
Weird 🤔 Can you post here the exported html and pdf files?

**Comment by OnyxDelta** [comment]
I have created a ZIP archive with both of them, along with the source file.
[Example of Failing to Parse KaTeX.zip](https://github.com/notable/notable/files/2941921/Example.of.Failing.to.Parse.KaTeX.zip)

**Comment by fabiospampinato** [comment]
@OnyxDelta what commands have you executed to get the app working? did you execute _all_ of the commands described [here](https://github.com/notable/notable/blob/master/.github/CONTRIBUTING.md#submit-a-pull-request)?

**Comment by fabiospampinato** [comment]
And did you change anything in the codebase? There seems to be something of that sort going on.

**Comment by OnyxDelta** [comment]
I did not change anything in the code base, but I did overlook that site by accident.
I was running:
npm install
npm run svelto:dev
npm run svelto:prod
npm run build:linux

I am trying to rebuild using the provided instructions now.

**Comment by fabiospampinato** [comment]
> npm run build:linux

So you're running the production version of the app, there may very well be an issue there, I haven't tested that yet because bundling the app takes a bit.

**Comment by OnyxDelta** [comment]
I see. I am unfortunately struggling to build following the development instructions, as once the "npm run dev" command is executed, the build process freezes on:
┏ Renderer -------------------

  ℹ ｢wdm｣: Compiled with warnings.

┗ ----------------------------
I am going to continue to try to work at it and update this post once I figure it out.

**Comment by fabiospampinato** [comment]
@OnyxDelta rebase on the master branch, there was an issue where webpack was trying to load some unneeded files from katex's folder..

**Comment by OnyxDelta** [comment]
Okay. I was now able to compile it and verify in the development build, everything exports properly.

**Comment by fabiospampinato** [comment]
Just fixed ✌️ 
 https://github.com/notable/notable/commit/192759503be4719101802058325a4f6f6ae9cc96
