### ISSUE TITLE
Support for footnotes

### ISSUE THREAD

**Issue by MarcoEstevez** [notable/notable#523]
### Feature description

Support for footnotes

example:   

Footnotes[^1] are added in-text like so ...
And with a matching footnote definition at the end of the document:

[^1]: Footnotes are the mind killer.

**Comment by fabiospampinato** [comment]
Sounds like a good suggestion, what programs are currently using this syntax?

**Comment by MarcoEstevez** [comment]
It's pretty standard I would say, I saw it in several places

Here https://www.markdownguide.org/extended-syntax/ you can read about extended markdown syntax including footnotes and document mentions

- CommonMark
- GitHub Flavored Markdown (GFM)
- Markdown Extra
- MultiMarkdown

But I saw also here on some sort of plugin for PHP
https://rephrase.net/box/word/footnotes/syntax/

And yet another python library
https://python-markdown.github.io/extensions/footnotes/

**Comment by fabiospampinato** [comment]
> and this document mentions:

They don't mention them as flavors of markdown that support this syntax though, as obviously your first comment isn't doing anything special with the footnotes.

**Comment by MarcoEstevez** [comment]
Sorry, I just readed to quick. :-)

But as said there:
>Extended syntax isn’t available in all Markdown applications. You’ll need to check whether or not the lightweight markup language your application is using supports extended syntax. If it doesn’t, it may still be possible to enable extensions in your Markdown processor.

Looks like this syntax is the recommended or proposed for the standard, and it could be a great addition to Notable, so far for me it is the only thing I'm missing to fully migrate from any other documentation system.

**Comment by PsiACE** [comment]
Footnote seems to work on Typora, but GitHub and GitBook don't support it very well.

**Comment by fabiospampinato** [comment]
For future reference: [here](https://github.com/markdown-it/markdown-it-footnote) theres a markdown-it that implement footnotes. It also adds inline footnotes, which sound very interesting and I've never seen before.

**Comment by fabiospampinato** [comment]
I just implemented this, wait for the next release to try it out.

**Comment by Unknow0059** [comment]
It's kind of strange that footnotes don't support alphabetic contents, but do support numeric and alphanumeric. E.g. If I want to have a footnote with content [^A] it just won't work.

**Comment by fabiospampinato** [comment]
@Unknow0059 All that seems to be supported actually, but the syntax for writing an inline footnote is slightly different:

![image](https://user-images.githubusercontent.com/1812093/93711753-b4566780-fb48-11ea-8bb3-bf4a2d601806.png)

Maybe there was a bug in v1.8 about this, check if the alphas of v1.9 work for you: https://github.com/notable/notable-experimental/releases

**Comment by Unknow0059** [comment]
Yeah, I am in that version. I was referring to how the footnotes aren't named after the content - they ignore the footnote content and just name themselves automatically. 

I hadn't realized this then, but if this is the standard then not much can nor should be done.

**Comment by fabiospampinato** [comment]
Oh yes I see what you mean now 🤔 Yeah that's how the work usually, it might not be worth changing that.
