### ISSUE TITLE
Move some menu items from Notable to Note

### ISSUE THREAD

**Issue by muescha** [notable/notable#533]
### Feature description

i would expect this `Notable` menu items more in the `Note` menu:
- Import...
- Export
- Open Data Directory
- Change Data Directory...

### Feature motivation

in the application menu i would expect only seldom used menus or the settings menu.

**Comment by fabiospampinato** [comment]
The `Note` menu, currently being renamed to `File`, currently includes action related to a single note.

Maybe `Import...` and `Export` should still be there, but I'm not sure about moving the commands about the data directory, as those are not really related to notes directly 🤔

**Comment by muescha** [comment]
i think i would also expect it there 

even more if you name it `File`
