### ISSUE TITLE
Notebook concept

### ISSUE THREAD

**Issue by muescha** [notable/notable#534]
### Feature description

add a submenu to the `~/.notable` directory
the name of the folder can be visible in a new title bar
the first example dataset can be saved as `~/.notable/tutorial/`
if there is a `title.txt' in the tutorial folder then this is used as title

maybe new menu items:
- New Notebook...
- Open Notebook...

### Feature motivation

as new user i know from the onboarding that all is saved in the data directory. and the first i was looking how to change it to have some different Notebooks (because i don't like to delete all tutorial files) resulting in filing #533

**Comment by fabiospampinato** [comment]
> the name of the folder can be visible in a new title bar

That might be problematic as there's no real titlebar on macOS.

> maybe new menu items:

Those are a good idea I think, let's track this here: #480 

> because i don't like to delete all tutorial files

You can actually re-import them at any time from the `Help -> Tutorial` menu.

In general about nested notes folders there's been some discussion about this here: #54, the TLDR; is that I don't see the _long-term_ value in this basically, let's continue talk about this in there if you want.
