### ISSUE TITLE
Linking notes breaks when target note is in subfolder

### ISSUE THREAD

**Issue by matejdro** [notable/notable#537]
- **OS Version**: Windows 10
- **Notable Version**: v1.3.0

### Steps to reproduce:

1. Create note `A`
2. Create note `B`
3. Add `[[A]]` text to the `B` and save.
4. When you click on the button/link, note A opens properly.

5. Create `/Test` folder inside notes folder and Move `A.md` file into that folder
6. Neither `[[A]]` or `[[Test/A]]` seems to work for linking, Notable will just open blank page upon clicking the button

**Comment by jeff9315** [comment]
As a workaround, just use a . at the start of the path to signify the current directory or .. to signify the parent directory. For example, these 2 methods work:

```
  * [[./Test/a.md]]
  * [Test](./Test/a.md)

```

**Comment by fabiospampinato** [comment]
> Neither [[A]] or [[Test/A]] seems to work for linking, Notable will just open blank page upon clicking the button

This issue got fixed along the way, or I recently fixed in my development branch. You should basically provide the path to the note you're linking to, relative to the note you're linking from, so `[[Test/A]]` will work and `[[A]]` won't in this scenario.
