### ISSUE TITLE
make it possible to maintian the notes structure inner a notebook

### ISSUE THREAD

**Issue by alexlavigne** [notable/notable#544]
### Feature description

I wish to maintain my notes like a tree  inner a notebook.
It means the notes inner a notebook has relationship with others .
It is something like that:

Notebooks
└── parent_notebook1
    ├── son_notebook1
    │   └── parent_note1(with some content)
    │       ├── son_note1(with some content relate to parent_note1)
    │       │   ├── grandson_note1(with some content relate to son_note1)
    │       │   └── grandson_note2(with some content relate to son_note1)
    │       └── son_note2(with another content relate to parent_note1 )
    └── son_notebook2

### Feature motivation

That is what my notes look like now.
It is a normal structure of knowleges .

**Comment by fabiospampinato** [comment]
There's been some discussion about this, I don't think this is going to happen: #54
