### ISSUE TITLE
Button "permanently delete" doesn't delete

### ISSUE THREAD

**Issue by jankatins** [notable/notable#550]
- **OS Version**: Mac
- **Notable Version**: 1.4.0

### Current behavior

Delete a note so that it turns up in the trash label. click on trash and on a note and then the button "permanently delete" in the menu bar above a note. Nothing happens.

### Expected behavior

Note is removed

**Comment by fabiospampinato** [comment]
It's working for me, are you doing something different?:

![foo](https://user-images.githubusercontent.com/1812093/54445575-51129a80-4745-11e9-8912-3685e6ae429f.gif)

Or perhaps the button itself isn't working because of #133?

**Comment by jankatins** [comment]
Could be, at least today it seemed random: sometimes it worked, sometimes it didn't. Closing for now, as #133 seems to describe such behaviour.
