### ISSUE TITLE
Right-click in the editor does not work

### ISSUE THREAD

**Issue by tbkrtz** [notable/notable#553]
- **OS Version**: Windows 10 and Linux Mint 19.1
- **Notable Version**: 1.4.0

### Current behavior

Right-click on selected text does not work in the editor

### Expected behavior

Right click opens menu with: Cut, Copy, Paste

**Comment by amelandri** [comment]
I think that it doesn't work on sidebar too. For example I'm missing the "Empyt trash" contextual menu

**Comment by fabiospampinato** [comment]
OP's issue has been fixed, thanks for @prashkup's PR.

@amelandri's issue has been fixed too. All other context menu seem to be working, the only broken one was the trash one.
