### ISSUE TITLE
checkbox check and un-check action will shift page up

### ISSUE THREAD

**Issue by tundra2002** [notable/notable#554]
- **OS Version**: macOS Majove 10.14.3 
- **Notable Version**: 1.4.0

### Current behavior
- Create a checkbox
```
- [ ]
```
- In view mode check or un-check the checkbox
- This action will take you to the top of the page

### Expected behavior
Checking and un-checking the checkbox in view mode should not shift the page up to top.

**Comment by fabiospampinato** [comment]
Duplicate of #446.
