### ISSUE TITLE
Update 404 AppImage

### ISSUE THREAD

**Issue by Philiphlop** [notable/notable#556]
- **OS Version**: Linux desktop 4.20.14-200.fc29.x86_64
- **Notable Version**: 1.3.0

### Current behavior

- Notable > Check for Updates...
- Notification, downloading update
- Notification, download failed https://github.com/notable/notable/releases/download/v1.4.0/notable-1.4.0-x86_64.AppImage

### Expected behavior

Actual AppImage location does not have x86_64 in filename https://github.com/notable/notable/releases/download/v1.4.0/Notable.1.4.0.AppImage

**Comment by fabiospampinato** [comment]
Indeed we are telling the app to download the wrong, non-existent, file. This is probably a bug with `electron-builder` itself, I'll report it tomorrow if that's not a known problem already.

I think we should be able to fix this by manually updating the published `latest-linux.yml` file 🤔 

Thanks for reporting the issue!

**Comment by fabiospampinato** [comment]
Upstream issue: https://github.com/electron-userland/electron-builder/issues/3890

**Comment by fabiospampinato** [comment]
Related issue: Wrong exe path listed in latest.yml
