### ISSUE TITLE
problem with "Alt+Shift" key

### ISSUE THREAD

**Issue by geeksesi** [notable/notable#557]
- **OS Version**: Ubuntu + Xfce : 18.04

- **Notable Version**: 1.3.0

### Current behavior
when i want to change keyboard language with "Alt+Shift" key i will see this 
![image](https://user-images.githubusercontent.com/28778964/54459733-d2d1ea80-477c-11e9-9166-e699dfa3a648.png)
i can't find any exist keyboard shortcut for this.

**Comment by fabiospampinato** [comment]
I'm not sure I'm understanding this right, you want to change the keyboard layout with an Alt+Shift but instead it opens up the menu?

**Comment by geeksesi** [comment]
yes. and while menu is open i can't write anything.

**Comment by geeksesi** [comment]
i know you don't have this shortcut.
i think it's my problem with some app made by electron.
test 2 other app.
- [postman](https://www.getpostman.com/) 
- [my electron-react test app](https://github.com/geeksesi/time_reminder)
in both of them i have this problem...
i don't know why? i have not any shortcut to open this menu.

**Comment by fabiospampinato** [comment]
@geeksesi Maybe you could try reporting this issue in the `electron` repo?

**Comment by geeksesi** [comment]
like this problem : 
[riot-web](https://github.com/vector-im/riot-web/issues/4345)

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.

@geeksesi Thanks for reporting this issue and providing links to a solution!

**Comment by alxpsr** [comment]
Have same bug with `v1.8.4`. OS: Linux Mint
