### ISSUE TITLE
Asciimath rendering in table headers

### ISSUE THREAD

**Issue by mtib** [notable/notable#559]
- **OS Version**: Ubuntu 18.10
- **Notable Version**: 1.4.0

### Current behavior

The following markdown:

```md
# Asciimath in Table Headers

| &sum& |
| ----- |
| table |
```

creates a document looking like this:

![image](https://user-images.githubusercontent.com/3661529/54475626-b58c3300-47f3-11e9-91c3-d318dcab389d.png)

Which means both the rendered math and the latex the asciimath gets converted to is visible. (This is true for any asciimath "formula")

### Expected behavior

Only the rendered latex should be visible.

![image](https://user-images.githubusercontent.com/3661529/54475643-eb311c00-47f3-11e9-8436-bb085dd1cece.png)

**Comment by mtib** [comment]
```md
# Asciimath in Table Headers

| $\sum$ | &sum& |
| ------ | ----- |
| right  | wrong |
```
![image](https://user-images.githubusercontent.com/3661529/54475679-727e8f80-47f4-11e9-8ac0-6e720ba747c5.png)

**Comment by mtib** [comment]
The fix should be simple, hiding `.katex-mathml` and `.katex-html` inside of `th` elements. Because `.katex` itself is looking fine.

**Comment by mtib** [comment]
Though the class of the containing `th` looks messed up.

![image](https://user-images.githubusercontent.com/3661529/54475731-4f081480-47f5-11e9-8c50-0e4c560e7ce3.png)

**Comment by fabiospampinato** [comment]
Fixe din v1.6.
