### ISSUE TITLE
Markdown error output capped to 25K characters

### ISSUE THREAD

**Issue by jdbrice** [notable/notable#565]
- **OS Version**: OS X 10.14
- **Notable Version**: 1.4.0

### Current behavior
Long notes get truncated with error message:
[markdown error: output capped to 25000 characters for performance]

This is only in preview mode. In edit mode I can see the full content of the note.

Can be reproduced by making a note with more than 25K characters.

### Expected behavior

Entire note should be rendered in preview mode

I did not have the same issue in v1.3.0

Thanks for the hard work on v1.4.0, overall a very nice set of improvements and updates.

**Comment by fabiospampinato** [comment]
I added that limit because very large notes could effectively crash the app.

You can edit very large notes on the editor because only the lines you're actually seeing are getting rendered, so in effect the actual length of the note doesn't matter much.

This is a problem in preview mode because the entirety of the note is getting rendered regardless of what portion of it you're currently able to see. This will be fixed when we switch to marked #531 as in my benchmarks it is about 100x faster than showdown so the problem kind of disappears.

**Comment by jdbrice** [comment]
Glad to hear there is already a plan for this.  It sounds like it will  be resolved with the switch to marked.  
Thanks!

**Comment by Blacksuan19** [comment]
> I added that limit because very large notes could effectively crash the app.
> 
> You can edit very large notes on the editor because only the lines you're actually seeing are getting rendered, so in effect the actual length of the note doesn't matter much.
> 
> This is a problem in preview mode because the entirety of the note is getting rendered regardless of what portion of it you're currently able to see. This will be fixed when we switch to marked #531 as in my benchmarks it is about 100x faster than showdown so the problem kind of disappears.

if i export a file as a pdf or HTML this text shows as well and the file is not the full markdown text 
this is the [exported file](https://github.com/notable/notable/files/3122013/Untitled.pdf)
this is the [original note](https://drive.google.com/file/d/1HOt60fmWWw3n-1aOotsnWhuYvs_sDCFl/view?usp=sharing)

**Comment by fabiospampinato** [comment]
@Blacksuan19 that's an unfortunate consequence of the limit which I didn't think about 🤔

**Comment by Blacksuan19** [comment]
any workaround?
by far the best markdown editor btw, I switched from Evernote and host the notes on my google drive now

**Comment by fabiospampinato** [comment]
Not currently unfortunately, I'll try to switch to marked sooner rather than later.

**Comment by fabiospampinato** [comment]
@Blacksuan19 let's track that [here](https://github.com/notable/notable/issues/643).

**Comment by gukandrew** [comment]
Maybe it's good idea to add some option to turn big files support on with warning? I really prefer to see in preview even big markdown files not only for export..

**Comment by fabiospampinato** [comment]
@gukandrew I'm probably going to switch to marked #531 during this iteration, then I'll just remove the character capping since marked renders large files 100x faster than showdown in my tests.

**Comment by fabiospampinato** [comment]
No longer an issue in v1.6.
