### ISSUE TITLE
Upgrade not working

### ISSUE THREAD

**Issue by jasonwhat** [notable/notable#571]
I've tried to upgrade along with all other Linux apps. Slack and Typora updated as expected, but not Notable. I then tried to specifically update Notable and got this message.
`sudo apt-get dist-upgrade notable
Reading package lists... Done
Building dependency tree       
Reading state information... Done
notable is already the newest version (1.3.0).
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

Trying to check for upgrade in Notable produces nothing, no update and no error message.

**Comment by fabiospampinato** [comment]
@jasonwhat how did you install the app?

**Comment by jasonwhat** [comment]
.deb file and used the point and click install that ChromeOS provides. I did this with Typora and Slack also.

**Comment by jasonwhat** [comment]
Will I get any weirdness with files and attachments existing folders if I uninstall this version and install the new one and then point it to my existing directory, or will Notable try to recreate the directory?

**Comment by fabiospampinato** [comment]
@jasonwhat it should just work.

**Comment by jasonwhat** [comment]
@fabiospampinato it did work seamlessly, once I uninstalled from the command line, installed the new version via download and ChromeOS, it opened with all my notes just as they were in the last version. Thank you.

**Comment by fabiospampinato** [comment]
I think the issue here is that the deb doesn't support autoupdating, I think in order to do that perhaps it should be published in some repository and kept up-to-date there.
