### ISSUE TITLE
Auto suggestive markdown insertions with TAB key

### ISSUE THREAD

**Issue by napstercc** [notable/notable#573]
### Feature description

Feature like the "suggestive" TAB creation feature similar to the current note taking app "Mark Text". Should I create an issue on Github? (without mentionning Mark Text)

### Feature motivation

To help in writing faster. by pressing TAB and scrolling to suggested options, ex Header 1 #
 , Header 2 ## , insert table, insert quote ... we can quickly write Mardown text without looking back on google, how to insert a table, a quote... the TAB suggestive feature will create it for you.

Please take a look at what the Mark Text app is doing if this is unclear.

**Comment by fabiospampinato** [comment]
I think what you want is a mixture of:

- Autocomplete #20 #103, but also for inserting some markdown elements 
- A markdown cheatsheet #392 
- Shortcuts for quickly/easily toggling some formatting #153 
- Some form of WYSIWYG editor #284, since according to Mark Text's demo they are using that kind of editor

Is this correct?

**Comment by napstercc** [comment]
Kind of. 
To be more precise, if you look at the GIF from Mark Text on their repo:
https://raw.githubusercontent.com/marktext/marktext/master/doc/marktext.gif
Something like that, which will pop up a textbox to help you add emojis, or insert a table, or if you are on a new line, help you add H1, H2, H3... quote block, ... just with TAB without having to type the markdown text.
Is it more clear?

**Comment by fabiospampinato** [comment]
Yes thanks.

**Comment by fabiospampinato** [comment]
I'm closing this in favor of the issues I mentioned and this other one: https://github.com/notable/notable/issues/576.

The autocompletable things will be taken care of in the core, the WYSIWYG editor part will at some point probably be implemented too, all the rest could be implemented by plugins #128 in the future.
