### ISSUE TITLE
Open Data Directory doesn't work

### ISSUE THREAD

**Issue by jeff9315** [notable/notable#579]
Version 1.3 and 1.4.0 under Windows 10 ...

I have never been able to get the Check for updates to work.

Open Data Directory only works occasionally. I have better luck if Notable is NOT maximized. And once I get Open Data Directory to work when it's NOT maximized, it seems to work for awhile even when Notable is maximized.

**Comment by fabiospampinato** [comment]
> I have never been able to get the Check for updates to work.

Let's track this here #577, I think I might have shipped a broken version of the updater in v1.3 🤔 

> Open Data Directory only works occasionally. I have better luck if Notable is NOT maximized. And once I get Open Data Directory to work when it's NOT maximized, it seems to work for awhile even when Notable is maximized.

That seems pretty random, I'm not sure what could cause that.

**Comment by jeff9315** [comment]
Is working in 1.8.2
