### ISSUE TITLE
Export to PDF doesn't export nothing except a folder with all the attachments

### ISSUE THREAD

**Issue by BobMilli** [notable/notable#582]
- **Windows 10**:
- **1.4.0**:

### Current behavior

I've got a big note with a lot of attached screen copy and when I do an export to pdf, a folder is created with no pdf and only the attachements folder with all the attachement.
### Expected behavior

Get a pdf with all the content of my note

**Comment by fabiospampinato** [comment]
Can you post here the note, or _a_ note, that reproduces the problem? Are you able to export the same note to HTML or Markdown?

**Comment by BobMilli** [comment]
Hello,
Here is a _a_ note on which I reproduce.
In the export folder, there no PDF and only one out of two attachement is there.
Thanks for your help.
HTH
Bob

[Notable_Export_Pdf_Bug.zip](https://github.com/notable/notable/files/3007195/Notable_Export_Pdf_Bug.zip)

**Comment by fabiospampinato** [comment]
@BobMilli the attached note reproduces the problem for me, thanks!

**Comment by fabiospampinato** [comment]
I think I found the root cause of this issue, let's track this here: #979
