### ISSUE TITLE
Code block grey background gets broken when indenting with multiple tabs

### ISSUE THREAD

**Issue by sdelatorrep** [notable/notable#583]
- **OS Version**: Ubuntu 16.04 64-bit
- **Notable Version**: 1.4.0

### Current behavior
Code block grey brackground gets broken when indenting with several tabs. This how it looks in Notable:
![image](https://user-images.githubusercontent.com/17491353/54920800-74d39e80-4f04-11e9-8029-fbf8ab914fe5.png)

To reproduce, paste this into a note in Notable:
```
* To replace null character `^@`, use <kbd>Ctrl-V</kbd><kbd>Ctrl-J</kbd>
    ```
    %s/<Ctrl-V><Ctrl-J>//g
    ```
* To use part of the matching pattern in the replacement, use `\( \)` (this is called atom):
    ```
    %s/\([0-9]\)E/\1\rE/gc
    ```
    * `\([0-9]\)E`: the atom
    * `\1\` is the 1st atom
```
### Expected behavior

This would be what I expect:

* To replace null character `^@`, use <kbd>Ctrl-V</kbd><kbd>Ctrl-J</kbd>
    ```
    %s/<Ctrl-V><Ctrl-J>//g
    ```
* To use part of the matching pattern in the replacement, use `\( \)` (this is called atom):
    ```
    %s/\([0-9]\)E/\1\rE/gc
    ```
    * `\([0-9]\)E`: the atom
    * `\1\` is the 1st atom

**Comment by fabiospampinato** [comment]
Fixed in v1.6.
