### ISSUE TITLE
Add support for `@search/*` urls

### ISSUE THREAD

**Issue by gramster** [notable/notable#584]
### Feature description

This is two related feature requests. 

- It would be great to be able to hyperlink notes, so clicking on s hyperlink would jump to the other note
- it would be great to be able to create "search links" - a special form of link that instead of jumping to a page uses the link to kick off a search and filters to the matching notes

The first supports one-to-one wiki-like linking functionality, while the second is more of a one-to-many zettelkasten approach.

### Feature motivation

Linking makes notes more powerful for structuring knowledge.

**Comment by fabiospampinato** [comment]
> It would be great to be able to hyperlink notes, so clicking on s hyperlink would jump to the other note

It's already possible, check [this](https://github.com/notable/notable/blob/master/resources%2Ftutorial%2Fnotes%2F10%20-%20Linking%20Attachments%E2%88%95Notes%E2%88%95Tags.md).

> it would be great to be able to create "search links" - a special form of link that instead of jumping to a page uses the link to kick off a search and filters to the matching notes

🤔 We already have something similar but for tags, I suppose it would make sense to add support for linking to specific searches too, especially when in the future the search engine would be much more useful #293.
