### ISSUE TITLE
To Do Checkboxes - checking off causes Notable to jump to top

### ISSUE THREAD

**Issue by jeff9315** [notable/notable#587]
Win 10, Notable 1.4.0 ...

I have a file of To Do items with checkboxes. When checking each off off, Notable jumps to the top of the file instead of staying where it is. When I'm going through a list of To Do items, the cursor and the view should just stay exactly where it is.

**Comment by fabiospampinato** [comment]
Definitely. Closing as duplicate of #446

**Comment by jeff9315** [comment]
Actually this is NOT a duplicate of that one. With this one, I'm only in the Preview pane not the Edit pane.

**Comment by fabiospampinato** [comment]
@jeff9315 Yeah I mentioned this [here](https://github.com/notable/notable/issues/446#issuecomment-473333347).
