### ISSUE TITLE
Query parameters rendered as AsciiMath

### ISSUE THREAD

**Issue by jlnbdt** [notable/notable#588]
- **Windows 10**
- **Notable Version: 1.4.0**

### Current behavior

The picture isn't displayed in view mode
`
![](https://media.licdn.com/dms/image/C560BAQHuyaTNK60n7A/company-logo_400_400/0?e=1561593600&v=beta&t=DLTCPd1cVaE4vMC72T6mdvUc-FUvhVXfHRr7Qao8Y4A)`

Result:

![Notable_2019-03-28_09-12-59](https://user-images.githubusercontent.com/6383095/55140882-65896680-5139-11e9-89f8-aade47813930.png)

### Expected behavior

Image must be displayed in view mode (the same piece of code works perfectly in other editors like Mark Text or Typora)

Thanks!

**Comment by fabiospampinato** [comment]
I think the problem here is that the string between the 2 `&` characters is being interpreted as AsciiMath. That's obviously problematic for urls which contain query parameters.

**Comment by fabiospampinato** [comment]
This has been fixed, the fix will be available in the next release.
