### ISSUE TITLE
Trailing # signs go into YAML Title and filename

### ISSUE THREAD

**Issue by jeff9315** [notable/notable#591]
If the level 1 heading ends in `#` (or any number of `###`), then the trailing `#` signs go into the tile and the filename and I don't think they should.

Also, the ending `#` signs should NOT show up in the view ... they should ONLY be kept in the editor. 

The trailing `#` in `H1-H6` headings are legal Markdown ... not parsed but used as an optional visual indicator. Any other Markdown editor I've used has stripped them out of the Preview.

**Comment by fabiospampinato** [comment]
This was fixed in v1.5.0
