### ISSUE TITLE
Lack of Find command within a document, coupled with Preview pane and Edit pane not in sync

### ISSUE THREAD

**Issue by jeff9315** [notable/notable#592]
When I'm looking at the Preview pane and see something I need to change, I switch to the Edit view. However, that view immediately jumps to the top of the document. Not to where my cursor is in the Preview pane. So, I'm no longer positioned where I need to change. That issue is made worse by the lack of a _Find_ command in the Edit view that will find the text I want to change.

Are basic edit commands planned for in the near-term?

**Comment by fabiospampinato** [comment]
> Not to where my cursor is in the Preview pane

There's no cursor in preview mode. I think we should definitely support being able to switch to a specific position in edit mode from preview mode.

> That issue is made worse by the lack of a Find command in the Edit view that will find the text I want to change.

Let's track this here #502 

> Are basic edit commands planned for in the near-term?

What commands are you thinking about?

**Comment by jeff9315** [comment]
* The major one that is needed is **Find**
* But other really useful formatting commands would be
  **Bold** (Ctrl-B),  **Italic** (Ctrl-I), **Strikethrough** (Ctrl-K), **Insert bulleted item or numbered item according to the line above** (similar to what you have Alt-Enter do)

* Others that would be useful are 
  * Search / Replace
  * Regex Search or Regex Search/Replace
  * Change case of highlighted text to regular, sentence, title case

**Comment by jeff9315** [comment]
@fabiospampinato ... not sure if you saw that I had added more info,

**Comment by fabiospampinato** [comment]
@jeff9315 Yeah I saw that, even if I don't reply immediately at some point all these "needs more info" issues will be categorized better at some point.

> The major one that is needed is Find
> Search / Replace
> Regex Search or Regex Search/Replace

Let's track this here #502.

Maybe we should also add global (regex) search & replace capabilities.

> But other really useful formatting shortcuts would be
Bold (Ctrl-B), Italic (Ctrl-I), Strikethrough (Ctrl-K), Insert bulleted item or numbered item according to the line above (similar to what you have Alt-Enter do)

Let's track this here #153.

> Change case of highlighted text to regular, sentence, title case

This sorts of features I think should/will be implemented via third-party plugins #128.

And finally let's track the part about synchronizing preview mode and edit mode here #311, which is very closely related.
