### ISSUE TITLE
Add Git Integration

### ISSUE THREAD

**Issue by evansan** [notable/notable#593]
### Feature description

Automatically or manual sync with a button in the app  (with git push)
Add note history support from git versioning system

**Comment by fabiospampinato** [comment]
Let's track versioning here #116 

There's going to be some synchronization

**Comment by pointbre** [comment]
I'm using FSWatch + Git-Sync(http://gitsync.sourceforge.net) for automatic synchronization to remote git repository like: `fswatch -o . | while read num; do (flock -x 200 && (echo "saved" | ./git-sync)) 200> /tmp/git-sync.lock ; done`.

I wish this helps until Notable supports synchronization and/or git integration.

**Comment by fabiospampinato** [comment]
@pointbre Thanks for sharing the script, it looks very useful!

**Comment by fabiospampinato** [comment]
I'm closing this in favor of #116
