### ISSUE TITLE
Sort by modification date

### ISSUE THREAD

**Issue by eitch** [notable/notable#598]
I searched the list, found none talking about sorting by modification date

### Feature description

I would like to sort the notes by modification date, and thus have the latest at the top.

### Feature motivation

This makes it easier to find notes i just edited, and is a behaviour most other note apps implement.

**Comment by fabiospampinato** [comment]
This is already implemented, the little section below the search bar is clickable:

<img width="685" alt="Screen Shot 2019-04-05 at 13 29 58" src="https://user-images.githubusercontent.com/1812093/55624685-fe0d8f80-57a6-11e9-8e12-654e71ba317c.png">

**Comment by eitch** [comment]
Awe shucks... Thanks! I didn't see that.
