### ISSUE TITLE
Copy the file name of attachments

### ISSUE THREAD

**Issue by pointbre** [notable/notable#599]
### Feature description
* When right-clicking attached file in note, `Copy file name` menu is displayed in pop up menu.
* When `Copy file name` is clicked, file name of the attachment is copied into clip board so that user can paste into a note easily.

### Feature motivation
For a note with multiple files and images, 
* Attach all of necessary files first
* Insert images from attachments easily from attached files
* Write links to attached files easily from attached images

When using Notable's markdown file for sharing or Hugo, it's important the contents of markdown file has no dependency like attachments in header section.

**Comment by fabiospampinato** [comment]
> (...) so that user can paste into a note easily.

I see the need for solving this problem, but I think autocomplete for attachments #20 would be a better solution, no?

**Comment by pointbre** [comment]
I have had a look at #20 and autocomplete is better than my suggestion. Closing now.
