### ISSUE TITLE
Mermaid diagram not exported to html/pdf

### ISSUE THREAD

**Issue by pointbre** [notable/notable#606]
- **OS Version**: Linux(Ubuntu 16.04)
- **Notable Version**: v 1.4.0

### Current behavior
Mermaid diagram is properly rendered in Notable
![image](https://user-images.githubusercontent.com/28047477/55763975-995f7700-5abd-11e9-9329-896484a1b216.png)

When exporting a note with mermaid diagram to html/pdf, diagram is not included in the exported result.
![image](https://user-images.githubusercontent.com/28047477/55763984-abd9b080-5abd-11e9-973a-2a9de7cdb9d8.png)

### Expected behavior
* When exporting a note with mermaid diagram to html/pdf, diagram is included in the exported result.

**Comment by fabiospampinato** [comment]
I can reproduce.

I think this may happen somewhat intermittently, as I'm sure before releasing v1.4 I checked that all [these](https://github.com/notable/notable/tree/master/resources/theming/notes) notes were exported properly and they were 🤔

**Comment by fabiospampinato** [comment]
I think this might be related to #621

**Comment by emiola** [comment]
Still true with v1.6.2 on mac.

**Comment by fabiospampinato** [comment]
Yes I can still reproduce it, I'll see if I can allocate some time to this. But it currently happens somewhat intermittently in my tests, there must be something unexpected going on 🤔

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
