### ISSUE TITLE
the question of evernote import

### ISSUE THREAD

**Issue by guqinglei123** [notable/notable#608]
this is very good sofeware， but i
had encounted a trouble and have one sugestion.when i import notes for .exen file，i find i will lose my image in note. Is there a way to solve this problem? what's more，I would like to ask after the software can support the way of folder tree management. Because when I sync my notes to another device, I can't easily find my notes. thank for you very much.

**Comment by fabiospampinato** [comment]
@guqinglei123 could you re-open the issue about Evernote [here](https://github.com/fabiospampinato/enex-dump/issues)? Which is the tool we are using for importing `.enex` files.

> I would like to ask after the software can support the way of folder tree management.

There's been some discussion about this here #54
