### ISSUE TITLE
No word wrap in editor on MacOS

### ISSUE THREAD

**Issue by adamlehenbauer** [notable/notable#609]
I'm using the Mac build and don't have any word wrapping in the editor. This occurs with Split View Mode on or off, and Zen Mode on or off.

Notable Version: 1.4.0
OS Version: OS X El Capitan, 10.11.6

See attached image

![notable-bug](https://user-images.githubusercontent.com/649544/55928397-58ef1e80-5bcd-11e9-9916-baeb694dc52e.png)

**Comment by tbkrtz** [comment]
The Shortcut doesn't work?
<kbd>Alt-Z</kbd> - Toggle word wrapping.

**Comment by adamlehenbauer** [comment]
Yes, thanks, that does work. I didn't know about it or see it anywhere in the menus or documentation.

**Comment by fabiospampinato** [comment]
@adamlehenbauer I think you've hit `alt+z+ by mistake, as word-wrapping is enabled by default. All the supported shortcuts are listed [here](https://github.com/notable/notable/blob/master/resources%2Ftutorial%2Fnotes%2F07%20-%20Shortcuts.md).
