### ISSUE TITLE
Scroll position in edit mode is not maintained when switching to the app

### ISSUE THREAD

**Issue by mochtu** [notable/notable#611]
- **OS Version**: macOS
- **Notable Version**: 1.4.0

### Current behavior

* Create a longer document, stay in edit mode
* Put the cursor at the beginning or end of the document (it doesn't matter)
* Switch away to another app (e.g. Finder), by CMD+Tab or mouse
* Go back to Notable by CMD+Tab or mouse
* Scroll position is set to 0 (goes all the way up) but cursor stays where it was. When starting to type, scroll position is set so that cursor is visible, but not exactly like it was before.

### Expected behavior

* Maintain exact scroll position when re-focusing the app.

-- 
Thanks for creating this great note taking app :-) !

**Comment by fabiospampinato** [comment]
Thanks for reporting the issue 👍

**Comment by mochtu** [comment]
I can not reproduce this any more. I don't know what changed, because there was no update. I will re-open this ticket, if I can figure out how to reproduce it.

**Comment by baldwindavid** [comment]
I was running into the same problem on a long document. Similar to @mochtu I somehow cannot reproduce. I'll leave a few details here in case it helps someone else.

I have two monitors, one of which is in vertical/portrait mode. I had a long Notable document displayed in the vertical monitor. Every time I clicked away from the app and came back, the document scrolled all the way to the top.

I started to troubleshoot by moving the Notable app to the other screen and the issue immediately went away. I then moved it back to the original vertical screen and the problem did not reappear. So maybe it has something to do with a multi-monitor setup? Maybe not.

Anyway, if others run into this problem hopefully this helps. Thanks.

**Comment by fabiospampinato** [comment]
I can't reproduce this. The condition under which it happened seem very strange to me, most probably this is an issue originating from Chromium or Electron themselves, which we don't really have any control over.

**Comment by baldwindavid** [comment]
For what it's worth, it is now back and seems to happen regardless of the screen I am on. Understandable if it is something in Chromium/Electron. I'll probably just try to use smaller documents. I tend to use one big scratchpad for in-process activities so it is more likely to be an issue for me.

**Comment by fabiospampinato** [comment]
If somebody can provide some reliable steps that reproduce the problem I'll be happy to take a closer look at this, but it seems to be that this is most probably an upstream issue, it may get resolved once we update Electron perhaps.
