### ISSUE TITLE
Export to PDF keep scrollbar in code block

### ISSUE THREAD

**Issue by inkx** [notable/notable#613]
- **OS Version**: Windows 10 (1809)
- **Notable Version**: 1.4.0

### Current behavior

When exporting note in pdf format, the code bloc part keep the scroolbar and of course, in static.
So i lose information.

![image](https://user-images.githubusercontent.com/2292513/56272539-31331580-60fb-11e9-9747-8b954fae3d82.png)

### Expected behavior

Some other way to keep all my information in PDF (usable to generate documentation)

**Comment by fabiospampinato** [comment]
Good point, I guess the only option here is to force line breaks in codeblocks when exporting to pdfs 🤔

**Comment by inkx** [comment]
Indeed ! And succeed to keep visible when it comes to a normal return to line or if it is only a formatting :)
