### ISSUE TITLE
Copy button for tags

### ISSUE THREAD

**Issue by Armagedoom** [notable/notable#617]
### Feature description

Allow to copy tag from the tag popover and filter by a specific tag with as few clicks as possible.

### Feature motivation

Two sub-features:
1. Once #106 is closed, we will need a fast way to filter by tag. Ideally, there would be a button that would automatically filter the selected notes by the tag clicked.
2. Moreover, sometimes while editing tags it would be very convenient to copy an existing tag instead of having to rewrite the full hierarchy. Currently this can only be done by hand, and if the tag is long, its not efficient.

The following pull request solves the second sub-feature: #616

**Comment by fabiospampinato** [comment]
I think a better solution to both problem will be having some kind of autocomplete #20. But in the meantime I guess a context menu option for copying a tag should be useful.

**Comment by fabiospampinato** [comment]
Closing as we implemented a "Copy" action via the context menu for this in v1.5.0
