### ISSUE TITLE
@note - copy path from sidebar / populate

### ISSUE THREAD

**Issue by mcconkiee** [notable/notable#619]
### Feature description

I love that I can link notes with the `@note/note-name.md` feature. It would be super convenient if we can either copy the name /path of the note from the sidebar, or (somehow) populate that as a user is typing. 

### Feature motivation

Probably, I'm just lazy.

**Comment by fabiospampinato** [comment]
That's a very good suggestion actually. In the long term we'll fix this once and for all with autocomplete #20, in the short term perhaps we can add a context-menu item for copying the filename, let's track this in this PR: #616
