### ISSUE TITLE
Master Branch build failed.

### ISSUE THREAD

**Issue by abdurrahmanekr** [notable/notable#624]
(app) version: 1.4.0

node: v11.13.0
yarn: 1.13.0
npm: 6.7.0

I'm running this code: 

```
yarn
yarn run build:mac
```
output:

![image](https://user-images.githubusercontent.com/15075759/56490292-5bb31300-64ed-11e9-815b-5816c80fecb5.png)

[output.log](https://github.com/notable/notable/files/3102711/output.log)

**Comment by Baldomo** [comment]
The error is here: [tree.tsx:41](https://github.com/notable/notable/blob/master/src/renderer/components/main/structures/tree.tsx#L41)
Here's a patch to remove the unneeded argument: 
```diff
diff --git a/src/renderer/components/main/structures/tree.tsx b/src/renderer/components/main/structures/tree.tsx
index 48ecca5..8f06a6b 100644
--- a/src/renderer/components/main/structures/tree.tsx
+++ b/src/renderer/components/main/structures/tree.tsx
@@ -38,7 +38,7 @@ class Tree extends React.Component<{ children, id: string, className?: string, d
   componentWillUnmount () {
 
     $.$window.off ( 'resize:height', this.updateHeight );
-    $.$window.off ( 'scroll-to-item', `#${this.props.id}`, this.scrollToItem );
+    $.$window.off ( 'scroll-to-item', this.scrollToItem );
 
   }
 

```
After patching `tree.tsx` everything works

**Comment by fabiospampinato** [comment]
Fixed, at least it works now for me with _npm_.
