### ISSUE TITLE
Improved dialog when the data directory cannot be found

### ISSUE THREAD

**Issue by CrashyBang** [notable/notable#627]
### Feature description

When starting Notable if the data directory cannot be found show an error as opposed to the initial "Please select your data directory" dialogue, this way a user would:
a) Know that their folder has gone missing (deleted/inaccessible)
b) Have an option to retry (they may know how to make it accessible)
c) Have the option to select a new data directory.

### Feature motivation

I use Notable a lot at work, but when I work remotely I have to connect to a VPN before I have access to the data drive at work, if I don't have the VPN started when I open Notable it will show the initial "Please select your data directory" dialogue.

NOTE: If I connect to the VPN while in the  "Please select your data directory" dialogue and then try and select the remote directory I get the #251 message and Notable locks up and I have to restart.

### Additional Thoughts

I did an issue search for "directory" and trawled through that, I couldn't find to many related issues other than #590 and #338 which both involve being able to set/swap data directories.

I think if we eventually allow a user to have a list of data directories and we can't find the last one they used (and they have more than one in the list) then  a prompt could show saying "Directory **XXX** is inaccessible, please select from..." and list their other directories, this would also show the "Retry" option mentioned above if the user knows how to make the desired data directory accessible.

Based off the issues I did look at this seems fairly edge case so I would be interested in your thoughts, I just thought given that multiple data directories seems to be a relatively sought after feature and does seem to be under consideration it would be a good time to get this in now.

**Comment by fabiospampinato** [comment]
There's a lot of valuable feedback here, thanks. Addressing some of the points:

- Maybe the previous data directory becomes available later on (say you have to mount a drive or something): in this situation I guess Notable should probably detect that and reload automatically. What do you think? 🤔 

- There's no message saying that the previous data directory has not been found: IMHO that wouldn't be very useful, as you can basically consider the window asking you to pick a data directory as that message, but we could also show a notification perhaps 🤔.

- No "retry" button: you can basically just close the window and re-open notable to retry. And if we detect the directory becoming available automatically there won't be a need for a retry button.

- List of previous data directories: sounds like a nice addition, but let's wait for #338 to be implemented first.

>  it would be a good time to get this in now.

There's currently no quickpick-related API nor any primitive support for plugins, I'd rather implement this once properly.

**Comment by CrashyBang** [comment]
Hey @fabiospampinato,

I like the points you have made here, I will give a more fleshed out comment soon, sorry I have been swamped.

Cheers!

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.

Now if the data directory is first unaccessible, but then becomes accessible, the app just detects that and reopens it.
