### ISSUE TITLE
Support spaces in attachment name

### ISSUE THREAD

**Issue by bspeice** [notable/notable#636]
### Feature description

Right now, attachments with spaces in the filename need URL escaping in order to work correctly (%20). Is it possible to parse the link URL (especially when using `@attachment` notation) to replace spaces accordingly?

### Feature motivation

Avoid broken links because URLs aren't escaped in markdown documents.

**Comment by fabiospampinato** [comment]
I think this is already supported, you can write urls like this:

```
[](@attachment/foo bar baz.png)
```

**Comment by bspeice** [comment]
Yeah, it's working now, must've been something screwy on my end. Thanks much!
