### ISSUE TITLE
Sorting Options (By Last Updated)

### ISSUE THREAD

**Issue by AdrianChungie** [notable/notable#637]
### Feature description
Besides sorting by title it would be nice to have a option to sort **by last updated**.

### Feature motivation
Usually there is a note that I just edited and when I want to go back to it the same day I sometimes forget which Note I was working on and so a sort by last updated option would put it at the top. Therefore, I can easily see the last one that I last edited/updated.

**Comment by fabiospampinato** [comment]
Already implemented, the thing below the search bar is clickable:

<img width="685" alt="Screen Shot 2019-04-30 at 23 06 59" src="https://user-images.githubusercontent.com/1812093/56993422-b5c27100-6b9c-11e9-8280-c44b09db8b33.png">

**Comment by AdrianChungie** [comment]
Oh yes so sorry! I did not realize I could have clicked on that.
