### ISSUE TITLE
The selected tag in the tag pane should be easier to spot

### ISSUE THREAD

**Issue by Armagedoom** [notable/notable#638]
### Feature description

It should be easier to spot which is the currently selected tag.

### Feature motivation

I find difficult to spot the selected tag due to small difference in colors in low-bright screens (which are less harmful for the eyes).
![image](https://user-images.githubusercontent.com/4046326/57015830-2ad28c80-6c17-11e9-9460-f81a04a2db4f.png)

Could we perhaphs set the text of the selected tag to other color than white? Or make the selected tag color stand a bit more?

**Comment by fabiospampinato** [comment]
This is a bit problematic. I've thought about this and for consistency I had decided to make all active buttons/items darker by default. But with the current light theme if the screen isn't bright enough the contrast just isn't great in the sidebar. The only option IMHO here is making the active sidebar item lighter instead, which will go a bit against the rest of the UI though. I think changing the color of the text would make the UI significantly uglier 🤔 I'll have to think more about this.

**Comment by fabiospampinato** [comment]
It should be slightly more readable now, I'll try to improve on it further in the future:

<img width="720" alt="Screen Shot 2020-01-12 at 22 27 41" src="https://user-images.githubusercontent.com/1812093/72226619-080cbc00-358b-11ea-8690-95cf99cb044a.png">
