### ISSUE TITLE
Note deleted when using Syncthing

### ISSUE THREAD

**Issue by fabiospampinato** [notable/notable#642]
@jeff9315 says:

> I use syncthing to synchronize my folders between my android phone and Windows. If I make a change on Android and the synchronize occurs while I am not viewing the same file on Windows, everything is OK. However, if I am viewing the same file on Windows, the file is deleted. This is consistent. I just tried it about 5 times. Editing my files on Windows and Android is a critical part of my process so I'll probably switch to Typora until the bug is resolved.

**Comment by memogarcia** [comment]
Same issue, notable delete files without warning and without even putting them on trash, this a very nasty bug

**Comment by fabiospampinato** [comment]
I'm closing this as a duplicate of #515, I'm pretty sure it's the same root issue and I think I've found what's causing this, update coming soon.
