### ISSUE TITLE
An error occurred: Object has been destroyed

### ISSUE THREAD

**Issue by slippard** [notable/notable#647]
- **OS Version**: linux 4.15.0-48-generic
- **Notable Version**: v1.4.0

```
Error: Object has been destroyed
    at /opt/Notable/resources/electron.asar/browser/rpc-server.js:433:50
    at EventEmitter.ipcMain.on.args (/opt/Notable/resources/electron.asar/browser/rpc-server.js:275:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/opt/Notable/resources/electron.asar/browser/api/web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)
```

**Comment by slippard** [comment]
I believe this was a result of unmounting the disk where the data directory was located, while a note was being edited. This caused the app to freeze and become unusable. I just force closed & reloaded and it loaded the notebook just fine.

**Comment by fabiospampinato** [comment]
I suppose in that situation we should re-open the "open data directory" window, and if there are unsaved changes we should save them somewhere, perhaps in the desktop.

How does that sound as a solution? :thinking:

**Comment by slippard** [comment]
I'm not sure if saving them to the desktop would be the best solution. At the time of this error, I am running `elementary OS 0.4.1 Loki` which does not allow you to utilize the desktop without 3rd party tools.

A possible solution: When data directory is no longer available, revert to the default `./notable` directory and create a sub dir called something like "recovery" to place the unsaved work? 

Just a side note, I didn't actually lose any of the data in that fairly large note. Maybe just having notable relaunch to get the prompt for the data directory would be enough.

**Comment by fabiospampinato** [comment]
Loki is pretty unique in this regard, even though the default desktop environment doesn't give you a usable desktop we should still be able to save stuff on `~/Dekstop` I think. Another option would be to save the note in the clipboard, but that could get lost more more easily.

**Comment by slippard** [comment]
I agree, the clipboard could be lost too easily. 

Would it be possible to support multiple data directories simultaneously in a way that they can fall back on each other? It's possible i'm over complicating this.

For example: If `./dir1` & `./dir2` are both known to hold data directories, then if `./dir2` becomes unavailable, revert to last known directory `./dir2` or even prompt which dir to load, if more than 2.

**Comment by fabiospampinato** [comment]
🤔 we could support multiple data directories in the same window in the future, but for this specific issue I'm not sure that would help, it would be weird if a note on dir1 got stored on dir2 because dir1 became unavailable.

**Comment by slippard** [comment]
I can't seem to reproduce the initial `Object has been destroyed` error. However, it is still necessary to relaunch app completely if disk is unmounted, as it does not update notes when device is re mounted. I'll provide a terribly recorded gif to show. Perhaps the initial error earlier was due to more than just unmounting said disk. I hope this is somehow helpful. 

![notable](https://user-images.githubusercontent.com/30223792/57148361-7318b880-6d97-11e9-86af-6234b79aa781.gif)

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.

Now if the data directory becomes unaccessible for whatever reason the app will ask you to pick a new one, and if the previous data directory becomes available again it just detects that and reopens it.
