### ISSUE TITLE
Escaped chars don't show properly on title view

### ISSUE THREAD

**Issue by muratsu** [notable/notable#649]
- **OS Version**: Win10
- **Notable Version**: 1.4.0

### Current behavior

* Create a new note
* Change the title to `\[foo\]`
* Toggle the edit mode
* The markdown will display `[foo]` whereas the title on the title view is `\foo\`

### Expected behavior

* The title on the title view should match the markdown
* Both should display `[foo]`

**Comment by fabiospampinato** [comment]
Can't reproduce, am I doing it right? (perhaps it got fixed by one of the recent commits 🤔) 

![Kapture 2019-05-04 at 22 07 34](https://user-images.githubusercontent.com/1812093/57184250-1ca39b00-6eb9-11e9-939a-3ec4ea0c3103.gif)

**Comment by muratsu** [comment]
Interesting! Yeah, could be a commit since the released version that might have fixed it. Is there a guide for building the project? I can double check

**Comment by fabiospampinato** [comment]
@muratsu That'd be helpful, thanks. You can follow [these steps](https://github.com/notable/notable/blob/master/.github%2FCONTRIBUTING.md#submit-a-pull-request).

**Comment by muratsu** [comment]
Phew! Running this in Windows was not super smooth but I've managed to run it. Looks like the issue is fixed in master. Looking forward to 1.4.1 release :)

**Comment by fabiospampinato** [comment]
Great, thanks for checking!

>  Running this in Windows was not super smooth

What issues have you encountered?

**Comment by muratsu** [comment]
1) Have to remove "fsevents" since package doesn't work on Windows
2) Need to rename weback.js to webpack.config.js, otherwise `npm run monaco` will run the webpack.js using Windows Script Host instead of running the binary under node_modules. 
3) `npm run tutorial` requires cmd zip which doesn't come pre-installed with Windows

**Comment by fabiospampinato** [comment]
> Have to remove "fsevents" since package doesn't work on Windows

This should be fixed now https://github.com/notable/notable/commit/b58ab1a53ece29346eda2da6ffabf261c08f5fe2

> Need to rename weback.js to webpack.config.js, otherwise npm run monaco will run the webpack.js using Windows Script Host instead of running the binary under node_modules.

That's weird, what version of NPM are you on?

> npm run tutorial requires cmd zip which doesn't come pre-installed with Windows

Yeah it took me a while to write that command and since I develop on macOS I didn't really bother to make it cross platform, I'd be happy to consider a PR for this though 👍
