### ISSUE TITLE
Feature Request: Greater Flexibility in data directory

### ISSUE THREAD

**Issue by sahil48** [notable/notable#651]
Note: I looked at Issue 54. I think my Feature Request is different from this one, since Issue 54 is focused on File Structure within the app, and I am focusing on the data directory itself

As indicated in the Readme, the data directory is currently as follows.

![image](https://user-images.githubusercontent.com/6100774/57229572-6e950f80-6fe4-11e9-80ca-1084b0bd6cf2.png)

Would it be possible to have Notable index all notes in the root folder and subfolders, and simply have attachments in an attachments folder. It would make it a lot easier to use notes stored in notable from other apps, and add existing markdown notes created already sorted in different folders to notable.

Also, where are tags stored, within the markdown file or in some other file?

**Comment by fabiospampinato** [comment]
Closing in favor of #54, which is about the structure on disk, not its internal representation within the app.

> Would it be possible to have Notable index all notes in the root folder and subfolders, and simply have attachments in an attachments folder.

It would be possible, but then should we start to duplicate attachments if you are adding them to multiple notes?

> Also, where are tags stored, within the markdown file or in some other file?

In the metadata section of the note.
