### ISSUE TITLE
I would ask why you don't define props type.

### ISSUE THREAD

**Issue by sosukesuzuki** [notable/notable#657]
Notable is great note-taking app built with TypeScript!
However It looks like it is not well typed. For example, component props type is not defined.
I think you should define component props type for static type check(It may be gradually).

**Comment by fabiospampinato** [comment]
Thanks! I don't like React's `PropTypes` in a TS codebase, I prefer TS to perform the checking at compile time instead.

That being said it's true that a lot of components are currently untyped, this will change when we switch to [overstated V2](https://github.com/fabiospampinato/overstated) (next iteration), whose `useStore` hook provides much better type interring than the current `connect` function.

Also I've made the codebase a bit more strictly typed in general a few commits ago.

**Comment by sosukesuzuki** [comment]
Thanks for your answering.
(I don't like React's `PropTypes` in TS, too. My said "props type" means compile type checking.)

Okay, overstated V2 looks good to me.:+1:
