### ISSUE TITLE
Latest Snap release (1.5.0) does not run (Sandbox error)

### ISSUE THREAD

**Issue by gitbrn** [notable/notable#658]
- **OS Version**: Ubuntu 19.04
- **Notable Version**: 1.5.0

### Current behavior

Attempt to run notable via desktop launcher results in nothing.
Attempt to run from terminal results in:

> 
> $ notable 
> [3445:0512/075126.263444:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /snap/notable/x1/chrome-sandbox is owned by root and has mode 4755.

### Expected behavior

Notable opens normally.

---

The v1.4.0 snap did not encounter this error and it has only occurred since update to 1.5.0.

This appears to be related to the electron upgrade - https://github.com/electron/electron/issues/17972.

**Comment by fabiospampinato** [comment]
Thanks for reporting the issue. 

Another related upstream issue would be: https://github.com/electron-userland/electron-builder/issues/3872

**Comment by OnyxDelta** [comment]
I just wanted to add that this behavior occurs with the .deb package too.

**Comment by fabiospampinato** [comment]
@OnyxDelta under what OS? Because before making the release I've tried it in Lubuntu and it worked for me.

**Comment by OnyxDelta** [comment]
> @OnyxDelta under what OS? Because before making the release I've tried the `.deb` in Lubuntu and it worked for me.

I am using Arch Linux with the PKGBUILD generated from the .deb package located [here](https://aur.archlinux.org/packages/notable-bin/).

**Comment by Thrilleratplay** [comment]
@OnyxDelta  Thanks for the heads up.  I corrected the AUR package build.

**Comment by fabiospampinato** [comment]
I think I found a way to get this working thanks to @thomasnordquist's [script](https://github.com/thomasnordquist/MQTT-Explorer/blob/6e4754f475f657f0efd5be563835feff5881380c/scripts/afterPack.ts).

I'll probably publish a patch release tomorrow, now it's time for me to to catch some z's.

**Comment by thomasnordquist** [comment]
Just tested a fresh copy of the v1.5.0 dmg release, it starts without issues on my MacBook (OSX Mojave 10.14.4).
Auto-updating didn't work for me for the [MQTT Explorer](https://mqtt-explorer.com/) on OSX. (Properly signed and osx a `zip` build, but the update crashed).

**Comment by fabiospampinato** [comment]
@semiopat let's track that here: #577

**Comment by semiopat** [comment]
Yes, exactly the same behavior I had.

**Comment by fabiospampinato** [comment]
@thomasnordquist do you think it would be possible to adapt the script to use `/bin/sh` instead? I think assuming that shell is available rather than bash would be (slightly) more reliable. I tried using `$0` but it doesn't seem to be returning the right path.

**Comment by thomasnordquist** [comment]
I see your point when packaging for more than snap / AppImage.
It may be better to set the SUID-flag for the other distribution formats, instead of the wrapper.

`$0` may greatly vary between different shells and execution context. You may produce a working solution but it is not guaranteed.
https://stackoverflow.com/a/35006505
https://www.ostricher.com/2014/10/the-right-way-to-get-the-directory-of-a-bash-script/
