### ISSUE TITLE
Multiple points with the comparison

### ISSUE THREAD

**Issue by noraj** [notable/notable#661]
On your comparison table, you said that `Joplin` *can export to markdown* in *proprietary format* but in reality it is using markdown files.

```
$ ls ~/Notes/Joplin 
0589d378de8b47bbba6b0f052033f76a.md  2fefe1a9160843a184fec9fa4c966561.md  544fedf7e9394f9bbbcd950b62e289a3.md  8114f985ca7942b7a4da658e528d9330.md  ad614b821d614e49aca1ce8843dded05.md  dad00b7e5050427ebdbbd78a0b4c8739.md  f35878d50966404584227c83f0cde3c1.md
08c4633c60314560a1be48e76f7aec91.md  32fb631bec5f41cfbcd6fdf759226657.md  583c6fec6dc84591abeb29b241ea6433.md  96edb504cac74599b43d9fd94bfe829a.md  b527e6e55cca4a2bb9c40bdc25e8c43c.md  dc45cb0c6feb40f78451aafaad809416.md  fc30dadb83cf4e77bc1509df3a43433c.md
09e38ba1a430480a8ec64be294a1b200.md  348c7fe501954074b1f417c507478a91.md  5f9ff78fb9e84e628a94c452392cfc0c.md  985ac3fc26e740798a7664cba58c1fd7.md  ba94c2b35b0a490d879e9bb73af3ca18.md  df13c999993f41a8814d83bc5e6dfe6a.md
0bd2436a75fa41b3b1fdb8b520887888.md  382f84c2417d41498e55f1ab4e2bab1a.md  656af428b42147ea936d0ebe3d2dea3b.md  99a561a41911426ebd929c0e907c4dc5.md  bac8825bf99b4ebdb4356d79013f52c6.md  e43f49996dc447fa968b91e3656c98b7.md
0ce14edcae7b4f98946a5d0cb6f487e8.md  408a07e967164de5a3a52d02c0fa5ab2.md  6ae365e5fe2d4bf4b7b50909462bede0.md  9d3c41b4f2c44523ab6e3c070d068201.md  c07c90b76af24dab9a27d9b5f87a299e.md  e4b52447b9364a74a8b2490b0fb2ddc0.md
10c49e8e384f4f239091b7fd1231b1e2.md  4a4aff4ba2624fa2952d6db2e6d4b4ee.md  71e164aabfa449db94bdeb307dcc7964.md  a8ed5de985754a0c91097855ab13c0c1.md  c4e0cafd8c294317939d1bd55ab1071d.md  e62b3fac8e87435f921b1a1fa3658823.md
196d0cfab9814ae0bac36c744ca658fa.md  4ebc61581f1a4b2dac8051d74ea45f07.md  72f4ad65c6414ddabaa8457775e7507a.md  aa06240e10604037a8a434a72c168ffd.md  ced7e33a1c7048d7a187f726e30f4e16.md  ede3d5202551416f949bc253ed9109c8.md
2e952495d46b47db8ae88c2dde9a44aa.md  4fae68fd41814ed7bc230b443d0daa62.md  7f12d82e737c46259edb00114b25aff7.md  ab28b75885a140888935b25be60a399a.md  d9cd31d4f9314315a76b710799843b17.md  f1dbd37a065f4075aed99bb6705331de.md
```

It is just using some *frontmatter* (or backmatter as it is at the end of the file) : 

```
id: 2e952495d46b47db8ae88c2dde9a44aa
parent_id: 10c49e8e384f4f239091b7fd1231b1e2
created_time: 2019-05-11T16:47:48.695Z
updated_time: 2019-05-11T16:47:48.695Z
is_conflict: 0
latitude: 0.00000000
longitude: 0.00000000
altitude: 0.0000
author: 
source_url: 
is_todo: 0
todo_due: 0
todo_completed: 0
source: joplin-desktop
source_application: net.cozic.joplin-desktop
application_data: 
order: 0
user_created_time: 2019-05-11T16:47:48.695Z
user_updated_time: 2019-05-11T16:47:48.695Z
encryption_cipher_text: 
encryption_applied: 0
type_: 
```

This not pure markdown but notable too since it is markodwn + frontmatter. Only tools like QOwnNotes or Vnotes are storing metadata in separate sqlite db or json files so data files are true markdown.

The problem with Joplin is more that it is not storing files in a tree, but is using metadata to store the tree state and the name of the file so all files are named with an UID and all in the same folder.

This is the same with Boostnotes:

```
$ ls ~/Notes/Boostnote/notes 
2f84fdd2-195e-454c-a303-591e536bd9ad.cson  5c0f16e3-82dd-4e29-aea6-738777f875d7.cson  7d7da090-8074-4209-90ee-b81e110d1a63.cson  b98d0e08-c13f-4086-ac17-56e6a5853080.cson  ececfcfb-7ef0-4e86-8d4a-3671cc8b6c78.cson
33d739a1-8c3f-4f19-be64-9b130b1c6045.cson  67757f9a-5ca4-439f-8f95-2a70b644ddec.cson  836624c7-9d37-44c6-9f2c-f7899c88b352.cson  c63604e4-8ac8-4c0f-a3d2-2a525946ffcc.cson  f3977561-dcbc-4595-97e3-bbcce6a785ba.cson
3904e1b8-c4d7-4073-9659-b4788d98f3bd.cson  67d9e097-2427-47df-a395-9522ec7318d8.cson  85bb2191-6ae8-4529-92b9-491aabbd6484.cson  caf910d7-3abf-4a17-8226-1820a09d3171.cson  f4fb872b-ac8f-4023-b4a0-e0f0db9a5769.cson
4988ad2c-f204-4482-ad22-d7bace755078.cson  6cb17de0-97cf-4b76-98dc-1a269516aee4.cson  869b0f1e-33dc-4c88-a544-1a4f031f2f44.cson  cc842114-75f6-44fe-b9a0-5bd411df3858.cson  f67d2d56-cd45-4351-860d-2b36563ea9d4.cson
554d1c70-7498-4e2e-b242-6721019ca661.cson  77db15f3-abeb-4113-b11c-a58b2ec77e56.cson  b041e583-28d8-4261-96b9-f95e4bbfcba5.cson  cd10e518-57b0-40d1-aed9-b9b131423324.cson  f96e2935-0614-4fff-a078-21682bb00630.cson
```

But even if Boostnotes is storing data in CSON files, the `content` value is markdown, you should rather ad a markdown support row in your table. Also COSN (CoffeeScript-Object-Notation) is not a proprietary format...

I know it is totally personal as you said but Boostnote is beautiful and Joplin is acceptable.

You shoudl also try QOwnNotes and Vnotes, those are awesome but they sucks so much for syntax highlighting (for code blocks) so this is a problem for tech notes. Also you should add the syntax highlight in your row.

Instead of an exported PNG you can make a html page embedded in a one page website, to present notable.

**Comment by fabiospampinato** [comment]
> you said that Joplin can export to markdown in proprietary format but in reality it is using markdown files

Sounds like an inaccuracy then, I'll make sure to update that.

> But even if Boostnotes is storing data in CSON files, the content value is markdown, you should rather ad a markdown support row in your table. Also COSN (CoffeeScript-Object-Notation) is not a proprietary format...

Your comment is reasonable. What I meant with the "no proprietary formats" is more like: is that a format that only this app understands? and could I edit its notes with a third party app? I think in the case of Boostnote while CSON is certainly not a proprietary format you can't use a third-party editor to edit Boostnote's notes without major hassles, so I have it a "X" for that row.

> Also you should add the syntax highlight in your row.

There is one already, it's called "Code syntax highlighting": https://github.com/notable/notable/blob/e37a1d87e6bdc4f0b5c94d6fca2de6614468168d/resources/comparison/table.html#L203-L217

> Instead of an exported PNG you can make a html page embedded in a one page website, to present notable.

The png is actually generated from some HTML: https://github.com/notable/notable/blob/e37a1d87e6bdc4f0b5c94d6fca2de6614468168d/resources/comparison/table.html

I will put that on a website at some point, but I can't just make a website with only a table in it, let's track the progress on the website here #481

**Comment by noraj** [comment]
> There is one already, it's called "Code syntax highlighting":

I'm sorry I missed it.

> The png is actually generated from some HTML: https://github.com/notable/notable/blob/e37a1d87e6bdc4f0b5c94d6fca2de6614468168d/resources/comparison/table.html

Nice to know.

**Comment by fabiospampinato** [comment]
We should also mention that newer versions of Notable aren't open-source anymore (we should mention this in the readme as well).

**Comment by fabiospampinato** [comment]
> On your comparison table, you said that Joplin can export to markdown in proprietary format but in reality it is using markdown files.

I've given this a second look, and the content of my Joplin directory is the following:

```
database.sqlite                                 log.txt
edit-87d55b6c749843218e1db011058cc052.md        resources
log-autoupdater.txt                             tmp
log-database.txt
```

It looks to me like notes are stored in an SQLite database, and attachments are stored as plain files.

So I think my statement that Joplin uses some kind of proprietary format, in the sense that I can't just edit Joplin notes without opening it, but it can export to Markdown is accurate.
