### ISSUE TITLE
Inline preview and minimalistic theme

### ISSUE THREAD

**Issue by rataman098** [notable/notable#668]
### Feature description

It'd be great to have some kind of 'Inline preview' while we edit notes, just like this:
https://caret.io/screenshots/1.png

PS: It also would be great to have a minimalistic theme like that (without borders and maybe more 'monochromatic', to make the editor more visually pleasant 😄 

### Feature motivation

I think for most users it'd be much more comfortable the editing of notes this way, as we could 'preview' how it will look like.

**Comment by fabiospampinato** [comment]
> It'd be great to have some kind of 'Inline preview' while we edit notes, just like this:
https://caret.io/screenshots/1.png

That'd be a WYSIWYG editor: #284.

> PS: It also would be great to have a minimalistic theme like that (without borders and maybe more 'monochromatic', to make the editor more visually pleasant 😄

The only way we are going to get all the themes we want is when we implement custom themes #104, I just can't implement a theme for everybody's tastes, but everyone deserves a theme that he/she likes.

**Comment by rataman098** [comment]
It's not necessarily a WYSIWYG editor, I'm talking about previewing the format (for example, making the text bigger when using `##` before it... etc), as shown in the image. I'm not talking about adding buttons or something, just be able to see how it will look while editing.

**Comment by fabiospampinato** [comment]
>  just be able to see how it will look while editing.

That's exactly what WYSIWYG means: What You See Is What You Get.

There's a separate issue about adding kind of a markdown toolbar.

**Comment by fabiospampinato** [comment]
> just be able to see how it will look while editing.

Btw you can use the Split View mode to achieve something similar. Is definitely not the same thing, but maybe it's something you'd like to try.

**Comment by rataman098** [comment]
```
That's exactly what WYSIWYG means: What You See Is What You Get.
```
Oh, sorry then, I didn't know 😅 
```
Btw you can use the Split View mode to achieve something similar. It's definitely not the same thing, but maybe it's something you'd like to try.
```
Okay, I'll give it a try :D

**Comment by JerryI** [comment]
> > It'd be great to have some kind of 'Inline preview' while we edit notes, just like this:
> > https://caret.io/screenshots/1.png
> 
> That'd be a WYSIWYG editor: #284.
> 
> > PS: It also would be great to have a minimalistic theme like that (without borders and maybe more 'monochromatic', to make the editor more visually pleasant 😄
> 
> The only way we are going to get all the themes we want is when we implement custom themes #104, I just can't implement a theme for everybody's tastes, but everyone deserves a theme that he/she likes.

Check out Obsidian, which uses CodeMirror 6 with Decorations. 
I think, in this sense it might be not a WYSIWYG in way we got used to it, but some editor with a syntax sugar, which still show source code and allows to lively see the preview. I think it could really satisfy both opponents of this idea.
