### ISSUE TITLE
Relative links shouldn't be escaped

### ISSUE THREAD

**Issue by lucashappy** [notable/notable#671]
- **OS Version**: Windows 10
- **Notable Version**: 1.5.1

### Current behavior

I'm using relative links to maintain them clickable when viewed on Github. When there aren't special characters on a note name, the link works both on Github and Notable's preview:
```
[shutdown](./Commands.md)
```
But when there is a special character (like a space) I have to escape the note name so the link is clickable on Github:
```
[shutdown](./Useful%20commands.md)
```
but this breaks the link on Notable's preview, because it escapes the % character turning ```Useful%20commands.md``` in ```Useful%2520commands.md``` in the link.

### Expected behavior

I think Notable shouldn't escape again a relative link already escaped like it does with http links.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
