### ISSUE TITLE
How can I search for text in a note?

### ISSUE THREAD

**Issue by titoesteves** [notable/notable#673]
How can I search for text in a note? I have tried control key + F and nothing happens. Is there a particular button or shortcut key to search for text?

**Comment by fabiospampinato** [comment]
When you search via the search field your notes content are searched in also, but currently there's no way to search specifically within a single note, let's track that here #140

**Comment by DevTomek-pl** [comment]
Hello @titoesteves 
I created a simple JS script for the Notable application that allows you to find a search phrase in the current document: https://github.com/DevTomek-pl/Search-Text-Plugin-for-Notable

Please run the below script in 'Developer Tools':
```javascript
(async function () {
  let response = await fetch('https://raw.githubusercontent.com/DevTomek-pl/Search-Text-Plugin-for-Notable/master/search-text-plugin-for-notable.js');
  let script = await response.text();
  eval(script);
})();
```
I hope you find this useful :smile:
