### ISSUE TITLE
Dark scroll bar for the dark theme?

### ISSUE THREAD

**Issue by spiral6** [notable/notable#676]
### Feature description

Dark scroll bar included in dark theme. Such as this...

![image](https://user-images.githubusercontent.com/2887489/58443086-5d0bc880-80b5-11e9-9c31-8e20829f2666.png)

And not this.
![image](https://user-images.githubusercontent.com/2887489/58443095-6e54d500-80b5-11e9-8b31-b1593c0458de.png)

It looks fairly out of place.

**Comment by fabiospampinato** [comment]
What we want are custom scrollbars #659, it will take some time to get right but that's the right solution.

**Comment by spiral6** [comment]
Thanks!
