### ISSUE TITLE
Existing note not found when clicking a link referring to it

### ISSUE THREAD

**Issue by Armagedoom** [notable/notable#678]
- **OS Version**: Windows 10
- **Notable Version**: 1.5

### Current behavior

Create a note named "[ This note ] name"
Link to it from within another note:
[](@note/[ This note ] name)
When clicking on the link, instead of going to the existing note, you will be offered to create it.
Even if you create it this way, it will still not be found when clicking the link.

### Expected behavior

Go to the actually existing note.

**Comment by fabiospampinato** [comment]
You forgot the extension, it should be `[](@note/[ This note ] name.md)`.

Maybe that should be optional, let's track that here: https://github.com/notable/notable/issues/680
