### ISSUE TITLE
Why does Vscode and other markdown editors like typora don't display markdown math inside an html table while notable can do this? and how can I achieve this on vscode?

### ISSUE THREAD

**Issue by LisztFranz** [notable/notable#681]
I like how notable can allow you to use some markdown inside html tables (I tried it with math equations and code snippets). The editor of notable is fine but i'm more comfortable using vscode to edit md files. The problem is that vscode doesn't display math equations and code inside html tables. How can I fix this?

**Comment by fabiospampinato** [comment]
You'd have to find a vscode extension for rendering latex inside markdown.

**Comment by LisztFranz** [comment]
I'm already using one but it can't display math inside html tags like this:

<table>
<th>
TEST
</th>
<th>
TEST
</th>
<tbody>
<tr>
<td>test</td>
<td>$\frac{5}{4}=\alpha+\beta^2$</td>
</tr>
<tr>
<td>
This is interesting
```javascript
let arr1=[1,2,3];
```

</td>
</tr>
</tbody>
</table>

this works perfectly fine in notable but not in vscode

**Comment by LisztFranz** [comment]
Would you know one by any chance? All the ones I tried don't seem to support this

**Comment by fabiospampinato** [comment]
Unfortunately I don't, I don't really write latex in my notes. You might want to ask that question in our subreddit: https://www.reddit.com/r/notable
