### ISSUE TITLE
Toggling Zen-mode enters data

### ISSUE THREAD

**Issue by awrog** [notable/notable#682]
Win 10 latest
Notable 1.5.1

Toggling Zen-mode adds (unwanted) text.

![error-zen-mode](https://user-images.githubusercontent.com/12153667/59012956-29f5d180-8839-11e9-9dda-e1e1fca8c8c9.gif)

**Comment by fabiospampinato** [comment]
🤔that's weird, can you post here the note with the added characters?

**Comment by awrog** [comment]
Hi Fabio it happens al the time
I created a new page and switched to ZEN-mode
```
---
title: No Title
tags: [Notebooks/Tutorial]
created: '2019-06-11T11:25:47.008Z'
modified: '2019-06-11T11:26:01.045Z'
---

# No Title

ææææææ
```
![special-character](https://user-images.githubusercontent.com/12153667/59268476-0bcf0d80-8c4d-11e9-8130-d95ab270358d.gif)

**Comment by fabiospampinato** [comment]
Strange 🤔 can you try that shortcut in another text editor? Perhaps your OS is inserting that character 🤔

**Comment by awrog** [comment]
You nailed it, it must be one of the other programs....
