### ISSUE TITLE
Keyboard shortcuts change depending on editor/preview mode

### ISSUE THREAD

**Issue by jsosulski** [notable/notable#683]
- **OS Version**: Ubuntu 18.04
- **Notable Version**: 1.5.1

### Current behavior

In preview mode, Ctrl+Backspace is used to delete notes. In Edit/Split mode, Ctrl+Alt+Backspace is used.

### Expected behavior

Shortcuts stay the same, i.e. maybe Ctrl+Alt+Backspace for both?

**Comment by fabiospampinato** [comment]
Duplicate of #532
