### ISSUE TITLE
Note title slightly different from heading

### ISSUE THREAD

**Issue by CavalloneChen** [notable/notable#685]
- **OS Version**:
Mac os 10.14.5
- **Notable Version**:
1.5.1
### Current behavior
<img width="768" alt="image" src="https://user-images.githubusercontent.com/28266566/59142135-bba54080-89eb-11e9-9966-e1932ac97163.png">

### Expected behavior
The note title in the list should render properly.

**Comment by fabiospampinato** [comment]
The first two asterisks are improperly being recognized as Markdown formatting for italic, and therefor removed.

**Comment by fabiospampinato** [comment]
Fixed in v1.6, you might need to update that note manually in order to get it's title refreshed though.
