### ISSUE TITLE
Something wrong with numbering

### ISSUE THREAD

**Issue by InfiniteFor** [notable/notable#690]
- OS Version: Windows 10
- Notable Version: 1.5.1

It looks like there is something wrong with the numbering in preview mode in combination with lists. Left is editing mode, right is preview. 
![numbering](https://user-images.githubusercontent.com/23584363/59361306-eec03a80-8d31-11e9-95b5-65e2e95f2764.png)
Btw really love notable, using it everyday. Keep up the good work 👍!

**Comment by fabiospampinato** [comment]
That seems a bit of an edge case example, what should that markdown render to anyway? Maybe like in Notable but with the list numbers incremented?

> Btw really love notable, using it everyday. Keep up the good work 👍!

Thanks, I'm happy people like it :)

**Comment by InfiniteFor** [comment]
Well I would expect a 5 where I entered a 5 and a 6 where I entered a 6, etc. 
This is how VS Code rendered the exact same file.
![numbering_vscode](https://user-images.githubusercontent.com/23584363/59454927-6ade7f00-8e13-11e9-9e65-4f95cbad765b.png)

**Comment by fabiospampinato** [comment]
Fixed in v1.6.
