### ISSUE TITLE
Use ESLint

### ISSUE THREAD

**Issue by fabiospampinato** [notable/notable#691]
### Feature description

ESLint should be used extensively.

### Feature motivation

There are many helpful plugins that can help catch real bugs.

Links for future reference:

- https://eslint.org/docs/rules
- https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin
- https://github.com/yannickcr/eslint-plugin-react
- https://github.com/wix/eslint-plugin-lodash
- https://github.com/mysticatea/eslint-plugin-node
- https://github.com/sindresorhus/eslint-plugin-unicorn
- https://github.com/jhusain/eslint-plugin-immutable

**Comment by Shagon94** [comment]
Using eslint alongside a CI can help contributors stick to a specific typing style. AirBNB is one popular stlye guide for javascript.

**Comment by DallasO** [comment]
Don't forget about 
* [prettier](https://www.npmjs.com/package/prettier)
* [eslint-plugin-prettier](https://www.npmjs.com/package/eslint-plugin-prettier)
* [eslint-config-prettier](https://www.npmjs.com/package/eslint-config-prettier)

I would also install [husky](https://www.npmjs.com/package/husky) and [lint-staged](https://www.npmjs.com/package/lint-staged).

husky config:
* pre-commit 
    * lint-staged - automatic styling
* pre-push  
    * if you want to do a check before pushing


I might have time to do this, if you'd like.

**Comment by fabiospampinato** [comment]
@DallasO Thanks for the suggestions, but I think being the one writing the code I should be the one configuring these kinds of tools.

**Comment by fabiospampinato** [comment]
Done.
