### ISSUE TITLE
Use correct path for binary in DEB package

### ISSUE THREAD

**Issue by Toothless204** [notable/notable#698]
### Feature description
Place binary in /usr/bin rather than /usr/local/bin

### Feature motivation
In Debian, software installed from a package is meant to go in /usr. /usr/local is typically only used for software that was not installed from a package, eg. the user compiled it from source

**Comment by fabiospampinato** [comment]
We are using [`electron-builder`](https://github.com/electron-userland/electron-builder) for generating the `.deb`, you should probably open an issue about this there (I couldn't find an existing one already, but GitHub's search isn't the best).

**Comment by Toothless204** [comment]
Fix has been merged into electron-builder and will no longer be a problem as of version 21
