### ISSUE TITLE
Can't select default data directory after reinstalling Notable

### ISSUE THREAD

**Issue by bitbacchus** [notable/notable#705]
- **OS Version**: Ubuntu 18.04
- **Notable Version**: 1.5.1

### Current behavior

1. Install Notable (notable_1.5.1_amd64.deb)
2. Uninstall Notable, purge and delete `~/.notable` folder
3. Install Notable again
4. Open app & click on "Use Default"
5. "This is already the current data directory"

### Expected behavior

Notable should create or open the default data directory

### Screen shot

![Screenshot from 2019-06-25 14-05-53](https://user-images.githubusercontent.com/19432439/60097568-f0d3c180-9753-11e9-98b6-5bebe0c59f76.png)

**Comment by fabiospampinato** [comment]
In the meantime I think recreating the `~/.notable` folder manually may fix this.

**Comment by bitbacchus** [comment]
> In the meantime I think recreating the `~/.notable` folder manually may fix this.

Yes, it does indeed, thank you!

**Comment by fabiospampinato** [comment]
I think I just fixed this, the fix will be available in the next release.
