### ISSUE TITLE
Zoom menu items not working

### ISSUE THREAD

**Issue by genericmoniker** [notable/notable#706]
- **OS Version**: Windows 10 Pro
- **Notable Version**: 1.5.1

### Current behavior

No effect when choosing any of the Zoom items from the View menu:
* Actual Size
* Zoom In
* Zoom Out

If the main part of the UI has input focus, then the shortcut keys for the equivalent menu commands work as expected, but if the menu bar has focus, the shortcut keys also don't work. 

### Expected behavior
UI scaling by menu.

**Comment by fabiospampinato** [comment]
It sounds like a bug with Electron, I use those menu items right from the menu bar under macOS, I'll see if I can reproduce it under Win10.

**Comment by TeChn4K** [comment]
Same under Linux Xubuntu with Snap package.
But zoom works good with AppImage package.

**Comment by fabiospampinato** [comment]
This is most probably an issue with Electron unfortunately.

**Comment by afonsomatos** [comment]
I have Windows 10, and those items don't work at all.

**Comment by fabiospampinato** [comment]
@genericmoniker can you still reproduce in v1.8.2? We updated Electron quite a few times since your first report.

**Comment by genericmoniker** [comment]
It seems to be working as expected now, running 1.8.2. Thanks.
