### ISSUE TITLE
A shortcut to create links

### ISSUE THREAD

**Issue by francescomucio** [notable/notable#707]
### Feature description
Add the [Github shortcuts for text formatting](https://help.github.com/en/articles/using-keyboard-shortcuts#comments).

### Feature motivation
Having some additional shortcuts will make writing notes faster.

I got used to ctrl+k to create links or ctrl+b for bold text.

**Comment by fabiospampinato** [comment]
Duplicate of https://github.com/notable/notable/issues/153.
