### ISSUE TITLE
Custom file directory structure

### ISSUE THREAD

**Issue by danielyzli** [notable/notable#712]
### Feature description

I'm wondering whether a custom way of organizing the directory would be possible in some sort of settings? 

### Feature motivation

Right now the directory structure tosses all the notes together and attachments together, differentiating notes by the tag in the header. I am using notable for multiple projects / classes so I would prefer if notes were put in a folder hierarchy similar to the notebook hierarchy, and if attachments were grouped with the notes they are affiliated with. This might not work for everybody. For instance, I usually won't attach the same attachments to two different notes, but for someone that does that, this way of organizing wouldn't make sense since you would use up more space having duplicate items. Thus I think it would be nice to have a customize-able set of directory rules so that everyone can have a file structure that satisfies their organizational needs.

There is already some stuff vaguely similar to this in #230, #54, #218, etc.

**Comment by fabiospampinato** [comment]
Let's keep the discussion about the structure of the data directory in #54.

IMHO this particular suggestion is probably never going to get implemented for the following reasons:

- Once Notable is available everywhere it will pretty much always be better to search for notes/attachments via the provided apps.
- If you want to leave Notable and have your data directory structured in a different way you're already free to do that, people can even share the scripts they are using to do that.
- The vast majority of users don't even care about having their notes editable via third-party tools (=> the most popular app in the space is Evernote which doesn't offer this feature), and those who do have different ideas of how this should work, I can't spend considerable amount of time implementing X different implementations to satisfy a minority, and it may not even be possible to support contrasting implementations at the same time.

That being said ~soon I'll have to rewrite the back-end, maybe if I implement it in a general enough way third-parties could provide special plugins for structuring the data directory differently, I doubt this is going to happen but I can't say for sure at this point in time.
