### ISSUE TITLE
Support inline meta tags

### ISSUE THREAD

**Issue by Brixy** [notable/notable#714]
*This is a great piece of software, and it is excellent that notes use internal front matter (instead of external JSON files) to store meta data. The simple folder structure makes notes portable to other software. **Thank you for this!***

For a long time I have been using ‘inline meta tags‘ (`#` + text without spaces) as now supported by iA Writer:

```markdown
Paragraph

#MetaTag

Paragraph
```

It would be a great benefit it Notable supported these to make markdown files even more cross-editor capable.

Meta tags within front matter do have advantages (nesting, support of white spaces …). So the support of inline meta tags should be optional/additional.

The most simple setup: Use tags as before + recognize inline tags.

**Comment by fabiospampinato** [comment]
At the end of the day we have to make some choices, I don't think it makes sense to us to implement the same feature in multiple ways.

IMHO between the two options front matter metadata makes more sense to me, iA Writer's "inline metadata" just looks like broken headings to me.

Maybe in future some plugins #128 could implement something like this though.

**Comment by Brixy** [comment]
Thank you. A plugin solution would be perfect.

`#TagName` might look strange (it could be styled for the editor and preview), but semantically it does not interfere with [ATX headings](https://spec.commonmark.org/0.29/#atx-headings):

> The opening sequence of # characters must be followed by a space or by the end of line.
