### ISSUE TITLE
Tag and sub tag

### ISSUE THREAD

**Issue by kampiamodikuesto** [notable/notable#716]
i'm using note app from osx desktopo environment and i'd like to create folder and subfolder for note. i think that a great features are:

- make possible to create sub tag (as the folders for note osx app)
- create folders and sub folders for note that will be in synch with real osx folder with all single note as i remember a Zim app doing.

**Comment by fabiospampinato** [comment]
I think what you're asking for has been discussed at length here: #54. The TL;DR is that I don't think is going to happen, but if it does it's gonna take a while.
