### ISSUE TITLE
Notable breaks when files in notes folder has no 'meta'-tags

### ISSUE THREAD

**Issue by adamsen9** [notable/notable#720]
- **OS Version**: Windows 10
- **Notable Version**: 1.6

### Current behavior

When a single file without any of the meta tags title, created etc. is in the notes folder, Notable will not be able to read any of the other .md files and will not be able to change data directory.

I tried removing all tags from the '---' part of the .md files and it breaks when there are no tags remaining at all. 

### Expected behavior

It should be able to open files without the associated meta-tags.

**Comment by fabiospampinato** [comment]
It looks like I probably forgot to handle this case, fix coming in v1.6.1 today.

**Comment by ymjonline** [comment]
I haven't investigated into the root cause, but I can only concur, 1.6.0 is broken under (my) Windows 10

--> it does not load the default folder
--> cannot open or change data directory, it does nothing
--> Theme does not change
--> Check for updates does not do anything
--> Exit does not respond either

Most of the menu items are not responsive. The app needs to be killed manually :-/

**Comment by fabiospampinato** [comment]
I'm building v1.6.1 right now. I think this issue was caused by this upstream issue: https://github.com/nodeca/js-yaml/issues/507

**Comment by fabiospampinato** [comment]
Just released v1.6.1: https://github.com/notable/notable/releases/tag/v1.6.1

You'll probably have to reinstall it manually.

Did it fix the issue for you guys?

**Comment by energetic-it** [comment]
That worked for me. Thanks for the quick fix

**Comment by ymjonline** [comment]
> Just released v1.6.1: https://github.com/notable/notable/releases/tag/v1.6.1
> 
> You'll probably have to reinstall it manually.
> 
> Does it fix the issue for you guys?

thanks a lot !
still a couple issues though --> https://github.com/notable/notable/issues/724#issuecomment-509662018

**Comment by fabiospampinato** [comment]
Great, thanks you guys for the prompt issue report.
