### ISSUE TITLE
libgnome-keyring0 no longer available on Debian Buster (nor testing)

### ISSUE THREAD

**Issue by dvergeylen** [notable/notable#725]
- **OS Version**: Debian stable (Buster)
- **Notable Version**: 1.6.1

As stated by the Debian team: [libgnome-keyring0 is deprecated](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892359) in favor of [libsecret](https://wiki.gnome.org/Projects/Libsecret).

As a result, Notable won't install on Debian Buster (nor Bullseye) because libgnome0-keyring package [has been removed from Buster](https://tracker.debian.org/pkg/libgnome-keyring) :confused:

**Comment by fabiospampinato** [comment]
This is most probably an upstream issue with the library we are using for generating the deb: https://github.com/electron-userland/electron-builder/issues/4033

I see Buster has been only released 3 days ago, so probably that's also a reason why this hasn't been addressed yet.

Does the `snap` install properly?

**Comment by fabiospampinato** [comment]
It looks like the upstream issue has been fixed already! I'll rebuild the deb as `electron-builder` gets updated 👍

**Comment by fabiospampinato** [comment]
It doesn't look like `electron-builder`'s update did fix this, I think we'll have to wait some more.

**Comment by AsierRF** [comment]
There is a new version 21.0.14 released that mentions the correction with the deb packages.

![image](https://user-images.githubusercontent.com/17161846/60959695-f2cb8200-a308-11e9-8bb4-875849fdb569.png)

https://github.com/electron-userland/electron-builder/releases

**Comment by fabiospampinato** [comment]
I've tried v21.0.14 but that doesn't work for me either.

[Here](https://drive.google.com/file/d/11RK1c5We2c-hK8u5--zPj1hGWWJ_dAXZ/view?usp=sharing) there's the updated `.deb` if you'd like to try it out for yourselves.

**Comment by AsierRF** [comment]
The error is now another dependency called **gir1.2-gnomekeyring-1.0** that seems to be part of the *libgnome-keyring0* package. 

I followed the issue you created for electron-builder [here](https://github.com/electron-userland/electron-builder/releases)

I checked the solution pushed in electron-builder; they changed the **libgnome-keyring0** for the **libsecret**. However, the **gir1.2-gnomekeyring-1.0** is still part of the dependencies.

@fabiospampinato Should you comment this in the issue you created for electron-builder?

**Comment by fabiospampinato** [comment]
@AsierRF I don't know I think the screenshots I posted should provide enough information. 

Feel free to join the discussion there though if you have something to add, I'm not really a Debian expert myself.

**Comment by fabiospampinato** [comment]
I think they might have fixed this in Electron v7, update coming probably tomorrow.

**Comment by fabiospampinato** [comment]
This might have been fixed in v1.8, could somebody please check this?

**Comment by dvergeylen** [comment]
I tested and could sucesfully install this on Debian 11 Bullseye :+1:

**Comment by fabiospampinato** [comment]
Awesome, thank you!
