### ISSUE TITLE
Checkbox also shows bullets

### ISSUE THREAD

**Issue by zawnk** [notable/notable#726]
- **OS Version**: Win 10 pro x64
- **Notable Version**: 1.6.1

### Current behavior

I've just downloaded this app and looked up how to do checkboxes and I've found that this should work:

```
- [ ] check
- [x] check
- [x] check
- [x] check
- [x] check
```

### Expected behavior

When I enter above code, there is actually checkboxes, but there's also bullet points for the list. If i remove the `-` in front of the checkbox, the checkbox doesn't work anymore: 

Edit mode:
![image](https://user-images.githubusercontent.com/10813608/60902136-7042b400-a26f-11e9-838a-a4b914a5af8a.png)

Stopped editing:

![image](https://user-images.githubusercontent.com/10813608/60902192-851f4780-a26f-11e9-8c50-c5b19151a292.png)

The bullet points should not be displayed in front of the checkboxes.

**Comment by fabiospampinato** [comment]
> When I enter above code, there is actually checkboxes, but there's also bullet points for the list. 

I see this is not how they are being rendered in GitHub, so I'd consider this a bug.

> If i remove the - in front of the checkbox, the checkbox doesn't work anymore

That's expected.

**Comment by fabiospampinato** [comment]
Just fixed, it will be available in the next release.
