### ISSUE TITLE
KaTeX rendering in fenced code blocks

### ISSUE THREAD

**Issue by BobMilli** [notable/notable#727]
- **Windows 10**:
- **1.6.1**:

### Current behavior

Create a note with the following content : 
# Bug Code

```
Get-ChildItem Env: | %{[PSCustomObject]@{"$($_.Name)"="$($_.Value)"}} | ConvertTo-Json
```

And as soon a quit the edit mode I get 

Get-ChildItem Env: | %{[PSCustomObject]@{"<span class="katex"><span class="katex-mathml"><math><semantics><mrow><mo stretchy="false">(</mo></mrow><annotation encoding="application/x-tex">(</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1em;vertical-align:-0.25em;"></span><span class="mopen">(</span></span></span></span>_.Name)"="<span class="katex"><span class="katex-mathml"><math><semantics><mrow><mo stretchy="false">(</mo></mrow><annotation encoding="application/x-tex">(</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1em;vertical-align:-0.25em;"></span><span class="mopen">(</span></span></span></span>_.Value)"}} | ConvertTo-Json

### Expected behavior

Normal block code behaviour

[Bug Code.txt](https://github.com/notable/notable/files/3373904/Bug.Code.txt)

**Comment by BobMilli** [comment]
![Notable_Bug_Code](https://user-images.githubusercontent.com/6640839/60905434-61f79680-a275-11e9-9bcf-ffd18891b00e.jpg)

**Comment by fabiospampinato** [comment]
That's weird, I get the following instead 🤔: 

<img width="830" alt="Screen Shot 2019-07-09 at 18 14 02" src="https://user-images.githubusercontent.com/1812093/60905432-60c66980-a275-11e9-834d-648c74b31485.png">

**Comment by fabiospampinato** [comment]
I can't reproduce this, perhaps it is related to https://github.com/notable/notable/issues/748 which I can't also reproduce with the note provided by the issue's author. 

@BobMilli Can you see the following code block, fenced with triple backticks, rendered correctly?

```
<?php
$a = array("foo" => 0, "bar" => 1);
foreach ($a as $key => $value) {
  // comment
  echo "{$key} => {$value}" . PHP_EOL;
}
```

**Comment by BobMilli** [comment]
@fabiospampinato 
Here is the result :
![image](https://user-images.githubusercontent.com/6640839/61848767-811a3900-aeaf-11e9-96b6-8976f33bae36.png)

It seems you found what was wrong !
Bob

**Comment by fabiospampinato** [comment]
Yes but I'm currently unable to reproduce this, I've no idea why :/

**Comment by fabiospampinato** [comment]
Wait I can totally reproduce this now, this is another issue related to Windows' weird `\r\n` newlines, previously I couldn't reproduce this because I was copy-pasting the provided snippet rather than loading it from disk, so those new lines were replaced by `\n`.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
