### ISSUE TITLE
What version is committed?

### ISSUE THREAD

**Issue by seanodell** [notable/notable#730]
Great project; thanks for doing this. I am wondering if some code needs to be committed? I see the 1.5.1 release was May 17, and then no commits until July 8. The current release is 1.6.2, but package.json still says 1.5.1. It looks like there are a LOT of great improvements from 1.6.0 through 1.6.2, but I don't see commits that line up with that.

**Comment by fabiospampinato** [comment]
The version available on the repo is mostly v1.5.1 with a few commits what eventually made it into v1.6. Read more about this [here](https://github.com/notable/notable/issues/432) and [here](https://www.reddit.com/r/Notable/comments/bu86e8/update_on_v160/), I'll make sure this is mentioned in the readme.

**Comment by croogie** [comment]
Can we again open it due to the fact that in `package.json` file there is still info about `1.5.1` and in changelog you've mentioned `1.7.2`? 
The value should be updated accordingly.

**Comment by fabiospampinato** [comment]
@croogie I think some people expect to find the full changelog here, so I think it'd be best to keep it updated.
