### ISSUE TITLE
Pressing ESC during multi-cursor editing should not exit edit mode

### ISSUE THREAD

**Issue by jclark-dot-org** [notable/notable#735]
- **OS Version**:
MacOS 10.14.5
- **Notable Version**:
1.6.2
### Current behavior

When using multi-cursor editing, pressing ESC (to return to a single cursor) ends edit mode.
To Reproduce:

Edit any note with multiple lines.  Enter multi-cursor mode by using  &#8984;+&#8997;+DnArrow.  Press escape to exit multi-cursor mode.  Notable exits edit mode entirely, rendering the Markdown doc as HTML (view mode).

### Expected behavior

When multi-cursor mode is active, pressing escape should remove all cursors save one.  Pressing escape a second time would then exit edit mode.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
