### ISSUE TITLE
Incorrect title when title contains a date

### ISSUE THREAD

**Issue by PJakober** [notable/notable#741]
### Prerequisites
Create a new file and put 
> \# 15.07.2019  

as first line

### Expected behavior
The inferred title should update to **15.07.2019**

### Current behavior
The inferred title updates to **2019**

### Notes
* Tested with v1.62
* Existing files are not affected when viewing them (the inferred title matches the first line of the file)
* When editing existing files, the behavior is the same as for new files

**Comment by fabiospampinato** [comment]
Interesting, I'm not sure why that doesn't work properly, I'll take a closer look at this 👍

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
