### ISSUE TITLE
Notable opens the web browser to check for updates when offline or on network change

### ISSUE THREAD

**Issue by tdemin** [notable/notable#742]
- **OS Version**: Windows 10 1903 x86_64, build 18362
- **Notable Version**: 1.6.2

### Current behavior

When I get offline and start Notable, Notable opens the default web browser pointing to the release page (which, needless to say, shows nothing since I'm offline), having failed to self-update or at least check for updates.

This also happens on resume after suspend, just with a different error: `ERR_NETWORK_CHANGE`.

### Expected behavior

Notable should check whether the Internet connection is available at all to prevent opening the web browser while offline.

### Additional notes

May or may not be possibly related to me using a local DNS resolution daemon.

**Comment by fabiospampinato** [comment]
Nice catch, we should be smarter about this and detect when offline automatically.

**Comment by fabiospampinato** [comment]
I just implemented this, wait for the next release to try it out.
