### ISSUE TITLE
Desktop icon on Ubuntu disappears after AppImage auto-update

### ISSUE THREAD

**Issue by cemeroncel** [notable/notable#743]
- **OS Version**: Ubuntu 19.04
- **Notable Version**: 1.6.2

### Current behavior

The desktop icons created via running the AppImage first time through the terminal disappeared after auto-updating to version 1.6.2 (the version I installed initially was 1.5.1). After investigating the .desktop file under `~/.local/share/applications`, I realized that the version numbers are still pointing to the old version (1.5.1 in my case). I tried to modify the version numbers in the file but it didn't work. I deleted the .desktop file hoping that running the new version from the terminal will recreate them but it didn't either.

### Expected behavior

Auto-updater should also take care of the .desktop file.

**Comment by fabiospampinato** [comment]
I think there was an upstream change in `electron-builder` where desktop integration for `AppImage`s has been removed entirely in favor of `AppImageLauncher`, read more about this [here](https://github.com/electron-userland/electron-builder/releases/tag/v21.0.1).

//cc @develar, as think this is actually working as expected right?

**Comment by cemeroncel** [comment]
Thank you for the clarification. I tried the `AppImageLauncher` and looks like it is working correctly.
