### ISSUE TITLE
KaTex is trying to render non-KaTeX expressions (&)

### ISSUE THREAD

**Issue by ColinNg** [notable/notable#745]
The issue is similar to [#199](https://github.com/notable/notable/issues/199) but for `&` instead of `~`. 

- **OS Version**: Windows 10 Pro
- **Notable Version**:1.6.2

### Current behavior

Put a URL with `&` in a document
```
https://example.com/query?test=1&why=2&not=3

[Testing a URL with & symbol](https://example.com/query?test=1&why=2&not=3)
```

The URL stops after `1` and then KaTeX takes over and messes up the URL and its rendering. 

### Expected behavior

The URL should render correctly.

**Comment by fabiospampinato** [comment]
Duplicate of https://github.com/notable/notable/issues/588.

This is especially an issue for embedded urls.
