### ISSUE TITLE
Checkboxes not showing

### ISSUE THREAD

**Issue by richardreeze** [notable/notable#750]
- **OS Version**: 10.14.5
- **Notable Version**: 1.6.2

### Current behavior
Checkboxes not showing even though I'm writing with proper syntax.
It's currently appearing as:
[ ] for unchecked
[X] for checked.

### Expected behavior
Should appear as 
- [ ] for uncheked.
- [x] for checked.

**Comment by fabiospampinato** [comment]
Can you post some actual markdown that I copy-paste into the app to reproduce the issue?

**Comment by richardreeze** [comment]
This is actual markdown I am using:

- [x] [How to Invent the Future I - Alan Kay](https://youtu.be/id1WShzzMCQ)

- [x] [How to Invent the Future II - Alan Kay](https://youtu.be/1e8VZlPBx_0)

**Comment by fabiospampinato** [comment]
Thanks, now I can reproduce the issue 👍

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
