### ISSUE TITLE
[Feature Request] paste clipboard image and Table of contents of markdown

### ISSUE THREAD

**Issue by utotch** [notable/notable#753]
Thank you very much for developing a nice editor.

I'm a Typora and Boostnote user and tried to change the editor to notable.
I found notable has some nice features but also I found it is insufficient for my usage.
I would like to request some features and share my impression of the editor. 

### Feature description
1. paste clipboard image (directly)
2. continuity camera for Mac
3. Table of contents of the markdown 

### Feature motivation
1.  usability of editing image
2. usability of editing real note capture
3. usability of editing large markdown

## comparison between Typora and Boostnote
|                                | Typora                                       | Notable            | Boostnote          | comment                            |
| ------------------------------ | -------------------------------------------- | ------------------ | ------------------ | ---------------------------------- |
| math (LaTeX)                   | :white_check_mark:                           | :white_check_mark: | :white_check_mark: |                                    |
| save as markdown file          | :white_check_mark:                           | :white_check_mark: | $\times$ (cson)    |                                    |
| paste clipboard image          | :white_check_mark:                           | $\times$           | :white_check_mark: |                                    |
| table of contens of a markdown | :white_check_mark:                           | $\times$           | $\times$           |                                    |
| continuity camera on Mac       | :white_check_mark:                           | $\times$           | $\times$           | useful for paste real note capture |
| usability of note management   | $\times$ (folder, file name input necessary) | :white_check_mark: | :white_check_mark: |                                    |
| huge flowchart on mermaid      | $\times$                                     | $\times$           | $\times$           | can't zoom                         |
| usability of table edit        | :white_check_mark:                           | $\times$           | $\times$           |                                    |
| usability of search            | $\times$                                     | :white_check_mark: | $\times$           |                                    |

**Comment by fabiospampinato** [comment]
> paste clipboard image (directly)

Let's track this here #26, this will be implemented in v1.7.

> Table of contents of the markdown

Let's track this here #530, as it seems a pretty popular request I'm probably going to implement it sooner rather than later.

> continuity camera for Mac

I don't know what this means, do you want to attach images taken from your iPhone or something?

**Comment by utotch** [comment]
Thank you very much for the quick response.

> > continuity camera for Mac
> 
> I don't know what this means, do you want to attach images taken from your iPhone or something?

Right.
I often take a photo of my real note by using iPhone and insert it to markdown file on Mac.

Continuity Camera
https://support.apple.com/en-us/HT209037

This function is very useful to make a note quickly with mixing typing and pen-based writing.

**Comment by fabiospampinato** [comment]
Got it, let's track that in this more specific issue: https://github.com/notable/notable/issues/754
