### ISSUE TITLE
Error Message after opening

### ISSUE THREAD

**Issue by eMerzh** [notable/notable#758]
- **OS Version**: OSX mojave
- **Notable Version**: 1.6.2

### Current behavior
Install app via dmg, 
open it,
got an error popup saying: 

```
Uncaught Exception:
TypeError: t.win.close is not a function
    at app_App.load (/Applications/Notable.app/Contents/Resources/app.asar/main.js:21:25338)
    at App.__ready (/Applications/Notable.app/Contents/Resources/app.asar/main.js:21:23287)
    at App.emit (events.js:199:15)
```

### Expected behavior

no error messages

**Comment by fabiospampinato** [comment]
Can you reproduce this every time you open the app?

**Comment by eMerzh** [comment]
hum no, seems to happen only the first time... not a biiiiig deal at all... but still might be fixed ;-)

**Comment by fabiospampinato** [comment]
Of course, I'll see if I can reproduce it.

Thanks for reporting the error!

**Comment by fabiospampinato** [comment]
I think I just fixed this, but I couldn't reproduce it in the first place, so please do let me know if you can still reproduce it in the upcoming v1.7.
