### ISSUE TITLE
Translucent setting isn't saved

### ISSUE THREAD

**Issue by Tjaaaaaf** [notable/notable#760]
- **Windows 10 home**:
- **Notable Version 1.6.2**:

### Current behavior

1. Make Notable translucent
2. Restart Notable
3. The translucent setting is not carried over.

### Expected behavior

I would expect that when you make Notable translucent it would save the setting so that the next time you open up it is also translucent.

**Comment by fabiospampinato** [comment]
I've added a task about this here: https://github.com/notable/notable/issues/339, let's track this there.
