### ISSUE TITLE
Bring back support for HTML entities (&dollar;)

### ISSUE THREAD

**Issue by thansk** [notable/notable#765]
### Feature description

In at least one of the previous versions of the app I was able to use HTML entities like `&dollar;`, `&euro;`, etc. And now it's missing and all my notes show just show (for example) `dollar` in cursive

### Feature motivation

I believe it is a useful feature where emoji's aren't enough and you can't search for the symbol anywhere.

**Comment by fabiospampinato** [comment]
Sounds useful, and GitHub already renders them, thanks for the suggestion.

**Comment by fabiospampinato** [comment]
@thansk I'm unable to reproduce this, can you post a note here that reproduces the issue for you?

**Comment by thansk** [comment]
@fabiospampinato 
```
# Title
 - &dollar;50 (&dollar;15 shipping) - item 1
 - &dollar;70 (&dollar;15 shipping) - item 2
```

In the previous release second-level unordered items were working, 1st and 3rd were not. In the last release 3rd-level unordered items are fixed, but 1st-level are still not working.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
