### ISSUE TITLE
Feature Request: Find and replace?

### ISSUE THREAD

**Issue by alonchis** [notable/notable#766]
would like a find and replace feature. for example, I had a note from Bear where a strikethrough is done with -{{word}}-, but in markdown is \~\~{{word}\~\~. I'd like to be able to find/replace all instances of '-' with '~~'.

**Comment by fabiospampinato** [comment]
Yeah that's one of the big missing features, let's track this here: #140

Right now you'll have to open your note (or entire data directory if you wish) in an editor like VSCode to do that.
