### ISSUE TITLE
Three GET params in URLs breaks HTML links

### ISSUE THREAD

**Issue by renanwillian** [notable/notable#769]
- **OS Version**: Linux Ubuntu 19.04
- **Notable Version**: 1.6.2

### Current behavior
In a note, add a URL which includes two '&'

`https://test.com?a=1&b=2&c=3`

![image](https://user-images.githubusercontent.com/30376796/62622125-0102c300-b8f4-11e9-8898-7ce2ceb0d83a.png)

### Expected behavior
It should return a link with the URL but instead returns a broken link.

**Comment by fabiospampinato** [comment]
I've fixed already for regular URLs, but not for autolinked URLs it looks like, thanks for reporting the issue!

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
