### ISSUE TITLE
Network_IO_Suspended

### ISSUE THREAD

**Issue by R083RT2** [notable/notable#770]
Every time I wake up my computer in the morning I see this.  I went to File > Check for updates and it says it's the latest version.  I'm on version 1.6.2

![2019-08-08_13-19-14](https://user-images.githubusercontent.com/9652593/62735031-21f41280-b9df-11e9-9db8-ca4da8654d8e.png)

**Comment by fabiospampinato** [comment]
It looks like your computer is still running at night, but with no connection available, so the app checks for updates but can't connect to the internet.

In the upcoming v1.7 if the app detects no internet connection it won't check for updates anymore, so you shouldn't stop seeing this issue. Let me know in case v1.7 doesn't solve the issue for you.

I see another 2 issues here though:

1. In the screenshot it looks liek the app checked for updates 3 times, and it is set to check for updates every 8 hours, so did you live your desktop running for 24h straight?

2. I see once the "An error occurred" notification got displayed after the "Update manually" notification, I'm not sure how that can happen 🤔

**Comment by LukaszGrela** [comment]
I have similar setup, overnight I have only single set of error toasts:
![image](https://user-images.githubusercontent.com/7643591/62757050-d8a0d300-ba71-11e9-897e-1c57f9f020f7.png)
but still it is bit annoying, also it seems to open the Notable github page.

**Comment by fabiospampinato** [comment]
This should be resolved now:

- Those sorts of toasts aren't displayed anymore multiple times simultaneously automatically.
- The app checks if it has access to the internet before attempting to look for updates.
