### ISSUE TITLE
Snap: permission denied when changing data directory

### ISSUE THREAD

**Issue by kinghat** [notable/notable#771]
- **OS Version**: KDE Neon 
- **Notable Version**: 1.7.0

### Current behavior
on a fresh manual install of the snap via `sudo snap install --dangerous notable_1.7.0_amd64.snap` when you are asked to give the data dir i get:

![image](https://user-images.githubusercontent.com/16073360/62799908-a14d1900-baa7-11e9-8b5a-1c05866a38c9.png)

when trying to select anything other than the OS drive. non of my other attached drives work.

### Expected behavior
should be able to select any dir.

**Comment by fabiospampinato** [comment]
I don't think this error arises from anything we have control over. Can you check if v1.6.2 doesn't have this error?

**Comment by k1nghat** [comment]
> I don't think this error arises from anything we have control over. Can you check if v1.6.2 doesn't have this error?

i was using v1.6.2 as an appimage and it was fine. though i use vscode as a snap and i can access directories just fine. not sure if it has something to do with not coming from the snap store and being installed manually or not. :man_shrugging:

**Comment by fabiospampinato** [comment]
No idea really 🤔 could you please check if the appimage for v1.7 works for you?

**Comment by k1nghat** [comment]
> No idea really thinking could you please check if the appimage for v1.7 works for you?

sorry for the delayed response. the appimage works fine for me. seems to be snap only.

**Comment by fabiospampinato** [comment]
I have an idea on what might fix this, this might be an issue with Electron's sandbox system 🤔

**Comment by fabiospampinato** [comment]
The idea I had didn't fix it, I've opened an [upstream issue](https://github.com/electron-userland/electron-builder/issues/4150) about this, as this sounds like an upstream bug to me.

**Comment by fabiospampinato** [comment]
I think this issue is now fixed with the new snap which uses the "classic" confinement rather than the "strict" one.
