### ISSUE TITLE
Toggle multiple checkboxes simultaneously

### ISSUE THREAD

**Issue by kitschmensch** [notable/notable#781]
### 1. Apply checkbox syntax to every line in a selection
Currently in the editor, if I select a group of lines and press ALT-Enter, only the first line is given a checkbox
![image](https://user-images.githubusercontent.com/46611895/63103267-fe2e5080-bf39-11e9-833a-e8dfc8fd6313.png)

It would be awesome if I could select a group of lines and apply a checkbox to all of them simultaneously. 
![image](https://user-images.githubusercontent.com/46611895/63103380-3c2b7480-bf3a-11e9-8197-f1ebdf8e1636.png)

Respect for tabs would be a bonus. 

Before:
![image](https://user-images.githubusercontent.com/46611895/63103875-29fe0600-bf3b-11e9-96d3-7c87f34e36c6.png)
After:
![image](https://user-images.githubusercontent.com/46611895/63103904-371af500-bf3b-11e9-8f1d-2bcad4a6f051.png)

### 2. Apply 'marked' syntax to every checkbox in a selection

Similar behavior show up when using ALT-D to mark tasks complete. If a group of checkboxes is selected and I press ALT-D, only the first line is marked
![image](https://user-images.githubusercontent.com/46611895/63104322-04bdc780-bf3c-11e9-8c42-2be0c557763f.png)
Just like before, I would expect all lines to be marked complete: 
![image](https://user-images.githubusercontent.com/46611895/63104376-2159ff80-bf3c-11e9-9112-5bc3bd258ae8.png)

### Feature motivation

1. Making to-do lists would be _extremely_ fast and easy. It would eliminate the need to press the shortcut at the end of every line.
2. The described behavior is consistent with standard word processing behavior. In many applications (including the GitHub editor!), users can select a body of text and apply a bullet point to every line separated by a line feed.

**Comment by fabiospampinato** [comment]
Makes sense, I actually implemented this already in my vscode [extension](https://github.com/fabiospampinato/vscode-todo-plus) for managing tasks, probably I can get backport part of the code from there.

**Comment by fabiospampinato** [comment]
This is already supported via multi-cursors, not yet supported via multi-line selections.

**Comment by teleksterling** [comment]
Close issue?
This works great on multiline selections in Version 1.9.0-beta.10

**Comment by fabiospampinato** [comment]
It should be supported via multi-line selections also.

**Comment by teleksterling** [comment]
Hmm! On my PC, it seems to work perfectly for both multi-line and multi-cursor selections (both Alt+Enter and Alt+D).

Version 1.9.0-beta.10 running on Windows 11.

**Comment by fabiospampinato** [comment]
Oh you are right, I guess I had implemented that at some point and forgot about it 😅
