### ISSUE TITLE
Feature for batch removing metadata 

### ISSUE THREAD

**Issue by stemcc** [notable/notable#782]
### Feature description

The ability to remove Notable metadata from Notable files in order to have the option for "clean" markdown files. Right now, even exported markdown files still include all Notable metadata. 

### Feature motivation

For easier integration of Notable notes with non-Notable applications.

**Comment by fabiospampinato** [comment]
@stemcc I don't think that is relevant to Notable. Markdown front matter is relatively widespread, you should probably ask the app you're using to support it instead. If you want to remove it you can do so in batch, today, just with a regex I think.
