### ISSUE TITLE
Tags with special names are not handled properly

### ISSUE THREAD

**Issue by afonsomatos** [notable/notable#784]
- **OS Version**: Ubuntu 18.14
- **Notable Version**: 1.5.1

### Current behavior

Add a tag to a note named **true**, **false**, **null** or an **integer** (example 42).
Right click on the tag on the sidebar.
The menu options don't appear, and there is an error in the console.

### Expected behavior

The menu option should have appeared as usual.

**Comment by afonsomatos** [comment]
This also breaks Previous Tag and Next Tag options. Because, the tag is not being treated as a string internally.

**Comment by fabiospampinato** [comment]
Good catch, we should review all the calls to `$.fn.data`, and perhaps use `$.fn.attr` instead.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
