### ISSUE TITLE
Full timestamp for clipboard image paste file naming

### ISSUE THREAD

**Issue by BobMilli** [notable/notable#788]
### Feature description
Actually when you copy/paste multiple images within a note, you get and attachment called `Clipboard_YYYY-MM-DD.png` for the first one, `Clipboard_YYYY-MM-DD (2).png` for the second one...
I think that if instead of only the date we could have a full timestamp in the attachment file name, this would be greater and less confusing.

### Feature motivation
Being able to copy/paste images directly within notes is a great enhancement. The way the attachment is named doesn't seems, IMHO, very consistent.

**Comment by fabiospampinato** [comment]
> very consistent.

We can't use the same format used in the front matter because I believe the `:` character is not a safe character to use in file names.

Maybe we could add a more specific timestamp, adding also hours, minutes and seconds, would that solve the issue?

**Comment by BobMilli** [comment]
Sure, I think adding hours, minutes and seconds will do the job.
Thx

**Comment by fabiospampinato** [comment]
@BobMilli Does `Clipboard_YYYY-MM-DD_HH-MM-SS` sound good to you? I feel with all these numbers the date is becoming significantly harder to read 🤔 I don't particularly like the underscore separating the two parts of the date, but perhaps that makes the date more readable.

**Comment by BobMilli** [comment]
@fabiospampinato IMHO `Clipboard-YYYYMMDD-HHMMSS.png`could be sufficient. Normally, we're not supposed to use this name, my concern was more to have a unique name for each clipboard paste and get something quite readable.
HTH

**Comment by fabiospampinato** [comment]
@BobMilli Thanks for the suggestion, I'll have to check how readable these timestamps will be with actual numbers before deciding.

**Comment by fabiospampinato** [comment]
In the end I went for: `Clipboard_{YYYY}-{MM}-{DD}-{HH}-{mm}-{ss}`, that seemed to strike the best balance between precision and readability.

For now I'd say this is good enough, in the future perhaps this will be customizable.
