### ISSUE TITLE
KaTeX block does not work when containing double ampersand

### ISSUE THREAD

**Issue by SCLeoX** [notable/notable#789]
- **OS Version**: Windows 10 1903
- **Notable Version**: 1.7.2

### Current behavior

```markdown
$$
\begin{aligned}
  x_1  && + 1.5x_2 && + \pi x_3 & = 4 \\
  5x_1 &&          && + 7x_3    & = 5 \\
\end{aligned}
$$
```

Gives

![image](https://user-images.githubusercontent.com/13428807/63377756-b2770f00-c35e-11e9-9071-cb4d06a78f86.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/13428807/63377806-c91d6600-c35e-11e9-900c-fd48c35960e6.png)

---

By the way, if you switch $$ to ```` ```katex``` ```` blocks, it renders just fine. However, ```` ```katex``` ```` blocks are not rendered in many other markdown viewers (for example Markor).

Also, since ```` ```katex``` ```` blocks work but `$$` does not, I think it is very likely a bug.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
