### ISSUE TITLE
Intra-document links for headers with backquotes

### ISSUE THREAD

**Issue by tetafro** [notable/notable#790]
- **OS Version**: Linux Mint 19.1
- **Notable Version**: 1.7.3

### Current behavior

Create a note with a header with backquotes and try to make a link to it. Like this
```
# Document title

## Table of Contents

* [Link](#part-1-hello-world)
* [Link](#part-2-hello-world)
* [Link](#part-3-hello-world)

## Part 1: Hello, world

This one works fine.

## Part 2: Hello, 'world'

This one works fine too.

## Part 3: Hello, `world`

This one doesn't work.

---

<some more content to make page scrollable>
```

The 3rd link doesn't work.

### Expected behavior

All links are working :)

**Comment by fabiospampinato** [comment]
It looks like we are computing `part-3-hello-codeworldcode` for its id 🤔

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
