### ISSUE TITLE
Disable warning before closing a window

### ISSUE THREAD

**Issue by Armagedoom** [notable/notable#791]
### Feature description

The recently added feature which prompts for confirmation before closing notable should be configurable.

### Feature motivation

More than 95% of the times I want to close Notable I am closing it for good, and having to always confirm forces an extra click on those 95% of the times, which can get annoying over time.

**Comment by alonchis** [comment]
I have lost data due to not having this feature. I hit cmd + w instead of e. Lost about 30 mins of progress (this was before auto save). I love this feature but I can see how it can be annoying for some user. It would be great to be able to disable it on settings.

**Comment by fabiospampinato** [comment]
> The recently added feature which prompts for confirmation before closing notable should be configurable.

Totally, I plan to introduce settings (and a way to disable that dialog) in v1.8.

**Comment by fabiospampinato** [comment]
@Anzan That's a good point 🤔 The thing is we use `CtrlOrCmd+E` pretty heavily, perhaps we should show the dialog only when closing via the shortcut 🤔

**Comment by fabiospampinato** [comment]
@Anzan Makes sense, I'll do that in v1.8 👍 Hopefully I'll also a setting for disabling/enabling the dialog itself.

**Comment by isundaylee** [comment]
Is it possible to also make is such that the dialog is only shown if we're in editing mode? For example, if I am just looking at the note and I'm not in editing mode, there should be no concern for accidental losing data.

**Comment by fabiospampinato** [comment]
> Is it possible to also make is such that the dialog is only shown if we're in editing mode? For example, if I am just looking at the note and I'm not in editing mode, there should be no concern for accidental losing data.

The concern might be that you might want to switch to edit mode via `cmd+e`, but you accidentally hit `cmd+w` instead and that'd be an annoyance.

I'm not sure how much customizability we want to have around this dialog, I think just choosing between showing it or not should be enough.

**Comment by isundaylee** [comment]
Are you saying that there'll be an option the user can toggle to not show the dialog at all? In that case, that would work great for me. Thanks!

**Comment by fabiospampinato** [comment]
> Are you saying that there'll be an option the user can toggle to not show the dialog at all? In that case, that would work great for me. Thanks!

Yeah I'll add one once we have proper settings #476, which should be coming in v1.9.

**Comment by fabiospampinato** [comment]
I've removed that dialog entirely.

From v.1.9 on if you feel like you hit Cmd+W or Ctrl+W by mistake too often you can just unbind that shortcut:

```json
{ shortcut: '-CmdOrCtrl+W' }
```

**Comment by fabiospampinato** [comment]
In any case whenever the app is closed it will safe its content before exiting. If you find any bug about this please do let me know as they'd be high priority issues I'd like to tackle as soon as possible.

**Comment by Tectract** [comment]
I wish I had the option to disable confirmation boxes on ALL button clicks, on my entire computer. Developers, don't second-guess your users. Yes I really meant to click the "x" button, I didn't want to start a quiz about my real intents with the computer before the program is going to close. You literally broke the "x" button. "x' means close the program, not anything else!!! yes I really meant to click EVERY BUTTON I CLICKED, and I didn't need a confirmation dialog or a confirmation window popping up either!!!
