### ISSUE TITLE
Thank you and a question (viewing notes on mobile)

### ISSUE THREAD

**Issue by patrickf3139** [notable/notable#793]
Hi. Let me start off I just spent all the free time in my past month researching and demoing so many notes apps and being disappointed with all of them after migrating off of Evernote. I tried  Bear, Quiver, Standard Notes, Simple Notes, FSNotes, Joplin, Boostnote, and Dropbox Paper. Finally somehow, in the late of night, I stumbled upon Notable and I just decided this will be my new note-taking home. Finally, my note-taking soul is at rest. So big THANK YOU Fabio and all the people who have helped me develop Notable.

Anyway, in light of that, my only slight disappointment is that I want to be able to view my notes on the go. Don't need to edit them. I know there's no iOS app yet and that's cool with me. How do people currently improvise for viewing their notes on iOS? Does anyone have a better system than just opening up your files on the Dropbox app? Thanks!

**Comment by fabiospampinato** [comment]
It's awesome that Notable resonated with you after having tried so many note-taking apps 😄.

I don't actually know what people use today for viewing their notes on iOS, I don't personally use my phone that much and I have an Android one. I'd suggest you to read what has already been written [here](https://github.com/notable/notable/issues/23) and in the [subreddit](https://www.reddit.com/r/Notable/), alternatively you should open a thread in the subreddit, I'm sure people will want to share their solution to this.

**Comment by patrickf3139** [comment]
Thanks Fabio for the quick reply! Didn't know there's a subreddit, I'll go there instead.
