### ISSUE TITLE
Context menu does not take into account zoom levels

### ISSUE THREAD

**Issue by gunt3001** [notable/notable#794]
- **OS Version**: Windows 10 Pro 1903 build 18362.295
- **Notable Version**: 1.7.3

### Current behavior

When zoomed in/out, context menus that opens does not correspond to the item under the cursor.

![Notable_ndf8wo4YYf](https://user-images.githubusercontent.com/5871589/63653800-215fc800-c7a4-11e9-9214-c40db2f19ce1.png)

In this example, I zoomed in and right clicked on the sidebar, and the context menu for the notes appears, as it is where the note list would have been at 100% zoom scaling.

Under high zoom levels this has caused context menus to seem to not work, or worse, perform actions on the wrong notes (like deleting!)

### Expected behavior

Context menu items should take into account zoom levels.

### Remarks

I tried to do a quick fix by dividing the x and y coordinates in 

https://github.com/notable/notable/blob/5268525128fd3a7d3d07e276afb76d0cb5a8f452/src/renderer/components/main/extra/context_menu.tsx#L52-L55

with electron's `webFrame.getZoomFactor()` and it seems to make things better from my very brief testing.

I'm not sure how much different the source for the latest version is now compared to the public one, so please consider accordingly.

Also possibly the cause of #755

**Comment by fabiospampinato** [comment]
I'm not sure if this is a bug in our code in Electron's, regardless I can reproduce the issue, thanks a lot for reporting it!

**Comment by fabiospampinato** [comment]
This is an upstream bug: https://github.com/electron/electron/issues/21145, but perhaps I can workaround it.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
