### ISSUE TITLE
Network-attached drive: improve support for Samba

### ISSUE THREAD

**Issue by janwo** [notable/notable#799]
- **OS Version**: Windows 10
- **Notable Version**: 1.7.3

### Current behavior

Create a new data directory to get a fresh setup. Open the *10 - Linking Attachments...* note. The preview is not shown up correctly.
![image](https://user-images.githubusercontent.com/7375724/63752130-fadb8300-c8b0-11e9-8859-bc359af1d9bc.png)

### Expected behavior

The Icon should be visible as inline image.

**Comment by fabiospampinato** [comment]
@janwo is the image opened when clicking the button? Is the `icon_small.png` actually in the attachment directory?

**Comment by janwo** [comment]
@fabiospampinato Okay, it depends on the use case.

On the local drive the image is shown and can be opened via right click => open.
On a network drive the image is not shown and when opening it via right click => open it says that the image was not found altough it is there.

After some retries it now works however. It seems like the handling with network shares is not really reliable. Unsure how to proceed here. Windows... Good to have Mac at home ;-)

**Comment by fabiospampinato** [comment]
I guess there's probably a way to make this work with network drives too, how do I reproduce this? I'm not very familiar with mounting drives over the network, are you just sshfs-ing something?

**Comment by janwo** [comment]
Yes, I cannot really reproduce it. Sometimes it happens on a network drive. It's connected via SMB2 / SMB3.

**Comment by fabiospampinato** [comment]
I've just tried using Notable with a Samba storage and it seems to work, although kind of slowly and maybe not very reliably?

There are probably some measures we could adopt to better support network-attached drives, but it'd say for now that's not a priority.
