### ISSUE TITLE
Broken embedded HTML parsing

### ISSUE THREAD

**Issue by hallowatcher** [notable/notable#802]
- **OS Version**: Windows 10
- **Notable Version**: 1.7.3

### Current behavior

Before closing a `<markdown>` tag, there NEEDS to be markdown text or a blank line or else all the markdown after it will just be interpreted as plain text

This means that if inside my `<markdown>` I include another html tag in the end, there has to be an empty line succeeding it or else all the markdown after that point will just be plain text

It's hard to explain with words so see screenshots:
![image](https://user-images.githubusercontent.com/6265839/63853458-0905ce00-c99b-11e9-848d-8e6bf5f20902.png)
![image](https://user-images.githubusercontent.com/6265839/63853461-0d31eb80-c99b-11e9-852d-f569b6d277f2.png)

with empty line
![image](https://user-images.githubusercontent.com/6265839/63853521-3ce0f380-c99b-11e9-9185-66862e22a4aa.png)
![image](https://user-images.githubusercontent.com/6265839/63853526-410d1100-c99b-11e9-8b19-6c275cb85ae4.png)

### Expected behavior

I would expect to be able to end my `<markdown>` however I want instead of making sure it doesn't end with an HTML tag. (note I say HTML tag but I only tried `<img />`

**Comment by fabiospampinato** [comment]
@hallowatcher Can you post a note that I can use to reproduce the issue? In general the HTML parser is pretty broken, by design, that's probably the root cause here.

**Comment by hallowatcher** [comment]
@fabiospampinato 

While reproducing it, I noticed some strange behaviors.

The markdown tags have to be wrapped in another element.

Sometimes it will bug it even with 1 empty line, so whenever I remove it, it works and sometimes its the other way around. I don't think this can be fixed that easily as I thought

```
# Bug 802

<div>
  <markdown>
  ### The bug

  The bug happens with the empty line above this line
  </markdown>
</div>

<div>
  <markdown>
  ### Bugged markdown
  </markdown>
</div>

<br>
<br>
<br>
<br>


<div>
  <markdown>
  ### The bug
  The bug doesnt happen without the empty line above this line
  </markdown>
</div>

<div>
  <markdown>
  ### Working markdown
  </markdown>
</div>
```

**Comment by fabiospampinato** [comment]
I can totally reproduce this, whatever the issue it should be fixable somehow 🤔

**Comment by fabiospampinato** [comment]
@hallowatcher I don't think I can reproduce anymore, can you still reproduce it?

**Comment by fabiospampinato** [comment]
I can more easily reproduce with the following:

```markdown
<div>
  <markdown>
  ### The bug
  
  The bug doesnt happen without the empty line above this line
  </markdown>
</div>

<div>
  <markdown>
  ### Working markdown
  </markdown>
</div>
```

The root cause of this issue is that the way HTML is parsed inside Markdown according to the CommonMark spec is crap. Reference: https://github.com/commonmark/commonmark-spec/issues/597

I'm not sure I can write a quick patch for solving this in general 🤔

**Comment by fabiospampinato** [comment]
I just fixed this particular issue about the `<markdown>` tag, but not super reliably and only for that tag, in the future I think we'll have to write a more sensible Markdown spec to fix this and other issues.
