### ISSUE TITLE
Make Menu bar stay hidden on launch if hidden before

### ISSUE THREAD

**Issue by LaVieEstDure** [notable/notable#803]
### Feature description

Hysteresis for the menu bar hiding would be good so that if I hide the menu bar, close the program and start it up again, the menu bar doesn't show up by default on next launch. Currently on next launch, menu bar is visible unless you hide it again manually. 

Unsure if this is as intended for a reason or if it's a bug or just something nobody else has asked for.

**Comment by fabiospampinato** [comment]
It's just something that hasn't been implemented yet, we are tracking this here: #339
