### ISSUE TITLE
No warning or error message when current data directory moved/deleted

### ISSUE THREAD

**Issue by patrickf3139** [notable/notable#806]
- **OS Version**: macOS 10.14.6
- **Notable Version**: 1.7.3

### Current behavior
1. Import some notes into Notable
2. rename the data directory being used
3. all the notes disappear but there's no warning
4. click on "Open Data Directory", nothing happens, not even an error

### Expected behavior

I'd expect a warning or popup of some sort at least, right?

**Comment by fabiospampinato** [comment]
Yes we should watch the current data directory explicitly. Another potential issue is that your data directory is in an external drive, when you open Notable it asks you to pick a data directory because it can't find it, but then you attach the external drive, Notable should just pick it up.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.

Now if the data directory becomes unaccessible for whatever reason the app will ask you to pick a new one, and if the previous data directory becomes available again it just detects that and reopens it.

**Comment by patrickf3139** [comment]
Thank you for fixing it!

**Comment by fabiospampinato** [comment]
Thank your for reporting it ✌️
