### ISSUE TITLE
"Zoom In" shortcut not working

### ISSUE THREAD

**Issue by partytoni** [notable/notable#807]
I'm using an Italian layout keyboard and the correct keyboard to use the Zoom In command is "Ctrl" + "Shift" + "+", but in the app it shows the same with "=", which i believe works with US layouts.
Sorry if it is a stupid issue, just wanted to let you know.

https://imgur.com/a/Fa5l6aR

**Comment by fabiospampinato** [comment]
It's a legitimate issue, but one that comes from some other tool we are building up, probably either Electron or Chrome. I'll see what can be done about this 🤔

**Comment by fabiospampinato** [comment]
This should be fixed in v1.9, the reported default shortcut for `view.zoom.in` is always `CmdOrCtrl+=`, no matter what keyboard layout is active.

**Comment by export-mike** [comment]
Seems to be the case for me on Mac `CMD +`

**Comment by export-mike** [comment]
I'm on 1.8.4, Where do I get 1.9?
