### ISSUE TITLE
Date created and modified format

### ISSUE THREAD

**Issue by patrickf3139** [notable/notable#810]
Hi there,
I'm still in the process of migrating from my old note taking apps (Evernote and Quiver) over to Notable. Unfortunately, due to my situation, I think I'm going to have to manually set the the timestamp fields myself (yes, I'm OCD about my notes).
1. Using Notable and not viewing the raw notes, is it possible to view or change the timestamps for the notes?
2. What format does Notable expect the timestamp to be in? What would happen, if, say, I use seconds since epoch for example instead of the expected format?

**Comment by fabiospampinato** [comment]
What would it take for you to have the all migration automated? Perhaps we would just need to add support for Quiver in [dumper](https://github.com/notable/dumper)?

> Using Notable and not viewing the raw notes, is it possible to view or change the timestamps for the notes?

You can't change the raw timestamps directly from within the app.

> What format does Notable expect the timestamp to be in? What would happen, if, say, I use seconds since epoch for example instead of the expected format?

Anything that you can pass as an argument to [`new Date ()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date), so timestamps would just work fine too.

**Comment by patrickf3139** [comment]
> What would it take for you to have all the migration process automated?

Quiver also has timestamps, tags, and a folder structure. If dumper could keep all those things when importing notes from Quiver, I think that'd be ideal. Note that to get timestamps and tags, dumper would need to take in the `qvnote` format, as Quiver doesn't include that information when it exports as Markdown or HTML. And if you want to maintain even the folder structure, you'll need to take in the whole `qvlibrary`.
I am biased, but on this note, I do want to say that I think Quiver users are probably a strategic target for Notable. If you look at Notable's features and the way it is marketed on https://happenapps.com, you may find that it targets a very similar audience of tech-saavy users who likely know git and prefer their notes with Markdown. The main reason Quiver didn't work for me was because it has a ill-advised data format that is hard to check into git, hard to read, and hard to export out from.

> Anything that you can pass as an argument to new Date (), so timestamps would work just fine too.

Thanks so much for your help!

**Comment by fabiospampinato** [comment]
> Quiver also has timestamps, tags, and a folder structure.

The folder structure could be preserved as well, but currently it's not very well supported in Notable.

> I am biased, but on this note, I do want to say that I think Quiver users are probably a strategic target for Notable. 

Yeah actually I thought the same when making the [comparison table](https://github.com/notable/notable#comparison), IMHO the single biggest insight Notable had above apps like Quiver is that you don't need a special data format for storing metadata, mermaid diagrams, katex expressions etc.

Anyway currently dumper doesn't support Quiver, but I think it should, I don't currently have the time to add support for it now, but perhaps you can think about adding support for it yourself, I've wrote a little contribution guide [here](https://github.com/notable/dumper/blob/master/.github/CONTRIBUTING.md), that would surely be more fun, and useful, than migrating notes by hand. 

If Quiver's data format is pretty simple adding a provider for it to dumper may take like 15 minutes even, maybe I should learn more about the `.qvnote` and `.qvlibrary` formats 🤔.

**Comment by patrickf3139** [comment]
> IMHO the single biggest insight Notable had above apps like Quiver is that you don't need a special data format.

Amen!

> perhaps you can think about adding support for it yourself, I've wrote a little contribution guide here, that would surely be more fun, and useful, than migrating notes by hand.

Sure, I'll think about it. It might take around the same amount of work as migrating it by hand anyway. The only issue is I am not handy with JS, and I'd be a bit embarrassed to submit low-quality code for the whole Internet to see.

**Comment by fabiospampinato** [comment]
I see 🤔 I don't know I can check how difficult it would be to implement a provider for Quiver, but I'm super busy with other things right now so I'm not sure when I'll be able to do that.

**Comment by patrickf3139** [comment]
No problem Fabio! I may end up giving it a go anyway

**Comment by sillykelvin** [comment]
Currently Notable saves the two dates automatically, Is there any way to customize the format? For me, I'd like to save the date like `2019-10-14`, omitting the hour/minute etc. I know I can modify this manually in other editors, but I think it might not be a "best" approach.

**Comment by fabiospampinato** [comment]
@sillykelvin It's not possible today and I'm not sure it should be customizable in the future, there will be incompatibility issues when sharing your notes with other people with a different configuration, or even with your own notes if you at some point decide to change the format.

**Comment by sillykelvin** [comment]
@fabiospampinato Thanks for your reply. However, if the format is compatible with `new Date()`, the sharing issue and the change-format issue should not be the problem. We might guide people that:

1. We highly not recommend that you customize the date format unless you are familiar with js
2. If you persist in customizing that, you should make it compatible with `new Date()`
3. If you do not make it compatible with `new Date()`, there will be issue 1, issue 2, etc. and you are on your own

And for those do not obey the rule or happen to mis-configured this option, we might show a warning or error message during parsing the configuration file.

**Comment by fabiospampinato** [comment]
> if the format is compatible with new Date(), the sharing issue and the change-format issue should not be the problem.

Yes, but that's an implementation detail.

> We might guide people that:

That's kind of a non-starter, I want to make things that are obvious, not make obvious things need a guide.

**Comment by patrickf3139** [comment]
I commend your sharp and focused product management skills @fabiospampinato .

**Comment by fabiospampinato** [comment]
Thanks 😄
