### ISSUE TITLE
Document list of languages supported by syntax highlighting

### ISSUE THREAD

**Issue by tarheels100** [notable/notable#811]
### Feature description

Document which programming languages are supported by the syntax highlighting feature.  This could either go in the "Cheatsheet" and/or the Tutorial.  At least specify/link-to which syntax highlighter library is being used so that users can track down the list of supported languages.

### Feature motivation

Based on searching the issues page, the syntax highlighter library seems to have changed a few times during development, so it's a bit difficult to determine what features are currently supported.  Without knowing which languages are supported, it's hard to know whether a lack of highlighting is due to lack of support by Notable or a mistake in the user's code block syntax.

**Comment by fabiospampinato** [comment]
We support all the languages supported by the Monaco editor: https://github.com/microsoft/monaco-languages/tree/master/src.

I think a better solution to this would be to provide autocompletion for them #576.

**Comment by tarheels100** [comment]
> We support all the languages supported by the Monaco editor: https://github.com/microsoft/monaco-languages/tree/master/src.

Thanks, that the conclusion that I eventually came to after scouring the GitHub issues page.  I just thought it would be worth the minor effort to include a link to that list of languages somewhere in Notable's documentation so that new users will have the information they need to use the software.  

> I think a better solution to this would be to provide autocompletion for them #576.

Of course, an autocomplete feature would be useful too, although it serves a somewhat different purpose.  Thanks!

**Comment by fabiospampinato** [comment]
> Of course, an autocomplete feature would be useful too, although it serves a somewhat different purpose.

You could see the list of supported extensions/languages via that too, but I think you have a point that some people might want to know which languages are supported before even trying out Notable 🤔 And we currently don't even have that autocomplete feature.

I'll think about this, thanks. Ideally though support for other languages should be implementable via plugins, making such list ultimately useless, but in the meantime it could be nice to have.

**Comment by tarheels100** [comment]
> some people might want to know which languages are supported before even trying out Notable

As a new user, I agree.

> I'll think about this, thanks. Ideally though support for other languages should be implementable via plugins, making such list ultimately useless, but in the meantime it could be nice to have.

That's understandable.  From what I can tell, it looks like you're at least on your third syntax highlighting library already.  But even if it continues to morph over time, as it stands, builtin syntax highlighting is somewhat of a standout feature and it's worth "advertising".  I think a link to monaco-languages' list would be a good start.  Keep in mind, autocomplete is a great feature for intermediate users who are familiar with the software, but it won't help a bit for someone who doesn't even know that Notable has syntax highlighting or how to access it.

**Comment by fabiospampinato** [comment]
> From what I can tell, it looks like you're at least on your third syntax highlighting library already.

Probably, I think originally I was using CodeMirror + Highlight.js, then I switched to CodeMirror/Monaco + Prism.js and finally just Monaco.

> but it won't help a bit for someone who doesn't even know that Notable has syntax highlighting or how to access it.

That's a good point.

**Comment by tarheels100** [comment]
@fabiospampinato Very interesting.  Thanks for the deep dive!

**Comment by Armagedoom** [comment]
I have tried to highlight scala code and no highlighting comes out of it.
What I am trying:

```
```scala
(someList: List[T]) match {
  case Nil => ...          // empty list
  case x :: Nil => ...     // list with only one element
  case List(x) => ...      // same as above
  case x :: xs => ...      // a list with at least one element. x is bound to the head,
                           // xs to the tail. xs could be Nil or some other list.
  case 1 :: 2 :: cs => ... // lists that starts with 1 and then 2
  case (x, y) :: ps => ... // a list where the head element is a pair
  case _ => ...            // default case if none of the above matches
}
```
```

At the very least, the comments should be highlighted. Am I doing something wrong? Thanks!

**Comment by fabiospampinato** [comment]
@Armagedoom are you using a custom theme that's not one of the built-in ones? It may be that I have to update the editor to add support for scala 🤔  I'm not entirely sure. I'd be useful if you could open a separate issue for this.

**Comment by Armagedoom** [comment]
@fabiospampinato done: https://github.com/notable/notable/issues/1476#issue-849961296
Answering your question, I am using everything by default.
