### ISSUE TITLE
KaTeX expressions don not display when \_ in expressions

### ISSUE THREAD

**Issue by greeCat** [notable/notable#814]
- **OS Version**:ubuntu18.04
- **Notable Version**:1.7.3

### Current behavior
```markdown
$$test$$
$$tes\_t$$
```

Gives
![2019-09-09 18-09-17](https://user-images.githubusercontent.com/18208143/64522621-fb523000-d32c-11e9-800f-6b802bd4a77b.png)

### Expected behavior
![2019-09-09 18-13-49](https://user-images.githubusercontent.com/18208143/64522914-c09cc780-d32d-11e9-8aac-62b1e2268337.png)

**Comment by fabiospampinato** [comment]
I can reproduce, it looks like everything after that expression is recognized as part of the expression too 🤔

**Comment by fabiospampinato** [comment]
This is an [upstream issue](https://github.com/commonmark/commonmark-spec/issues/597#issuecomment-552145944), I'm not sure how much I can do about it 🤔.

**Comment by fabiospampinato** [comment]
I don't think I can fix this without terrible hacks, let's wait until they fix this upstream.

In the meantime you can write that as a katex code block, e.g. (but with backticks):

```
'''katex
tes\_t
'''
```

**Comment by fabiospampinato** [comment]
The upstream package's maintainers don't consider this a bug, for understandable reasons, so I went with the terrible hack for fixing this, the fix will be available in the next release.
