### ISSUE TITLE
Allow default directory path change from ../Notes

### ISSUE THREAD

**Issue by c-torre** [notable/notable#815]
### Feature description

Right now, the default directory can be completely changed, but the directory that finally stores the notes is always fixed as "/Notes".
The requested feature would allow to fully change the default directory path without this restriction.

### Feature motivation

The default directory should be fully editable.

If not, it may interfere with the pre-existing directory structure.

**Comment by fabiospampinato** [comment]
> but the directory that finally stores the notes is always fixed as "/Notes".

If that's happening to you then this is a bug, there's no point in changing data directory if notes are being saved elsewhere anyway.

I'm not sure how to reproduce this issue, I don't see it happening for me 🤔

**Comment by ssalinasf** [comment]
It's just happened to me. I downloaded the last version for ubuntu. After install I define the default directory, but when I want to save my notes in my notes folder it create a new folder called /Notes and only read notes from there.

**Comment by fabiospampinato** [comment]
That's pretty weird, there's no hardcoded `/Notes` directory anywhere, the default one is `~/.notable`. Where did you guys download the app from?

**Comment by ssalinasf** [comment]
https://github.com/notable/notable/releases

I downloaded `notable_1.7.3_amd64.deb`

**Comment by ctorr148** [comment]
https://aur.archlinux.org/packages/notable-bin (notable-bin  1.7.3-2)
Built from Pamac on Manjaro

After building, the Notes directory is created, storing all the .md files from the docs/tutorials. This folder will then remain as default to store all the notes. If the directory is changed, a new /Notes directory is created and needed to store the notes in the new default path.

**Comment by fabiospampinato** [comment]
Wait are you guys talking about the "notes" (not "Notes") directory created inside a data directory?

**Comment by SichongP** [comment]
> Wait are you guys talking about the "notes" (not "Notes") directory created inside a data directory?

I think that's what OP was referring to. Select any path for data directory, a `notes` directory will be created inside to store all notes. Understandably, it can be desirable to be able to fully customize data directory for notes.

**Comment by fabiospampinato** [comment]
Let's track this in #54 then.
