### ISSUE TITLE
Multicursor using Alt+Click in Windows

### ISSUE THREAD

**Issue by tarheels100** [notable/notable#818]
- **OS Version**: Windows 10 (build 18362.295)
- **Notable Version**: 1.7.3

### Current behavior

The Alt+Click shortcut to create a new cursor changes focus to the menu bar, preventing any typing or editing until focus is returned to the editor (either by pressing Alt again or pressing Esc).  When focus is returned to the editor, both cursors are still there and can be used as expected.  The specific series of steps looks like this:

| Step | Action  | Result |
| --- | ------------- | ------------- |
| 1 | Depress Alt  | No result  |
| 2 | Click left mouse button in editor  | Additional cursor appears  |
| 3 | Release Alt | Both cursors disappear and "Notable" menu in menu bar is highlighted |

The other multicursor shortcuts seem to work fine, although for me, Ctrl-Alt-Up/Down and Alt-Ctrl-Up/Down both yield the same result (create an additional cursor) despite having different descriptions in the shortcuts help menu.

My guess is the problem stems from Windows' default behavior of using the Alt key as a menu bar shortcut.  In many programs, pressing Alt automatically highlights the leftmost menu and a second press returns focus to where it was before.  Windows doesn't appear to recognize Alt+Click as a distinct shortcut (in contrast with keyboard-based shortcuts like Alt-Ctrl-<key>) and goes ahead with the default action.  Perhaps Notable needs to "catch" the Alt keypress if the mouse is clicked instead of letting the keypress flow up to the system level.

### Expected behavior

Alt+Click in the editor should create a new cursor and focus should remain in the editor for immediate editing.

**Comment by fabiospampinato** [comment]
@tarheels100 Can you check if this has been fixed in v1.8.3 once I release it?

**Comment by tarheels100** [comment]
> @tarheels100 Can you check if this has been fixed in v1.8.3 once I release it?

Sure, do you have a rough estimate for when that will happen?

**Comment by fabiospampinato** [comment]
@tarheels100 probably today, I still have a few more bugs to fix and then I'll make the release.

**Comment by tarheels100** [comment]
@fabiospampinato I just updated to 1.8.3, and unfortunately I'm getting the exact same behavior.

**Comment by fabiospampinato** [comment]
I can reproduce, I guess we'll have to switch to Ctrl+Click instead.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
