### ISSUE TITLE
"Tab" and "Shift Tab" to increase indent and decrease indent a list item when editing a List

### ISSUE THREAD

**Issue by jmtscaff** [notable/notable#822]
Would be nice to be able to use "Tab" and "Shift Tab" to increase indent and decrease indent a list item when editing a List like in Visual Studio Code.

This will allow faster editing of outlines.

**Comment by fabiospampinato** [comment]
I believe our editor works exactly like the one used in VSCode in this regard, doesn't it? In fact it's actually the same editor under the hood.

**Comment by jmtscaff** [comment]
@fabiospampinato 

Maybe this is a bug then... jejejeje... no they are not working the same.

This is what I expect (vscode):
![VSCode_tab_demo](https://user-images.githubusercontent.com/26261627/64996168-d74d9c00-d8a2-11e9-87bd-afbf9b807e91.gif)

And this is how Notable currently works:
![Notable_tab_demo](https://user-images.githubusercontent.com/26261627/64996197-e896a880-d8a2-11e9-9695-9da44048de79.gif)

There are two problems
1. When I hit enter I'm expecting the dash is automatically added
2. When I hit tab or shift-tab the indentation is increased or decreased, only the shift-tab works not the tab.

One thing to note is that this only works when the cursor is after the dash (-) at least on VSCode. If I have text on the item and try to do it at the end it does not work at least the tab.

**Comment by fabiospampinato** [comment]
I don't think that's actually how vscode works, I think an extension is providing those features to you.

Let's track this here: #88
