### ISSUE TITLE
Why is "No WYSIWYG" a good feature?

### ISSUE THREAD

**Issue by ThiagoRangel7** [notable/notable#823]
I noticed that in the [comparison table](https://raw.githubusercontent.com/notable/notable/master/resources/comparison/table.png) in the ReadMe file, "No WYSIWYG" seems to be considered a good feature. Why is that? I really liked Notable, but I think that Bear's, Notion's and Typora's WYSIWYG feature is really cool, as it enables the writer to see the results ("after Markdown rendering") of what he's writing at the same time as he writes.

I'd really appreciate if someone can explain me why "No WYSIWYG" is considered a good thing. Thanks

**Comment by fabiospampinato** [comment]
Actually I think "No WYSIWYG" isn't quite accurate, I think the feature I'm interested in is being able to write the source code of the note directly, I'm not really interested in not having the option to use a WYSIWYG editor, in fact we have an issue tracking adding one #284.

I personally prefer a non-WYSIWYG editor for many reasons, like:

- The interface is generally way less cluttered.
- When I paste something or type something I always know what I'm going to get, sometimes in a WYSIWYG editor things just get written in a different style than you intended.
- With a non-WYSIWYG editor I can do interesting things with multiple cursors, like selecting all quotations, selecting their first word and making that bold, you just can't do these sorts of things with a WYSIWYG editor.
