### ISSUE TITLE
HTML Export Feature

### ISSUE THREAD

**Issue by bismay4u** [notable/notable#827]
It would be great to have HTML export button on each note

As we can then use Notable for writing Web Friendly content for articles and books.

**Comment by fabiospampinato** [comment]
Notes can already be exported to HTML, either individually or in bulk, is this feature request specifically about adding a button to the UI for triggering this action?

**Comment by bismay4u** [comment]
What I meant was, a Single Note Export To HTML and copy directly for use.



Thanks And Regards,
Bismay Kumar Mohapatra
Phone : +91-8097695850
EMail  : bismay4u@gmail.com
Skype  : bismay4u1

This e-mail message may contain confidential, proprietary or legally
privileged information. It should not be used by anyone who is not the
original intended recipient. If you have erroneously received this message,
please delete it immediately and notify the sender. Before opening any
attachments please check them for viruses and defects.

**Comment by fabiospampinato** [comment]
I don't understand, do you want the produced HTML to be copied into your clipboard?
