### ISSUE TITLE
Question: About Windows install files

### ISSUE THREAD

**Issue by Gamegenorator** [notable/notable#830]
On Linux, I can pick between a .appimage, .deb etc and I know what they do, on Windows I see a:  Notable.Setup.1.7.3.exe, Notable.1.7.3.exe, and a Notable-1.7.3-win.zip, file, which is recommended?

**Comment by fabiospampinato** [comment]
I'd recommend "Notable.Setup.1.7.3.exe", the other one is a version of the app that doesn't require installation, you can just run it, the other file is used by the uploader for auto-updating the app.

**Comment by Gamegenorator** [comment]
Understood, Thank you for building such an incredible tool!

**Comment by fabiospampinato** [comment]
Thank you for using it :) Btw I've just updated the readme of the repository, I think now it's much easier to download the right version of the app for each person, do you feel the same way?

**Comment by Gamegenorator** [comment]
If you mean literally adding a download button that looks at the detected OS and automatically provides the file for the operating system, **Absolutely!** Thank you very much!

**Comment by fabiospampinato** [comment]
Yeah that's exactly how it works, you can check it out in the readme.

**Comment by Gamegenorator** [comment]
Great, Thank you again for all you've done!
