### ISSUE TITLE
Vim support

### ISSUE THREAD

**Issue by pman215** [notable/notable#833]
### Feature description

Supporting Vim bindings to edit files

### Feature motivation

Vim support is aligned with the core principle of "beyond not sucking"

Are you guys allowing new contributors? I'll be down to help with this task

**Comment by fabiospampinato** [comment]
Duplicate of #52.

> Are you guys allowing new contributors? I'll be down to help with this task

Read the bottom of the readme and the contributing section, they answer your question.
