### ISSUE TITLE
Markdown syntax highlighting broken after $$ math w/ bulleted list

### ISSUE THREAD

**Issue by darsnack** [notable/notable#836]
- **OS Version**: macOS 10.14.6
- **Notable Version**: 1.7.3

### Current behavior

The following example breaks Markdown highlighting immediately following the math.
```
6. Define the cross product of two positive quantities as $f: [0, 1]^3 \times [0, 1]^3 \mapsto [0, 1]^3 \times [0, 1]^3$ such that
   $$f(x, y) = ((x \times y)_p, (x \times y)_n) \text{ and } (x \times y) = (x \times y)_p - (x \times y)_n$$
   where $(x \times y)_p$ and $(x \times y)_n$ can be easily calculated from Step 3 above under the assumption that $x, y, \geq 0$.
```
The rendered highlighting looks like
<img width="725" alt="Screen Shot 2019-09-24 at 9 47 28 AM" src="https://user-images.githubusercontent.com/4811350/65522495-7597be00-deb0-11e9-92cd-2ace1905efd1.png">

This can be fixed by placing the closing `$$` on its own line.

### Expected behavior

The expected behavior is shown below (except it should be achieved without having to place `$$` on its own line.
<img width="721" alt="Screen Shot 2019-09-24 at 9 49 27 AM" src="https://user-images.githubusercontent.com/4811350/65522591-9b24c780-deb0-11e9-9d37-65b4b5cedb88.png">

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
