### ISSUE TITLE
Too high CPU usage at idle.

### ISSUE THREAD

**Issue by Pusnow** [notable/notable#838]
- macOS 10.14.6
- 1.7.3

### Current behavior

Notable Helper consumes too much CPU cycles and battery when it is in idle state. (8% ~ 10%)

<img width="815" alt="스크린샷 2019-09-25 오후 7 45 37" src="https://user-images.githubusercontent.com/6031017/65594243-56db1980-dfcd-11e9-9e54-2f875b66f4a3.png">

### Expected behavior

Chrome uses under 1% CPU when it is at idle (single tab, google.com).
Notable should be similar to this.

<img width="815" alt="스크린샷 2019-09-25 오후 7 49 05" src="https://user-images.githubusercontent.com/6031017/65594365-8ee25c80-dfcd-11e9-9b2c-2a05e650bf60.png">

**Comment by fabiospampinato** [comment]
Does it stay at 8% forever for you?

I've just checked this and for me when idle its CPU utilization goes to almost zero constantly, which occasional spikes to 0.8% or more.

<img width="864" alt="Screen Shot 2019-09-25 at 14 21 47" src="https://user-images.githubusercontent.com/1812093/65600175-ef5aa500-df9f-11e9-8840-2a7ae0c6e0df.png">

**Comment by Pusnow** [comment]
Yes, it stays around 8% ~ 10%.
It seems the number of notes affects CPU usage.

0 notes : 1.2%
my database (173 notes, 509KB, 113 attachments): 8%

**Comment by Pusnow** [comment]
10.000 notes consumes 150% of CPU.

I think it should be related to #837 and file watcher issues.

**Comment by fabiospampinato** [comment]
I can't reproduce, with about ~2k notes nothing changes for me.

Can you record a performance profile for me so that I can see what the app is actually doing?

<img width="864" alt="Screen Shot 2019-09-25 at 18 13 54" src="https://user-images.githubusercontent.com/1812093/65619468-7b7cc480-dfc0-11e9-9a3c-e2d564de01bd.png">

**Comment by Pusnow** [comment]
Profile json:
[Profile-20190926T132403.zip](https://github.com/notable/notable/files/3655876/Profile-20190926T132403.zip)

Screenshot:
<img width="1390" alt="스크린샷 2019-09-26 오후 1 25 42" src="https://user-images.githubusercontent.com/6031017/65658145-6d32b500-e061-11e9-8119-970f560045f8.png">

**Comment by fabiospampinato** [comment]
I don't see much going on other than tons of anonymous functions gettin called, which I'm not sure what they are about, was that a recording after a fresh start of the app?

**Comment by fabiospampinato** [comment]
Also did you have 10k notes in the app? Perhaps repeating the recording in that condition may better show the issue here. As far as I can see the app stayed idle for the vast majority of the time.

**Comment by fabiospampinato** [comment]
Also did you have 10k notes in the app? Perhaps repeating the recording in that condition may better show the issue here. As far as I can see the app stayed idle for the vast majority of the time.

**Comment by Pusnow** [comment]
With 10K notes.

Profile.json:

[Profile-20190927T102558.zip](https://github.com/notable/notable/files/3660475/Profile-20190927T102558.zip)

Screenshot: 

<img width="1026" alt="스크린샷 2019-09-27 오전 10 25 51" src="https://user-images.githubusercontent.com/6031017/65735208-5d72a980-e111-11e9-9cc3-0d25825e5074.png">

**Comment by fabiospampinato** [comment]
These many anonymous functions getting called seem to be the issue, I'll give this a closer look, thanks 👍

**Comment by BaldEagleX02** [comment]
18 notes: 2.2% CPU
1389 notes: ~15% CPU

**Comment by BaldEagleX02** [comment]
It seems that Notable is having difficulty in looking for file modifications if we have a lot of notes.

**Comment by fabiospampinato** [comment]
@BaldEagleX02 what OS are you on?

**Comment by BaldEagleX02** [comment]
macOS 10.14.6

**Comment by dbuskariol** [comment]
I'm running macOS 10.15.1 and `Notable Helper (Renderer)` sits at ~30-50% CPU usage at idle. I have 609 notes. Any update on this issue?

**Comment by fabiospampinato** [comment]
@dbuskariol I haven't found the cause of this yet, mostly because I'm unable to reproduce it.

**Comment by dbuskariol** [comment]
@fabiospampinato if there’s anything I can do to help please let me know. Notable Renderer is always sitting at high CPU for me.

**Comment by fabiospampinato** [comment]
@dbuskariol how many notes do you have? Are they stored locally or in a network-attached device? Can you reproduce the issue by switching to a new data directory that contains only the tutorial notes in it? (you can import them back in from `Help -> Tutorial`)

**Comment by dbuskariol** [comment]
@fabiospampinato notes are stored locally on my rMBP SSD. This directory contains only notes and is at `~/.notable`. I've changed the data directory and imported tutorial notes and will monitor and update here when I know if it's reduced CPU.

**Comment by RqC4X10o** [comment]
Just fyi, I tried to reproduce this on my Linux machine (Ubuntu 18.04) with no success. CPU is 0% at idle.

**Comment by fabiospampinato** [comment]
@RqC4X10o how many notes do you have?

**Comment by RqC4X10o** [comment]
@fabiospampinato 10.

**Comment by yatahonga** [comment]
- macOS 10.15.2
- Notable 1.8.2

Same issue here: 2,000 notes with about 1,500 attachments all in a Notable directory synchronised with OneDrive (on a local SSD drive) and the CPU for the Notable Helper (Renderer) process stays around **40%**.

As a point of comparison, [nValt](https://brettterpstra.com/projects/nvalt/) with the exact same set of notes and attachments duplicated in its own directory on the same drive (with the same OneDrive sync in the background) consumes 0.1% at most.

**Comment by fabiospampinato** [comment]
I'm now taking a closer look at this again. My current line of thought is: 

1. The app does some work in the background
2. The only work that it should be doing in the background is watching files for changes
3. It should watch files via performant native calls, hence the CPU utilization should be very low
4. Since the CPU utilization isn't very low maybe it is resorting to polling instead, and forcing polling on manually seems to make me be able to reproduce this very clearly
5. The problem seems to only happen on macOS, which is the only platform which requires a particular NPM module to be loaded for file watching to work efficiently
6. Hypothesis: maybe for some reason this NPM module we need, `fsevents`, isn't getting bundled or loaded properly on production, as I can't reproduce this during development

Hopefully I'm on the right track here and the problem will be resolved quickly.

**Comment by fabiospampinato** [comment]
I seem to be on the right track, during development everything works, but after bundling the app for production it starts to consume lots of CPU in background.

**Comment by fabiospampinato** [comment]
Super weird, if I sign the `dmg` then the app has this background CPU utilization issue, otherwise it doesn't.

I'll dig deeper on this tomorrow, hopefully somebody else already stumbled on this and there's an easy solution.

**Comment by fabiospampinato** [comment]
I just fixed this, it was indeed an issue with `fsevents` not getting loaded in signed builds.

Before background usage with a 3816 notes data directory:

![before](https://user-images.githubusercontent.com/1812093/72266612-a2fea800-3616-11ea-92d1-e37998b6960a.gif)

After background usage with a 3816 notes data directory:

![after](https://user-images.githubusercontent.com/1812093/72266619-a8f48900-3616-11ea-9b13-f751ef09619c.gif)
