### ISSUE TITLE
Update #4 - Moving updates to our subreddit

### ISSUE THREAD

**Issue by fabiospampinato** [notable/notable#844]
Hello everyone 👋

In the past I've published a few [updates](https://github.com/notable/notable/issues?q=label%3Aannouncement+is%3Aclosed+sort%3Acreated-asc) about Notable's progress and roadmap here on GitHub, but future updates will be published under our subreddit instead: [/r/Notable](https://www.reddit.com/r/Notable). 

In case you missed it, the last update I published there is available [here](https://www.reddit.com/r/Notable/comments/d7yzjn/notablemd_various_updates/).

I'd invite everyone reading this to join the subreddit, that's where general day-to-day discussion happens.

GitHub will remain our issue tracker.

**Comment by ajit555db** [comment]
So any feature request/enhancements need to be posted to subreddit but any errors/issues need to be posted to GitHub issues?

**Comment by fabiospampinato** [comment]
GitHub "issues" is a bit of a misnomer, we'll track [enhancements](https://github.com/notable/notable/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Aenhancement) here too.
