### ISSUE TITLE
Add support for custom metadata

### ISSUE THREAD

**Issue by JakeI** [notable/notable#850]
### Feature description
Support adding custom YAML code to the .md files metadata in the front matter. 

### Current behavior
From within Notable you don't have access to the front matter YAML meta data. If you use a 3rd party editor to add YAML to the front matter and than go back to editing the file in Notable all changes are overwritten.

### Feature motivation
One of the key features of Notable is that notes are not looked away in some database but exist as simple files ready to be processed by 3rd party tools. Many tools processing markdown use this metadata. e.g. [pandoc](https://pandoc.org/) and [caddy](https://caddyserver.com/docs/markdown#front-matter-document-metadata) configure templates through front matter entries. This ranges from a simple `author: John Miller` to `include: [myDependencyList, ...]`

### Problem with the `title` meta data
The YAML top level keyword `title` is used a lot in pandoc, caddy, etc. Notable sets this automatically to the filename/first `h1` heading in the document. But users may want to define a separate document title that gets parsed by 3rd party tools so it might be nicer if Notable didn't use that keyword already.

**Comment by fabiospampinato** [comment]
Let's track this here: #67 

> go back to editing the file in Notable all changes are overwritten.

We probably shouldn't do that.

> But users may want to define a separate document title that gets parsed by 3rd party tools so it might be nicer if Notable didn't use that keyword already.

I haven't implemented this yet, but I imagine in the future overriding the inferred title string will make the app output a "title_custom: true" metadata field or something, telling the app to not override that title.
