### ISSUE TITLE
Will releases still happen on Github?

### ISSUE THREAD

**Issue by patrickf3139** [notable/notable#854]
For those of us who watch Notable's GitHub releases, it's nice to be able to subscribe to new releases as they come in without having to monitor Reddit ourselves. I was wondering if you'd still upload the binaries as releases in this repo (though the source code is no longer here) so we can get notified of releases automatically? Just a thought. Totally understand if it's a big hassle for you!

**Comment by fabiospampinato** [comment]
Yes, actually the uploader is querying GitHub's releases when checking for updates, so actually moving them elsewhere would be a hassle, plus GitHub's infrastructure is quite stable and serves our packages pretty quickly too.
