### ISSUE TITLE
Clicking on a tag wont open in the collapsed tag tree

### ISSUE THREAD

**Issue by Armagedoom** [notable/notable#856]
- **OS Version**: Ubuntu
- **Notable Version**: Latest

### Current behavior

Clicking a tag listed after clicking on the tag icon should open the collapsed tag tree and show you the clicked tag. Instead, notable does nothing.

![image](https://user-images.githubusercontent.com/4046326/66370549-fa023a80-e9a0-11e9-9a5b-0d6e86f27c36.png) <- Tag icon I'm referring to.

### Expected behavior

Notable should expand the tag tree to show the tag that was selected using the tag icon.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
