### ISSUE TITLE
Links using [](C:\folder\file.md) format method fail to open

### ISSUE THREAD

**Issue by jhconning** [notable/notable#859]
- **OS Version**: Windows 10
- **Notable Version**: 1.7.3

### Current behavior

Links to folders, files and notes using the following `method 1` format open correctly in both Notable and Typora: 
```
[method 1 link to folder](file://G:/Code)
[method 1 link to pdf file](file://G:/Code/sample.pdf)
[method 1 link to md file](file://G:/Code/README.md)
```
(`G:` here is a mapped drive but this could have been 'C:\`)

However when the links are formed using the following `method 2' format they still open fine in Typora but they fail to open in Notable:
```
[method 2 folder link](G:\Code)
[method 2 link to file](G:\Code\sample.pdf)
[method 2 link to md file](G:\Code\README.md)
```
In Notable they lead to a pop up error message "You will need another app to open this ...' (see screenshot)
![image](https://user-images.githubusercontent.com/5048607/66702848-1d4b2380-ecda-11e9-8069-b4501814a0cc.png)

### Expected behavior

Notable ought to be able to open up links using either method, but fails at method 2.

Method 2 is **much preferable** for many use cases. Why? Because to one needs to only Shift-right-click on a file or folder in File Explorer, choose 'Copy as path', and then paste that link into the note for it to work.   In order to convert that pasted link into `file://...` format adds a time consuming and error-prone step.   

Is this a bug, a feature, or a configuration problem on my end?  

Thanks!

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
