### ISSUE TITLE
Support all language aliases supported by Prism

### ISSUE THREAD

**Issue by fabiospampinato** [notable/notable#860]
@sillykelvin wrote:

> Thanks for this great app, it's my main note-taking app now! However, there is a little question: if I tag a code snippet with C++, the syntax highlighting does work, but it works if I tag it with cpp or CPP. And I think C++ is a valid code type word, it works for GitHub, VSCode and Typora. Is it intended in Notable, or is it a bug?

**Comment by fabiospampinato** [comment]
We recently changed syntax highlighter so some previously supported language names might have get lost along the way, I'll try to add this and the other ones back 👍

**Comment by sillykelvin** [comment]
Wow, thanks for your quick reply, and I'm looking forward to a new version for this and other awesome features!

**Comment by WilsonCWong** [comment]
@fabiospampinato Is PHP one of the ones that got lost? I noticed the syntax highlighting isn't working while I was taking my Laravel notes. 😅

**Comment by fabiospampinato** [comment]
@WilsonCWong PHP should still be supported, can you post a sample code block that doesn't get highlighted properly?

**Comment by WilsonCWong** [comment]
@fabiospampinato This is the snippet I have in my notes:
```php
public function index() {
    $projects = Project::all();

    return view('projects.index', compact('projects'));
}
```

**Comment by fabiospampinato** [comment]
@WilsonCWong I can reproduce, I'll take care of that too 👍

**Comment by WilsonCWong** [comment]
@fabiospampinato Thank you! 😄

**Comment by fabiospampinato** [comment]
An update on this:

- @sillykelvin `c++` is not properly recognized as a language name.
- @WilsonCWong your issue is kind of different, the snippet you posted technically isn't PHP because the initial `<?php` thing is missing. Now obviously the snippet should get highlighted regardless, but this is an issue with the language definition we are using, I've opened an upstream issue about this: https://github.com/microsoft/monaco-editor/issues/1658
- I'm keeping this issue open as there are probably more language aliases to support.

**Comment by sillykelvin** [comment]
Glad to hear that it's fixed, is there any plan to publish a new version with theses fixes?

**Comment by fabiospampinato** [comment]
I've just added support for lots more aliases.

@WilsonCWong I'd say let's track your issue [here](https://github.com/microsoft/monaco-editor/issues/1658), if they don't want to fix it I'll see what I can do.

**Comment by fabiospampinato** [comment]
@WilsonCWong Now PHP is highlighted slightly differently, sort of making the `<?php` token optional, it's not perfect but I think it's an improvement for our use case:

<img width="914" alt="Screen Shot 2020-01-09 at 21 30 47" src="https://user-images.githubusercontent.com/1812093/72106531-78b39e80-3327-11ea-81b4-debd9a5f860c.png">
