### ISSUE TITLE
Another request regarding pasting image in Notable Note

### ISSUE THREAD

**Issue by BobMilli** [notable/notable#867]
### Feature description
The fact that we have now the date and time of the screen copy is already a great thing but it will be even better IMHO if the file name of the attachment could start with the Note name instead of Clipboard...

**Comment by fabiospampinato** [comment]
The thing is what should happen if you add the same attachments to two notes at the same time?

**Comment by BobMilli** [comment]
This case shouldn't arrive quite often as you've got a timestamp with the seconds in it and in the clipboard you could only have a single image at a time.
Don't you agree ?

**Comment by fabiospampinato** [comment]
It won't be likely to happen, especially when adding attachments via copy/paste, but if it happens what do we do? 🤷‍♀️ Plus we would have to rename attachments whenever the notes they are attached to get renamed, which sounds quite messy to me.

I think the root issue here is being able to find the attachment you're looking for more quickly?

**Comment by BobMilli** [comment]
Ok, I get your point. It's the attachments folder which seems quite messy to me. 
It doesn't have any impact on Notable usage itself, it's more, as you mentioned, if I need to find a specific attachment, I need to go through 102 Clipboard_*.png files which are in the middle of 168 attachments. 
It's not that important as it's still manageable.

**Comment by fabiospampinato** [comment]
Let's track part of this here: #54, as this might get solved that way.

Also we may implement better tools for handling attachments within the app, that could probably solve this issue too.

**Comment by fabiospampinato** [comment]
> Also we may implement better tools for handling attachments within the app, that could probably solve this issue too.

#869
