### ISSUE TITLE
Cant get menu bar on Mac

### ISSUE THREAD

**Issue by drskuce** [notable/notable#872]
- **Mac mojave**:
- **cannot see version but It was downloaded today**:

### Current behavior

when N opens on Mac there is no menu bar.  there is on PC
when I try the shortcut it does not work.   
I cannot work without a menu bar
hard to see how this has not been fixed
also I cannot resize the window

**Comment by fabiospampinato** [comment]
Are you new to macOS?

Apps on macOS generally have no local menubar, they use the global menu bar.
