### ISSUE TITLE
Portable version not really portable

### ISSUE THREAD

**Issue by teamayu** [notable/notable#874]
Hi,

Really nice software btw. Very clean :)

My question is about the portable version. I`ve downloaded it and ran it, but under 'AppData/Roaming' I see a whole load of files/folders.

![screenshot-25-10-2019_141958](https://user-images.githubusercontent.com/10624092/67547793-a29af300-f732-11e9-810f-4c9bda3edbdf.png)

So, not really portable?

**Comment by fabiospampinato** [comment]
> So, not really portable?

🤔 Yeah I guess so. Those files are created by Electron, I'm not sure how we could get rid of them. 

If you have a suggestion for what we should rename the "Portable" bundle to I'm all ears.

**Comment by teamayu** [comment]
I would at least add a note about the appData files. For me, I'll have to find something else.

**Comment by AldieNightStar** [comment]
> Hi,
> 
> Really nice software btw. Very clean :)
> 
> My question is about the portable version. I`ve downloaded it and ran it, but under 'AppData/Roaming' I see a whole load of files/folders.
> 
> ![screenshot-25-10-2019_141958](https://user-images.githubusercontent.com/10624092/67547793-a29af300-f732-11e9-810f-4c9bda3edbdf.png)
> 
> So, not really portable?

I guess it still remains portable, but Electron just leave some files in Roaming folder. You see, Electron works as a Chrome browser itself. So it in some case it emulates the whole environment to make Front work as well as we expect from HTML + JS (Node-Backend).
I'm not sure, but i guess all the settings (Which is Notable settings) still remains in the App Folder. So even if you will put App on a USB stick, and plug in to the another pc/mac - it will work as it was on prev machine. But with one minus -> in Roaming folder will be some files from Electron.

Notable is really cool. And i guess some small Garbage files in Roaming don't make it bad. Just some minus. Nothing more

**Comment by fabiospampinato** [comment]
> I'm not sure, but i guess all the settings (Which is Notable settings) still remains in the App Folder. So even if you will put App on a USB stick, and plug in to the another pc/mac - it will work as it was on prev machine. But with one minus -> in Roaming folder will be some files from Electron.

The app currently also creates a file at `~/.notable.json`, it's possible to make it work without this file, but I'm not sure it's worth the effort especially considering that there would still be those Electron-related files laying around 🤔

**Comment by retsuyama** [comment]
You maybe want to check [milolav](https://gist.github.com/milolav) [guide](https://gist.github.com/milolav/f7a12285761db9726bce2aff11adb3af). This how i make most of apps that using electron become portable.

**Comment by fabiospampinato** [comment]
Let's track this here: #233
