### ISSUE TITLE
Register a "notable" protocol for cross-app linking

### ISSUE THREAD

**Issue by fabiospampinato** [notable/notable#876]
Being able to link to notes from outside Notable, and being able to execute some actions outside of the app will open some very interesting possibility.

Basically we should do what Bear is doing: https://bear.app/faq/X-callback-url%20Scheme%20documentation/

**Comment by CavalloneChen** [comment]
Will this protocol be restricted to apple platform?

**Comment by fabiospampinato** [comment]
@CavalloneChen No, and I think you might not even need to have the desktop app installed, it may work when using the future webapp as well.

**Comment by fabiospampinato** [comment]
Done: https://www.reddit.com/r/Notable/comments/fcw7ii/preview_command_palette_macro_command_links_to/
