### ISSUE TITLE
Confusing message after editing a note using an external editor

### ISSUE THREAD

**Issue by childerico** [notable/notable#877]
### Current behavior

After editing a note using an external editor, Notable detects the changes on disk and asks the user whether to "Keep Changes"  or "Overwrite the changes". 
As a new user, I find these options ambiguous, as it is not clear *which* changes we are talking about (either the external changes or those made in the built-in editor).

### Expected behavior

The displayed message should be written in terms of "external changes" (or something similar).

**Comment by fabiospampinato** [comment]
I agree, what exact wording do you think we should use? 🤔

**Comment by childerico** [comment]
In my opinion this could be a solution:  "Ignore external changes" (which is now "Keep changes") and "Reload from disk" (which is now "Overwrite changes").

**Comment by fabiospampinato** [comment]
Done, now it says:

```
This note changed on disk, do you want to ignore the changes or reload the note from disk?
Ignore disk changes                Reload note from disk
```

That should be a lot clearer, thanks.
