### ISSUE TITLE
Error in classDiagram mermaid

### ISSUE THREAD

**Issue by jfneto** [notable/notable#881]
- **Windows Server 2012**:
- **1.7.3**:

### Current behavior

```mermaid
classDiagram
Class01 <|-- AveryLongClass : Cool
Class03 *-- Class04
Class05 o-- Class06
Class07 .. Class08
Class09 --> C2 : Where am i?
Class09 --* C3
Class09 --|> Class07
Class07 : equals()
Class07 : Object[] elementData
Class01 : size()
Class01 : int chimp
Class01 : int gorilla
Class08 <--> C2: Cool label
```

[mermaid error: Parse error on line 15: ...<--> C2: Cool label ----------------------^ Expecting 'CLASS', 'MEMBER', 'SEPARATOR', 'UNICODE_TEXT', 'NUM', 'ALPHA', got 'EOF']

**Comment by fabiospampinato** [comment]
I can't reproduce, I see this:

<img width="726" alt="Screen Shot 2019-11-08 at 21 49 22" src="https://user-images.githubusercontent.com/1812093/68512937-a752c180-0271-11ea-8bc7-f11d4fc000e7.png">

Could you post an actual note that reproduces the issue for you?

**Comment by fabiospampinato** [comment]
Here's a test note that I _can't_ reproduce the problem with: 

````
```mermaid
classDiagram
Class01 <|-- AveryLongClass : Cool
Class03 *-- Class04
Class05 o-- Class06
Class07 .. Class08
Class09 --> C2 : Where am i?
Class09 --* C3
Class09 --|> Class07
Class07 : equals()
Class07 : Object[] elementData
Class01 : size()
Class01 : int chimp
Class01 : int gorilla
Class08 <--> C2: Cool label
```
````

Maybe we updated mermaid to a version that fixed your problem.

If anybody has a note that reproduce the issue I'd be happy to reopen this.
