### ISSUE TITLE
Notes Untagged after install version 1.8

### ISSUE THREAD

**Issue by energetic-it** [notable/notable#884]
- **OS Version**: Win10 1903 x64
- **Notable Version**: 1.8.0

### Current behavior

After installing the new version, about 11 notes were untagged / unpinned. Also the information in the note is not correct, showing only a portion of it (in Notable)

Using VS Code, the note looks normal and has no issues. After changing something in the note using VS Code and saving it, does not resolve the issue. Copying the text back in Notable and then saving it works.

### Expected behavior

After installing a new version of Notable my Notes are still tagged and showing all the information

**Comment by energetic-it** [comment]
Update: 

it seems every time I close Notable and reopen it, there is another Note that is untagged again.
Sometimes it is the same Note I just 'fixed', sometimes it's one that was edited today. There is something wrong, unsure what it could be.

My Notes have 
- Horizontal lines
- checked boxes
- Links

Nothing fancy

**Comment by Vinayak-kadu** [comment]
same behaviour here also, i will try the horizontal line trick

**Comment by energetic-it** [comment]
What I did was open it in another editor and copy everything back. 
And indeed, always have a backup.

**Comment by Vinayak-kadu** [comment]
> What I did was open it in another editor and copy everything back.
> And indeed, always have a backup.

i have to us vscode for search function every time, so i had it in open and managed to save it again but yes this is costly mishap, now might again have to search for new app..

**Comment by fabiospampinato** [comment]
Could you guys post a note that reproduces the problem?

**Comment by fabiospampinato** [comment]
I think I know what might be wrong here, I should hope to push a patch release about this soon 👍

**Comment by energetic-it** [comment]
> Could you guys post a note that reproduces the problem?

If you still need this, let me know.

**Comment by fabiospampinato** [comment]
@energetic-it Yeah that'd be useful to have, thanks.

**Comment by energetic-it** [comment]
> @energetic-it Yeah that'd be useful to have, thanks.

I'll do that tomorrow morning

**Comment by energetic-it** [comment]
Here is one note that does not show all the content, and is untagged.
Hope it helps.

[error_Git Tips.zip](https://github.com/notable/notable/files/3827071/error_Git.Tips.zip)

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
