### ISSUE TITLE
Same page anchor links stopped working in Notable v1.8.0 (Windows 10)

### ISSUE THREAD

**Issue by Anzan** [notable/notable#887]
- **Windows 10**:
- **1.8.0**:

### Current behavior

Same page anchor links stopped working for me with Notable v1.8.0 (Windows 10), it worked fine prior to this new version. When I click on a link, now it simply doesn't do anything. This is a very valuable feature for lengthy documents.

### Expected behavior

Clicking on the following same page anchor links:

```
* [1. Overview](#1-overview)
* [2. Files](#2-files)
```

should send me to corresponding titles in the page.

```
## 1. Overview

blah blah blah

## 2. Files

blah blah blah
```

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.

**Comment by Anzan** [comment]
1.8.1 fixed it for me, thanks.
