### ISSUE TITLE
Double backticks break code syntax highlighting in editor

### ISSUE THREAD

**Issue by JayZ2398** [notable/notable#888]
- **OS Version**: Ubuntu 18.04.3 LTS
- **Notable Version**: 1.7.3

### Current behavior

Creating inline code blocks with double backticks (i.e. to escape single backticks in the code block) results in the block not being highlighted correctly.

1. Paste this into Notable: 
```
``filter (\x -> x `mod` 2 == 0) list``
```
2. Get this.

![image](https://user-images.githubusercontent.com/28042291/68451081-76f32f00-0241-11ea-90c4-74ffb62b47ec.png)

### Expected behavior

Code should be highlighted correctly for single, double and triple backticked code blocks.

**Comment by fabiospampinato** [comment]
This is the first time I hear about double-backticks code blocks. This may be an issue with CommonMark, my guess is that they don't support this so we aren't either.

**Comment by JayZ2398** [comment]
This was where I found it.

https://stackoverflow.com/a/25943045

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.

I also fixed syntax highlighting for inline code wrapped in 3+ backticks.
