### ISSUE TITLE
"highlighter error" in some Cheatsheet sections

### ISSUE THREAD

**Issue by bar2cha** [notable/notable#889]
- **OS Version**: MacOS 10.15.1
- **Notable Version**: 1.8.0

### Current behavior
Markdown Cheatsheet error in section Code, Table, Separator...
Error: [highlighter error: this._embeddedModes.hasOwnProperty is not a function]

**Comment by fabiospampinato** [comment]
This might be an upstream issue 🤔

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.

This is an upstream issue though: https://github.com/microsoft/vscode/issues/84394
