### ISSUE TITLE
Horizontal rule breaks notes

### ISSUE THREAD

**Issue by vallentin** [notable/notable#891]
- **OS Version**: Windows 10
- **Notable Version**: 1.8.0

### Current behavior

1. Create a new note
2. Write something that contains three dashes (hr rule)
    ```markdown
    # Test

    Section 1

    ---

    Section 2

    ---

    Section 3
    ```
3. Save and the note is rendered as expected
4. Then close and reopen Notable, and the note is broken

The content isn't deleted upfront, however editing the note does end up deleting the "hidden" content.

*I assume it's the YAML front matter parser that gets confused due to the 3 dashes.*

### Expected behavior

That they load correctly.

### Temporary Solution

Using more than 3 dashes seem to work.

### Screenshots

<table>
<tr>
<td>1. Create a new note containing a horizontal rule of 3 dashes</td>
<td>2. Save and it's rendered correctly</td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/17464404/68514759-efc4ac00-027e-11ea-8bf4-23db7e0ba329.png"></td>
<td><img src="https://user-images.githubusercontent.com/17464404/68514766-f3583300-027e-11ea-9684-5074565004e4.png"></td>
</tr>
<tr>
<td>3. Close and reopen Notable and it's rendered incorrectly</td>
<td>4. Press edit it and it's still incorrect<td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/17464404/68514770-f6532380-027e-11ea-83be-7d0d520bbf77.png"></td>
<td><img src="https://user-images.githubusercontent.com/17464404/68514775-f8b57d80-027e-11ea-8ed5-153bb8bd8248.png"></td>
</tr>
<tr>
<td>5. Opening in VSCode shows the content isn't deleted</td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/17464404/68514779-fa7f4100-027e-11ea-9c19-93c97b741e7b.png"></td>
</tr>
</table>

**Comment by fabiospampinato** [comment]
@vallentin Could you post a note that reproduces the issue for you?

**Comment by vallentin** [comment]
This happens to any note I create. However the issue only "appears" after closing and reopening Notable.

Here: [Test.zip](https://github.com/notable/notable/files/3826580/Test.zip)

This is how it looks for me. I can't see the "This is hidden".

![note](https://user-images.githubusercontent.com/17464404/68516289-d96d1f00-0283-11ea-81cd-c862c3024ca8.png)

**Comment by fabiospampinato** [comment]
I can totally reproduce. This seems the most severe issue introduced in this release, expect a patch release soon.

**Comment by vallentin** [comment]
Thanks! I really like Notable.

I just finished moving a bunch of notes, and half of them ended up "Untagged" and content missing, so I got really scared. So I'll use 5 dashes as a solution for now.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
