### ISSUE TITLE
Error report: Loading chunk 0 failed.(error: file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/chunk.8b07b121c6ebf7443097.js)

### ISSUE THREAD

**Issue by avanavana** [notable/notable#893]
I just restarted to install the latest update, and now the vast majority of my notes are showing 'loading chunk 0 failed', and causing Notable to crash.

- **OS Version**: darwin 10.14.6
- **Notable Version**: v1.8.0

```
Error: Loading chunk 0 failed.
(error: file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/chunk.8b07b121c6ebf7443097.js)
    at HTMLScriptElement.onScriptComplete (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.js:2:3922)
```

**Comment by avanavana** [comment]
Note: I restarted again and it seems to be working, but I think you should be aware this happened at least.

**Comment by fabiospampinato** [comment]
This is the second time a similar error has been reported, it looks like something outside of my control but maybe I can do something about it 🤔

**Comment by fabiospampinato** [comment]
Let's track this here: #890
