### ISSUE TITLE
Bug that shows double quotes as single quotes when using code blocks

### ISSUE THREAD

**Issue by danielvelara** [notable/notable#896]
When using code blocks (triple ticks) and typing double quotes(""), it displays as single quotes (''). This didn't happen on older versions (<1.8.1)

**Code example**
```java
"Hello World"
```

![image](https://i.ibb.co/BLgB0vm/image.png)

**Issue: It shows like this:**
`'Hello World'`

![image](https://i.ibb.co/KG0hJJV/image.png)

- **OS Version**: MacOS High Sierra
- **Notable Version**: 1.8.1

**Comment by fabiospampinato** [comment]
I noticed it as well, it's most probably an upstream issue, I'll have to check if they are tracking this already.

**Comment by jaegdi** [comment]
I noticed this also as well in any kind of block, when i define a syntax (like txt or java or bash) to the block.
Wihout a syntax the doublequotes are not converted to single quotes

**Comment by AldieNightStar** [comment]
Yup. This is horrible bug. :(

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
