### ISSUE TITLE
Tutorial link

### ISSUE THREAD

**Issue by alexriabtsev** [notable/notable#900]
- **OS Version**:
- **Notable Version**:
macOS, 1.8.1

### Current behavior
404 error if launching online tutorial. 
https://github.com/notable/notable/tree/v1.8.1/resources/tutorial/notes

Help -> Tutorial -> Online tutorial

### Expected behavior
Online tutorial should be opened.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
