### ISSUE TITLE
Markdown Cheatsheet shows JS-Error-Messages instead of source-examples.

### ISSUE THREAD

**Issue by alex224** [notable/notable#902]
- **OS Version**:
Windows 10

- **Notable Version**:
1.8.1

### Current behavior
The Markdown Cheatsheet shows for some categories e.g. "Code", "Table", "Separator" an Javascript error message instead of the markdown source example.
The shown text is: "[highlighter error: this._embeddedModes.hasOwnProperty is not a function]"

### Expected behavior
Like in the other categories e.g. "Quotation" the correct samples should be shown.

**Comment by fabiospampinato** [comment]
I must have updated the dependency I had patched to fix this issue.

**Comment by fabiospampinato** [comment]
Fixed again, let's hope they'll fix the upstream bug soon, because I'll probably forget to patch Monaco editor again in the future otherwise.

https://github.com/microsoft/vscode/issues/84394

**Comment by dtjm** [comment]
Is there a way to get a build of Notable that includes this fix? Thank you.

**Comment by fabiospampinato** [comment]
No, but I plan to make a release relatively soon. It's just that I've recently moved to London and like looking for a more permanent accommodation is turning out to be a much bigger hassle than I expected.

**Comment by dtjm** [comment]
Ok thank you! Good luck with the moving.  I'm loving Notable so far, after having tried so many different apps.  Especially the Mermaid rendering.
