### ISSUE TITLE
cheatsheet is broken

### ISSUE THREAD

**Issue by StefanoCecere** [notable/notable#904]
- **OS Version**: Mojave
- **Notable Version**: 1.8.1

### Current behavior

from Code section we can't see the syntax, but this error
```
[highlighter error: this._embeddedModes.hasOwnProperty is not a function]
```

<img width="634" alt="Screenshot 2019-11-13 at 06 09 32" src="https://user-images.githubusercontent.com/640536/68734893-3cd8b300-05dc-11ea-8ab3-f59fd0432adb.png">

**Comment by fabiospampinato** [comment]
Let's track it here: https://github.com/notable/notable/issues/902
