### ISSUE TITLE
Rendering vectors in title does not work

### ISSUE THREAD

**Issue by thisfro** [notable/notable#906]
- **OS Version**: MacOS 10.14.4
- **Notable Version**: 1.8.1

### Current behavior
`## The $\vec{E}$-Field`
renders as
<img width="597" alt="Screenshot 2019-11-13 at 18 04 00" src="https://user-images.githubusercontent.com/9142702/68786385-fd43b280-063f-11ea-9038-1d33e675b31d.png">
)

### Expected behavior
Rendering correctly as an E with an arrow on top.

## Notes
As normal text it works just fine.
Also other stuff like `\bar{E}` works as expected.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
