### ISSUE TITLE
Support auto linked urls containing underscores

### ISSUE THREAD

**Issue by vallentin** [notable/notable#909]
- **OS Version**: Windows 10
- **Notable Version**: 1.8.1

### Current behavior

Some auto linked URLs that contains underscores next slashes are italicized.

```
**Correct:**

- http://example.com/foo/bar/baz
- http://example.com/_foo/_bar/baz
- http://example.com/f_oo/ba_r/baz
- http://example.com/f_o_o/b_a_r/baz

**Incorrect:**

- http://example.com/_foo_/bar/baz
- http://example.com/_foo/bar_/baz
- http://example.com/_foo/bar/baz_
```

![autolink](https://user-images.githubusercontent.com/17464404/68860093-13597d80-06e9-11ea-844a-28112f722f5e.png)

### Expected behavior

URLs containing underscores to be correctly auto linked.

**Comment by fabiospampinato** [comment]
This seems an upstream bug: https://github.com/markdown-it/linkify-it/issues/80

**Comment by fabiospampinato** [comment]
And they have no intention to fix this for some reason: https://github.com/markdown-it/linkify-it/issues/80#issuecomment-553894852 🤷‍♂️

**Comment by fabiospampinato** [comment]
I've learned more about this issue, and as I'm understanding it this can't be fixed properly without moving the auto-linking logic into the parser itself, which other than being a significant change in and of itself it will also come with a big performance penalty, so this issue may never get properly fixed.

There are 2 possible simple workarounds though:

- Escape your underscores: `http://example.com/\_foo\_`
- Wrap your links in angle brackets: `<http://example.com/_foo_>`

**Comment by vallentin** [comment]
Personally, those workarounds are fine with me.

However, it would probably be nice to add as a side note, in one of the tutorials notes.

**Comment by fabiospampinato** [comment]
> However, it would probably be nice to add as a side note, in one of the tutorials notes.

I'm mentioning urls wrapped in angle brackets in the cheatsheet now. I should probably mention escaping as well 🤔 

I'm closing this as I labeled it as "wontfix".
