### ISSUE TITLE
Make tutorial directory OSS again

### ISSUE THREAD

**Issue by tallpants** [notable/notable#910]
### Feature description
Make the tutorial directory open source again -- [this directory specifically](https://github.com/notable/notable/tree/v1.7.3/resources/tutorial).

### Feature motivation
Right now if you delete the tutorial the first time you open Notable there's no way to see it again without going to GitHub and checking out the older releases, and it's also not hosted anywhere afaik.

**Comment by fabiospampinato** [comment]
It's hosted right within the app, just click: "Help -> Tutorial" and then you can re-import them in. I'll fix the missing online version for the current version of the app, let's track that here: https://github.com/notable/notable/issues/900
