### ISSUE TITLE
Displaying a message if no "notes" directory has been found

### ISSUE THREAD

**Issue by tumluliu** [notable/notable#911]
First time try notable on Linux as an alternative to Quiver app on mac, but got pretty bad experience unfortunately.

- **OS Version**: Ubuntu 18.04
- **Notable Version**: 1.8.1

### Current behavior

I have a dir called `notes` with a bunch of sub-dirs containing `.md` files like this:
```
/home/me/dropbox/notes
|-- work
|  |-- note1.md
|  |-- note2.md
|-- family
|  |-- note3.md
|  |-- note4.md
|-- others
|  |-- note5.md
```
I clicked `Change Data Directory...` and point it to `/home/me/dropbox/notes`, nothing happened. I waited for a while and have no idea what was going on. There was no log or status. And then I tried clicking the `File->Import`, then the UI got stuck like this:

![Selection_069](https://user-images.githubusercontent.com/1563792/68925766-1fdee400-0784-11ea-9467-96f3ce66cce2.png)

### Expected behavior

I don't know what the expected behavior should be by design in such case. Personally, I would expect all my existing markdown files can be loaded into the Notebooks/Notes list so I can open or edit them

**Comment by fabiospampinato** [comment]
@tumluliu Notable is expecting all your notes to be in a "notes" subdirectory of your data directory, so it was looking for notes under `/home/me/dropbox/notes/notes`.

Regarding the app getting stuck I'm not sure I'm understanding you correctly, did the app just freeze upon clicking the "File" menu item?

**Comment by tumluliu** [comment]
Many thanks for the hints! @fabiospampinato . Now I can get the notes shown in Notable. But all the markdown files are basically flattened with all the subdirs getting lost. Is that expected? For my case, it would be great to treat those subdirs as Notebooks while the md files in them as the notes. But I don't know if this is conflict with Notable's idea. 

About the application freezing, yes, it got freezing and then crashed. I met it again just now but could not reproduce unfortunately. Is there any error log file or sth. can be dumped for more details?

**Comment by fabiospampinato** [comment]
> Is that expected?

Yes currently we don't support arbitrary notes structures.

> it would be great to treat those subdirs as Notebooks

There's been some discussion about this here: #54 

> About the application freezing, yes, it got freezing and then crashed. I met it again just now but could not reproduce unfortunately. Is there any error log file or sth. can be dumped for more details?

Not really unfortunately. What package did you install, a `snap`?

**Comment by tumluliu** [comment]
I use the `.deb` package for my case. But also could try with snap. 
As I could not reproduce the issue, this can be closed for now. When I find sth. new, I will update here. 
For the subdir/tag thing, I personally prefer tag than physical dirs. I will write a script to generate the necessary metadata headers for the md files. 
Again, thank you for your fast support! @fabiospampinato

**Comment by tumluliu** [comment]
A follow-up suggestion to the initial Data Directory opening (or changing to.. , not sure the best verb here for this action), it will be much more informative to have a message like:
> We do not find a directory named **notes** under `/home/me/dropbox/notes`. You may need to create it, or change to another location

**Comment by fabiospampinato** [comment]
> A follow-up suggestion to the initial Data Directory opening (or changing to.. , not sure the best verb here for this action) is that, it will be much more informative to have some message like:

Yeah that's a good suggestion. I'll keep this open this track that.

**Comment by fabiospampinato** [comment]
Done, now when switching to an empty data directory the app will tell you:

> No "notes" subdirectory found in this data directory, if this isn't supposed to be a new data directory make sure your notes are stored in a subdirectory named "notes"

**Comment by tumluliu** [comment]
@fabiospampinato as follow-up of the script I mentioned above to add necessary headers to existing md note files to make my dir/subdir structured notes readable by Notable, I have open-sourced it and successfully processed my notes. 
Just for anyone have the same requirements, perhaps this script can help: https://github.com/tumluliu/markdown-notes-tagger

**Comment by fabiospampinato** [comment]
@tumluliu Thanks for sharing, you might want to publish that in our subreddit too: https://www.reddit.com/r/Notable
