### ISSUE TITLE
"The character you entered is forbidden" appears when num-pad 0 is typed in

### ISSUE THREAD

**Issue by WilliamSBunin** [notable/notable#915]
- **Windows**:
- **1.8.1**:

### Current behavior

When I type in 0 using the num-pad into the tag section, I get a message saying "The character you entered is forbidden". If I type in 0 using the top number keys, I get no error.

### Expected behavior

I would expect the num-pad 0 to have the same behavior as a regular 0.

**Comment by fabiospampinato** [comment]
Can you write the number 0 that way inside a note but not inside a tag?

**Comment by WilliamSBunin** [comment]
Yes.
The only time I get the message is if I type 0 in the add tag section.

**Comment by fabiospampinato** [comment]
That's a bug then, as I don't have a numpad I'll see if I can reproduce it with the on-screen keyboard or something.

**Comment by fabiospampinato** [comment]
I think I just fixed this, but I'm not 100% sure as I don't have a real keyboard with a numpad to test this with, so please do let me know in case you still have this problem in v1.8.3 once that's published.

**Comment by WilliamSBunin** [comment]
Fixed! Thank you.
