### ISSUE TITLE
Code Block -> PDF

### ISSUE THREAD

**Issue by elijahjcobb** [notable/notable#919]
OS: MacOS Catalina
Version: 1.8.1

When saving as a PDF, any code blocks over a certain width to not get wrapped and just cut off. I am not sure if this is intentional but if there was an option to wrap when exporting that would be awesome! Also, is there a way to have the export be saved in the folder you select instead of in a nested folder?

Thanks!

**Comment by fabiospampinato** [comment]
Can you post a codeblock that reproduces the problem? Codeblocks are always supposed to wrap when exporting them to PDF, so I'd consider this a bug.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.

I think this might have broke when we switched to Monaco's syntax highlighter.
