### ISSUE TITLE
Change data direcory and F5 produce unexpected results with several application instances

### ISSUE THREAD

**Issue by silmaril42** [notable/notable#924]
- **OS Version**: LinuxMint
- **Notable Version**: 1.8.1

### Current behavior

- Open Notable (data directory `~/notable`)
- Open another instance of Notable (same data directory `~/notable`)
- Change data directory of second instance to `~/notable2`
- Switch to first Notable instance and hit F5
  - Now the first instance shows the contents of `~/notable2` instead of `~/notable`
- In first instance: try to change data directory back to `~/notable`
  - Error message "That is already the current data directory"

### Expected behavior

Each application instance should know it's own data directory, which should be preserved, even when reloading using F5.

**Comment by fabiospampinato** [comment]
Yeah currently the app doesn't really support multiple instances running at the same time, this is an area it should improve on.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
