### ISSUE TITLE
Error report: Couldn't write atomically to unused path - Importing large Evernote Export

### ISSUE THREAD

**Issue by omad** [notable/notable#931]
- **OS Version**: win32 10.0.16299
- **Notable Version**: v1.8.2

```
Error: Couldn't write atomically to unused path
    at end (file:///C:/w10dev/Notable/resources/app.asar/renderer/renderer.js:2:366585)
```

**Comment by fabiospampinato** [comment]
Were you trying to import a large collection of notes?

**Comment by omad** [comment]
Yes, it was 1000+ notes. I tried a couple of times and found some logs, it was the same note each time, but I gave up digging further. If I get time in the next few days I'll try again to get more information.
Thanks

**Comment by fabiospampinato** [comment]
Thanks, no need to gather extra data, I think I know what the problem is here.

**Comment by fabiospampinato** [comment]
@omad I think I fixed this, but I'm not 100% sure, please let me know if once v1.8.3 gets release you can still reproduce.
