### ISSUE TITLE
Find in page by key words

### ISSUE THREAD

**Issue by TheoXiong** [notable/notable#932]
Suggest a new feature: find in page by key words

There is a component that supports this feature

![image](https://user-images.githubusercontent.com/42533484/69839004-c81a9f80-1290-11ea-9c5e-a25773cb0886.png)

![image](https://user-images.githubusercontent.com/42533484/69839011-d4066180-1290-11ea-90ef-7ec29d0c13b6.png)

[https://github.com/TheoXiong/electron-find](https://github.com/TheoXiong/electron-find)

**Comment by fabiospampinato** [comment]
Duplicate of #140
