### ISSUE TITLE
Disable automatic updates!

### ISSUE THREAD

**Issue by cr0ssmind** [notable/notable#935]
### Feature motivation
Guys, this automatic update annoying as hell! It opens 4-5 release notes page when I leave it for night.

### Feature description
I don't want to dig in the code, but I would like to ask, implement a "disable updates" settings in the app pls. Thx!

**Comment by fabiospampinato** [comment]
Duplicate of https://github.com/notable/notable/issues/612.

The release notes page should get opened I think, that's probably the deeper issue, what OS and app package did you install?
