### ISSUE TITLE
Don't add duplicate toasts for new updates

### ISSUE THREAD

**Issue by kyldvs** [notable/notable#937]
### Feature description

When there is a new update you get a toast in the bottom right saying "A new update is ready to install". If you leave the app open for a long time like I do, eventually you get a tall stack of these toasts because they never dismiss. Would it be possible to de-dupe these toasts so that if there is already one with a certain message the exact same toast cannot be added?

### Feature motivation

It looks pretty spammy in the current implementation. The entire UI is filled with the same toast because I leave the app open in the background for several days/weeks without necessarily looking at it.

![Screenshot (20)](https://user-images.githubusercontent.com/1830497/70265505-65714a00-174f-11ea-8198-6808bf095b6c.png)

**Comment by fabiospampinato** [comment]
Sure, I'll take care of that. In the meantime you can just keep the Esc key pressed to dismiss many toasts quickly.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.

Now if there's already one of those toasts visible another one won't be opened.
