### ISSUE TITLE
Code block in list have space on first line

### ISSUE THREAD

**Issue by vallentin** [notable/notable#939]
- **OS Version**: Windows 10
- **Notable Version**: 1.8.2

### Current behavior

If a code block is in a list, then the first line appears to have a space in front of it.

I took a look in the developer tools, and the cause is the `padding: .2em .4em!important;` applied in `.preview li code`. Removing the padding fixes the issue. Though I didn't look beyond, to see if it causes issues elsewhere.

Markdown to reproduce the issue:

    ```python
    print("Test")
    print("Test")
    print("Test")
    ```

    - ```python
      print("Test")
      print("Test")
      print("Test")
      ```
    - 
      ```python
      print("Test")
      print("Test")
      print("Test")
      ```
    - Some text
      ```python
      print("Test")
      print("Test")
      print("Test")
      ```

Screenshot of Notable:

![notable](https://user-images.githubusercontent.com/17464404/70375755-1a4b6880-1902-11ea-9f8c-ac0e5129d0db.png)

### Expected behavior

That all consecutive lines are aligned.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.

**Comment by fabiospampinato** [comment]
I just fixed the issue with syntax highlighting as well.
