### ISSUE TITLE
Support importing HTML notes

### ISSUE THREAD

**Issue by fabiospampinato** [notable/notable#94]
Many note apps already support exporting notes to HTML, and I've already written a thing for converting HTML to Markdown [here](https://github.com/fabiospampinato/enex-dump/blob/master/src/content.js#L39).

**Comment by k1nghat** [comment]
would this be able to import from url?

**Comment by fabiospampinato** [comment]
@k1nghat no, what's the use case here? You could just download it and them feed it to Notable.

**Comment by k1nghat** [comment]
> @k1nghat no, what's the use case here? You could just download it and them feed it to Notable.

ease of use mostly. just let the users give notable the link and have it go get it and import it. seems like it would be the next logical step from downloading, importing, then deleting the local html file.

**Comment by fabiospampinato** [comment]
🤔 I'm not sure the use case is important enough though. If you only need this for a few pages there's no point in coding special logic for this, if you need this for many pages there's no point in this either, as you'd better download everything via a script or something and then importing everything at once.

**Comment by k1nghat** [comment]
>  I'm not sure the use case is important enough though. If you only need this for a few pages there's no point in coding special logic for this, if you need this for many pages there's no point in this either, as you'd better download everything via a script or something and then importing everything at once.

you are probably correct about that. maybe the html importer would also get images and put them in the attachment folder for you as well. instead of having to get text then get individual images. unless that would be part of the copy/paste feature? to copy/paste a whole webpage and keep formatting?

**Comment by fabiospampinato** [comment]
I just implemented this as part of switching to [dumper](https://github.com/notable/dumper), wait for the next release to try it out.

This is pretty powerful as most existing note-taking apps can export their notes to HTML.
