### ISSUE TITLE
Error report: The maximum number of attempts has been reached

### ISSUE THREAD

**Issue by cryptCEE** [notable/notable#944]
- **OS Version**: darwin 10.15.0
- **Notable Version**: v1.8.2

```
Error: The maximum number of attempts has been reached
    at attempt (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.js:2:167394)
    at file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.js:2:167627
    at FSReqCallback.oncomplete (fs.js:153:23)
```

**Comment by fabiospampinato** [comment]
What happened before the program crashed, did you try to export something? Where you creating a new note? Do you have lots of notes with the same or very similar titles?

**Comment by davidrast3** [comment]
Attempted to import .enex file with > 15,000 notes + attachments (> 550mb). After 200 entries are imported, Notable crashes. Repeated several times, Notable would only import the same 200 entries form the .enex.

**Comment by fabiospampinato** [comment]
@davidrast3 Do you have many notes with the same/similar title?

**Comment by davidrast3** [comment]
About half start with "YYYY-MM-DD-note_title".

**Comment by fabiospampinato** [comment]
And is `note_title` often reused across your notes? What's happening here is that the app is trying to write the note on disk, but after 128 attempts it didn't find an unused path it could write to. I should probably raise that limit when importing notes.

**Comment by davidrast3** [comment]
Nope. Not in conjunction with the same date. If `note_title` is the same, it's rare and the date field will not match.

**Comment by cryptCEE** [comment]
> What happened before the program crashed, did you try to export something? Were you creating a new note? Do you have lots of notes with the same or very similar titles?



> What happened before the program crashed, did you try to export something? Were you creating a new note? Do you have lots of notes with the same or very similar titles?

Attempted to import .enex file with 1944 notes, error triggered after 1261 imports

**Comment by fabiospampinato** [comment]
Large notes collections are now imported more reliably, the app can now import collections containing 1000+ notes and attachments all having the same title.

I'm attaching a test collection I made for this purpose for future reference.

[1000.enex.zip](https://github.com/notable/notable/files/4060483/1000.enex.zip)

**Comment by cryptCEE** [comment]
> Large notes collections are now imported more reliably, the app can now import collections containing 1000+ notes and attachments all having the same title.
> 
> I'm attaching a test collection I made for this purpose for future reference.
> 
> [1000.enex.zip](https://github.com/notable/notable/files/4060483/1000.enex.zip)

💯 Can confirm this works, imported 1951 notes successfully (on Notable v1.8.4, macOS Catalina). Thanks 👍
