### ISSUE TITLE
Right-Click-delete-note, deletes wrong note.

### ISSUE THREAD

**Issue by funkrusher** [notable/notable#945]
Tested with Notable 1.8.1 (Ubuntu Linux)

If a note is selected in the list and then "Move To Trash" or "Permanently Delete" is clicked with right-click of the mouse, the note is not deleted, but the note below in the list is deleted.

This is a dangerous bug, because a user may accidently delete a very important note permanently because of this bug.

for me the bug is consistent. It does always delete the wrong note.

**Comment by fabiospampinato** [comment]
@funkrusher Can you reproduce on 1.8.2? There was a bug related to zooming and displaying context menus that got fixed there which may cause what you're seeing.

**Comment by funkrusher** [comment]
have installed 1.8.2 and can not reproduce with 1.8.2.
Thx, it works now.

**Comment by fabiospampinato** [comment]
Great, thanks for updating. May I ask why you weren't running v1.8.2 already?

**Comment by funkrusher** [comment]
hmm, well i installed the "Deb" Package of notable.
And yes, it strangely seemed to stay on 1.8.1 even though i have run "sudo apt-get update" and so on... normally it should be automatically updated by ubuntu-linux i think.

**Comment by funkrusher** [comment]
ah it says "the current app-format cant be updated automatically" in notable when i select auto-update.

**Comment by fabiospampinato** [comment]
Oh right, yes, not all package formats can be updated automatically currently, I'll improve on that.
