### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by funkrusher** [notable/notable#948]
Sometimes we may need to refactor the contents of a note into another note.

It would be helpful to open the notes in Tabs, so that multiple of such Tabs may be open at the same time. This way the user can easily move Text-Fragments between notes.

Many code-editors provide such a feature (Visual Studio Code, Eclipse-UI).
It could also be helpful for note-editing

**Comment by fabiospampinato** [comment]
I just implemented this, wait for the next release to try it out.

However things like a grid structure for tabs that allows for multiple tabs to be visible at the same time are not implemented yet.

**Comment by logicbomb421** [comment]
Just curious if this will be released soon? Happy to see this feature was implemented, but looks like there hasn't been a release since January. Thanks!

**Comment by fabiospampinato** [comment]
You can get it now: https://github.com/notable/notable-experimental/releases/tag/v1.9.0-alpha.16

We are getting closer to the final release but we are not there yet.
