### ISSUE TITLE
Two suggestions: Cheatsheet window and font on export

### ISSUE THREAD

**Issue by 1ecstasy** [notable/notable#952]
Hey there,
awesome software, I used it for some months now. Anyway I have two very unimportant suggestions:
1. I like the cheatsheet. It's really helpful, however one has to got back and forth between it and the editing. It would be much more helpful if it was in a separate window. Maybe it's a bit too much effort for such a simple feature though.
2. tl;dr: Substitute pdf export font by something nicer like Computer Modern?
I like being able easily introducing code and other things into a pdf and markdown and your pdf export are one of the best ways I know how to do that. However I come from the LaTeX side of things and the style of the documents exported from markdown is sometimes rather rudimentary. Doing web development myself I found that substituting the font by i.e. computer modern immensely improves the visual presentation (even if the nice typesetting of LaTeX requires even more).

Just two ideas to think about.

**Comment by fabiospampinato** [comment]
> I like the cheatsheet. It's really helpful, however one has to got back and forth between it and the editing. It would be much more helpful if it was in a separate window. Maybe it's a bit too much effort for such a simple feature though.

Just load or download the online version of it instead, available at [https://cheatsheet.notable.md](https://cheatsheet.notable.md).

> Substitute pdf export font by something nicer like Computer Modern?

Let's track this here: #102
