### ISSUE TITLE
Confirmation message upon closing app

### ISSUE THREAD

**Issue by leo-carmo** [notable/notable#956]
- **OS Version**: Windows 10
- **Notable Version**: 1.8.2, also 1.8.1.

### Current behavior

Not technically a bug, but a improvement suggestion that wouldn't precisely fit into the feature request category. The message displayed when app is closed could be better. "Close *this* window?" The program is comprised of only one window, so there is no point asking about the "current" window.  What about "Are you sure you want to exit Notable?" or "Are you sure you want to close the app?". Saying "this window" also diminishes the value of the program and the brand!

### Expected behavior

Message changed to one of the suggestions above.

**Comment by fabiospampinato** [comment]
Technically you can open multiple instances of the same app, so the current message is more appropriate. Also in the future I want it to be easier to open multiple windows of the app simultaneously.
