### ISSUE TITLE
Dropbox: not syncing filenames containing emojis

### ISSUE THREAD

**Issue by jinjie** [notable/notable#959]
- **OS Version**: macOS Mojave 10.14.6
- **Notable Version**: Version 1.8.2

### Current behavior

Create a new note with title that contains an emoticon. For example

```
# :car: About My Car
```

### Expected behavior

After saving the file, it should sync to Dropbox. But dropbox not able to sync.

Not tested with other synchronisation services.

**Comment by fabiospampinato** [comment]
Yeah that's an issue with Dropbox, and one of the reasons why we need built-in synchronization support #819

**Comment by fabiospampinato** [comment]
I'm closing this as there's nothing we can do about this specific issue (i.e. I can't fix this in Dropbox).
