### ISSUE TITLE
Hide notes from parent notebooks/tags

### ISSUE THREAD

**Issue by MLR96** [notable/notable#960]
It would be possible that a note with the **Notebooks/work/server** tag is not visible in work notebook.

It could be implemented adding '!' in Notebooks/work/server.
Example tag: !Notebooks/work/server

Then note is visible in **_server_** Notebook but not in **_work_** notebook.

**Comment by EricSchumann** [comment]
Another more straight-forward way would be: Only show the notes in the end location of the tag and never in the paths between:
A page with `Notebooks/work/server` shows up only in `Notebooks/work/server`
If you want to appear it in `Notebooks `or `Notebooks/work` you have to add those tags as well.
