### ISSUE TITLE
How to upload a .md file to echo.notable.md?

### ISSUE THREAD

**Issue by toonsevrin** [notable/notable#963]
Can we manually (/through API) upload markdown files to echo.notable.md? What is the specification?

**Comment by fabiospampinato** [comment]
Technically yes, run the following, or a similar command with different HTML, and the endpoint will return you the URL:

```sh
curl --header "Content-Type: application/json" --request POST --data '{"html":"<b>Hello, World!</b>"}' https://echo.notable.md
```

This isn't meant to be used programmatically and the interface can change at any time.

**Comment by toonsevrin** [comment]
Oh in this case it is indeed not too useful. Would be cool if we could upload .md files and it would render them in the browser.

Perhaps a cool idea: 
`https://viewer.notable.md?url=raw.github.com/toonsevrin/exampleproject/NOTE.md`

**Comment by fabiospampinato** [comment]
The thing is the way a Markdown file is rendered depends on some local state, like if you're referencing a local image how can the server resolve that?

**Comment by toonsevrin** [comment]
Haha I didn't even know that was possible (installed notable a couple of hours ago).

If you want to get crazy, but I doubt this API would be used at all: you could allow for the uploading of the data folder as a tarball. That way all dependencies are uploaded as well. 


Tip for if you do ever implement this: Go with a serverless design for the html rendering (that way you don't have to worry as much about there being viruses in the files).

**Comment by fabiospampinato** [comment]
Just base64-encoding everything and posting the final HTML works better. As in the future things might get more complicated otherwise, like you may have some custom CSS, custom font family, non-default plugins etc.

**Comment by toonsevrin** [comment]
I see! Sorry for going off-topic here but is there (a plan for) simple headless functionality? 
Eg. `notable render -o note.html note.md`

And yes, I want to be able to share files written in your markdown flavour without leaving vim :smile:

**Comment by fabiospampinato** [comment]
Not officially, but yeah that's something I thought about, it would enable some interesting features.

**Comment by toonsevrin** [comment]
Yeah, would be quite cool to be able to use your markdown flavour in websites etc. 

If you do ever implement this, I would really appreciate a notification!

**Comment by fabiospampinato** [comment]
Follow this issue: https://github.com/notable/notable/issues/667
