### ISSUE TITLE
Xcode project?

### ISSUE THREAD

**Issue by saiedg** [notable/notable#964]
How do I build this app? Developer said mentions version 1.0-1.30 source code are available but there is no Xcode project file for Mac. Please can you teach me how to get it? Thank you.

**Comment by fabiospampinato** [comment]
- v1.5.1 code: https://github.com/notable/notable/tree/v1.5.1
- Building instructions: https://github.com/notable/notable/blob/v1.5.1/.github/CONTRIBUTING.md#submit-a-pull-request

You'll probably have to learn more about the JS ecosystem.

**Comment by saiedg** [comment]
Thank you for replaying! Will these instructions create an Xcode project?

**Comment by fabiospampinato** [comment]
No, I don't think anybody uses Xcode with JS, what why I said you'll probably have to learn more about the JS ecosystem.
