### ISSUE TITLE
Data loss when saving a note while there is a search parameter

### ISSUE THREAD

**Issue by ColinNg** [notable/notable#966]
- **OS Version**: Windows 10 Pro (10.0.17763 Build 17763)
- **Notable Version**: 1.8.2

### Current behavior

1. Enter a search term. 
2. Create a new note. Paste some data in. Optionally make changes to the note. Choose Cmd-S or Ctrl-S to save. 
3. Changes made in step 2 are lost. 

### Expected behavior

3. Changes made in step 2 are not lost.

**Comment by fabiospampinato** [comment]
I can't reproduce, am I doing it right: 

![bug](https://user-images.githubusercontent.com/1812093/71903826-d47dfc00-315c-11ea-8fcd-76f5c037579d.gif)

**Comment by ColinNg** [comment]
Oh, after the search (regardless of whether the doc exists) do Ctrl-N/Cmd-N for new doc, then edit it. Upon save, bad things happen. 

What tool did you use to make the screen capture?

**Comment by fabiospampinato** [comment]
> Oh, after the search (regardless of whether the doc exists) do Ctrl-N/Cmd-N for new doc, then edit it. Upon save, bad things happen.

I still can't reproduce.

Could you perhaps make a screen recording yourself so that I can check if we're missing some steps?

> What tool did you use to make the screen capture?

MacOS Mojave's built-in screen recording features + Gifski.

**Comment by ColinNg** [comment]
Sorry I’m not able to make a video right now, but these steps should do it. I did it in Windows 10 but I think the steps are the same on Mac. 

# To Reproduce the Bug

1. Search such that something is found. 
2. Click through found items. 
3. Create New (it will be created as #Untitled)
4. Modify such that it does not fulfill the search criteria. 
5. Context Switch away. What exists at this point, is saved. 
6. Context Switch back. 
7. Make changes. *All changes will be lost.*
8. Ctrl-S
9. You get #Untitled. It looks like step 3 but it isn't. 
10. Make changes. *Any data entered will be lost.*
11. Ctrl-S. **Poof**

**Comment by fabiospampinato** [comment]
> 5. Context Switch away. What exists at this point, is saved.

That means switching the focus to another app right?

**Comment by ColinNg** [comment]
Yes, just clicking the Windows Desktop suffices.

**Comment by fabiospampinato** [comment]
I can reproduce, I'm working on a fix.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.

Thanks a lot for reporting the error, please feel free to open new issues in the future as they are very useful.
