### ISSUE TITLE
Unexpected Note Link Behavior in Linux

### ISSUE THREAD

**Issue by renanwillian** [notable/notable#967]
- **OS Version**: Linux Mint
- **Notable Version**: 1.8.2

### Current behavior
When I link a note in my Linux Mint I have to use the following syntax (otherwise it will link to the root folder):
`[Test](@note/notes/Test.md)`

But when I open the same note in my Windows 10 with Notable 1.8.2, I have the following message: 'Note not found, do you want to create it?', and if I click yes it will create a new file 'Test (1).md' and the message remains.

The only way it works on Windows is this syntax:
`[Test](@note/Test.md)` or just `[[Test]]`

But both of them don't work on Linux Mint

### Expected behavior
Notes link should have the same behavior in every OS.

**Comment by fabiospampinato** [comment]
That looks like a bug 🤔

**Comment by fabiospampinato** [comment]
I can't reproduce this under Ubuntu 16.

I'll try reproducing it in Linux Mint. What bundle did you install, a `deb`?

**Comment by renanwillian** [comment]
OS: Linux Mint 19.3 "Tricia" Cinnamon Edition
Bundle: notable_1.8.2_amd64.deb

**Comment by renanwillian** [comment]
I'm able to reproduce this in my work with Linux Mint 19.3 and in my personal notebook with Linux Mint 19.2.

Strangely I'm unable to reproduce this in Windows 10 using Virtual Box with Linux Mint 19.1.

**Comment by renanwillian** [comment]
For some reason I'm unable to reproduce either in my VM with Linux Mint, I'll do some tests tomorrow and post here more info.

**Comment by renanwillian** [comment]
I found out what was wrong, I had the following directory structure (git checkout mistake):
```
~/.notable/notes/notes
~/.notable/notes/attachments
```
And my notable Data Directory was `~/.notable` instead of `~/.notable/notes`. For some reason everything was working correctly except linking notes / attachments.

I hope you didn't waste much time with this issue.

**Comment by fabiospampinato** [comment]
Thanks for taking a closer look at this 👍 I'm glad this didn't turn out to be an issue with Notable itself.
