### ISSUE TITLE
Ugly default font in Windows

### ISSUE THREAD

**Issue by algorithmax** [notable/notable#969]
Why is the font on Windows so ugly and on MacOS or Linux so pretty?

**Comment by fabiospampinato** [comment]
We are defaulting to the default system font, so maybe the default one on Windows is just ugly? Or does Notable's font look uglier than other apps of yours under Windows?

**Comment by algorithmax** [comment]
Problem solved. I reinstalled the system.

**Comment by fabiospampinato** [comment]
Did you reinstall Windows and that fixed the issue for you?

**Comment by algorithmax** [comment]
yes, now everything works fine
