### ISSUE TITLE
Mermaid diagram shows no arrows when exporting to HTML or PDF

### ISSUE THREAD

**Issue by DanteDeRuwe** [notable/notable#970]
## Mermaid diagram shows no arrows when exporting to HTML or PDF

- **OS**: Windows 10
- **Notable Version**: 1.8.2

### Current behavior

When creating a simple mermaid diagram (see below), the arrows don't render when exporting from notable to PDF & HTML.

![image](https://user-images.githubusercontent.com/23363437/72219383-de7d7180-3545-11ea-9def-3cd14a35d764.png)

The diagram code:

```
graph LR
  A((A))
  B((B))
  A-. <<Include>> .-> B
```

### Expected behaviour
The diagram should render the same way in notable and in exported PDF/HTML

**Comment by fabiospampinato** [comment]
I just fixed this by updating mermaid, the fix will be available in the next release.
