### ISSUE TITLE
Easy arbitrary page breaks

### ISSUE THREAD

**Issue by fabiospampinato** [notable/notable#972]
- A simple short token, like `[@break]` perhaps, for inserting a page break.
  - Because inserting `<div style="page-break-after: always;"></div>` is not very ergonomic.
- Optionally the token should render into something that hints at a page break during preview.
  - So that one doesn't have to actually go print notes to PDF just for checking how they are going to look like.

**Comment by fabiospampinato** [comment]
Done.

I'll showcase this in the subreddit in the following days.

**Comment by XavAM** [comment]
I didn't find the mentionned subreddit but for those who are looking for an answer, the solution is to insert those lines of code into your document : 

<div style="page-break-after: always; visibility: hidden"> 
\pagebreak 
</div>

**Comment by fabiospampinato** [comment]
@XavAM 

- Subreddit: https://www.reddit.com/r/notable
- Betas: https://github.com/notable/notable-insiders/releases/tag/v1.9.0-beta.1
- If you are on the betas you can just write `[[@pagebreak]]`
