### ISSUE TITLE
Strikethroughed text remains black even in dark theme

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [notable/notable#974]
- Windows 10 Home Version 1809:
- Notable Version 1.8.2:

### Current behavior

Current Behavior is that when you use strikethrough in editor mode the text will always be black, even if your theme is dark mode. 

### Expected behavior

Expected Behavior is text color should match color according to theme; Black for Light Theme and white for dark theme.

Photo: 
![BugDarkText](https://user-images.githubusercontent.com/26726264/72264065-0f15e780-35e8-11ea-8801-86a9bd687fa3.png)

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
