### ISSUE TITLE
More than one Note displayed on screen

### ISSUE THREAD

**Issue by BobMilli** [notable/notable#975]
### Feature description
I would like to be able to open 2 notes at the same time : on in display mode and one in edit mode.

### Feature motivation
Notable is my one and only note taking application and so sometimes I need to edit a note refering to a previous note?

**Comment by fabiospampinato** [comment]
I'm closing this in favor of the more specific issues:

- One way to approach this problem would be to implement tabs: #948 
- Another approach would be being able to open single notes into separate windows: #976 

And I think eventually we can implement both of these. We need to adopt UUIDs #538 first though or keeping references to notes will be a mess.

- Also we need better support for multiple data directories #60 in case those notes are not stored in a single data directory.
