### ISSUE TITLE
Publish to the Snap store

### ISSUE THREAD

**Issue by owais** [notable/notable#98]
I see a snap file available for downloads but couldn't find it on the Snap store. Would be great if this could be installed from the snap store. It's a lot more convenient and takes care of automatic delta updates.

**Comment by fabiospampinato** [comment]
I'm not familiar with the Snap store, I'll be happy to do that in the future, especially if the whole process is automatable after the initial release.

**Comment by owais** [comment]
Thanks. Pretty sure it can be automated. Some docs: 

https://docs.snapcraft.io/releasing-your-app/6795
https://docs.snapcraft.io/releasing-to-the-snap-store/6848

Possibly add a "help-wanted" tag to the issue so somone else could contribute it?

**Comment by Lin-Buo-Ren** [comment]
Every contributor with the write access to the repo can set up automatic building upon ever Git push.  Check out <https://snapcraft.io/build>, it really only needs a few minutes to set it up, then you can add a build status badge and "install from snap store" badge stuff in your README or website.

I'm willing to help if you have any problems.

REFERER: [Error installing snap downloaded from github - snapd - snapcraft.io](https://forum.snapcraft.io/t/error-installing-snap-downloaded-from-github/9548)

**Comment by Lin-Buo-Ren** [comment]
One problem I noticed is that you didn't seem to have a Snapcraft recipe in your source tree, the Snapcraft build service requires a Snapcraft recipe existed at /snap/snapcraft.yaml, /snapcraft.yaml or /.snapcraft.yaml in the same source repository to be built[1]

[1] [build.snapcraft.io doesn't allow custom snapcraft.yaml location · Issue #1094 · canonical-websites/build.snapcraft.io](https://github.com/canonical-websites/build.snapcraft.io/issues/1094)

**Comment by flexiondotorg** [comment]
Hey @fabiospampinato I work on the Snapcraft team and would love to help get Notable published in the [Snap Store](https://snapcraft.io/store), which is the app store for Linux :smiley:

Once published, I'd be delighted to feature Notable as a editors pick and put together a social campaign to promote Notable. What help do you need to get the snap you are producing published in the store?

**Comment by fabiospampinato** [comment]
Hey @flexiondotorg, let me get v1.4 ready and then I'll take care of releasing it to the snap store and the other places where people currently expect to find it 👍 I'll let you know when that's done and if I encounter any issues.

**Comment by nmabhinandan** [comment]
Any updates?

**Comment by fabiospampinato** [comment]
@nmabhinandan No updates yet, this is still an issue I plan to work on [next](https://github.com/notable/notable/milestone/1), but I haven't had much time recently.

**Comment by fabiospampinato** [comment]
I just published Notable to the Snap store.

Here's the store's page: https://snapcraft.io/notable

To install it just run:

```bash
sudo snap install notable
```

When installed this way the app will now keep itself updated automatically, I will be able to see how many people are using it and perhaps we could reach more users that didn't know about Notable before.

Enjoy 🎉

**Comment by fabiospampinato** [comment]
There has been an issue reported about the newly published snap, basically because of a sandbox restriction error the app can't successfully write files on disk right now. I think I know how to fix the issue, I need to switch to a more relaxed sandboxing environment, however I can't do that without a manual review first.

In the meantime just installing the [released snap file](https://github.com/notable/notable/releases) manually with `--dangerous` flag should work fine.

**Comment by fabiospampinato** [comment]
Finally fixed the issue! Now the snap published in the snap store uses the "classic" confinement, which allows it to work properly.
