### ISSUE TITLE
Synchronized scrolling

### ISSUE THREAD

**Issue by fabiospampinato** [notable/notable#981]
Surely when using the split-editor, but perhaps also by default when toggling between preview and edit mode? 🤔 

---

For future ref: the html shield, or anything else, shouldn't change the number of lines.

**Comment by stingray21** [comment]
Yes, it would be great if the cursor stays in the same position when toggling from preview to edit mode. It can be hard to find the line in question in longer files.

**Comment by washere** [comment]
I've tested thousands of note/productivity apps over the years & communicated with many devs & still do. For .md editors (& opml) i always advise: Dark mode, tags, multi panes (folders/files, edit, preview), Rich View toolbars (sp. for .md fn shortcuts), etc. Most of these are now in Notable. Sync-Scroll or Scroll-Sync is also what i have advised many devs & most did it, even a few on Andoird (good for Chromebooks, tablets & big phones). There are diff types of Scroll-Sync implementations (many Win/Mac/Linux/Android apps, also plugins VSCode/Atom?SublomText etc:

0) Non functional or faulty
1) Scrolling edit mode pane: updates/scrolls preview pane
2) Scrolling preview mode pane: updates/scrolls edit pane
3) Scrolling either edit mode pane or preview pane: updates .scrolls the other

Of course 3 is the best.

Other features Notable needs:

+ Dropbox Sync (better privacy than GDrive/OneDrive) 
+ Dropbox Data Folder Option in left pane (like iA Writer etc)
+ Settings interface
+ Option: Remember last session layout: Columns, column sizes, etc
+ Option: Auto-Save (set number of seconds in settings) On/Off
+ Tags Search Column: Usually right column in outliner apps: Highlighted search results in document 
+ .md Tree Pane Column: Download a md file with multi levels of headings (markdown-it.md etc) to see (iA Writer: Content Block Levels Column or in QOwnNotes Windows (menu): Panels: Show navigation Panel

And other suggestions, but these are most needed now, incl. Sync-Scroll
+ left icon in toolbar toggling edit mode & preview mode, should cycle through also dual pane (Ctrl+Alt+S) so goes through all 3 modes. Pref. Dual Pane should have it's own icon.

Best wishes.

**Comment by fabiospampinato** [comment]
@washere I agree with most of you said. Commenting on a few points:

> Of course 3 is the best.

That's what I plan to implement.

> Dropbox Sync (better privacy than GDrive/OneDrive)

You can already sync your data directory via Dropbox just by putting it inside Dropbox.

> Tags Search Column: Usually right column in outliner apps

I'm not sure I understand what you mean by that, is that a column that displays the tags the current note is tagged with?

> left icon in toolbar toggling edit mode & preview mode, should cycle through also dual pane (Ctrl+Alt+S) so goes through all 3 modes.

I don't think so, you never want to jump between 2 of 3 states possible by passing through the third one which you don't need. Maybe a separate button as you suggest should be added for split-mode, currently that button is kind of imaginary and can be triggered via a shortcut.

If you'd like to provide some more feedback we have a section with some questions about this in the subreddit: https://www.reddit.com/r/Notable/comments/erhjgf/request_for_product_feedback_1/

**Comment by washere** [comment]
> @washere I agree with most of you said. Commenting on a few points:
> 
> > Of course 3 is the best.
> 
> That's what I plan to implement.
> 
> > Dropbox Sync (better privacy than GDrive/OneDrive)
> 
> You can already sync your data directory via Dropbox (or anything else really) just by putting it inside Dropbox.
> 
> > Tags Search Column: Usually right column in outliner apps
> 
> I'm not sure I understand what you mean by that, would that be a column that displays the tags the current note is tagged with?
> 
> > left icon in toolbar toggling edit mode & preview mode, should cycle through also dual pane (Ctrl+Alt+S) so goes through all 3 modes.
> 
> I don't think so, you never want to jump between 2 of the 3 states possible by passing through the third one which you don't need. Maybe a separate button as you suggest should be added for split-mode, currently that button is kind of imaginary and can be triggered via a shortcut.
> 
> If you'd like to provide some more feedback we have a section with some questions about this in the subreddit: https://www.reddit.com/r/Notable/comments/erhjgf/request_for_product_feedback_1/

Yes Fabio, a separate icon for dual pane would be better. Also getting rid of confirmation on exit in SETTINGS would be good, not needed for most if auto-save per seconds (option) is also there.

Of course Dropbox folders can be synced, there are also popular apps that schedule Dropbox/gdrive syncs in windows Android etc. However, I was talking of adding Dropbox as a working space folder area, like local disk drive, so clicking on it will show folders/files on the assigned folder (or root of Dropbox):

https://ia.net/writer/blog/a-new-document-library

Tags column is used in certain apps. You're in a document, it shows it's tags there. The column usually has sections. Another is a search box, results (file names) for any tags are shown below in another section. Some sections in the column have tabs sub-sections (like Photoshop floating toolbar tabs), etc etc. It can get even more complex and useful. Tags are hyperlinks between documents, potentials are endless. I'd say a settings section is needed before tags column.

I noted the suggestions link. Thanks for the good work.

**Comment by dibstern** [comment]
This would be amazing. If this + a better folder management system or even a collapsible tree system like Trilium, and then a server to sync between the computer and the phone (that works better than BoostNote's which is super slow and buggy), then this would be the killer 10/10 note taking app IMO. The scroll sync and collapsible tree system make large notes manageable. I use a markdown note for work, creating a ### Title per day, ## per Month and # Per year, so these features are huge for this kind of use.

**Comment by fabiospampinato** [comment]
Duplicate of #311
