### ISSUE TITLE
Disable middle-click pasting on linux

### ISSUE THREAD

**Issue by renanwillian** [notable/notable#982]
### Feature description
In Linux we have this very annoying shortcut for pasting, with no way of disabling it globally, having to disable it in every application.

### Feature motivation
This shortcut ruins multi-line editing:
![Peek 2020-01-16 14-13](https://user-images.githubusercontent.com/30376796/72546930-6aefa300-386a-11ea-86a4-2fffaf3a4e72.gif)

**Comment by fabiospampinato** [comment]
So basically when you middle-click it's exactly like if you `ctrl+v`'d?

How is this breaking multi-line editing? For instance I don't think I middle-click anywhere inside Notable.

**Comment by renanwillian** [comment]
> So basically when you middle-click it's exactly like if you ctrl+v'd?

Exacly

> How is this breaking multi-line editing? For instance I don't think I middle-click anywhere inside Notable.

I click and drag with middle click to select the lines I want to edit, for me at least it's faster than using the 'insert new cursor' shortcut.

**Comment by fabiospampinato** [comment]
> I click and drag with middle click to select the lines I want to edit, for me at least it's faster than using the 'insert new cursor' shortcut.

Oh nice, I didn't even know that was possible 😄 I'll see what I can do about this.

**Comment by fabiospampinato** [comment]
After a bit of googling it seems that maybe there's a way to disable this behavior globally, depending on your desktop environment perhaps.

I think we don't necessarily want to disable middle clicks entirely, but we just don't want a middle click to paste anything when using in a `MiddleClick+Drag`, right? 

I'll see what I can do about it.

**Comment by fabiospampinato** [comment]
Related vscode issue: https://github.com/microsoft/vscode/issues/49693

**Comment by renanwillian** [comment]
> After a bit of googling it seems that maybe there's a way to disable this behavior globally, depending on your desktop environment perhaps.

I already tried lots of hacks, but there is always a drawback.


> I think we don't necessarily want to disable middle clicks entirely, but we just don't want a middle click to paste anything when using in a MiddleClick+Drag, right?

This IMHO is the most annoying thing in Linux, so I wouldn't mind it entirely disabled, but I undertand that someone may be using this shortcut for pasting.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.

**Comment by renanwillian** [comment]
I can't no longer do multi-line editing with middle click, now it behaves like a left click.

Current behavior:
![Peek 2020-01-20 08-35](https://user-images.githubusercontent.com/30376796/72723686-0c733f00-3b60-11ea-82ed-db1de2511a62.gif)

Expected behavior:
![Peek 2020-01-20 08-35 2](https://user-images.githubusercontent.com/30376796/72723705-1c8b1e80-3b60-11ea-8e4f-8e08f25c3510.gif)

No more pasting though.

**Comment by fabiospampinato** [comment]
I can reproduce. I didn't see this behavior while developing the fix because I executed the code for fixing this via the devtools after the editor was already loaded, for convenience, but now that it's executed before the editor is loaded it doesn't work.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.

**Comment by sguizard** [comment]
Middle click paste is essential for some Linux users. 
Is it possible to add an option in preference to Enable/Disable this feature ?

**Comment by fabiospampinato** [comment]
@sguizard middle-click pasting has not been affected, except when you're also middle-click dragging. The thing I had to turn off to fix this issue is automatic copying to the clipboard the selected text, at least when inside the editor. Would you consider that a very important feature? 🤔 I'll make this configurable in v1.9 anyway.

**Comment by sguizard** [comment]
@fabiospampinato I use this copy/paste method for very often in my daily work. 
When I develop a new analysis, I have my terminal and notable in editor mode open side by side and jump from one to another to log everything I do.
Having this feature disabled would be very annoying for me ...

**Comment by fabiospampinato** [comment]
@squizard isn't Ctrl-C-ing just faster anyway especially when switching back and forth from using the terminal?

**Comment by sguizard** [comment]
@fabiospampinato It's not really a question of speed. In terminal, <kbd>Ctrl</kbd> + <kbd>C</kbd> kills your running command. You have to use <kbd>Ctrl</kbd> + <kbd>shift</kbd> + <kbd>C</kbd> to copy and <kbd>Ctrl</kbd> + <kbd>shift</kbd> + <kbd>V</kbd>. Using copy/paste by select text and middle click allow to get rid discordant keyboard shortcuts. It avoid the frustration of mixing those shortcuts X times by day :)

**Comment by fabiospampinato** [comment]
Oh I see 🤔 As a pragmatic choice I think it might still be better to ensure middle-click dragging works, as it was completely broken under linux, and asking users to Ctrl-C inside the editor. But I will add an option for this in v1.9 once we have settings #476, but also I don't see why copy-on-select should be disabled in order to enable middle-click dragging, I think this issue hasn't been fixed properly at the editor level and I'll report back the issue to them.

**Comment by sguizard** [comment]
OK, I'll wait for the updates :wink: 
Thanks for this nice tool.
