### ISSUE TITLE
Improve startup time

### ISSUE THREAD

**Issue by fabiospampinato** [notable/notable#99]
Somebody mentioned that Boostnote loads a few times quicker than Notable, if anything we should strive for the opposite.

- [x] Instead of waiting for the notes/attachments to be loaded we should load an "empty" version of the app instead of keeping the app blank.
- [x] Load heavy packages lazily
- [x] Deeper node_modules cleanup
- [x] Show the window as soon as possible
- [x] Upgrade to Electron v4
- [x] [Reduce heavy dependencies](https://github.com/fabiospampinato/notable/issues/323)
- [ ] use [v8-compile-cache](https://www.npmjs.com/package/v8-compile-cache)
- [x] [Target ES6 or later](https://github.com/fabiospampinato/notable/issues/100)

**Comment by amelandri** [comment]
I would suggest to display some sort of "loading" animation while waiting the notes to be loaded otherwise the app seems freezed.

Currently I'm on a i5 Winddows 10 PC with 12 GB of ram and the empty interface appear fater 2,3 seconds and then i have to wait another 9 seconds for the notes to show up. 

I have 252 notes and 228 attachments. (244 Mb total)

**Comment by fabiospampinato** [comment]
@amelandri I'd rather keep improving the startup time than showing a spinner. 2s/3s + 9s sounds like a lot. Are you using an SSD?

**Comment by amelandri** [comment]
Yes, I'm using an SSD. I did multiple tests and I get always the same results.

During the app startup the pc was alwast idle.

**Comment by Fastidious** [comment]
@amelandri I would rather prefer to wait, than receiving a placebo. The "blank" application on loading is merely 1-2 seconds.

**Comment by fabiospampinato** [comment]
@amelandri are you sure the app didn't update itself? 🤔

**Comment by amelandri** [comment]
I don’t think so, since I was already using version 1.2

**Comment by fabiospampinato** [comment]
I'm closing this as all points in the list have been addressed, except "use v8-compile-cache", which will actually be pretty tricky to implement, perhaps it's not worth it.
