### ISSUE TITLE
Can't move window after vertical resize

### ISSUE THREAD

**Issue by invad0r** [notable/notable#998]
- **OS Version**: macOS Mojave 10.14.6
- **Notable Version**:  1.8.2

### Current behavior

When I resize the notable window vertically by dragging downwards I can't move the window afterwards. After I resize top left, then the window is movable again

https://recordit.co/OrFTXd8R8T

### Expected behavior

The main window should alway be movable

**Comment by fabiospampinato** [comment]
I remember reading something about this in Electron's changelog.

I can't reproduce under Electron v7.1.9, I think it might have been fixed.

Let me know if you can still reproduce after updating to v1.8.3, which I should release today.

**Comment by invad0r** [comment]
Yep `v1.8.3` fixed it. Thanks 👍

**Comment by fabiospampinato** [comment]
Nice, thanks for checking.
