### ISSUE TITLE
Auto link .dev URLs

### ISSUE THREAD

**Issue by vallentin** [notable/notable#999]
- **OS Version**: Windows 10
- **Notable Version**: 1.8.2

### Current behavior

*This is a minor issue and more of an enhancement request than a "bug".*

Currently `.dev` URLs without a scheme are not auto linked.

**Example:**

```markdown
### Auto Linked

- example.com
- example.com/foo/bar
- https://example.com
- https://example.com
- https://example.dev (note .dev)

### Not Auto Linked

- example.dev
- example.dev/foo/bar
```

I remember you mentioned using [linkify-it](https://github.com/markdown-it/linkify-it) on a previous issue (#909). I was about to post the issue there, however I noticed this comment, and thus decided posting the issue here instead:

>     // DON'T try to make PRs with changes. Extend TLDs with LinkifyIt.tlds() instead
>
> - https://github.com/markdown-it/linkify-it/blob/6f3c94916a5e1bd9a246cb7166ec3ee6adbde6bb/index.js#L119-L120

### Expected behavior

That `.dev` URLs without a scheme are auto linked.

**Comment by vallentin** [comment]
Related, I noticed something odd with angle brackets and URLs without schemes as well.

**Example:**

```md
- <https://example.com>
- <https://example.dev>

vs

- <example.com>
- <example.dev>
```

**Screenshot of Notable:**

![angle](https://user-images.githubusercontent.com/17464404/72607944-e3656b00-3921-11ea-8482-2b8ad8ec2b94.png)

**Comment by fabiospampinato** [comment]
> Related, I noticed something odd with angle brackets and URLs without schemes as well.

Strange 🤔 Maybe I should raise an upstream bug about this.

**Comment by fabiospampinato** [comment]
There are a lot more TLDs than I expected: https://github.com/stephenmathieson/node-tlds/blob/master/index.js 🤔

> - https://example.dev (note .dev)

I guess if there's a protocol specified then the auto-linker can be much more confident this is actually a link.

> That .dev URLs without a scheme are auto linked.

Fixed. The issue with angle brackets has been fixed too.

Now all valid ICANN TLDs should be supported, I basically added support for ~1200 more TLDs, as listed here: https://github.com/fabiospampinato/linkify-it-tlds/blob/master/src/index.ts

**Comment by vallentin** [comment]
That's a lot! Many thanks for adding them anyways! :smile:
